Dataset Count =
DISTINCTCOUNT ( DimDataset[DatasetKey] )

Critical Dataset Count =
CALCULATE ( [Dataset Count], DimDataset[Criticality] = "Tier 1" )

Certified Dataset Count =
CALCULATE ( [Dataset Count], DimDataset[Certified] = "Y" )

Data Quality Score =
AVERAGE ( FactDatasetDaily[DataQualityScore] )

Completeness % =
DIVIDE ( SUM ( FactDatasetDaily[RowsLoaded] ), SUM ( FactDatasetDaily[RowsExpected] ) )

Freshness SLA % =
DIVIDE ( SUM ( FactDatasetDaily[FreshnessWithinSLAFlag] ), COUNTROWS ( FactDatasetDaily ) )

Refresh Runs =
COUNTROWS ( FactRefreshRuns )

Refresh Success % =
DIVIDE ( CALCULATE ( [Refresh Runs], FactRefreshRuns[Status] = "Success" ), [Refresh Runs] )

Failed Refreshes =
CALCULATE ( [Refresh Runs], FactRefreshRuns[Status] = "Failed" )

Avg Refresh Duration Min =
AVERAGE ( FactRefreshRuns[DurationMinutes] )

DQ Issue Count =
SUM ( FactDatasetDaily[NullCriticalCount] ) + SUM ( FactDatasetDaily[DuplicateKeyCount] ) + SUM ( FactDatasetDaily[SchemaDriftCount] )

Open Incidents =
CALCULATE ( COUNTROWS ( FactIncidents ), FactIncidents[IncidentStatus] <> "Closed" )

Avg MTTR Hours =
AVERAGE ( FactIncidents[MTTRHours] )

Reconciliation Variance =
SUM ( FactReconciliation[VarianceAmount] )

Abs Reconciliation Variance =
SUMX ( FactReconciliation, ABS ( FactReconciliation[VarianceAmount] ) )

Reconciliation Pass % =
DIVIDE ( CALCULATE ( COUNTROWS ( FactReconciliation ), FactReconciliation[ReconciliationStatus] = "Pass" ), COUNTROWS ( FactReconciliation ) )

Report Views =
SUM ( FactUsage[Views] )

Active Viewer Days =
SUM ( FactUsage[UniqueViewers] )

Export Events =
SUM ( FactUsage[ExportEvents] )

Avg Report Load Seconds =
AVERAGE ( FactUsage[AvgLoadSeconds] )

Failed Visual Count =
SUM ( FactUsage[FailedVisualCount] )

Access Risk Events =
SUM ( FactAccessReview[RLSExceptions] ) + SUM ( FactAccessReview[OrphanedUsers] ) + SUM ( FactAccessReview[UnauthorizedSharingEvents] )

RLS Exceptions =
SUM ( FactAccessReview[RLSExceptions] )

Pending Access Reviews =
SUM ( FactAccessReview[PendingAccessReviews] )

Deployment Control Score =
AVERAGE ( FactAccessReview[DeploymentControlScore] )

Current Lens Label =
VAR MonthLens = SELECTEDVALUE ( DimDate[MonthYear], "All Months" )
VAR DomainLens = SELECTEDVALUE ( DimDataset[Domain], "All Domains" )
VAR CriticalityLens = SELECTEDVALUE ( DimDataset[Criticality], "All Tiers" )
RETURN "Lens: " & MonthLens & " | " & DomainLens & " | " & CriticalityLens

Usage Lens Label =
VAR WorkspaceLens = SELECTEDVALUE ( DimReport[Workspace], "All Workspaces" )
VAR SensitivityLens = SELECTEDVALUE ( DimReport[SensitivityLabel], "All Sensitivity" )
RETURN "Lens: " & WorkspaceLens & " | " & SensitivityLens

Action Lens Label =
VAR MonthLens = SELECTEDVALUE ( DimDate[MonthYear], "All Months" )
VAR DepartmentLens = SELECTEDVALUE ( DimDepartment[Department], "All Departments" )
RETURN "Lens: " & MonthLens & " | " & DepartmentLens

Governance Decision Chip =
VAR Dq = [Data Quality Score]
VAR Fresh = [Freshness SLA %]
VAR OpenIncidents = [Open Incidents]
RETURN IF ( Dq >= 92 && Fresh >= 0.95 && OpenIncidents <= 30, "PASS: trust posture on track", IF ( OpenIncidents > 45, "ESCALATE: incident load above guardrail", "WATCH: owner review required" ) )

Reliability Decision Chip =
VAR Failed = [Failed Refreshes]
VAR Complete = [Completeness %]
VAR RecPass = [Reconciliation Pass %]
RETURN IF ( Failed <= 25 && Complete >= 0.99 && RecPass >= 0.90, "PASS: close-ready reliability", IF ( Failed > 40 || Complete < 0.985, "ESCALATE: reliability SLA at risk", "WATCH: validate exception queue" ) )

Adoption Decision Chip =
VAR LoadSec = [Avg Report Load Seconds]
VAR AccessRisk = [Access Risk Events]
VAR ControlScore = [Deployment Control Score]
RETURN IF ( LoadSec <= 3.0 && AccessRisk <= 800 && ControlScore >= 92, "PASS: governed adoption healthy", IF ( AccessRisk > 950, "ESCALATE: access risk concentration", "WATCH: control follow-up needed" ) )

Risk Action Decision Chip =
VAR OpenIncidents = [Open Incidents]
VAR AccessRisk = [Access Risk Events]
VAR Pending = [Pending Access Reviews]
RETURN IF ( OpenIncidents <= 30 && AccessRisk <= 800 && Pending <= 900, "PASS: action load inside guardrail", IF ( OpenIncidents > 45 || Pending > 1100, "ESCALATE: prioritize owner actions", "WATCH: triage aging queues" ) )
