{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DimDate\",\"DimDataset\",\"DimReport\",\"DimDepartment\",\"FactDatasetDaily\",\"FactRefreshRuns\",\"FactReconciliation\",\"FactUsage\",\"FactAccessReview\",\"FactIncidents\",\"KPI Measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "FactDatasetDaily_DateKey_DimDate_DateKey",
        "fromColumn": "DateKey",
        "fromTable": "FactDatasetDaily",
        "toColumn": "DateKey",
        "toTable": "DimDate"
      },
      {
        "name": "FactDatasetDaily_DatasetKey_DimDataset_DatasetKey",
        "fromColumn": "DatasetKey",
        "fromTable": "FactDatasetDaily",
        "toColumn": "DatasetKey",
        "toTable": "DimDataset"
      },
      {
        "name": "FactRefreshRuns_DateKey_DimDate_DateKey",
        "fromColumn": "DateKey",
        "fromTable": "FactRefreshRuns",
        "toColumn": "DateKey",
        "toTable": "DimDate"
      },
      {
        "name": "FactRefreshRuns_DatasetKey_DimDataset_DatasetKey",
        "fromColumn": "DatasetKey",
        "fromTable": "FactRefreshRuns",
        "toColumn": "DatasetKey",
        "toTable": "DimDataset"
      },
      {
        "name": "FactReconciliation_DateKey_DimDate_DateKey",
        "fromColumn": "DateKey",
        "fromTable": "FactReconciliation",
        "toColumn": "DateKey",
        "toTable": "DimDate"
      },
      {
        "name": "FactReconciliation_DatasetKey_DimDataset_DatasetKey",
        "fromColumn": "DatasetKey",
        "fromTable": "FactReconciliation",
        "toColumn": "DatasetKey",
        "toTable": "DimDataset"
      },
      {
        "name": "FactIncidents_DateKey_DimDate_DateKey",
        "fromColumn": "DateKey",
        "fromTable": "FactIncidents",
        "toColumn": "DateKey",
        "toTable": "DimDate"
      },
      {
        "name": "FactIncidents_DatasetKey_DimDataset_DatasetKey",
        "fromColumn": "DatasetKey",
        "fromTable": "FactIncidents",
        "toColumn": "DatasetKey",
        "toTable": "DimDataset"
      },
      {
        "name": "FactReconciliation_DeptKey_DimDepartment_DeptKey",
        "fromColumn": "DeptKey",
        "fromTable": "FactReconciliation",
        "toColumn": "DeptKey",
        "toTable": "DimDepartment"
      },
      {
        "name": "FactUsage_DateKey_DimDate_DateKey",
        "fromColumn": "DateKey",
        "fromTable": "FactUsage",
        "toColumn": "DateKey",
        "toTable": "DimDate"
      },
      {
        "name": "FactUsage_ReportKey_DimReport_ReportKey",
        "fromColumn": "ReportKey",
        "fromTable": "FactUsage",
        "toColumn": "ReportKey",
        "toTable": "DimReport"
      },
      {
        "name": "FactUsage_DeptKey_DimDepartment_DeptKey",
        "fromColumn": "DeptKey",
        "fromTable": "FactUsage",
        "toColumn": "DeptKey",
        "toTable": "DimDepartment"
      },
      {
        "name": "FactAccessReview_DateKey_DimDate_DateKey",
        "fromColumn": "DateKey",
        "fromTable": "FactAccessReview",
        "toColumn": "DateKey",
        "toTable": "DimDate"
      },
      {
        "name": "FactAccessReview_ReportKey_DimReport_ReportKey",
        "fromColumn": "ReportKey",
        "fromTable": "FactAccessReview",
        "toColumn": "ReportKey",
        "toTable": "DimReport"
      },
      {
        "name": "FactAccessReview_DeptKey_DimDepartment_DeptKey",
        "fromColumn": "DeptKey",
        "fromTable": "FactAccessReview",
        "toColumn": "DeptKey",
        "toTable": "DimDepartment"
      },
      {
        "name": "6d3d8ad7-28ba-44c0-8e38-eaabee8af805",
        "fromColumn": "Date",
        "fromTable": "DimDate",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dd93922a-7145-4242-a187-5533e7726260"
      },
      {
        "name": "a60e5e1b-eaff-4892-b1bf-ed91049c97e6",
        "fromColumn": "MonthEndDate",
        "fromTable": "DimDate",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3fcce349-f814-4faf-8847-0a9d59a024ba"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "lineageTag": "84418167-da08-47fc-ab6f-1866f63406bd",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f9fc5bac-76f6-42ab-945e-8efb5d3d5f34",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_dd93922a-7145-4242-a187-5533e7726260"
                },
                "isDefault": true,
                "relationship": "6d3d8ad7-28ba-44c0-8e38-eaabee8af805"
              }
            ]
          },
          {
            "name": "MonthEndDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "691c8605-86bf-498f-8272-63afee504972",
            "sourceColumn": "MonthEndDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3fcce349-f814-4faf-8847-0a9d59a024ba"
                },
                "isDefault": true,
                "relationship": "a60e5e1b-eaff-4892-b1bf-ed91049c97e6"
              }
            ]
          },
          {
            "name": "MonthKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "26203062-bde3-408c-b37b-da002b5f7f91",
            "sourceColumn": "MonthKey",
            "summarizeBy": "count"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "lineageTag": "e57ce655-9b27-4791-8fcd-2054189f8992",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "lineageTag": "b1aca9bd-1b65-4a33-9ea6-c7712abc497a",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumber",
            "dataType": "int64",
            "lineageTag": "a5273b5c-1611-48ca-a72f-5edd39603c10",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "lineageTag": "cc96f8dd-3500-479e-999e-d7a6de176b60",
            "sortByColumn": "MonthNumber",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "lineageTag": "e08cb552-6ea5-4ec0-8a5e-b428c613beda",
            "sortByColumn": "MonthIndex",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none"
          },
          {
            "name": "MonthIndex",
            "dataType": "int64",
            "lineageTag": "4781a218-627f-4cac-818e-8bd99777856a",
            "sourceColumn": "MonthIndex",
            "summarizeBy": "sum"
          },
          {
            "name": "IsLatestCompleteMonth",
            "dataType": "string",
            "lineageTag": "7b4ff51c-57c4-448f-9970-f47edc2ed1c7",
            "sourceColumn": "IsLatestCompleteMonth",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fa21cefb-fc22-47f8-870a-50d691775705",
        "partitions": [
          {
            "name": "DimDate-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/dimdate.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"DateKey\", Int64.Type}, {\"Date\", type date}, {\"MonthEndDate\", type date}, {\"MonthKey\", Int64.Type}, {\"Year\", Int64.Type}, {\"Quarter\", type text}, {\"MonthNumber\", Int64.Type}, {\"MonthName\", type text}, {\"MonthYear\", type text}, {\"MonthIndex\", Int64.Type}, {\"IsLatestCompleteMonth\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDataset",
        "columns": [
          {
            "name": "DatasetKey",
            "dataType": "string",
            "lineageTag": "49ea2c2e-41e3-4128-8f98-3b0acd9322d4",
            "sourceColumn": "DatasetKey",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetName",
            "dataType": "string",
            "lineageTag": "996bdde4-2c9c-4a3c-b988-f7f7cfa8395f",
            "sourceColumn": "DatasetName",
            "summarizeBy": "none"
          },
          {
            "name": "Domain",
            "dataType": "string",
            "lineageTag": "318a3474-022b-473c-a2dd-117491ee32ec",
            "sourceColumn": "Domain",
            "summarizeBy": "none"
          },
          {
            "name": "SourceSystem",
            "dataType": "string",
            "lineageTag": "8e6e0ec0-1d6f-4082-ab8a-bfe87c836dc2",
            "sourceColumn": "SourceSystem",
            "summarizeBy": "none"
          },
          {
            "name": "Criticality",
            "dataType": "string",
            "lineageTag": "c5e4ef7b-4d6c-45b6-b6b2-bbefe24330d8",
            "sourceColumn": "Criticality",
            "summarizeBy": "none"
          },
          {
            "name": "OwnerTeam",
            "dataType": "string",
            "lineageTag": "712b58dc-8894-4b5f-9905-4bf3c482996b",
            "sourceColumn": "OwnerTeam",
            "summarizeBy": "none"
          },
          {
            "name": "SLAHours",
            "dataType": "int64",
            "lineageTag": "289115dc-4e08-4e31-808f-710da36e71d8",
            "sourceColumn": "SLAHours",
            "summarizeBy": "sum"
          },
          {
            "name": "RefreshFrequency",
            "dataType": "string",
            "lineageTag": "88526a55-c4e1-4702-8473-f986e0ae0366",
            "sourceColumn": "RefreshFrequency",
            "summarizeBy": "none"
          },
          {
            "name": "RLSRequired",
            "dataType": "string",
            "lineageTag": "61cd10f2-7c10-4cfd-91c4-d4502ea841d5",
            "sourceColumn": "RLSRequired",
            "summarizeBy": "none"
          },
          {
            "name": "Certified",
            "dataType": "string",
            "lineageTag": "610682ba-a940-4d1c-b7ee-6755ebc790aa",
            "sourceColumn": "Certified",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "624879cf-ef10-4e31-9fb1-7501eb5ab32f",
        "partitions": [
          {
            "name": "DimDataset-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/dimdataset.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"DatasetKey\", type text}, {\"DatasetName\", type text}, {\"Domain\", type text}, {\"SourceSystem\", type text}, {\"Criticality\", type text}, {\"OwnerTeam\", type text}, {\"SLAHours\", Int64.Type}, {\"RefreshFrequency\", type text}, {\"RLSRequired\", type text}, {\"Certified\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimReport",
        "columns": [
          {
            "name": "ReportKey",
            "dataType": "string",
            "lineageTag": "fdee162e-b7bc-4059-98e4-7c7fc32dea36",
            "sourceColumn": "ReportKey",
            "summarizeBy": "none"
          },
          {
            "name": "ReportName",
            "dataType": "string",
            "lineageTag": "c97ebf4a-5f33-4d90-8fbf-f39cc123a2b8",
            "sourceColumn": "ReportName",
            "summarizeBy": "none"
          },
          {
            "name": "Workspace",
            "dataType": "string",
            "lineageTag": "44d1e7e5-68f0-40c0-8e72-1a9f7fc1a1cd",
            "sourceColumn": "Workspace",
            "summarizeBy": "none"
          },
          {
            "name": "Audience",
            "dataType": "string",
            "lineageTag": "0747ad33-d01d-4ba3-b040-64d677e554ed",
            "sourceColumn": "Audience",
            "summarizeBy": "none"
          },
          {
            "name": "OwnerTeam",
            "dataType": "string",
            "lineageTag": "147647b1-ccfe-42d1-9de8-401341912137",
            "sourceColumn": "OwnerTeam",
            "summarizeBy": "none"
          },
          {
            "name": "Certified",
            "dataType": "string",
            "lineageTag": "34f40c55-4f12-4257-ba49-c183376ddb30",
            "sourceColumn": "Certified",
            "summarizeBy": "none"
          },
          {
            "name": "SensitivityLabel",
            "dataType": "string",
            "lineageTag": "d0605e7d-c881-4a5b-9877-7488ec5016a5",
            "sourceColumn": "SensitivityLabel",
            "summarizeBy": "none"
          },
          {
            "name": "ReportTier",
            "dataType": "string",
            "lineageTag": "7247e93f-5ae7-42c4-8238-4892bcc029e0",
            "sourceColumn": "ReportTier",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c6cbdf52-d0a9-4889-85de-a92d5ec05a11",
        "partitions": [
          {
            "name": "DimReport-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/dimreport.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"ReportKey\", type text}, {\"ReportName\", type text}, {\"Workspace\", type text}, {\"Audience\", type text}, {\"OwnerTeam\", type text}, {\"Certified\", type text}, {\"SensitivityLabel\", type text}, {\"ReportTier\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDepartment",
        "columns": [
          {
            "name": "DeptKey",
            "dataType": "string",
            "lineageTag": "65f7c662-ffcc-42d0-a282-6cd9e1dd90f6",
            "sourceColumn": "DeptKey",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "dataType": "string",
            "lineageTag": "3656c1f4-2de8-4393-be36-7f18a4490d92",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Function",
            "dataType": "string",
            "lineageTag": "dd4ad646-a15d-4437-8556-c7f41487d381",
            "sourceColumn": "Function",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "dataType": "string",
            "lineageTag": "abfdcd0d-d28b-49f9-81c0-18ad34541f50",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2dd6f0f7-7fc6-40ff-9896-1c9f5e31d71a",
        "partitions": [
          {
            "name": "DimDepartment-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/dimdepartment.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"DeptKey\", type text}, {\"Department\", type text}, {\"Function\", type text}, {\"Region\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactDatasetDaily",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "lineageTag": "ec4fc851-7b7b-4296-a7bf-94e59617ab15",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetKey",
            "dataType": "string",
            "lineageTag": "e51676c3-6e3a-4093-8633-e8e7f9b78eb1",
            "sourceColumn": "DatasetKey",
            "summarizeBy": "none"
          },
          {
            "name": "RowsExpected",
            "dataType": "int64",
            "lineageTag": "7b6949a6-8d5f-46c6-88ca-cde68db1f48d",
            "sourceColumn": "RowsExpected",
            "summarizeBy": "sum"
          },
          {
            "name": "RowsLoaded",
            "dataType": "int64",
            "lineageTag": "6b1860ad-04b0-4895-9332-ada20a094941",
            "sourceColumn": "RowsLoaded",
            "summarizeBy": "sum"
          },
          {
            "name": "CompletenessPct",
            "dataType": "double",
            "lineageTag": "3058f9c8-2492-4a7d-bd56-d6e36637fe79",
            "sourceColumn": "CompletenessPct",
            "summarizeBy": "sum"
          },
          {
            "name": "NullCriticalCount",
            "dataType": "int64",
            "lineageTag": "bd2fba51-6a5b-484c-bb79-046443013e68",
            "sourceColumn": "NullCriticalCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DuplicateKeyCount",
            "dataType": "int64",
            "lineageTag": "2a93d969-8641-47fc-b4d7-97b6d73f61ca",
            "sourceColumn": "DuplicateKeyCount",
            "summarizeBy": "sum"
          },
          {
            "name": "SchemaDriftCount",
            "dataType": "int64",
            "lineageTag": "7af4b389-15ee-4782-ad4d-b675aeb766f3",
            "sourceColumn": "SchemaDriftCount",
            "summarizeBy": "sum"
          },
          {
            "name": "FreshnessMinutes",
            "dataType": "int64",
            "lineageTag": "c3e8ece8-ad3d-4298-bea6-332407bb26f5",
            "sourceColumn": "FreshnessMinutes",
            "summarizeBy": "sum"
          },
          {
            "name": "FreshnessWithinSLAFlag",
            "dataType": "int64",
            "lineageTag": "c25d9d20-5703-4b9a-95e2-8d60e2e47985",
            "sourceColumn": "FreshnessWithinSLAFlag",
            "summarizeBy": "sum"
          },
          {
            "name": "DataQualityScore",
            "dataType": "double",
            "lineageTag": "a080d6e6-6c3e-404f-9bb8-abbcb14a6dc1",
            "sourceColumn": "DataQualityScore",
            "summarizeBy": "sum"
          },
          {
            "name": "ReconciliationVarianceAmount",
            "dataType": "double",
            "lineageTag": "e4766446-54be-40e6-8b0c-d7e7ce358d11",
            "sourceColumn": "ReconciliationVarianceAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "OpenIssueCount",
            "dataType": "int64",
            "lineageTag": "33afc1c8-0eb7-459f-ba9b-4b858caddb2d",
            "sourceColumn": "OpenIssueCount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ec859e1a-b790-44f4-ac94-a364d0262f9f",
        "partitions": [
          {
            "name": "FactDatasetDaily-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/factdatasetdaily.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"DateKey\", Int64.Type}, {\"DatasetKey\", type text}, {\"RowsExpected\", Int64.Type}, {\"RowsLoaded\", Int64.Type}, {\"CompletenessPct\", type number}, {\"NullCriticalCount\", Int64.Type}, {\"DuplicateKeyCount\", Int64.Type}, {\"SchemaDriftCount\", Int64.Type}, {\"FreshnessMinutes\", Int64.Type}, {\"FreshnessWithinSLAFlag\", Int64.Type}, {\"DataQualityScore\", type number}, {\"ReconciliationVarianceAmount\", type number}, {\"OpenIssueCount\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactRefreshRuns",
        "columns": [
          {
            "name": "RefreshRunKey",
            "dataType": "string",
            "lineageTag": "33a8bca1-9ea7-4e8c-b44d-88e2c5eec00b",
            "sourceColumn": "RefreshRunKey",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "lineageTag": "f37599bb-4d21-44dc-8eae-93f051bfb6e7",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetKey",
            "dataType": "string",
            "lineageTag": "f2ece1a8-b74a-4e99-b20c-7b4c62e2818f",
            "sourceColumn": "DatasetKey",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "dataType": "string",
            "lineageTag": "dad9f3ed-fcd4-46a3-852a-69c072b650f6",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "FailureCategory",
            "dataType": "string",
            "lineageTag": "84ad20a2-9ee8-4a4c-bae9-f4227fd9019e",
            "sourceColumn": "FailureCategory",
            "summarizeBy": "none"
          },
          {
            "name": "DurationMinutes",
            "dataType": "int64",
            "lineageTag": "7661ccc0-2c20-4804-88a8-4d85b9847ad9",
            "sourceColumn": "DurationMinutes",
            "summarizeBy": "sum"
          },
          {
            "name": "SLACompliantFlag",
            "dataType": "int64",
            "lineageTag": "25c3a20d-f9b0-4411-b685-a09562f791c9",
            "sourceColumn": "SLACompliantFlag",
            "summarizeBy": "sum"
          },
          {
            "name": "RetryCount",
            "dataType": "int64",
            "lineageTag": "36330ffa-1961-4c4f-8f5b-d0c2bb74dd31",
            "sourceColumn": "RetryCount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "783bf63f-0f4f-42c8-b0c9-6203bb1b0691",
        "partitions": [
          {
            "name": "FactRefreshRuns-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/factrefreshruns.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"RefreshRunKey\", type text}, {\"DateKey\", Int64.Type}, {\"DatasetKey\", type text}, {\"Status\", type text}, {\"FailureCategory\", type text}, {\"DurationMinutes\", Int64.Type}, {\"SLACompliantFlag\", Int64.Type}, {\"RetryCount\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactReconciliation",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "lineageTag": "dc5a7597-0528-491d-86c8-8ac21228576d",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetKey",
            "dataType": "string",
            "lineageTag": "f126c922-0af3-4dff-ba50-f2eb12541847",
            "sourceColumn": "DatasetKey",
            "summarizeBy": "none"
          },
          {
            "name": "DeptKey",
            "dataType": "string",
            "lineageTag": "37d41e80-11cf-436b-acb9-ca0906835f79",
            "sourceColumn": "DeptKey",
            "summarizeBy": "none"
          },
          {
            "name": "LedgerAmount",
            "dataType": "double",
            "lineageTag": "d5d30ef7-2c7e-486f-9748-8c913fd3a856",
            "sourceColumn": "LedgerAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "SubledgerAmount",
            "dataType": "double",
            "lineageTag": "e558b711-ec71-43e5-9ef1-cc427bdee44c",
            "sourceColumn": "SubledgerAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "VarianceAmount",
            "dataType": "double",
            "lineageTag": "303bd404-7768-4c10-af74-d4bb3e75416b",
            "sourceColumn": "VarianceAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "VariancePct",
            "dataType": "double",
            "lineageTag": "284dd301-7c5a-4c2c-8f23-7d41cba883ce",
            "sourceColumn": "VariancePct",
            "summarizeBy": "sum"
          },
          {
            "name": "ReconciliationStatus",
            "dataType": "string",
            "lineageTag": "927243e9-671f-4b06-a037-207dd6fc005b",
            "sourceColumn": "ReconciliationStatus",
            "summarizeBy": "none"
          },
          {
            "name": "AgingBucket",
            "dataType": "string",
            "lineageTag": "73da0c3d-df76-4bc5-98c0-689d4174d41a",
            "sourceColumn": "AgingBucket",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bc1fb01b-c93a-4add-9d46-9329ef1870e7",
        "partitions": [
          {
            "name": "FactReconciliation-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/factreconciliation.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"DateKey\", Int64.Type}, {\"DatasetKey\", type text}, {\"DeptKey\", type text}, {\"LedgerAmount\", type number}, {\"SubledgerAmount\", type number}, {\"VarianceAmount\", type number}, {\"VariancePct\", type number}, {\"ReconciliationStatus\", type text}, {\"AgingBucket\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactUsage",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "lineageTag": "b416d00e-39af-4e02-8b97-dd941e3b4686",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ReportKey",
            "dataType": "string",
            "lineageTag": "ee42a9da-bca0-4aa1-9fbc-50ef8f25d9ac",
            "sourceColumn": "ReportKey",
            "summarizeBy": "none"
          },
          {
            "name": "DeptKey",
            "dataType": "string",
            "lineageTag": "79b246a9-476f-4c96-832d-4d60d39b3b3b",
            "sourceColumn": "DeptKey",
            "summarizeBy": "none"
          },
          {
            "name": "Views",
            "dataType": "int64",
            "lineageTag": "bad74e8e-2cff-490a-82b8-ab0422d291a7",
            "sourceColumn": "Views",
            "summarizeBy": "sum"
          },
          {
            "name": "UniqueViewers",
            "dataType": "int64",
            "lineageTag": "b192757e-2489-4e91-8f48-969d09b8b51e",
            "sourceColumn": "UniqueViewers",
            "summarizeBy": "sum"
          },
          {
            "name": "ExportEvents",
            "dataType": "int64",
            "lineageTag": "2c36cf4a-02b8-448b-a8bc-7e8e424b677e",
            "sourceColumn": "ExportEvents",
            "summarizeBy": "sum"
          },
          {
            "name": "SubscriptionRuns",
            "dataType": "int64",
            "lineageTag": "13f36f6d-46d2-44ce-a1f7-e284c0bd16e0",
            "sourceColumn": "SubscriptionRuns",
            "summarizeBy": "sum"
          },
          {
            "name": "AvgLoadSeconds",
            "dataType": "double",
            "lineageTag": "4744627a-db4c-4ff3-89f1-c4530184d2f8",
            "sourceColumn": "AvgLoadSeconds",
            "summarizeBy": "sum"
          },
          {
            "name": "FailedVisualCount",
            "dataType": "int64",
            "lineageTag": "e206e2a5-7818-4aec-a757-63c6e3ba1330",
            "sourceColumn": "FailedVisualCount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8fa7837b-e7b9-4be3-a5ff-b7ea73bca427",
        "partitions": [
          {
            "name": "FactUsage-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/factusage.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"DateKey\", Int64.Type}, {\"ReportKey\", type text}, {\"DeptKey\", type text}, {\"Views\", Int64.Type}, {\"UniqueViewers\", Int64.Type}, {\"ExportEvents\", Int64.Type}, {\"SubscriptionRuns\", Int64.Type}, {\"AvgLoadSeconds\", type number}, {\"FailedVisualCount\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactAccessReview",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "lineageTag": "75d2657d-98be-4f1c-959b-79f27cb9a951",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ReportKey",
            "dataType": "string",
            "lineageTag": "f6c0a254-1a3f-44fc-9f75-3ab49f3e26b7",
            "sourceColumn": "ReportKey",
            "summarizeBy": "none"
          },
          {
            "name": "DeptKey",
            "dataType": "string",
            "lineageTag": "9479f4dd-5a07-4011-a749-eed9860d2e96",
            "sourceColumn": "DeptKey",
            "summarizeBy": "none"
          },
          {
            "name": "UsersWithAccess",
            "dataType": "int64",
            "lineageTag": "b26c5829-e874-4cc8-9455-f82b91da8394",
            "sourceColumn": "UsersWithAccess",
            "summarizeBy": "sum"
          },
          {
            "name": "PrivilegedUsers",
            "dataType": "int64",
            "lineageTag": "fffaf992-9cbd-4dc4-8590-6b31a9328f03",
            "sourceColumn": "PrivilegedUsers",
            "summarizeBy": "sum"
          },
          {
            "name": "OrphanedUsers",
            "dataType": "int64",
            "lineageTag": "b9c6786d-e310-47a3-bf26-1370be72b6ff",
            "sourceColumn": "OrphanedUsers",
            "summarizeBy": "sum"
          },
          {
            "name": "RLSExceptions",
            "dataType": "int64",
            "lineageTag": "35ec2fa9-8a7a-41c4-a160-b46061a993e8",
            "sourceColumn": "RLSExceptions",
            "summarizeBy": "sum"
          },
          {
            "name": "PendingAccessReviews",
            "dataType": "int64",
            "lineageTag": "3bdc4452-6870-4f59-a130-8cafa44db019",
            "sourceColumn": "PendingAccessReviews",
            "summarizeBy": "sum"
          },
          {
            "name": "UnauthorizedSharingEvents",
            "dataType": "int64",
            "lineageTag": "11d3f2c1-4af5-4d2e-89ec-d0cf6730ed70",
            "sourceColumn": "UnauthorizedSharingEvents",
            "summarizeBy": "sum"
          },
          {
            "name": "DeploymentControlScore",
            "dataType": "double",
            "lineageTag": "a7e7947a-2976-481c-956d-a45f3ecec0b3",
            "sourceColumn": "DeploymentControlScore",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "cf65c0cd-e7d5-4a8d-a70c-97ce8e1dc25a",
        "partitions": [
          {
            "name": "FactAccessReview-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/factaccessreview.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"DateKey\", Int64.Type}, {\"ReportKey\", type text}, {\"DeptKey\", type text}, {\"UsersWithAccess\", Int64.Type}, {\"PrivilegedUsers\", Int64.Type}, {\"OrphanedUsers\", Int64.Type}, {\"RLSExceptions\", Int64.Type}, {\"PendingAccessReviews\", Int64.Type}, {\"UnauthorizedSharingEvents\", Int64.Type}, {\"DeploymentControlScore\", type number}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactIncidents",
        "columns": [
          {
            "name": "IncidentKey",
            "dataType": "string",
            "lineageTag": "3a4a6f62-3f43-49bb-a78e-cd81133a98d2",
            "sourceColumn": "IncidentKey",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "lineageTag": "6acd6855-411c-400d-8750-aa269f18a683",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "OpenMonthIndex",
            "dataType": "int64",
            "lineageTag": "44b63c5f-d547-4363-8cd1-e0f4a4a04da7",
            "sourceColumn": "OpenMonthIndex",
            "summarizeBy": "sum"
          },
          {
            "name": "CloseMonthIndex",
            "dataType": "int64",
            "lineageTag": "658ce7cb-42f7-4769-afcf-58eeff7b3f8e",
            "sourceColumn": "CloseMonthIndex",
            "summarizeBy": "sum"
          },
          {
            "name": "DatasetKey",
            "dataType": "string",
            "lineageTag": "d764306a-14db-45e0-a7d1-44fa43ff642d",
            "sourceColumn": "DatasetKey",
            "summarizeBy": "none"
          },
          {
            "name": "Severity",
            "dataType": "string",
            "lineageTag": "48846ed1-b74a-4538-b38c-a93d03fb82b6",
            "sourceColumn": "Severity",
            "summarizeBy": "none"
          },
          {
            "name": "IncidentStatus",
            "dataType": "string",
            "lineageTag": "e0a06073-ba52-45c1-8a3e-5f24096105a9",
            "sourceColumn": "IncidentStatus",
            "summarizeBy": "none"
          },
          {
            "name": "RootCause",
            "dataType": "string",
            "lineageTag": "5aed49f5-3c62-4ec5-b724-66b39abb4a11",
            "sourceColumn": "RootCause",
            "summarizeBy": "none"
          },
          {
            "name": "MTTRHours",
            "dataType": "double",
            "lineageTag": "a3748032-f669-4dbc-a874-de49da4d97bb",
            "sourceColumn": "MTTRHours",
            "summarizeBy": "sum"
          },
          {
            "name": "SLAOverdueFlag",
            "dataType": "int64",
            "lineageTag": "1b3a68f9-ccb6-469d-ab04-a68c62155285",
            "sourceColumn": "SLAOverdueFlag",
            "summarizeBy": "sum"
          },
          {
            "name": "BusinessImpact",
            "dataType": "string",
            "lineageTag": "1520ddaa-f820-49d5-802d-52cc87deae59",
            "sourceColumn": "BusinessImpact",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bd50683c-fe3a-4b5a-a5c1-ab1f071525e5",
        "partitions": [
          {
            "name": "FactIncidents-Import",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/prepared/factincidents.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(PromotedHeaders, {{\"IncidentKey\", type text}, {\"DateKey\", Int64.Type}, {\"OpenMonthIndex\", Int64.Type}, {\"CloseMonthIndex\", Int64.Type}, {\"DatasetKey\", type text}, {\"Severity\", type text}, {\"IncidentStatus\", type text}, {\"RootCause\", type text}, {\"MTTRHours\", type number}, {\"SLAOverdueFlag\", Int64.Type}, {\"BusinessImpact\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Measures",
        "columns": [
          {
            "name": "MeasureKey",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bc80b561-7bd1-4b11-b3e3-724c52286f07",
            "sourceColumn": "MeasureKey"
          }
        ],
        "lineageTag": "b0998165-5005-4b5d-ba8d-a44f8dfbb160",
        "measures": [
          {
            "name": "Dataset Count",
            "displayFolder": "Overview",
            "expression": "DISTINCTCOUNT ( DimDataset[DatasetKey] )",
            "formatString": "#,0",
            "lineageTag": "aa4b5aeb-7d57-4d8f-9ce3-935f6718ddcc"
          },
          {
            "name": "Critical Dataset Count",
            "displayFolder": "Overview",
            "expression": "CALCULATE ( [Dataset Count], DimDataset[Criticality] = \"Tier 1\" )",
            "formatString": "#,0",
            "lineageTag": "59149879-2a3b-40df-9362-244ce96281cd"
          },
          {
            "name": "Certified Dataset Count",
            "displayFolder": "Overview",
            "expression": "CALCULATE ( [Dataset Count], DimDataset[Certified] = \"Y\" )",
            "formatString": "#,0",
            "lineageTag": "c154f50c-46ab-48e7-a952-09bcaae07f6b"
          },
          {
            "name": "Data Quality Score",
            "displayFolder": "Quality",
            "expression": "AVERAGE ( FactDatasetDaily[DataQualityScore] )",
            "formatString": "0.0",
            "lineageTag": "240f7718-a912-461f-a131-638293b4eaea"
          },
          {
            "name": "Completeness %",
            "displayFolder": "Quality",
            "expression": "DIVIDE ( SUM ( FactDatasetDaily[RowsLoaded] ), SUM ( FactDatasetDaily[RowsExpected] ) )",
            "formatString": "0.0%",
            "lineageTag": "584d0ff3-6896-4d16-a132-0997078257c2"
          },
          {
            "name": "Freshness SLA %",
            "displayFolder": "Reliability",
            "expression": "DIVIDE ( SUM ( FactDatasetDaily[FreshnessWithinSLAFlag] ), COUNTROWS ( FactDatasetDaily ) )",
            "formatString": "0.0%",
            "lineageTag": "36615f7c-a4de-4108-b34e-33133bcd8116"
          },
          {
            "name": "Refresh Runs",
            "displayFolder": "Reliability",
            "expression": "COUNTROWS ( FactRefreshRuns )",
            "formatString": "#,0",
            "lineageTag": "1eb388f9-3531-46f7-8ab5-388088a77aa4"
          },
          {
            "name": "Refresh Success %",
            "displayFolder": "Reliability",
            "expression": "DIVIDE ( CALCULATE ( [Refresh Runs], FactRefreshRuns[Status] = \"Success\" ), [Refresh Runs] )",
            "formatString": "0.0%",
            "lineageTag": "cf78b057-3da6-47d5-bd3f-8029b3fc3d15"
          },
          {
            "name": "Failed Refreshes",
            "displayFolder": "Reliability",
            "expression": "CALCULATE ( [Refresh Runs], FactRefreshRuns[Status] = \"Failed\" )",
            "formatString": "#,0",
            "lineageTag": "f17a410f-cecb-4136-af72-0d04ac6b6768"
          },
          {
            "name": "Avg Refresh Duration Min",
            "displayFolder": "Reliability",
            "expression": "AVERAGE ( FactRefreshRuns[DurationMinutes] )",
            "formatString": "0.0",
            "lineageTag": "8f7117f2-1b5d-451c-9aa6-799f210a8a6d"
          },
          {
            "name": "DQ Issue Count",
            "displayFolder": "Quality",
            "expression": "SUM ( FactDatasetDaily[NullCriticalCount] ) + SUM ( FactDatasetDaily[DuplicateKeyCount] ) + SUM ( FactDatasetDaily[SchemaDriftCount] )",
            "formatString": "#,0",
            "lineageTag": "7f5300d6-bb35-4830-bdef-2c128e5c0891"
          },
          {
            "name": "Open Incidents",
            "displayFolder": "Reliability",
            "expression": [
              "VAR AsOfMonth = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "RETURN",
              "    CALCULATE (",
              "        COUNTROWS ( FactIncidents ),",
              "        REMOVEFILTERS ( DimDate ),",
              "        KEEPFILTERS (",
              "            FILTER (",
              "                FactIncidents,",
              "                FactIncidents[OpenMonthIndex] <= AsOfMonth",
              "                    && ( FactIncidents[CloseMonthIndex] = 0 || FactIncidents[CloseMonthIndex] > AsOfMonth )",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "713a6a88-5497-425e-87d4-efb21b8e039a"
          },
          {
            "name": "Avg MTTR Hours",
            "displayFolder": "Reliability",
            "expression": "AVERAGE ( FactIncidents[MTTRHours] )",
            "formatString": "0.0",
            "lineageTag": "ca9f009f-1c08-4077-8486-798a5ad4c913"
          },
          {
            "name": "Reconciliation Variance",
            "displayFolder": "Reconciliation",
            "expression": "SUM ( FactReconciliation[VarianceAmount] )",
            "formatString": "$#,0",
            "lineageTag": "a3287247-d166-4cc3-9a2b-1e9e1517f5e5"
          },
          {
            "name": "Abs Reconciliation Variance",
            "displayFolder": "Reconciliation",
            "expression": "SUMX ( FactReconciliation, ABS ( FactReconciliation[VarianceAmount] ) )",
            "formatString": "$#,0",
            "lineageTag": "81e3cc56-d924-4e09-9685-ba4d51e9d5a2"
          },
          {
            "name": "Reconciliation Pass %",
            "displayFolder": "Reconciliation",
            "expression": "DIVIDE ( CALCULATE ( COUNTROWS ( FactReconciliation ), FactReconciliation[ReconciliationStatus] = \"Pass\" ), COUNTROWS ( FactReconciliation ) )",
            "formatString": "0.0%",
            "lineageTag": "162adce8-fd58-4512-a917-c8c52abb2726"
          },
          {
            "name": "Report Views",
            "displayFolder": "Adoption",
            "expression": "SUM ( FactUsage[Views] )",
            "formatString": "#,0",
            "lineageTag": "4301ebd5-379e-40c1-9ae0-cc5ff8bf827a"
          },
          {
            "name": "Active Viewer Days",
            "displayFolder": "Adoption",
            "expression": "SUM ( FactUsage[UniqueViewers] )",
            "formatString": "#,0",
            "lineageTag": "21a5e5f2-bd81-4f98-ac77-5dd4cc77ffe2"
          },
          {
            "name": "Export Events",
            "displayFolder": "Adoption",
            "expression": "SUM ( FactUsage[ExportEvents] )",
            "formatString": "#,0",
            "lineageTag": "7ea5e34d-2d36-4b67-9713-df639dafb5ab"
          },
          {
            "name": "Avg Report Load Seconds",
            "displayFolder": "Adoption",
            "expression": "AVERAGE ( FactUsage[AvgLoadSeconds] )",
            "formatString": "0.0",
            "lineageTag": "85cd40b0-fb9a-4cbc-9f6d-bb59ce317b5a"
          },
          {
            "name": "Failed Visual Count",
            "displayFolder": "Adoption",
            "expression": "SUM ( FactUsage[FailedVisualCount] )",
            "formatString": "#,0",
            "lineageTag": "97bc0d16-9780-46a9-bba4-8f66eafd03ab"
          },
          {
            "name": "Access Risk Events",
            "displayFolder": "Controls",
            "expression": "SUM ( FactAccessReview[RLSExceptions] ) + SUM ( FactAccessReview[OrphanedUsers] ) + SUM ( FactAccessReview[UnauthorizedSharingEvents] )",
            "formatString": "#,0",
            "lineageTag": "d967c10b-d341-43da-bcd0-c1efa302bc35"
          },
          {
            "name": "RLS Exceptions",
            "displayFolder": "Controls",
            "expression": "SUM ( FactAccessReview[RLSExceptions] )",
            "formatString": "#,0",
            "lineageTag": "71cd2ce3-0815-4c12-9792-be34f63228f1"
          },
          {
            "name": "Pending Access Reviews",
            "displayFolder": "Controls",
            "expression": "SUM ( FactAccessReview[PendingAccessReviews] )",
            "formatString": "#,0",
            "lineageTag": "29f90cec-e09d-4b09-8d83-00a3a151926f"
          },
          {
            "name": "Deployment Control Score",
            "displayFolder": "Controls",
            "expression": "AVERAGE ( FactAccessReview[DeploymentControlScore] )",
            "formatString": "0.0",
            "lineageTag": "14262402-f9ee-4eef-90e0-33a7b9c252a0"
          },
          {
            "name": "Current Lens Label",
            "displayFolder": "Executive Lens",
            "expression": [
              "VAR MonthLens = SELECTEDVALUE ( DimDate[MonthYear], \"All Months\" )",
              "VAR DomainLens = SELECTEDVALUE ( DimDataset[Domain], \"All Domains\" )",
              "VAR CriticalityLens = SELECTEDVALUE ( DimDataset[Criticality], \"All Tiers\" )",
              "RETURN \"Lens: \" & MonthLens & \" | \" & DomainLens & \" | \" & CriticalityLens"
            ],
            "lineageTag": "35618693-4397-434c-94cb-2d74479c3c01"
          },
          {
            "name": "Usage Lens Label",
            "displayFolder": "Executive Lens",
            "expression": [
              "VAR WorkspaceLens = SELECTEDVALUE ( DimReport[Workspace], \"All Workspaces\" )",
              "VAR SensitivityLens = SELECTEDVALUE ( DimReport[SensitivityLabel], \"All Sensitivity\" )",
              "RETURN \"Lens: \" & WorkspaceLens & \" | \" & SensitivityLens"
            ],
            "lineageTag": "9c897340-215a-4932-acb6-7d6d5ced80bf"
          },
          {
            "name": "Action Lens Label",
            "displayFolder": "Executive Lens",
            "expression": [
              "VAR MonthLens = SELECTEDVALUE ( DimDate[MonthYear], \"All Months\" )",
              "VAR DepartmentLens = SELECTEDVALUE ( DimDepartment[Department], \"All Departments\" )",
              "RETURN \"Lens: \" & MonthLens & \" | \" & DepartmentLens"
            ],
            "lineageTag": "46b825f7-2b89-44fb-bfc5-5798d48a631b"
          },
          {
            "name": "Governance Decision Chip",
            "displayFolder": "Executive Lens",
            "expression": [
              "VAR Dq = [Data Quality Score]",
              "VAR Fresh = [Freshness SLA %]",
              "VAR OpenIncidents = [Open Incidents]",
              "RETURN IF ( Dq >= 92 && Fresh >= 0.95 && OpenIncidents <= 30, \"PASS: trust posture on track\", IF ( OpenIncidents > 45, \"ESCALATE: incident load above guardrail\", \"WATCH: owner review required\" ) )"
            ],
            "lineageTag": "4153b43f-9cd6-4368-9ac0-f2e2767bf3b9"
          },
          {
            "name": "Reliability Decision Chip",
            "displayFolder": "Executive Lens",
            "expression": [
              "VAR Failed = [Failed Refreshes]",
              "VAR Complete = [Completeness %]",
              "VAR RecPass = [Reconciliation Pass %]",
              "RETURN IF ( Failed <= 25 && Complete >= 0.99 && RecPass >= 0.90, \"PASS: close-ready reliability\", IF ( Failed > 40 || Complete < 0.985, \"ESCALATE: reliability SLA at risk\", \"WATCH: validate exception queue\" ) )"
            ],
            "lineageTag": "08b8b2c9-41d9-4243-9ce0-bb11ce7a2505"
          },
          {
            "name": "Adoption Decision Chip",
            "displayFolder": "Executive Lens",
            "expression": [
              "VAR LoadSec = [Avg Report Load Seconds]",
              "VAR AccessRisk = [Access Risk Events]",
              "VAR ControlScore = [Deployment Control Score]",
              "RETURN IF ( LoadSec <= 3.0 && AccessRisk <= 800 && ControlScore >= 92, \"PASS: governed adoption healthy\", IF ( AccessRisk > 950, \"ESCALATE: access risk concentration\", \"WATCH: control follow-up needed\" ) )"
            ],
            "lineageTag": "51b26efd-c1c9-4ef6-80e8-de68ecbdce26"
          },
          {
            "name": "Risk Action Decision Chip",
            "displayFolder": "Executive Lens",
            "expression": [
              "VAR OpenIncidents = [Open Incidents]",
              "VAR AccessRisk = [Access Risk Events]",
              "VAR Pending = [Pending Access Reviews]",
              "RETURN IF ( OpenIncidents <= 30 && AccessRisk <= 800 && Pending <= 900, \"PASS: action load inside guardrail\", IF ( OpenIncidents > 45 || Pending > 1100, \"ESCALATE: prioritize owner actions\", \"WATCH: triage aging queues\" ) )"
            ],
            "lineageTag": "897fc21d-f479-47ff-a79a-cf5b9649aa2c"
          },
          {
            "name": "Data Quality Score Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Data Quality Score] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%231B4D89\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "16360e05-ccf1-48e2-bb65-97fe2be400c3"
          },
          {
            "name": "Freshness SLA % Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Freshness SLA %] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%232A9D8F\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "bdb66256-c997-4420-a968-f19cc91be56f"
          },
          {
            "name": "Refresh Success % Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Refresh Success %] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%23247A5A\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "dd6bdf94-56cc-4cae-ac24-b239ba1959e6"
          },
          {
            "name": "Open Incidents Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Open Incidents] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23C44E52\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "5ac765f8-40a1-4e87-bcd1-1d09fbb7264d"
          },
          {
            "name": "Failed Refreshes Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Failed Refreshes] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23C44E52\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "f0d4d53c-bfbf-43c5-8158-da341fa7cc53"
          },
          {
            "name": "Completeness % Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Completeness %] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%232A9D8F\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "a0cd2e54-1dd0-4ab6-a3da-c6db542d7a21"
          },
          {
            "name": "Reconciliation Pass % Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Reconciliation Pass %] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%23247A5A\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "e22a608d-8303-4c39-9d2c-0922bdc2bf4c"
          },
          {
            "name": "Avg MTTR Hours Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Avg MTTR Hours] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23D99A2B\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "9e16b1e9-c677-4a04-aefb-90dcd3f93b70"
          },
          {
            "name": "Report Views Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Report Views] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%231B4D89\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "1a278e67-1862-49f4-9ed2-771877584502"
          },
          {
            "name": "Active Viewer Days Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Active Viewer Days] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%232A9D8F\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "32378698-c383-4bf8-98e5-41f118b6fd06"
          },
          {
            "name": "Access Risk Events Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Access Risk Events] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23C44E52\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "6aa948f9-a687-49f8-8e57-9c00210858a9"
          },
          {
            "name": "Deployment Control Score Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Deployment Control Score] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%23247A5A\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "e08f6e11-47fb-4d24-8455-9f6b80aebbaf"
          },
          {
            "name": "Pending Access Reviews Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Pending Access Reviews] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23D99A2B\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "825f2827-f1fa-44a1-a617-d0524ed21f75"
          },
          {
            "name": "Abs Reconciliation Variance Sparkline SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline SVG",
            "expression": [
              "VAR LatestIndex = MAXX ( ALLSELECTED ( DimDate ), DimDate[MonthIndex] )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        FILTER (",
              "            ALL ( DimDate ),",
              "            DimDate[MonthIndex] <= LatestIndex",
              "                && DimDate[MonthIndex] > LatestIndex - 12",
              "        ),",
              "        \"__Value\", CALCULATE ( [Abs Reconciliation Variance] )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = MINX ( CleanTable, [__Value] )",
              "VAR MaxValue = MAXX ( CleanTable, [__Value] )",
              "VAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], ASC ), [__Value] )",
              "VAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthIndex], DESC ), [__Value] )",
              "VAR StartYValue = 38 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR EndYValue = 38 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%238E5572\", \"%23C94A4A\" )",
              "VAR Points =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR RankValue = RANKX ( CleanTable, DimDate[MonthIndex],, ASC, DENSE ) - 1",
              "        VAR XValue = 8 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 184",
              "        VAR YValue = 38 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 30",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        DimDate[MonthIndex],",
              "        ASC",
              "    )",
              "RETURN",
              "    IF (",
              "        RowCount < 2,",
              "        BLANK (),",
              "        \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='44' viewBox='0 0 200 44'><rect x='0' y='0' width='200' height='44' rx='7' fill='%23F4FAFB'/><line x1='8' y1='25' x2='192' y2='25' stroke='%23D3E0E3' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\"",
              "            & Points",
              "            & \"' fill='none' stroke='\"",
              "            & TrendColor",
              "            & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='8' cy='\"",
              "            & FORMAT ( StartYValue, \"0.0\" )",
              "            & \"' r='3' fill='%23FFFFFF' stroke='%237D9197' stroke-width='1.4'/><circle cx='192' cy='\"",
              "            & FORMAT ( EndYValue, \"0.0\" )",
              "            & \"' r='4' fill='\"",
              "            & TrendColor",
              "            & \"' stroke='%23FFFFFF' stroke-width='1.4'/></svg>\"",
              "    )"
            ],
            "lineageTag": "dd881c0f-88be-4aa1-9c6d-54f536ba5d11"
          },
          {
            "name": "Data Quality Score KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Data Quality Score],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Data Quality Score],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+0.0;-0.0;0.0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue >= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Data Quality Score],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%231B4D89\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%231B4D89' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%231B4D89' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>DQ Score</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%231B4D89'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "6ec29b4d-3fcb-4789-8744-99346dcbfcce"
          },
          {
            "name": "Freshness SLA % KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Freshness SLA %],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Freshness SLA %],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue * 100, \"+0.0;-0.0;0.0\" ) & \"pt\" )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue >= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Freshness SLA %],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%232A9D8F\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%232A9D8F' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%232A9D8F' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Freshness SLA</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%232A9D8F'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "41ddddc2-ee07-4de2-a30e-e6d6849433aa"
          },
          {
            "name": "Refresh Success % KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Refresh Success %],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Refresh Success %],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue * 100, \"+0.0;-0.0;0.0\" ) & \"pt\" )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue >= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Refresh Success %],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%23247A5A\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%23247A5A' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%23247A5A' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Refresh Success</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23247A5A'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "f5764936-32b5-4bab-9a00-8aaf4c064eb0"
          },
          {
            "name": "Open Incidents KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Open Incidents],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Open Incidents],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"#,0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"#,0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+#,0;-#,0;0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue <= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Open Incidents],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23C44E52\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%23C44E52' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%23C44E52' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Open Incidents</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23C44E52'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "68902ef5-345c-4c3c-90c7-acb581f2b892"
          },
          {
            "name": "Failed Refreshes KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Failed Refreshes],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Failed Refreshes],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"#,0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"#,0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+#,0;-#,0;0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue <= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Failed Refreshes],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23C44E52\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%23C44E52' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%23C44E52' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Failed Refreshes</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23C44E52'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "ed21e7f3-f310-4994-813e-5ce84fdd7ab4"
          },
          {
            "name": "Completeness % KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Completeness %],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Completeness %],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue * 100, \"+0.0;-0.0;0.0\" ) & \"pt\" )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue >= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Completeness %],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%232A9D8F\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%232A9D8F' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%232A9D8F' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Completeness</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%232A9D8F'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "4c6f0c34-07e9-4b7d-b01d-61ab40a3b502"
          },
          {
            "name": "Reconciliation Pass % KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Reconciliation Pass %],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Reconciliation Pass %],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue * 100, \"+0.0;-0.0;0.0\" ) & \"pt\" )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue >= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Reconciliation Pass %],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%23247A5A\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%23247A5A' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%23247A5A' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Recon Pass</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23247A5A'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "9265f1ba-59c9-44d4-9866-dfcb6615e650"
          },
          {
            "name": "Avg MTTR Hours KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Avg MTTR Hours],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Avg MTTR Hours],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+0.0;-0.0;0.0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue <= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Avg MTTR Hours],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23D99A2B\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%23D99A2B' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%23D99A2B' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Avg MTTR</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23D99A2B'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "4d2e4187-c39c-4d44-9fd7-f95b68cc03f7"
          },
          {
            "name": "Report Views KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Report Views],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Report Views],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"#,0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"#,0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+#,0;-#,0;0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue >= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Report Views],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%231B4D89\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%231B4D89' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%231B4D89' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Report Views</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%231B4D89'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "eaa0b2f1-47ae-4f32-a553-e49105ecfac0"
          },
          {
            "name": "Active Viewer Days KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Active Viewer Days],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Active Viewer Days],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"#,0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"#,0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+#,0;-#,0;0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue >= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Active Viewer Days],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%232A9D8F\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%232A9D8F' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%232A9D8F' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Viewer Days</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%232A9D8F'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "2f436ac5-8cd9-4ff2-be81-d3d87da19ad3"
          },
          {
            "name": "Access Risk Events KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Access Risk Events],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Access Risk Events],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"#,0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"#,0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+#,0;-#,0;0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue <= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Access Risk Events],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23C44E52\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%23C44E52' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%23C44E52' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Access Risk</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23C44E52'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "744156f6-aa93-4d10-82b0-edbf48d1fcb7"
          },
          {
            "name": "Deployment Control Score KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Deployment Control Score],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Deployment Control Score],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+0.0;-0.0;0.0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue >= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Deployment Control Score],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue >= FirstValue, \"%23247A5A\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%23247A5A' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%23247A5A' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Control Score</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23247A5A'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "7471a283-f878-4d8f-81d8-5bd498b88a1f"
          },
          {
            "name": "Pending Access Reviews KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Pending Access Reviews],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Pending Access Reviews],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"#,0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"#,0\" ) )",
              "VAR YoYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangeValue, \"+#,0;-#,0;0\" ) )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue <= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Pending Access Reviews],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%23D99A2B\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%23D99A2B' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%23D99A2B' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Pending Reviews</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23D99A2B'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "fe3e338b-a181-47e3-b9de-9f0924129bcd"
          },
          {
            "name": "Abs Reconciliation Variance KPI Card SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "KPI Card SVG",
            "expression": [
              "VAR SelectedMonths = ALLSELECTED ( DimDate[MonthIndex] )",
              "VAR SelectedMonthCount = COUNTROWS ( SelectedMonths )",
              "VAR LatestIndex = MAXX ( SelectedMonths, DimDate[MonthIndex] )",
              "VAR MonthFilterActive =",
              "    ISFILTERED ( DimDate[MonthYear] )",
              "        || ISFILTERED ( DimDate[MonthIndex] )",
              "VAR UseSelectedMonths =",
              "    MonthFilterActive",
              "        && SelectedMonthCount > 1",
              "        && SelectedMonthCount <= 12",
              "VAR PriorIndex = LatestIndex - 12",
              "VAR RawCurrentValue =",
              "    CALCULATE (",
              "        [Abs Reconciliation Variance],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = LatestIndex )",
              "    )",
              "VAR CurrentValue = COALESCE ( RawCurrentValue, 0 )",
              "VAR PriorValue =",
              "    CALCULATE (",
              "        [Abs Reconciliation Variance],",
              "        FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = PriorIndex )",
              "    )",
              "VAR ChangeValue = CurrentValue - PriorValue",
              "VAR ValueTextRaw = FORMAT ( CurrentValue, \"$#,0\" )",
              "VAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"$#,0\" ) )",
              "VAR YoYTextRaw =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"n/a\",",
              "        SWITCH (",
              "            TRUE (),",
              "            ABS ( ChangeValue ) >= 1000000, FORMAT ( DIVIDE ( ChangeValue, 1000000 ), \"+$0.0M;-$0.0M;$0.0M\" ),",
              "            ABS ( ChangeValue ) >= 1000, FORMAT ( DIVIDE ( ChangeValue, 1000 ), \"+$0.0K;-$0.0K;$0.0K\" ),",
              "            FORMAT ( ChangeValue, \"+$#,0;-$#,0;$0\" )",
              "        )",
              "    )",
              "VAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )",
              "VAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )",
              "VAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )",
              "VAR YoYColor =",
              "    IF (",
              "        ISBLANK ( PriorValue ),",
              "        \"%2355707D\",",
              "        IF ( ChangeValue <= 0, \"%23247A5A\", \"%23C44E52\" )",
              "    )",
              "VAR SelectedAxisMonths =",
              "    SELECTCOLUMNS (",
              "        SelectedMonths,",
              "        \"AxisMonthIndex\", DimDate[MonthIndex]",
              "    )",
              "VAR TrailingAxisMonths =",
              "    SELECTCOLUMNS (",
              "        GENERATESERIES ( LatestIndex - 11, LatestIndex, 1 ),",
              "        \"AxisMonthIndex\", [Value]",
              "    )",
              "VAR AxisMonths =",
              "    DISTINCT (",
              "        UNION (",
              "            FILTER ( SelectedAxisMonths, UseSelectedMonths ),",
              "            FILTER ( TrailingAxisMonths, NOT UseSelectedMonths )",
              "        )",
              "    )",
              "VAR MonthTable =",
              "    ADDCOLUMNS (",
              "        AxisMonths,",
              "        \"AxisValue\",",
              "            VAR ThisMonthIndex = [AxisMonthIndex]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Abs Reconciliation Variance],",
              "                    FILTER ( ALL ( DimDate ), DimDate[MonthIndex] = ThisMonthIndex )",
              "                )",
              "    )",
              "VAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [AxisValue] ) )",
              "VAR RowCount = COUNTROWS ( CleanTable )",
              "VAR MinValue = COALESCE ( MINX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR MaxValue = COALESCE ( MAXX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR FirstValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], ASC ), [AxisValue] ), CurrentValue )",
              "VAR LastValue = COALESCE ( MINX ( TOPN ( 1, CleanTable, [AxisMonthIndex], DESC ), [AxisValue] ), CurrentValue )",
              "VAR MinAxisIndex = COALESCE ( MINX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR MaxAxisIndex = COALESCE ( MAXX ( CleanTable, [AxisMonthIndex] ), LatestIndex )",
              "VAR SparkX0 = 132",
              "VAR SparkX1 = 236",
              "VAR SparkW = SparkX1 - SparkX0",
              "VAR SparkYTop = 44",
              "VAR SparkYBase = 88",
              "VAR SparkH = SparkYBase - SparkYTop",
              "VAR AverageValue = COALESCE ( AVERAGEX ( CleanTable, [AxisValue] ), CurrentValue )",
              "VAR StartYValue = SparkYBase - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR EndYValue = SparkYBase - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR ReferenceYValue = SparkYBase - DIVIDE ( AverageValue - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "VAR TrendColor = IF ( LastValue <= FirstValue, \"%238E5572\", \"%23C44E52\" )",
              "VAR LinePoints =",
              "    CONCATENATEX (",
              "        CleanTable,",
              "        VAR XValue = SparkX0 + DIVIDE ( [AxisMonthIndex] - MinAxisIndex, MAX ( 1, MaxAxisIndex - MinAxisIndex ), 0 ) * SparkW",
              "        VAR YValue = SparkYBase - DIVIDE ( [AxisValue] - MinValue, MaxValue - MinValue, 0.5 ) * SparkH",
              "        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),",
              "        \" \",",
              "        [AxisMonthIndex],",
              "        ASC",
              "    )",
              "VAR SafeLinePoints =",
              "    IF (",
              "        RowCount <= 1,",
              "        FORMAT ( SparkX0, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" )",
              "            & \" \"",
              "            & FORMAT ( SparkX1, \"0.0\" ) & \",\" & FORMAT ( EndYValue, \"0.0\" ),",
              "        LinePoints",
              "    )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='226' height='150' viewBox='0 0 252 166'>\"",
              "        & \"<defs><clipPath id='sparkClip'><rect x='130' y='40' width='108' height='52' rx='7'/></clipPath></defs>\"",
              "        & \"<rect x='1' y='1' width='250' height='164' rx='12' fill='%23FBFDFE' stroke='%23D8E5E8' stroke-width='1.5'/>\"",
              "        & \"<rect x='14' y='12' width='224' height='4' rx='2' fill='%238E5572' opacity='0.9'/>\"",
              "        & \"<rect x='16' y='30' width='13' height='13' rx='3' fill='%238E5572' opacity='0.95'/>\"",
              "        & \"<circle cx='22.5' cy='36.5' r='2.1' fill='%23FFFFFF' opacity='0.9'/>\"",
              "        & \"<text x='36' y='42' font-family='Segoe UI' font-size='13' font-weight='750' fill='%2317324A'>Recon Variance</text>\"",
              "        & \"<text x='16' y='82' font-family='Segoe UI' font-size='27' font-weight='750' fill='%238E5572'>\" & ValueText & \"</text>\"",
              "        & \"<rect x='128' y='36' width='112' height='60' rx='9' fill='%23F7FBFC' stroke='%23E5EFF2' stroke-width='1'/>\"",
              "        & \"<g clip-path='url(%23sparkClip)'>\"",
              "        & \"<line x1='132' y1='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' x2='236' y2='\" & FORMAT ( ReferenceYValue, \"0.0\" ) & \"' stroke='%23BFD0D5' stroke-width='1' stroke-dasharray='4 5' opacity='0.65'/>\"",
              "        & \"<polyline points='\" & SafeLinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='2.25' stroke-linecap='round' stroke-linejoin='round'/>\"",
              "        & \"<circle cx='132' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='2.4' fill='%23FFFFFF' stroke='\" & TrendColor & \"' stroke-width='1.15' opacity='0.78'/>\"",
              "        & \"<circle cx='236' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.0' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.65'/>\"",
              "        & \"</g>\"",
              "        & \"<rect x='16' y='108' width='100' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<rect x='124' y='108' width='112' height='42' rx='8' fill='%23F4FAFB' stroke='%23DDE8EB' stroke-width='1'/>\"",
              "        & \"<text x='25' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>PY</text>\"",
              "        & \"<text x='25' y='146' font-family='Segoe UI' font-size='14' font-weight='650' fill='%2355707D'>\" & PYText & \"</text>\"",
              "        & \"<text x='134' y='125' font-family='Segoe UI' font-size='11.8' font-weight='800' fill='%2317324A'>YoY</text>\"",
              "        & \"<text x='134' y='146' font-family='Segoe UI' font-size='14' font-weight='800' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "1e329b9c-b666-41f5-b98d-717549f9b1a3"
          },
          {
            "name": "Rail Shell 01 SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Rail Shell SVG",
            "expression": [
              "VAR MonthLens = SELECTEDVALUE ( DimDate[MonthYear], \"All months\" )",
              "VAR DomainLens = SELECTEDVALUE ( DimDataset[Domain], \"All domains\" )",
              "VAR TierLens = SELECTEDVALUE ( DimDataset[Criticality], \"All tiers\" )",
              "VAR LensLineOne = LEFT ( MonthLens & \" | \" & DomainLens, 30 )",
              "VAR LensLineTwo = LEFT ( TierLens, 30 )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='176' height='700' viewBox='0 0 176 700'>\"",
              "        & \"<rect x='0' y='0' width='176' height='700' rx='6' fill='%23102B3C'/>\"",
              "        & \"<text x='10' y='40' font-family='Segoe UI' font-size='23' font-weight='700' fill='%23E8F4F6'>Project 19</text>\"",
              "        & \"<text x='10' y='62' font-family='Segoe UI' font-size='11.5' font-weight='600' fill='%23A9C8D0'>Finance DQ Governance</text>\"",
              "        & \"<rect x='6' y='108' width='162' height='34' rx='6' fill='%231B4D89' stroke='%238CB9C2' stroke-width='1'/><text x='16' y='130' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23E8F4F6'>01 Governance</text><rect x='6' y='150' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='172' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>02 Reliability</text><rect x='6' y='192' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='214' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>03 Controls</text><rect x='6' y='234' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='256' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>04 Actions</text>\"",
              "        & \"<line x1='6' y1='282' x2='168' y2='282' stroke='%236D95A0' stroke-width='1' opacity='0.75'/>\"",
              "        & \"<text x='10' y='310' font-family='Segoe UI' font-size='9.2' font-weight='700' fill='%23A9C8D0'>SIGNATURE</text>\"",
              "        & \"<text x='10' y='332' font-family='Segoe UI' font-size='12.1' font-weight='700' fill='%23E8F4F6'>Finance Trust Control Room</text>\"",
              "        & \"<text x='10' y='386' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23A9C8D0'>GLOBAL LENS</text>\"",
              "        & \"<rect x='6' y='562' width='166' height='78' rx='8' fill='%23173E55' stroke='%233F7180' stroke-width='1'/>\"",
              "        & \"<text x='16' y='585' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23A9C8D0'>Current Lens</text>\"",
              "        & \"<text x='16' y='609' font-family='Segoe UI' font-size='10.4' font-weight='700' fill='%23E8F4F6'>\" & LensLineOne & \"</text>\"",
              "        & \"<text x='16' y='632' font-family='Segoe UI' font-size='10.4' font-weight='700' fill='%23E8F4F6'>\" & LensLineTwo & \"</text>\"",
              "        & \"<rect x='6' y='642' width='162' height='52' rx='7' fill='%23173E55' stroke='%233F7180' stroke-width='1'/>\"",
              "        & \"<text x='16' y='665' font-family='Segoe UI' font-size='10' font-weight='700' fill='%23A9C8D0'>LATEST COMPLETE</text>\"",
              "        & \"<text x='16' y='687' font-family='Segoe UI' font-size='13.6' font-weight='700' fill='%23E8F4F6'>May 2026</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "f1f80275-2622-445f-89ad-e1690065fcb8"
          },
          {
            "name": "Rail Shell 02 SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Rail Shell SVG",
            "expression": [
              "VAR MonthLens = SELECTEDVALUE ( DimDate[MonthYear], \"All months\" )",
              "VAR DomainLens = SELECTEDVALUE ( DimDataset[Domain], \"All domains\" )",
              "VAR TierLens = SELECTEDVALUE ( DimDataset[Criticality], \"All tiers\" )",
              "VAR LensLineOne = LEFT ( MonthLens & \" | \" & DomainLens, 30 )",
              "VAR LensLineTwo = LEFT ( TierLens, 30 )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='176' height='700' viewBox='0 0 176 700'>\"",
              "        & \"<rect x='0' y='0' width='176' height='700' rx='6' fill='%23102B3C'/>\"",
              "        & \"<text x='10' y='40' font-family='Segoe UI' font-size='23' font-weight='700' fill='%23E8F4F6'>Project 19</text>\"",
              "        & \"<text x='10' y='62' font-family='Segoe UI' font-size='11.5' font-weight='600' fill='%23A9C8D0'>Finance DQ Governance</text>\"",
              "        & \"<rect x='6' y='108' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='130' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>01 Governance</text><rect x='6' y='150' width='162' height='34' rx='6' fill='%231B4D89' stroke='%238CB9C2' stroke-width='1'/><text x='16' y='172' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23E8F4F6'>02 Reliability</text><rect x='6' y='192' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='214' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>03 Controls</text><rect x='6' y='234' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='256' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>04 Actions</text>\"",
              "        & \"<line x1='6' y1='282' x2='168' y2='282' stroke='%236D95A0' stroke-width='1' opacity='0.75'/>\"",
              "        & \"<text x='10' y='310' font-family='Segoe UI' font-size='9.2' font-weight='700' fill='%23A9C8D0'>SIGNATURE</text>\"",
              "        & \"<text x='10' y='332' font-family='Segoe UI' font-size='12.1' font-weight='700' fill='%23E8F4F6'>Refresh, Completeness, Reconc</text><text x='10' y='349' font-family='Segoe UI' font-size='12.1' font-weight='700' fill='%23E8F4F6'>iliation</text>\"",
              "        & \"<text x='10' y='386' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23A9C8D0'>GLOBAL LENS</text>\"",
              "        & \"<rect x='6' y='562' width='166' height='78' rx='8' fill='%23173E55' stroke='%233F7180' stroke-width='1'/>\"",
              "        & \"<text x='16' y='585' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23A9C8D0'>Current Lens</text>\"",
              "        & \"<text x='16' y='609' font-family='Segoe UI' font-size='10.4' font-weight='700' fill='%23E8F4F6'>\" & LensLineOne & \"</text>\"",
              "        & \"<text x='16' y='632' font-family='Segoe UI' font-size='10.4' font-weight='700' fill='%23E8F4F6'>\" & LensLineTwo & \"</text>\"",
              "        & \"<rect x='6' y='642' width='162' height='52' rx='7' fill='%23173E55' stroke='%233F7180' stroke-width='1'/>\"",
              "        & \"<text x='16' y='665' font-family='Segoe UI' font-size='10' font-weight='700' fill='%23A9C8D0'>LATEST COMPLETE</text>\"",
              "        & \"<text x='16' y='687' font-family='Segoe UI' font-size='13.6' font-weight='700' fill='%23E8F4F6'>May 2026</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "9df425a0-cdfb-4914-991d-4799cbe2b1e8"
          },
          {
            "name": "Rail Shell 03 SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Rail Shell SVG",
            "expression": [
              "VAR MonthLens = SELECTEDVALUE ( DimDate[MonthYear], \"All months\" )",
              "VAR DomainLens = SELECTEDVALUE ( DimDataset[Domain], \"All domains\" )",
              "VAR TierLens = SELECTEDVALUE ( DimDataset[Criticality], \"All tiers\" )",
              "VAR LensLineOne = LEFT ( MonthLens & \" | \" & DomainLens, 30 )",
              "VAR LensLineTwo = LEFT ( TierLens, 30 )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='176' height='700' viewBox='0 0 176 700'>\"",
              "        & \"<rect x='0' y='0' width='176' height='700' rx='6' fill='%23102B3C'/>\"",
              "        & \"<text x='10' y='40' font-family='Segoe UI' font-size='23' font-weight='700' fill='%23E8F4F6'>Project 19</text>\"",
              "        & \"<text x='10' y='62' font-family='Segoe UI' font-size='11.5' font-weight='600' fill='%23A9C8D0'>Finance DQ Governance</text>\"",
              "        & \"<rect x='6' y='108' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='130' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>01 Governance</text><rect x='6' y='150' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='172' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>02 Reliability</text><rect x='6' y='192' width='162' height='34' rx='6' fill='%231B4D89' stroke='%238CB9C2' stroke-width='1'/><text x='16' y='214' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23E8F4F6'>03 Controls</text><rect x='6' y='234' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='256' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>04 Actions</text>\"",
              "        & \"<line x1='6' y1='282' x2='168' y2='282' stroke='%236D95A0' stroke-width='1' opacity='0.75'/>\"",
              "        & \"<text x='10' y='310' font-family='Segoe UI' font-size='9.2' font-weight='700' fill='%23A9C8D0'>SIGNATURE</text>\"",
              "        & \"<text x='10' y='332' font-family='Segoe UI' font-size='12.1' font-weight='700' fill='%23E8F4F6'>Usage, Access, Deployment Gua</text><text x='10' y='349' font-family='Segoe UI' font-size='12.1' font-weight='700' fill='%23E8F4F6'>rdrails</text>\"",
              "        & \"<text x='10' y='386' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23A9C8D0'>GLOBAL LENS</text>\"",
              "        & \"<rect x='6' y='562' width='166' height='78' rx='8' fill='%23173E55' stroke='%233F7180' stroke-width='1'/>\"",
              "        & \"<text x='16' y='585' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23A9C8D0'>Current Lens</text>\"",
              "        & \"<text x='16' y='609' font-family='Segoe UI' font-size='10.4' font-weight='700' fill='%23E8F4F6'>\" & LensLineOne & \"</text>\"",
              "        & \"<text x='16' y='632' font-family='Segoe UI' font-size='10.4' font-weight='700' fill='%23E8F4F6'>\" & LensLineTwo & \"</text>\"",
              "        & \"<rect x='6' y='642' width='162' height='52' rx='7' fill='%23173E55' stroke='%233F7180' stroke-width='1'/>\"",
              "        & \"<text x='16' y='665' font-family='Segoe UI' font-size='10' font-weight='700' fill='%23A9C8D0'>LATEST COMPLETE</text>\"",
              "        & \"<text x='16' y='687' font-family='Segoe UI' font-size='13.6' font-weight='700' fill='%23E8F4F6'>May 2026</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "07627755-9bd6-410d-a8a1-e0b530f83c4c"
          },
          {
            "name": "Rail Shell 04 SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Rail Shell SVG",
            "expression": [
              "VAR MonthLens = SELECTEDVALUE ( DimDate[MonthYear], \"All months\" )",
              "VAR DomainLens = SELECTEDVALUE ( DimDataset[Domain], \"All domains\" )",
              "VAR TierLens = SELECTEDVALUE ( DimDataset[Criticality], \"All tiers\" )",
              "VAR LensLineOne = LEFT ( MonthLens & \" | \" & DomainLens, 30 )",
              "VAR LensLineTwo = LEFT ( TierLens, 30 )",
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='176' height='700' viewBox='0 0 176 700'>\"",
              "        & \"<rect x='0' y='0' width='176' height='700' rx='6' fill='%23102B3C'/>\"",
              "        & \"<text x='10' y='40' font-family='Segoe UI' font-size='23' font-weight='700' fill='%23E8F4F6'>Project 19</text>\"",
              "        & \"<text x='10' y='62' font-family='Segoe UI' font-size='11.5' font-weight='600' fill='%23A9C8D0'>Finance DQ Governance</text>\"",
              "        & \"<rect x='6' y='108' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='130' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>01 Governance</text><rect x='6' y='150' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='172' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>02 Reliability</text><rect x='6' y='192' width='162' height='34' rx='6' fill='%23173E55' stroke='%23315B6B' stroke-width='1'/><text x='16' y='214' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23CFE3E7'>03 Controls</text><rect x='6' y='234' width='162' height='34' rx='6' fill='%231B4D89' stroke='%238CB9C2' stroke-width='1'/><text x='16' y='256' font-family='Segoe UI' font-size='11.2' font-weight='700' fill='%23E8F4F6'>04 Actions</text>\"",
              "        & \"<line x1='6' y1='282' x2='168' y2='282' stroke='%236D95A0' stroke-width='1' opacity='0.75'/>\"",
              "        & \"<text x='10' y='310' font-family='Segoe UI' font-size='9.2' font-weight='700' fill='%23A9C8D0'>SIGNATURE</text>\"",
              "        & \"<text x='10' y='332' font-family='Segoe UI' font-size='12.1' font-weight='700' fill='%23E8F4F6'>Prioritized Close and Control</text><text x='10' y='349' font-family='Segoe UI' font-size='12.1' font-weight='700' fill='%23E8F4F6'> Queue</text>\"",
              "        & \"<text x='10' y='386' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23A9C8D0'>GLOBAL LENS</text>\"",
              "        & \"<rect x='6' y='562' width='166' height='78' rx='8' fill='%23173E55' stroke='%233F7180' stroke-width='1'/>\"",
              "        & \"<text x='16' y='585' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23A9C8D0'>Current Lens</text>\"",
              "        & \"<text x='16' y='609' font-family='Segoe UI' font-size='10.4' font-weight='700' fill='%23E8F4F6'>\" & LensLineOne & \"</text>\"",
              "        & \"<text x='16' y='632' font-family='Segoe UI' font-size='10.4' font-weight='700' fill='%23E8F4F6'>\" & LensLineTwo & \"</text>\"",
              "        & \"<rect x='6' y='642' width='162' height='52' rx='7' fill='%23173E55' stroke='%233F7180' stroke-width='1'/>\"",
              "        & \"<text x='16' y='665' font-family='Segoe UI' font-size='10' font-weight='700' fill='%23A9C8D0'>LATEST COMPLETE</text>\"",
              "        & \"<text x='16' y='687' font-family='Segoe UI' font-size='13.6' font-weight='700' fill='%23E8F4F6'>May 2026</text>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "739c79a7-6ba5-4caf-aba8-598e192c5b93"
          },
          {
            "name": "Header Shell 1 SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Header Shell SVG",
            "expression": [
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='1052' height='64' viewBox='0 0 1052 64'>\"",
              "        & \"<text x='0' y='29' font-family='Segoe UI' font-size='23' font-weight='750' fill='%2313212B'>Governance Overview</text>\"",
              "        & \"<text x='0' y='50' font-family='Segoe UI' font-size='10.8' font-weight='650' fill='%235B6673'>Finance Trust Control Room</text>\"",
              "        & \"<rect x='296' y='0' width='544' height='58' rx='8' fill='%23F9FCFD' stroke='%23C9D5D8' stroke-width='1'/>\"",
              "        & \"<text x='316' y='20' font-family='Segoe UI' font-size='9.5' font-weight='800' fill='%235B6673'>Decision Chip</text>\"",
              "        & \"<text x='316' y='43' font-family='Segoe UI' font-size='12' font-weight='800' fill='%2313212B'>WATCH: owner review required</text>\"",
              "        & \"<line x1='0' y1='62' x2='1052' y2='62' stroke='%23DDE8EB' stroke-width='2'/>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "82683702-ba27-4e66-a65d-1bc9c763c42b"
          },
          {
            "name": "Header Shell 2 SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Header Shell SVG",
            "expression": [
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='1052' height='64' viewBox='0 0 1052 64'>\"",
              "        & \"<text x='0' y='29' font-family='Segoe UI' font-size='23' font-weight='750' fill='%2313212B'>Reliability &amp; Quality</text>\"",
              "        & \"<text x='0' y='50' font-family='Segoe UI' font-size='10.8' font-weight='650' fill='%235B6673'>Refresh, Completeness, Reconciliation</text>\"",
              "        & \"<rect x='296' y='0' width='544' height='58' rx='8' fill='%23F9FCFD' stroke='%23C9D5D8' stroke-width='1'/>\"",
              "        & \"<text x='316' y='20' font-family='Segoe UI' font-size='9.5' font-weight='800' fill='%235B6673'>Decision Chip</text>\"",
              "        & \"<text x='316' y='43' font-family='Segoe UI' font-size='12' font-weight='800' fill='%2313212B'>WATCH: validate exception queue</text>\"",
              "        & \"<line x1='0' y1='62' x2='1052' y2='62' stroke='%23DDE8EB' stroke-width='2'/>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "b7ac953e-e0bd-42cb-a593-740471fd7a36"
          },
          {
            "name": "Header Shell 3 SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Header Shell SVG",
            "expression": [
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='1052' height='64' viewBox='0 0 1052 64'>\"",
              "        & \"<text x='0' y='29' font-family='Segoe UI' font-size='23' font-weight='750' fill='%2313212B'>Adoption &amp; Controls</text>\"",
              "        & \"<text x='0' y='50' font-family='Segoe UI' font-size='10.8' font-weight='650' fill='%235B6673'>Usage, Access, Deployment Guardrails</text>\"",
              "        & \"<rect x='296' y='0' width='544' height='58' rx='8' fill='%23F9FCFD' stroke='%23C9D5D8' stroke-width='1'/>\"",
              "        & \"<text x='316' y='20' font-family='Segoe UI' font-size='9.5' font-weight='800' fill='%235B6673'>Decision Chip</text>\"",
              "        & \"<text x='316' y='43' font-family='Segoe UI' font-size='12' font-weight='800' fill='%2313212B'>WATCH: control follow-up needed</text>\"",
              "        & \"<line x1='0' y1='62' x2='1052' y2='62' stroke='%23DDE8EB' stroke-width='2'/>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "84ecb083-89a1-46ba-adf5-f1379ae1d01b"
          },
          {
            "name": "Header Shell 4 SVG",
            "dataCategory": "ImageUrl",
            "displayFolder": "Header Shell SVG",
            "expression": [
              "VAR SVG =",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' width='1052' height='64' viewBox='0 0 1052 64'>\"",
              "        & \"<text x='0' y='29' font-family='Segoe UI' font-size='23' font-weight='750' fill='%2313212B'>Risk &amp; Action Queue</text>\"",
              "        & \"<text x='0' y='50' font-family='Segoe UI' font-size='10.8' font-weight='650' fill='%235B6673'>Prioritized Close and Control Queue</text>\"",
              "        & \"<rect x='296' y='0' width='544' height='58' rx='8' fill='%23F9FCFD' stroke='%23C9D5D8' stroke-width='1'/>\"",
              "        & \"<text x='316' y='20' font-family='Segoe UI' font-size='9.5' font-weight='800' fill='%235B6673'>Decision Chip</text>\"",
              "        & \"<text x='316' y='43' font-family='Segoe UI' font-size='12' font-weight='800' fill='%2313212B'>WATCH: triage aging queues</text>\"",
              "        & \"<line x1='0' y1='62' x2='1052' y2='62' stroke='%23DDE8EB' stroke-width='2'/>\"",
              "        & \"</svg>\"",
              "RETURN",
              "    \"data:image/svg+xml;utf8,\" & SVG"
            ],
            "lineageTag": "82beb230-9e4c-4ccc-b84b-0f3bd52f99ed"
          }
        ],
        "partitions": [
          {
            "name": "KPI Measures-Import",
            "mode": "import",
            "source": {
              "expression": "let Source = #table(type table [MeasureKey = text], {{\"KPI\"}}) in Source",
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_1302fe1e-7e55-45d4-b12a-9d2f860e26d9",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1fa25e83-d3da-4fe6-9188-03bed065b10a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bb2c8aff-897f-47af-9b1e-eb799d2dbbb5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7d47a9ac-0dc1-44f6-8486-4932d0606003",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5cd39ce9-a5fe-4af3-9e7f-cace58ab6785",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3f606643-efba-4f69-9911-8184355a4c1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "77e27c31-9442-452a-8c24-e6c82322771a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7bd502db-58ca-4330-a0d4-ad413a0cce24",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "28b0bf42-0433-4b09-be9b-e0b17f65ce1d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b2c64c28-1901-4a4a-a6d4-4aecd7f07cb3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "952eb2fe-cae0-4d81-b0c5-9de696aee32b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9d942dd4-f5b2-430d-b0e9-39b0c8fa7516",
                "ordinal": 3
              }
            ],
            "lineageTag": "16082139-bb85-4381-8f70-f5247231eec2"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "63a9ebe3-4134-42b3-9959-53a2c54a92e2",
        "partitions": [
          {
            "name": "DateTableTemplate_1302fe1e-7e55-45d4-b12a-9d2f860e26d9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_dd93922a-7145-4242-a187-5533e7726260",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ec6a35eb-c2fd-45e0-b9e5-6690f36f838a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d0c333a9-ddff-4194-9af2-c3493b535834",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "15abf9f3-793f-4bab-8d79-9f84510e84c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "33aa9c8b-a196-454c-86ee-e48d021a0f3d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f7af6f0e-2e42-4c3f-aa61-68aeb8dd0c71",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f6ae1f38-1a00-4431-a52e-bd15cc44739a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1ae64298-a054-4641-9280-6de406ad3966",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7ed4b1a8-38cd-4cc0-88ac-3a03f5d704f8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e60a4361-4323-4985-a7fa-e1d8311af0ba",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bccb7459-910c-4a1d-946e-88c102c7cb90",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "20e4b2a1-a06f-466f-a276-04223829aaf7",
                "ordinal": 3
              }
            ],
            "lineageTag": "cab4bee9-3411-43cd-a63e-3ea67d1933c6"
          }
        ],
        "isHidden": true,
        "lineageTag": "86ba37ff-3ad7-4fe8-91f5-3c1e9e8f7534",
        "partitions": [
          {
            "name": "LocalDateTable_dd93922a-7145-4242-a187-5533e7726260",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimDate'[Date])), 1, 1), Date(Year(MAX('DimDate'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_3fcce349-f814-4faf-8847-0a9d59a024ba",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "98aedf28-b48b-4343-9a83-cc2f9d4111bb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f1380473-b499-4aab-8eee-10a89ef5341b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "42bc85ba-5ef0-4507-abf1-edfcc2db7b08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1731413b-8043-459c-9ae9-87a0547e3597",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8d5edd2a-f2e0-4e16-b734-39b6693d0009",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b428739f-0cfc-4e19-a3e8-2af7b2da4532",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a9e00f45-9cc5-4b3a-bf9b-ea32eb539d8d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a435a84e-9cda-4770-b38a-3617ee073dfe",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c637d69b-f8bf-4294-a169-7485a2960216",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2c3266f9-dd2d-4543-a029-eb4a8a02f91c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e34293a5-548f-45d9-8d6e-2b328cbeb561",
                "ordinal": 3
              }
            ],
            "lineageTag": "793209f7-9770-4350-a897-4eb57a0b4361"
          }
        ],
        "isHidden": true,
        "lineageTag": "e8fd6568-f7f9-44a8-b394-add10b77e7fc",
        "partitions": [
          {
            "name": "LocalDateTable_3fcce349-f814-4faf-8847-0a9d59a024ba",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimDate'[MonthEndDate])), 1, 1), Date(Year(MAX('DimDate'[MonthEndDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}