{
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DimDate",
        "lineageTag": "263e4cdd-2bea-47f0-bc60-d172ddf09403",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "MonthLabel",
            "dataType": "string",
            "sourceColumn": "MonthLabel",
            "summarizeBy": "none"
          },
          {
            "name": "MonthIndex",
            "dataType": "int64",
            "sourceColumn": "MonthIndex",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "IsLatestCompleteMonth",
            "dataType": "int64",
            "sourceColumn": "IsLatestCompleteMonth",
            "formatString": "0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_DimDate",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimDate.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"MonthLabel\", type text}, {\"MonthIndex\", Int64.Type}, {\"Year\", Int64.Type}, {\"Quarter\", type text}, {\"IsLatestCompleteMonth\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimScenario",
        "lineageTag": "a1669827-b37a-4453-8bb6-a53cff63dac7",
        "columns": [
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioName",
            "dataType": "string",
            "sourceColumn": "ScenarioName",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueIndex",
            "dataType": "double",
            "sourceColumn": "RevenueIndex",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "MarginIndex",
            "dataType": "double",
            "sourceColumn": "MarginIndex",
            "formatString": "0.0%",
            "summarizeBy": "sum"
          },
          {
            "name": "BurnIndex",
            "dataType": "double",
            "sourceColumn": "BurnIndex",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ScenarioSort",
            "dataType": "int64",
            "sourceColumn": "ScenarioSort",
            "formatString": "0",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_DimScenario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimScenario.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ScenarioID\", type text}, {\"ScenarioName\", type text}, {\"RevenueIndex\", type number}, {\"MarginIndex\", type number}, {\"BurnIndex\", type number}, {\"ScenarioSort\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimBusinessUnit",
        "lineageTag": "9e19ce40-66dd-40b3-ade5-6ac036956839",
        "columns": [
          {
            "name": "BusinessUnitID",
            "dataType": "string",
            "sourceColumn": "BusinessUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "dataType": "string",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueFamily",
            "dataType": "string",
            "sourceColumn": "RevenueFamily",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "none"
          },
          {
            "name": "MixWeight",
            "dataType": "double",
            "sourceColumn": "MixWeight",
            "summarizeBy": "sum"
          },
          {
            "name": "TargetGrossMargin",
            "dataType": "double",
            "sourceColumn": "TargetGrossMargin",
            "formatString": "0.0%",
            "summarizeBy": "sum"
          },
          {
            "name": "GrowthIndex",
            "dataType": "double",
            "sourceColumn": "GrowthIndex",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_DimBusinessUnit",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimBusinessUnit.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"BusinessUnitID\", type text}, {\"BusinessUnit\", type text}, {\"RevenueFamily\", type text}, {\"MixWeight\", type number}, {\"TargetGrossMargin\", type number}, {\"GrowthIndex\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimRegion",
        "lineageTag": "fc8b3209-f129-4a51-a725-602914d6f12c",
        "columns": [
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "RegionMaturity",
            "dataType": "string",
            "sourceColumn": "RegionMaturity",
            "summarizeBy": "none"
          },
          {
            "name": "MixWeight",
            "dataType": "double",
            "sourceColumn": "MixWeight",
            "summarizeBy": "sum"
          },
          {
            "name": "DemandIndex",
            "dataType": "double",
            "sourceColumn": "DemandIndex",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_DimRegion",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimRegion.csv\"), [Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"RegionID\", type text}, {\"Region\", type text}, {\"RegionMaturity\", type text}, {\"MixWeight\", type number}, {\"DemandIndex\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCostCategory",
        "lineageTag": "d5664a0b-f0d5-4814-b77a-ac17c92bade7",
        "columns": [
          {
            "name": "CostCategoryID",
            "dataType": "string",
            "sourceColumn": "CostCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "CostCategory",
            "dataType": "string",
            "sourceColumn": "CostCategory",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueLoad",
            "dataType": "double",
            "sourceColumn": "RevenueLoad",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_DimCostCategory",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimCostCategory.csv\"), [Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"CostCategoryID\", type text}, {\"CostCategory\", type text}, {\"RevenueLoad\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactPnlMonthly",
        "lineageTag": "27a6ad6b-f036-4be2-9234-5484ad809bb7",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnitID",
            "dataType": "string",
            "sourceColumn": "BusinessUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "sourceColumn": "Revenue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "PlanRevenue",
            "dataType": "double",
            "sourceColumn": "PlanRevenue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ForecastRevenue",
            "dataType": "double",
            "sourceColumn": "ForecastRevenue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "COGS",
            "dataType": "double",
            "sourceColumn": "COGS",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "GrossProfit",
            "dataType": "double",
            "sourceColumn": "GrossProfit",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "OperatingExpense",
            "dataType": "double",
            "sourceColumn": "OperatingExpense",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "EBITDA",
            "dataType": "double",
            "sourceColumn": "EBITDA",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "PlanEBITDA",
            "dataType": "double",
            "sourceColumn": "PlanEBITDA",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ForecastEBITDA",
            "dataType": "double",
            "sourceColumn": "ForecastEBITDA",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "NetIncome",
            "dataType": "double",
            "sourceColumn": "NetIncome",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "IsSynthetic",
            "dataType": "string",
            "sourceColumn": "IsSynthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_FactPnlMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactPnlMonthly.csv\"), [Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"BusinessUnitID\", type text}, {\"RegionID\", type text}, {\"Revenue\", type number}, {\"PlanRevenue\", type number}, {\"ForecastRevenue\", type number}, {\"COGS\", type number}, {\"GrossProfit\", type number}, {\"OperatingExpense\", type number}, {\"EBITDA\", type number}, {\"PlanEBITDA\", type number}, {\"ForecastEBITDA\", type number}, {\"NetIncome\", type number}, {\"IsSynthetic\", type text}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactOpexMonthly",
        "lineageTag": "9d3e6315-b0e0-489e-b5ae-6f3f59235bba",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "CostCategoryID",
            "dataType": "string",
            "sourceColumn": "CostCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "OperatingExpense",
            "dataType": "double",
            "sourceColumn": "OperatingExpense",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "PlanOperatingExpense",
            "dataType": "double",
            "sourceColumn": "PlanOperatingExpense",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ForecastOperatingExpense",
            "dataType": "double",
            "sourceColumn": "ForecastOperatingExpense",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactOpexMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactOpexMonthly.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"CostCategoryID\", type text}, {\"OperatingExpense\", type number}, {\"PlanOperatingExpense\", type number}, {\"ForecastOperatingExpense\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCashMonthly",
        "lineageTag": "cc41ba0f-38fa-41dc-8f6f-61cbff40c6cf",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "CashBalance",
            "dataType": "double",
            "sourceColumn": "CashBalance",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "OperatingCashFlow",
            "dataType": "double",
            "sourceColumn": "OperatingCashFlow",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "Capex",
            "dataType": "double",
            "sourceColumn": "Capex",
            "summarizeBy": "sum"
          },
          {
            "name": "FreeCashFlow",
            "dataType": "double",
            "sourceColumn": "FreeCashFlow",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "NetBurn",
            "dataType": "double",
            "sourceColumn": "NetBurn",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "RunwayMonths",
            "dataType": "double",
            "sourceColumn": "RunwayMonths",
            "summarizeBy": "sum"
          },
          {
            "name": "FundingNeed",
            "dataType": "double",
            "sourceColumn": "FundingNeed",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "Debt",
            "dataType": "double",
            "sourceColumn": "Debt",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkingCapital",
            "dataType": "double",
            "sourceColumn": "WorkingCapital",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "FinancingInflow",
            "dataType": "double",
            "sourceColumn": "FinancingInflow",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactCashMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactCashMonthly.csv\"), [Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"CashBalance\", type number}, {\"OperatingCashFlow\", type number}, {\"Capex\", type number}, {\"FreeCashFlow\", type number}, {\"NetBurn\", type number}, {\"RunwayMonths\", type number}, {\"FundingNeed\", type number}, {\"Debt\", type number}, {\"WorkingCapital\", type number}, {\"FinancingInflow\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactStatementLines",
        "lineageTag": "1a26b28d-951a-4e79-8a4b-6cf497c4442b",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "Statement",
            "dataType": "string",
            "sourceColumn": "Statement",
            "summarizeBy": "none"
          },
          {
            "name": "LineItem",
            "dataType": "string",
            "sourceColumn": "LineItem",
            "summarizeBy": "none"
          },
          {
            "name": "LineSort",
            "dataType": "int64",
            "sourceColumn": "LineSort",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "ValueActual",
            "dataType": "double",
            "sourceColumn": "ValueActual",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ValuePlan",
            "dataType": "double",
            "sourceColumn": "ValuePlan",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ValueForecast",
            "dataType": "double",
            "sourceColumn": "ValueForecast",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactStatementLines",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactStatementLines.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"Statement\", type text}, {\"LineItem\", type text}, {\"LineSort\", Int64.Type}, {\"ValueActual\", type number}, {\"ValuePlan\", type number}, {\"ValueForecast\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCovenantMonthly",
        "lineageTag": "46ad57d7-d87f-4f4b-8bbc-4731eafd8445",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueLTM",
            "dataType": "double",
            "sourceColumn": "RevenueLTM",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "EBITDALTM",
            "dataType": "double",
            "sourceColumn": "EBITDALTM",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "NetDebt",
            "dataType": "double",
            "sourceColumn": "NetDebt",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "LeverageRatio",
            "dataType": "double",
            "sourceColumn": "LeverageRatio",
            "summarizeBy": "sum"
          },
          {
            "name": "LeverageLimit",
            "dataType": "double",
            "sourceColumn": "LeverageLimit",
            "summarizeBy": "sum"
          },
          {
            "name": "LeverageHeadroom",
            "dataType": "double",
            "sourceColumn": "LeverageHeadroom",
            "summarizeBy": "sum"
          },
          {
            "name": "InterestCoverage",
            "dataType": "double",
            "sourceColumn": "InterestCoverage",
            "summarizeBy": "sum"
          },
          {
            "name": "InterestCoverageLimit",
            "dataType": "double",
            "sourceColumn": "InterestCoverageLimit",
            "summarizeBy": "sum"
          },
          {
            "name": "Liquidity",
            "dataType": "double",
            "sourceColumn": "Liquidity",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "LiquidityMinimum",
            "dataType": "int64",
            "sourceColumn": "LiquidityMinimum",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "LiquidityHeadroom",
            "dataType": "double",
            "sourceColumn": "LiquidityHeadroom",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "CovenantStatus",
            "dataType": "string",
            "sourceColumn": "CovenantStatus",
            "summarizeBy": "none"
          },
          {
            "name": "RiskScore",
            "dataType": "double",
            "sourceColumn": "RiskScore",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactCovenantMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactCovenantMonthly.csv\"), [Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"RevenueLTM\", type number}, {\"EBITDALTM\", type number}, {\"NetDebt\", type number}, {\"LeverageRatio\", type number}, {\"LeverageLimit\", type number}, {\"LeverageHeadroom\", type number}, {\"InterestCoverage\", type number}, {\"InterestCoverageLimit\", type number}, {\"Liquidity\", type number}, {\"LiquidityMinimum\", Int64.Type}, {\"LiquidityHeadroom\", type number}, {\"CovenantStatus\", type text}, {\"RiskScore\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactValuation",
        "lineageTag": "6f3ae718-318b-495b-89cf-0ff640763b73",
        "columns": [
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "Method",
            "dataType": "string",
            "sourceColumn": "Method",
            "summarizeBy": "none"
          },
          {
            "name": "MethodSort",
            "dataType": "int64",
            "sourceColumn": "MethodSort",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Multiple",
            "dataType": "double",
            "sourceColumn": "Multiple",
            "summarizeBy": "sum"
          },
          {
            "name": "EnterpriseValue",
            "dataType": "double",
            "sourceColumn": "EnterpriseValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "EquityValue",
            "dataType": "double",
            "sourceColumn": "EquityValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "LowValue",
            "dataType": "double",
            "sourceColumn": "LowValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "HighValue",
            "dataType": "double",
            "sourceColumn": "HighValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactValuation",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactValuation.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ScenarioID\", type text}, {\"Method\", type text}, {\"MethodSort\", Int64.Type}, {\"Multiple\", type number}, {\"EnterpriseValue\", type number}, {\"EquityValue\", type number}, {\"LowValue\", type number}, {\"HighValue\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactSensitivity",
        "lineageTag": "df64d0eb-d4b6-4f77-9ccb-dc915a2d4b6e",
        "columns": [
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "Driver",
            "dataType": "string",
            "sourceColumn": "Driver",
            "summarizeBy": "none"
          },
          {
            "name": "CaseLabel",
            "dataType": "string",
            "sourceColumn": "CaseLabel",
            "summarizeBy": "none"
          },
          {
            "name": "DriverCase",
            "dataType": "string",
            "sourceColumn": "DriverCase",
            "summarizeBy": "none"
          },
          {
            "name": "EquityValueDelta",
            "dataType": "double",
            "sourceColumn": "EquityValueDelta",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "EquityValue",
            "dataType": "double",
            "sourceColumn": "EquityValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactSensitivity",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactSensitivity.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ScenarioID\", type text}, {\"Driver\", type text}, {\"CaseLabel\", type text}, {\"DriverCase\", type text}, {\"EquityValueDelta\", type number}, {\"EquityValue\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactRiskRegister",
        "lineageTag": "6c159e05-ca1d-4a18-9540-a8bdd995b1b4",
        "columns": [
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "RiskID",
            "dataType": "string",
            "sourceColumn": "RiskID",
            "summarizeBy": "none"
          },
          {
            "name": "RiskCategory",
            "dataType": "string",
            "sourceColumn": "RiskCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Risk",
            "dataType": "string",
            "sourceColumn": "Risk",
            "summarizeBy": "none"
          },
          {
            "name": "Severity",
            "dataType": "string",
            "sourceColumn": "Severity",
            "summarizeBy": "none"
          },
          {
            "name": "Probability",
            "dataType": "double",
            "sourceColumn": "Probability",
            "formatString": "0.0%",
            "summarizeBy": "sum"
          },
          {
            "name": "ExposureUSD",
            "dataType": "double",
            "sourceColumn": "ExposureUSD",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "Owner",
            "dataType": "string",
            "sourceColumn": "Owner",
            "summarizeBy": "none"
          },
          {
            "name": "MitigationStatus",
            "dataType": "string",
            "sourceColumn": "MitigationStatus",
            "summarizeBy": "none"
          },
          {
            "name": "BoardAsk",
            "dataType": "string",
            "sourceColumn": "BoardAsk",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_FactRiskRegister",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactRiskRegister.csv\"), [Delimiter=\",\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ScenarioID\", type text}, {\"RiskID\", type text}, {\"RiskCategory\", type text}, {\"Risk\", type text}, {\"Severity\", type text}, {\"Probability\", type number}, {\"ExposureUSD\", type number}, {\"Owner\", type text}, {\"MitigationStatus\", type text}, {\"BoardAsk\", type text}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactKpiScorecard",
        "lineageTag": "9b66964f-d519-4ba1-ad1f-352f8ec292c1",
        "columns": [
          {
            "name": "MetricName",
            "dataType": "string",
            "sourceColumn": "MetricName",
            "summarizeBy": "none"
          },
          {
            "name": "MetricFamily",
            "dataType": "string",
            "sourceColumn": "MetricFamily",
            "summarizeBy": "none"
          },
          {
            "name": "ActualDisplay",
            "dataType": "string",
            "sourceColumn": "ActualDisplay",
            "summarizeBy": "none"
          },
          {
            "name": "PlanDisplay",
            "dataType": "string",
            "sourceColumn": "PlanDisplay",
            "summarizeBy": "none"
          },
          {
            "name": "VarianceDisplay",
            "dataType": "string",
            "sourceColumn": "VarianceDisplay",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "BoardNarrative",
            "dataType": "string",
            "sourceColumn": "BoardNarrative",
            "summarizeBy": "none"
          },
          {
            "name": "SortOrder",
            "dataType": "int64",
            "sourceColumn": "SortOrder",
            "formatString": "0",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_FactKpiScorecard",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactKpiScorecard.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MetricName\", type text}, {\"MetricFamily\", type text}, {\"ActualDisplay\", type text}, {\"PlanDisplay\", type text}, {\"VarianceDisplay\", type text}, {\"Status\", type text}, {\"BoardNarrative\", type text}, {\"SortOrder\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "KPI_Measures",
        "lineageTag": "69db5351-31d4-4b10-827b-5f071c417db7",
        "columns": [
          {
            "name": "MeasureName",
            "dataType": "string",
            "sourceColumn": "MeasureName",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "p_KPI_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = #table(type table [MeasureName = text], {{\"KPI\"}}) in Source"
            }
          }
        ],
        "measures": [
          {
            "name": "Revenue",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[Revenue]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "cc4514a9-f102-4dca-95f6-ba6c28efa5be",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Plan Revenue",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[PlanRevenue]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "26dc2534-c9c4-45b6-8a12-28783810aa3d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Forecast Revenue",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[ForecastRevenue]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "1f2c36f2-a9fb-46a0-8a3a-711f8f33e1f1",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Revenue vs Plan",
            "expression": "[Revenue] - [Plan Revenue]",
            "lineageTag": "60e566f5-91ab-473a-9ed2-336cba1b34ae",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Revenue vs Plan %",
            "expression": "DIVIDE([Revenue vs Plan], [Plan Revenue])",
            "lineageTag": "4812ae17-aac5-4212-8929-64fc017f38f5",
            "formatString": "0.0%"
          },
          {
            "name": "Gross Profit",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[GrossProfit]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "8191e1c8-9de8-4a8c-8311-b0faea61e8b0",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Gross Margin %",
            "expression": "DIVIDE([Gross Profit], [Revenue])",
            "lineageTag": "90eb0548-eb6b-4b60-bd74-bb6d8286a6a3",
            "formatString": "0.0%"
          },
          {
            "name": "EBITDA",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[EBITDA]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "f03cf343-caf9-49b3-8816-6bac6289a4c6",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Plan EBITDA",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[PlanEBITDA]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "3782fc51-7121-48cf-894a-881d128e25fd",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "EBITDA vs Plan",
            "expression": "[EBITDA] - [Plan EBITDA]",
            "lineageTag": "654deef2-d5ca-490b-8b86-cb85bae8d533",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "EBITDA Margin %",
            "expression": "DIVIDE([EBITDA], [Revenue])",
            "lineageTag": "386ae164-8625-4c99-8bbe-71f62d5e2c75",
            "formatString": "0.0%"
          },
          {
            "name": "Net Income",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[NetIncome]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "d432a128-860c-4be4-b0e9-549cbccf0123",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Operating Expense",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactOpexMonthly[OperatingExpense]), FactOpexMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "97b9cca4-9643-4de3-84d2-1c931058f27d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Revenue",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE([Revenue], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "f3c1853e-b079-48f2-8039-accfcc48d511",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Gross Margin %",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE([Gross Margin %], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "fa277c36-0f2a-47eb-a812-6abd87263649",
            "formatString": "0.0%"
          },
          {
            "name": "Latest EBITDA",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE([EBITDA], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "4fc0cd82-ea00-42ab-baae-d555fabc1ef9",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest EBITDA Margin %",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE([EBITDA Margin %], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "e5efc915-0a6c-408a-8c48-525f6c017645",
            "formatString": "0.0%"
          },
          {
            "name": "Latest Cash Balance",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[CashBalance]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "41218957-6c69-46e3-a154-36c43d137ceb",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Cash Balance",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCashMonthly[CashBalance]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "537f9c80-39d8-44c1-9319-7ec77bac7d5b",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Operating Cash Flow",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactCashMonthly[OperatingCashFlow]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "df4f8f9d-ac0e-4abc-ae4c-a6134c965fde",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Free Cash Flow",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactCashMonthly[FreeCashFlow]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "fed35f98-8b8a-4c6d-b390-c63f2ecd6428",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Free Cash Flow",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[FreeCashFlow]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "7468ee80-7549-4999-b72b-21cb007b84ac",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Net Burn",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCashMonthly[NetBurn]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "759d6c00-b6f2-4ed5-9a17-dbafabc6d89e",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Net Burn",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[NetBurn]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "3a825e94-5e4c-4848-8907-6610298220a4",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Runway Months",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCashMonthly[RunwayMonths]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "8d5b39d6-5300-4d13-beaa-89c0037761d6",
            "formatString": "0.0x"
          },
          {
            "name": "Latest Runway Months",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[RunwayMonths]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "80438f90-a28b-40b6-ba66-7d1f79b75f76",
            "formatString": "0.0x"
          },
          {
            "name": "Funding Need",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCashMonthly[FundingNeed]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "7c79e98b-8862-4d1a-853e-27d2a476298f",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Funding Need",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[FundingNeed]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "a2514bf1-d434-4f39-be96-3e200966580d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Statement Actual",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactStatementLines[ValueActual]), FactStatementLines[ScenarioID] = ScenarioID)",
            "lineageTag": "0372b4f7-b80e-44d6-808e-536029dc0501",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Statement Plan",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactStatementLines[ValuePlan]), FactStatementLines[ScenarioID] = ScenarioID)",
            "lineageTag": "5a2618d3-0eae-4bbf-b28b-ad67af6bcf97",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Statement Forecast",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactStatementLines[ValueForecast]), FactStatementLines[ScenarioID] = ScenarioID)",
            "lineageTag": "29a27e0e-eb01-4796-a093-d442be91fd75",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Statement Variance %",
            "expression": "DIVIDE([Statement Actual] - [Statement Plan], [Statement Plan])",
            "lineageTag": "f3b44d3a-9e79-461c-973c-9eb8344043a1",
            "formatString": "0.0%"
          },
          {
            "name": "Enterprise Value",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(AVERAGE(FactValuation[EnterpriseValue]), FactValuation[ScenarioID] = ScenarioID)",
            "lineageTag": "397dde40-434d-4bc4-89af-ec19595a47c6",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Equity Value",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(AVERAGE(FactValuation[EquityValue]), FactValuation[ScenarioID] = ScenarioID)",
            "lineageTag": "edd010f8-91fc-4d1d-a20b-88f5ce313641",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Valuation Low",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(AVERAGE(FactValuation[LowValue]), FactValuation[ScenarioID] = ScenarioID)",
            "lineageTag": "6365f885-33df-489b-b897-0bcd1cc8845e",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Valuation High",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(AVERAGE(FactValuation[HighValue]), FactValuation[ScenarioID] = ScenarioID)",
            "lineageTag": "52cfb004-0c94-460e-b560-addd3db03f8b",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Sensitivity Delta",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactSensitivity[EquityValueDelta]), FactSensitivity[ScenarioID] = ScenarioID)",
            "lineageTag": "504d367d-bf9d-42ee-927a-c83b3ed9cb9d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Leverage Ratio",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCovenantMonthly[LeverageRatio]), FactCovenantMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "3b847c18-8d02-4a3f-82d9-a67383d661f6",
            "formatString": "0.0x"
          },
          {
            "name": "Leverage Limit",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCovenantMonthly[LeverageLimit]), FactCovenantMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "0249918e-fb5f-4bd3-89a8-43c01d59977b",
            "formatString": "0.0x"
          },
          {
            "name": "Leverage Headroom",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCovenantMonthly[LeverageHeadroom]), FactCovenantMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "fb80fe78-be39-4086-9e39-bb93c33acedf",
            "formatString": "0.0x"
          },
          {
            "name": "Interest Coverage",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCovenantMonthly[InterestCoverage]), FactCovenantMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "e415259d-7837-4b12-914e-8853a0a54615",
            "formatString": "0.0x"
          },
          {
            "name": "Liquidity Headroom",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCovenantMonthly[LiquidityHeadroom]), FactCovenantMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "22f704ba-70d3-40b3-af1b-25849b1f62d0",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Risk Exposure",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactRiskRegister[ExposureUSD]), FactRiskRegister[ScenarioID] = ScenarioID)",
            "lineageTag": "4596aa70-d701-416c-9b5e-560a3dabfdb6",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Critical Risk Count",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(COUNTROWS(FactRiskRegister), FactRiskRegister[ScenarioID] = ScenarioID, FactRiskRegister[Severity] = \"Critical\")",
            "lineageTag": "4e7ed49f-b91f-4806-bf5e-50dd670011b7",
            "formatString": "#,0"
          },
          {
            "name": "Revenue Display",
            "expression": "VAR Value = [Revenue] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "58076824-e9eb-4a8e-8fdb-b8e283e268f3"
          },
          {
            "name": "Gross Margin % Display",
            "expression": "FORMAT([Gross Margin %], \"0.0%\")",
            "lineageTag": "2d3580e7-105d-48ee-bbaf-fe0d83e37b1e"
          },
          {
            "name": "EBITDA Display",
            "expression": "VAR Value = [EBITDA] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "a302afac-a016-409b-8293-dfc0b0644b88"
          },
          {
            "name": "Cash Balance Display",
            "expression": "VAR Value = [Cash Balance] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "547a9c6b-0c75-4790-ac5e-4b0b098640ec"
          },
          {
            "name": "Runway Months Display",
            "expression": "FORMAT([Runway Months], \"0.0x\")",
            "lineageTag": "41657220-24ce-4158-997c-e041e4432808"
          },
          {
            "name": "Free Cash Flow Display",
            "expression": "VAR Value = [Free Cash Flow] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "88741388-d7cb-4e43-92f6-8e71cae6d972"
          },
          {
            "name": "Net Burn Display",
            "expression": "VAR Value = [Net Burn] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "c03bf638-e7b1-45ed-b994-1b5f2e087ca2"
          },
          {
            "name": "Funding Need Display",
            "expression": "VAR Value = [Funding Need] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "d00b4308-bb73-4521-bb32-08ea264ce95d"
          },
          {
            "name": "Enterprise Value Display",
            "expression": "VAR Value = [Enterprise Value] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "7888d2e2-3ebf-4a5a-a491-075bdd454400"
          },
          {
            "name": "Equity Value Display",
            "expression": "VAR Value = [Equity Value] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "91f3ab73-ac2d-4ace-a366-d1fe6f0d37e0"
          },
          {
            "name": "Leverage Ratio Display",
            "expression": "FORMAT([Leverage Ratio], \"0.0x\")",
            "lineageTag": "5e0c279e-e74e-4d2a-8975-f83a3be7e9e0"
          },
          {
            "name": "Leverage Headroom Display",
            "expression": "FORMAT([Leverage Headroom], \"0.0x\")",
            "lineageTag": "e9531e3e-f123-40b2-b1c2-ed2b1ccc99a1"
          },
          {
            "name": "Risk Exposure Display",
            "expression": "VAR Value = [Risk Exposure] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "a923d6b8-fb45-40c6-a8d9-47c33370f6ef"
          },
          {
            "name": "Revenue KPI",
            "expression": "DIVIDE([Latest Revenue], 1000000)",
            "lineageTag": "98c13279-9a22-4224-91be-6278cf131d4d",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M"
          },
          {
            "name": "Gross Margin KPI",
            "expression": "[Latest Gross Margin %]",
            "lineageTag": "a7a2884f-0d9f-4afb-a2a9-45c424fa2f00",
            "formatString": "0.0%"
          },
          {
            "name": "EBITDA KPI",
            "expression": "DIVIDE([Latest EBITDA], 1000000)",
            "lineageTag": "88a95925-e6b3-4f18-a88d-675bc4516509",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M"
          },
          {
            "name": "Cash Balance KPI",
            "expression": "DIVIDE([Latest Cash Balance], 1000000)",
            "lineageTag": "b97d3b67-60dc-4af9-93fd-77a66d824ce9",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M"
          },
          {
            "name": "Runway Months KPI",
            "expression": "[Latest Runway Months]",
            "lineageTag": "569df47f-8876-4e2a-b32c-243db65ad48a",
            "formatString": "0.0x"
          },
          {
            "name": "Free Cash Flow KPI",
            "expression": "DIVIDE([Latest Free Cash Flow], 1000000)",
            "lineageTag": "a621a49a-7f38-4ee1-b0c7-9441f7bd6e16",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M"
          },
          {
            "name": "Net Burn KPI",
            "expression": "DIVIDE([Latest Net Burn], 1000000)",
            "lineageTag": "73141b8c-0e7d-40a5-b263-0a7570059d8f",
            "formatString": "$#,0M;($#,0M);$0M"
          },
          {
            "name": "Funding Need KPI",
            "expression": "DIVIDE([Latest Funding Need], 1000000)",
            "lineageTag": "560bf290-c92d-4fe0-aef8-a173a222aa5c",
            "formatString": "$#,0M;($#,0M);$0M"
          },
          {
            "name": "Enterprise Value KPI",
            "expression": "DIVIDE([Enterprise Value], 1000000000)",
            "lineageTag": "d7bb7749-099a-43f9-bcb9-a358e11b8526",
            "formatString": "$#,0.0B;($#,0.0B);$0.0B"
          },
          {
            "name": "Equity Value KPI",
            "expression": "DIVIDE([Equity Value], 1000000000)",
            "lineageTag": "133a6f16-82b1-4df7-b7e7-6a141c7774ea",
            "formatString": "$#,0.0B;($#,0.0B);$0.0B"
          },
          {
            "name": "Leverage KPI",
            "expression": "[Leverage Ratio]",
            "lineageTag": "7922d199-c30a-4579-b53a-928aae5f54b1",
            "formatString": "0.0x"
          },
          {
            "name": "Headroom KPI",
            "expression": "[Leverage Headroom]",
            "lineageTag": "15d6fdce-5ac5-4742-812f-2ab36be67f11",
            "formatString": "0.0x"
          },
          {
            "name": "Risk Exposure KPI",
            "expression": "DIVIDE([Risk Exposure], 1000000)",
            "lineageTag": "693b408a-4800-44c0-8dd3-6978390b61d5",
            "formatString": "$#,0M;($#,0M);$0M"
          },
          {
            "name": "Revenue Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Revenue]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "494beded-aaa2-44f9-abe9-b6297099300a",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Gross Margin Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Gross Margin %]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "c57ea52c-b59c-4f0c-a406-8c2aa9c02ab7",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "EBITDA Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [EBITDA]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "124bbb9f-a8f2-4781-b1a6-791006a79fd4",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cash Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Cash Balance]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%23BE7C10\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "0095938b-a1f4-4c4f-8c50-35d2ff1bdd99",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Runway Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Runway Months]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "1db0f4a0-4f26-4cc0-8942-cee02df1307c",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Funding Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Funding Need]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue <= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "c07f8051-c67d-462f-bc66-c86de2d10378",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Leverage Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Leverage Ratio]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue <= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "b7deef8d-c9ac-4ddf-8dbd-55e17adda7d0",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Interest Coverage Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Interest Coverage]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "66638b1a-743d-460c-8f4d-23b74420fbb4",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Statement Trend SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Statement Actual]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "806d3f6a-d0fd-444f-9f7b-b54e8f9ebc61",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Board KPI Trend SVG",
            "expression": "VAR MetricName = SELECTEDVALUE(FactKpiScorecard[MetricName])\nRETURN\n    SWITCH(\n        TRUE(),\n        MetricName = \"Revenue\", [Revenue Sparkline SVG],\n        MetricName = \"Gross Margin\", [Gross Margin Sparkline SVG],\n        MetricName = \"EBITDA\", [EBITDA Sparkline SVG],\n        MetricName = \"Cash Balance\", [Cash Sparkline SVG],\n        MetricName = \"Runway\", [Runway Sparkline SVG],\n        MetricName = \"Funding Need\", [Funding Sparkline SVG],\n        MetricName = \"Leverage\", [Leverage Sparkline SVG],\n        MetricName = \"Interest Coverage\", [Interest Coverage Sparkline SVG],\n        [Revenue Sparkline SVG]\n    )",
            "lineageTag": "58e124ca-1965-44d8-8448-c44bea1561df",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Risk Signal SVG",
            "expression": "VAR SeverityValue = SELECTEDVALUE(FactRiskRegister[Severity], \"Watch\")\nVAR ProbabilityValue = MIN(0.98, MAX(0.02, MAX(FactRiskRegister[Probability])))\nVAR MarkerX = 12 + ProbabilityValue * 96\nVAR SeverityColor =\n    SWITCH(\n        SeverityValue,\n        \"Critical\", \"%23B73535\",\n        \"High\", \"%23BE7C10\",\n        \"%231F8E45\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'>\" &\n    \"<rect x='0' y='0' width='120' height='44' rx='7' fill='%23F8F5FC'/>\" &\n    \"<rect x='12' y='17' width='32' height='10' rx='5' fill='%23DDEEDC'/>\" &\n    \"<rect x='44' y='17' width='32' height='10' rx='5' fill='%23FFF3D6'/>\" &\n    \"<rect x='76' y='17' width='32' height='10' rx='5' fill='%23F3D7D7'/>\" &\n    \"<line x1='12' y1='32' x2='108' y2='32' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='3 4'/>\" &\n    \"<circle cx='\" & FORMAT(MarkerX, \"0.0\") & \"' cy='22' r='6' fill='\" & SeverityColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(MarkerX, \"0.0\") & \"' cy='22' r='2' fill='%23FFFFFF'/>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "4ffc49b8-6b5b-4188-bf7f-2296c8af4ae5",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Portfolio Signature SVG",
            "expression": "VAR SVG =\n    \"<svg xmlns=\"\"http://www.w3.org/2000/svg\"\" viewBox=\"\"0 0 64 64\"\" role=\"\"img\"\" aria-label=\"\"AT modern FP&amp;A monogram\"\"> <defs> <linearGradient id=\"\"bg\"\" x1=\"\"7\"\" y1=\"\"58\"\" x2=\"\"57\"\" y2=\"\"6\"\" gradientUnits=\"\"userSpaceOnUse\"\"> <stop stop-color=\"\"%230a1323\"\"/> <stop offset=\"\"0.58\"\" stop-color=\"\"%23101b2d\"\"/> <stop offset=\"\"1\"\" stop-color=\"\"%2314303a\"\"/> </linearGradient> <linearGradient id=\"\"accent\"\" x1=\"\"12\"\" y1=\"\"51\"\" x2=\"\"52\"\" y2=\"\"44\"\" gradientUnits=\"\"userSpaceOnUse\"\"> <stop stop-color=\"\"%238ab8ff\"\"/> <stop offset=\"\"1\"\" stop-color=\"\"%238de1d6\"\"/> </linearGradient> </defs> <rect width=\"\"64\"\" height=\"\"64\"\" rx=\"\"14\"\" fill=\"\"url(%23bg)\"\"/> <rect x=\"\"6\"\" y=\"\"6\"\" width=\"\"52\"\" height=\"\"52\"\" rx=\"\"11\"\" fill=\"\"%23f8fbff\"\" fill-opacity=\"\"0.025\"\"/> <rect x=\"\"6.5\"\" y=\"\"6.5\"\" width=\"\"51\"\" height=\"\"51\"\" rx=\"\"10.5\"\" fill=\"\"none\"\" stroke=\"\"%23f8fbff\"\" stroke-opacity=\"\"0.13\"\" stroke-width=\"\"1.6\"\"/> <text x=\"\"8.5\"\" y=\"\"43\"\" fill=\"\"%23f8fbff\"\" font-family=\"\"Arial, Helvetica, sans-serif\"\" font-size=\"\"31\"\" font-weight=\"\"900\"\">AT</text> <path d=\"\"M12 50C22 46.5 35 48 52 42.5\"\" fill=\"\"none\"\" stroke=\"\"url(%23accent)\"\" stroke-width=\"\"2.8\"\" stroke-linecap=\"\"round\"\" opacity=\"\"0.88\"\"/> <circle cx=\"\"52\"\" cy=\"\"42.5\"\" r=\"\"2.85\"\" fill=\"\"%23e9bf72\"\"/> </svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "22f62970-7e54-408c-8818-82f3817e122c",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Revenue KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Revenue], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Revenue], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Revenue]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%234F87F5' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%234F87F5' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Revenue</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%234F87F5'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "b7819870-5044-4e32-a24e-13e52e525ce1",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Margin KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Gross Margin %], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Gross Margin %], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0%\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0%\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue * 100, \"+0.0;-0.0;0.0\") & \"pt\")\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Gross Margin %]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%230F9F95' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%230F9F95' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Margin</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%230F9F95'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "c599ac03-beca-42ec-b107-61d8aa3aa152",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "EBITDA KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([EBITDA], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([EBITDA], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [EBITDA]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%231F8E45' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%231F8E45' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>EBITDA</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%231F8E45'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "e7dafad0-d5bb-4a19-8897-fedfecd43c2f",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cash KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Cash Balance], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Cash Balance], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Cash Balance]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%23BE7C10\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%23BE7C10' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%23BE7C10' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Cash</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23BE7C10'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "bc9bfedf-09a9-4000-844d-2b6f1e67a57d",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Runway KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Runway Months], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Runway Months], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0x\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0x\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue, \"+0.0x;-0.0x;0.0x\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Runway Months]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%234F87F5' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%234F87F5' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Runway</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%234F87F5'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "81977575-b620-4db7-9d56-c0a5b61a3b50",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "FCF KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Free Cash Flow], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Free Cash Flow], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Free Cash Flow]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%230F9F95' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%230F9F95' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>FCF</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%230F9F95'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "aa103661-f62a-4c5b-aefa-28d34fd848ba",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Burn KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Net Burn], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Net Burn], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue <= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Net Burn]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23B73535\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%23B73535' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%23B73535' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Burn</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23B73535'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "f5c7e3f2-8c88-4bc8-a7a0-1146910561eb",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Funding KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Funding Need], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Funding Need], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0M;($#,0M);$0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0M;($#,0M);$0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue <= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Funding Need]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue <= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%231F8E45' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%231F8E45' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Funding</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%231F8E45'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "9356c064-b40f-40b3-a633-a4a5854d789d",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "EV KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Enterprise Value], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Enterprise Value], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Enterprise Value]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%234F87F5' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%234F87F5' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>EV</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%234F87F5'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "6ce36ccc-d455-4041-80f3-36d6f7d85518",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Equity KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Equity Value], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Equity Value], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Equity Value]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%231F8E45' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%231F8E45' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Equity</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%231F8E45'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "3ba3dce0-b972-4b32-a66f-c463c16df9df",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Leverage KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Leverage Ratio], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Leverage Ratio], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0x\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0x\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue, \"+0.0x;-0.0x;0.0x\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue <= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Leverage Ratio]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23BE7C10\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%23BE7C10' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%23BE7C10' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Leverage</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23BE7C10'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "4ed98bcd-8bb5-4294-8745-8d252d8fda90",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Headroom KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Leverage Headroom], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Leverage Headroom], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0x\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0x\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue, \"+0.0x;-0.0x;0.0x\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Leverage Headroom]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%230F9F95' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%230F9F95' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Headroom</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%230F9F95'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "9a7ea8c2-6b94-4946-b597-bf2b5f4ae9c0",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Risk KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Risk Exposure], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Risk Exposure], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0M;($#,0M);$0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0M;($#,0M);$0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue <= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Risk Exposure]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23B73535\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='240' height='132' viewBox='0 0 248 140'>\" &\n    \"<rect x='5' y='5' width='238' height='130' rx='14' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='18' y='13' width='212' height='4' rx='2' fill='%23B73535' opacity='0.9'/>\" &\n    \"<rect x='18' y='29' width='12' height='12' rx='3' fill='%23B73535' opacity='0.95'/>\" &\n    \"<circle cx='24' cy='35' r='2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='39' font-family='Segoe UI' font-size='14' font-weight='750' fill='%23211A32'>Risk</text>\" &\n    \"<text x='18' y='80' font-family='Segoe UI' font-size='27' font-weight='750' fill='%23B73535'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='94' width='98' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='122' y='94' width='110' height='34' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='123' font-family='Segoe UI' font-size='12' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='132' y='108' font-family='Segoe UI' font-size='11' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='134,114 140,124 128,124' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='148' y='123' font-family='Segoe UI' font-size='12' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "e5c2fa22-0ddf-4037-b2ac-bf11746d483f",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Board Status Icon",
            "expression": "SWITCH(TRUE(), [Revenue vs Plan %] >= 0.03, UNICHAR(9650), [Revenue vs Plan %] >= -0.02, UNICHAR(8212), UNICHAR(9660))",
            "lineageTag": "3819e220-5020-462f-9bfe-82dd5cc863da"
          },
          {
            "name": "Board Status Color",
            "expression": "SWITCH(TRUE(), [Revenue vs Plan %] >= 0.03, \"#2FA66A\", [Revenue vs Plan %] >= -0.02, \"#C58A18\", \"#C94A4A\")",
            "lineageTag": "f43fbf50-3a85-4193-ab6a-91fba83f97a3"
          },
          {
            "name": "Lens Summary SVG",
            "expression": "VAR YearText =\n    IF(HASONEVALUE(DimDate[Year]), FORMAT(SELECTEDVALUE(DimDate[Year]), \"0\"), \"All Years\")\nVAR ScenarioText =\n    IF(HASONEVALUE(DimScenario[ScenarioName]), SELECTEDVALUE(DimScenario[ScenarioName]), FORMAT(COUNTROWS(VALUES(DimScenario[ScenarioName])), \"0\") & \" scenarios\")\nVAR BUCount = COUNTROWS(VALUES(DimBusinessUnit[BusinessUnit]))\nVAR BUTotal = CALCULATE(COUNTROWS(VALUES(DimBusinessUnit[BusinessUnit])), ALL(DimBusinessUnit[BusinessUnit]))\nVAR BUText =\n    IF(NOT ISFILTERED(DimBusinessUnit[BusinessUnit]) || BUCount = BUTotal,\n        \"All BU\",\n        IF(BUCount = 1, SELECTEDVALUE(DimBusinessUnit[BusinessUnit]), FORMAT(BUCount, \"0\") & \" BU\"))\nVAR RegionCount = COUNTROWS(VALUES(DimRegion[Region]))\nVAR RegionTotal = CALCULATE(COUNTROWS(VALUES(DimRegion[Region])), ALL(DimRegion[Region]))\nVAR RegionText =\n    IF(NOT ISFILTERED(DimRegion[Region]) || RegionCount = RegionTotal,\n        \"All Regions\",\n        IF(RegionCount = 1, SELECTEDVALUE(DimRegion[Region]), FORMAT(RegionCount, \"0\") & \" Regions\"))\nVAR Line1 = LEFT(YearText & \" | \" & ScenarioText, 25)\nVAR Line2 = LEFT(BUText & \" | \" & RegionText, 28)\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='154' height='52' viewBox='0 0 154 52'>\" &\n    \"<rect x='0.5' y='0.5' width='153' height='51' rx='7' fill='%233F1A63' stroke='%238E73E7' stroke-width='1'/>\" &\n    \"<text x='10' y='16' font-family='Segoe UI' font-size='9.5' font-weight='700' fill='%23CFC3E6'>Current Lens</text>\" &\n    \"<circle cx='136' cy='13' r='3.4' fill='%236EE4CF'/>\" &\n    \"<text x='10' y='33' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%23FFFFFF'>\" & Line1 & \"</text>\" &\n    \"<text x='10' y='46' font-family='Segoe UI' font-size='8.7' fill='%23CFC3E6'>\" & Line2 & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "d4984e1c-4acf-412e-a5b6-50358b4ba5a7",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Performance Decision Chips SVG",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\")\nVAR Chip1Text = \"Scenario: \" & SWITCH(ScenarioID, \"Upside\", \"Upside\", \"Downside\", \"Downside\", \"Base\")\nVAR Chip2Text = SWITCH(ScenarioID, \"Upside\", \"GM: +1.4 pts\", \"Downside\", \"GM: -0.7 pts\", \"GM: +0.8 pts\")\nVAR Chip3Text = SWITCH(ScenarioID, \"Upside\", \"Runway: >99 mo\", \"Downside\", \"Runway: 18.5 mo\", \"Runway: >99 mo\")\nVAR Chip1Accent = SWITCH(ScenarioID, \"Upside\", \"%230F9F95\", \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip1Fill = SWITCH(ScenarioID, \"Upside\", \"%23EAF7FF\", \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR Chip2Accent = SWITCH(ScenarioID, \"Downside\", \"%23B73535\", \"%230F9F95\")\nVAR Chip2Fill = SWITCH(ScenarioID, \"Downside\", \"%23FCE7E7\", \"%23E7F0FF\")\nVAR Chip3Accent = SWITCH(ScenarioID, \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip3Fill = SWITCH(ScenarioID, \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\" &\n    \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\" &\n    \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='\" & Chip1Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='13' y='13' width='11' height='11' rx='3' fill='\" & Chip1Accent & \"'/>\" &\n    \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\" &\n    \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='\" & Chip2Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='169' y='13' width='11' height='11' rx='3' fill='\" & Chip2Accent & \"'/>\" &\n    \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\" &\n    \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='\" & Chip3Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='333' y='13' width='11' height='11' rx='3' fill='\" & Chip3Accent & \"'/>\" &\n    \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "a5372791-d089-44fd-bcb9-3648fa8346a1",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cash Decision Chips SVG",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\")\nVAR Chip1Text = \"Scenario: \" & SWITCH(ScenarioID, \"Upside\", \"Upside\", \"Downside\", \"Downside\", \"Base\")\nVAR Chip2Text = SWITCH(ScenarioID, \"Upside\", \"Funding: $0M\", \"Downside\", \"Funding: $14M\", \"Funding: $0M\")\nVAR Chip3Text = SWITCH(ScenarioID, \"Upside\", \"FCF: $38.0M\", \"Downside\", \"FCF: ($8.5M)\", \"FCF: $22.5M\")\nVAR Chip1Accent = SWITCH(ScenarioID, \"Upside\", \"%230F9F95\", \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip1Fill = SWITCH(ScenarioID, \"Upside\", \"%23EAF7FF\", \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR Chip2Accent = SWITCH(ScenarioID, \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip2Fill = SWITCH(ScenarioID, \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR Chip3Accent = SWITCH(ScenarioID, \"Downside\", \"%23B73535\", \"%230F9F95\")\nVAR Chip3Fill = SWITCH(ScenarioID, \"Downside\", \"%23FCE7E7\", \"%23E7F0FF\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\" &\n    \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\" &\n    \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='\" & Chip1Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='13' y='13' width='11' height='11' rx='3' fill='\" & Chip1Accent & \"'/>\" &\n    \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\" &\n    \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='\" & Chip2Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='169' y='13' width='11' height='11' rx='3' fill='\" & Chip2Accent & \"'/>\" &\n    \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\" &\n    \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='\" & Chip3Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='333' y='13' width='11' height='11' rx='3' fill='\" & Chip3Accent & \"'/>\" &\n    \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "e3739550-ab14-499c-aa48-d135f56dcf57",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Risk Decision Chips SVG",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\")\nVAR Chip1Text = \"Scenario: \" & SWITCH(ScenarioID, \"Upside\", \"Upside\", \"Downside\", \"Downside\", \"Base\")\nVAR Chip2Text = SWITCH(ScenarioID, \"Upside\", \"Headroom: 2.1x\", \"Downside\", \"Headroom: 0.4x\", \"Headroom: 1.3x\")\nVAR Chip3Text = SWITCH(ScenarioID, \"Upside\", \"Risk: $7M\", \"Downside\", \"Risk: $26M\", \"Risk: $14M\")\nVAR Chip1Accent = SWITCH(ScenarioID, \"Upside\", \"%230F9F95\", \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip1Fill = SWITCH(ScenarioID, \"Upside\", \"%23EAF7FF\", \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR Chip2Accent = SWITCH(ScenarioID, \"Downside\", \"%23BE7C10\", \"%230F9F95\")\nVAR Chip2Fill = SWITCH(ScenarioID, \"Downside\", \"%23FFF3D6\", \"%23E7F0FF\")\nVAR Chip3Accent = SWITCH(ScenarioID, \"Downside\", \"%23B73535\", \"Upside\", \"%232FA66A\", \"%23BE7C10\")\nVAR Chip3Fill = SWITCH(ScenarioID, \"Downside\", \"%23FCE7E7\", \"Upside\", \"%23E6F4EC\", \"%23FFF3D6\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\" &\n    \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\" &\n    \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='\" & Chip1Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='13' y='13' width='11' height='11' rx='3' fill='\" & Chip1Accent & \"'/>\" &\n    \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\" &\n    \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='\" & Chip2Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='169' y='13' width='11' height='11' rx='3' fill='\" & Chip2Accent & \"'/>\" &\n    \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\" &\n    \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='\" & Chip3Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='333' y='13' width='11' height='11' rx='3' fill='\" & Chip3Accent & \"'/>\" &\n    \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "265d2e8e-355e-4254-8be2-6528a02b16ba",
            "dataCategory": "ImageUrl"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Rel_FactPnlMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactPnlMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactPnlMonthly_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactPnlMonthly",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactPnlMonthly_BusinessUnitID_DimBusinessUnit_BusinessUnitID",
        "fromTable": "FactPnlMonthly",
        "fromColumn": "BusinessUnitID",
        "toTable": "DimBusinessUnit",
        "toColumn": "BusinessUnitID"
      },
      {
        "name": "Rel_FactPnlMonthly_RegionID_DimRegion_RegionID",
        "fromTable": "FactPnlMonthly",
        "fromColumn": "RegionID",
        "toTable": "DimRegion",
        "toColumn": "RegionID"
      },
      {
        "name": "Rel_FactOpexMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactOpexMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactOpexMonthly_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactOpexMonthly",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactOpexMonthly_CostCategoryID_DimCostCategory_CostCategoryID",
        "fromTable": "FactOpexMonthly",
        "fromColumn": "CostCategoryID",
        "toTable": "DimCostCategory",
        "toColumn": "CostCategoryID"
      },
      {
        "name": "Rel_FactCashMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactCashMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactCashMonthly_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactCashMonthly",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactStatementLines_MonthStart_DimDate_MonthStart",
        "fromTable": "FactStatementLines",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactStatementLines_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactStatementLines",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactCovenantMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactCovenantMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactCovenantMonthly_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactCovenantMonthly",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactValuation_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactValuation",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactSensitivity_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactSensitivity",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactRiskRegister_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactRiskRegister",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      }
    ]
  }
}