{
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DimDate",
        "lineageTag": "51448cfd-f81c-460e-8210-70582188b4c3",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "MonthLabel",
            "dataType": "string",
            "sourceColumn": "MonthLabel",
            "summarizeBy": "none"
          },
          {
            "name": "MonthIndex",
            "dataType": "int64",
            "sourceColumn": "MonthIndex",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "IsLatestCompleteMonth",
            "dataType": "int64",
            "sourceColumn": "IsLatestCompleteMonth",
            "formatString": "0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_DimDate",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimDate.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"MonthLabel\", type text}, {\"MonthIndex\", Int64.Type}, {\"Year\", Int64.Type}, {\"Quarter\", type text}, {\"IsLatestCompleteMonth\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimScenario",
        "lineageTag": "23dad2b0-689f-4665-a128-6aa529121151",
        "columns": [
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioName",
            "dataType": "string",
            "sourceColumn": "ScenarioName",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueIndex",
            "dataType": "double",
            "sourceColumn": "RevenueIndex",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "MarginIndex",
            "dataType": "double",
            "sourceColumn": "MarginIndex",
            "formatString": "0.0%",
            "summarizeBy": "sum"
          },
          {
            "name": "BurnIndex",
            "dataType": "double",
            "sourceColumn": "BurnIndex",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ScenarioSort",
            "dataType": "int64",
            "sourceColumn": "ScenarioSort",
            "formatString": "0",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_DimScenario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimScenario.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ScenarioID\", type text}, {\"ScenarioName\", type text}, {\"RevenueIndex\", type number}, {\"MarginIndex\", type number}, {\"BurnIndex\", type number}, {\"ScenarioSort\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimBusinessUnit",
        "lineageTag": "3ee3eb91-86a3-497e-8fb6-e2e499669068",
        "columns": [
          {
            "name": "BusinessUnitID",
            "dataType": "string",
            "sourceColumn": "BusinessUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "dataType": "string",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueFamily",
            "dataType": "string",
            "sourceColumn": "RevenueFamily",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "none"
          },
          {
            "name": "MixWeight",
            "dataType": "double",
            "sourceColumn": "MixWeight",
            "summarizeBy": "sum"
          },
          {
            "name": "TargetGrossMargin",
            "dataType": "double",
            "sourceColumn": "TargetGrossMargin",
            "formatString": "0.0%",
            "summarizeBy": "sum"
          },
          {
            "name": "GrowthIndex",
            "dataType": "double",
            "sourceColumn": "GrowthIndex",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_DimBusinessUnit",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimBusinessUnit.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"BusinessUnitID\", type text}, {\"BusinessUnit\", type text}, {\"RevenueFamily\", type text}, {\"MixWeight\", type number}, {\"TargetGrossMargin\", type number}, {\"GrowthIndex\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimRegion",
        "lineageTag": "44fb447c-c7e5-4b4e-8252-13f2ed2fa603",
        "columns": [
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "RegionMaturity",
            "dataType": "string",
            "sourceColumn": "RegionMaturity",
            "summarizeBy": "none"
          },
          {
            "name": "MixWeight",
            "dataType": "double",
            "sourceColumn": "MixWeight",
            "summarizeBy": "sum"
          },
          {
            "name": "DemandIndex",
            "dataType": "double",
            "sourceColumn": "DemandIndex",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_DimRegion",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimRegion.csv\"), [Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"RegionID\", type text}, {\"Region\", type text}, {\"RegionMaturity\", type text}, {\"MixWeight\", type number}, {\"DemandIndex\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCostCategory",
        "lineageTag": "9e0c4588-9024-4559-9f70-ad104d7cda09",
        "columns": [
          {
            "name": "CostCategoryID",
            "dataType": "string",
            "sourceColumn": "CostCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "CostCategory",
            "dataType": "string",
            "sourceColumn": "CostCategory",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueLoad",
            "dataType": "double",
            "sourceColumn": "RevenueLoad",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_DimCostCategory",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\DimCostCategory.csv\"), [Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"CostCategoryID\", type text}, {\"CostCategory\", type text}, {\"RevenueLoad\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactPnlMonthly",
        "lineageTag": "5594e52b-3126-48cd-a7ee-dce8c7908a08",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnitID",
            "dataType": "string",
            "sourceColumn": "BusinessUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "sourceColumn": "Revenue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "PlanRevenue",
            "dataType": "double",
            "sourceColumn": "PlanRevenue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ForecastRevenue",
            "dataType": "double",
            "sourceColumn": "ForecastRevenue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "COGS",
            "dataType": "double",
            "sourceColumn": "COGS",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "GrossProfit",
            "dataType": "double",
            "sourceColumn": "GrossProfit",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "OperatingExpense",
            "dataType": "double",
            "sourceColumn": "OperatingExpense",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "EBITDA",
            "dataType": "double",
            "sourceColumn": "EBITDA",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "PlanEBITDA",
            "dataType": "double",
            "sourceColumn": "PlanEBITDA",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ForecastEBITDA",
            "dataType": "double",
            "sourceColumn": "ForecastEBITDA",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "NetIncome",
            "dataType": "double",
            "sourceColumn": "NetIncome",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "IsSynthetic",
            "dataType": "string",
            "sourceColumn": "IsSynthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_FactPnlMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactPnlMonthly.csv\"), [Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"BusinessUnitID\", type text}, {\"RegionID\", type text}, {\"Revenue\", type number}, {\"PlanRevenue\", type number}, {\"ForecastRevenue\", type number}, {\"COGS\", type number}, {\"GrossProfit\", type number}, {\"OperatingExpense\", type number}, {\"EBITDA\", type number}, {\"PlanEBITDA\", type number}, {\"ForecastEBITDA\", type number}, {\"NetIncome\", type number}, {\"IsSynthetic\", type text}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactOpexMonthly",
        "lineageTag": "927ee631-4916-410e-b776-1a6eef5587d2",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "CostCategoryID",
            "dataType": "string",
            "sourceColumn": "CostCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "OperatingExpense",
            "dataType": "double",
            "sourceColumn": "OperatingExpense",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "PlanOperatingExpense",
            "dataType": "double",
            "sourceColumn": "PlanOperatingExpense",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ForecastOperatingExpense",
            "dataType": "double",
            "sourceColumn": "ForecastOperatingExpense",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactOpexMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactOpexMonthly.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"CostCategoryID\", type text}, {\"OperatingExpense\", type number}, {\"PlanOperatingExpense\", type number}, {\"ForecastOperatingExpense\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCashMonthly",
        "lineageTag": "e32a785d-eb8e-4576-a5a7-b3d998e5a533",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "CashBalance",
            "dataType": "double",
            "sourceColumn": "CashBalance",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "OperatingCashFlow",
            "dataType": "double",
            "sourceColumn": "OperatingCashFlow",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "Capex",
            "dataType": "double",
            "sourceColumn": "Capex",
            "summarizeBy": "sum"
          },
          {
            "name": "FreeCashFlow",
            "dataType": "double",
            "sourceColumn": "FreeCashFlow",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "NetBurn",
            "dataType": "double",
            "sourceColumn": "NetBurn",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "RunwayMonths",
            "dataType": "double",
            "sourceColumn": "RunwayMonths",
            "summarizeBy": "sum"
          },
          {
            "name": "FundingNeed",
            "dataType": "double",
            "sourceColumn": "FundingNeed",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "Debt",
            "dataType": "double",
            "sourceColumn": "Debt",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkingCapital",
            "dataType": "double",
            "sourceColumn": "WorkingCapital",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "FinancingInflow",
            "dataType": "double",
            "sourceColumn": "FinancingInflow",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactCashMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactCashMonthly.csv\"), [Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"CashBalance\", type number}, {\"OperatingCashFlow\", type number}, {\"Capex\", type number}, {\"FreeCashFlow\", type number}, {\"NetBurn\", type number}, {\"RunwayMonths\", type number}, {\"FundingNeed\", type number}, {\"Debt\", type number}, {\"WorkingCapital\", type number}, {\"FinancingInflow\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactStatementLines",
        "lineageTag": "73da39dc-1fee-422a-b63c-3cbdec574678",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "Statement",
            "dataType": "string",
            "sourceColumn": "Statement",
            "summarizeBy": "none"
          },
          {
            "name": "LineItem",
            "dataType": "string",
            "sourceColumn": "LineItem",
            "summarizeBy": "none"
          },
          {
            "name": "LineSort",
            "dataType": "int64",
            "sourceColumn": "LineSort",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "ValueActual",
            "dataType": "double",
            "sourceColumn": "ValueActual",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ValuePlan",
            "dataType": "double",
            "sourceColumn": "ValuePlan",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "ValueForecast",
            "dataType": "double",
            "sourceColumn": "ValueForecast",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactStatementLines",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactStatementLines.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"Statement\", type text}, {\"LineItem\", type text}, {\"LineSort\", Int64.Type}, {\"ValueActual\", type number}, {\"ValuePlan\", type number}, {\"ValueForecast\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCovenantMonthly",
        "lineageTag": "29790c20-d899-48a8-a125-08e78bbaa307",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "summarizeBy": "none"
          },
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueLTM",
            "dataType": "double",
            "sourceColumn": "RevenueLTM",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "EBITDALTM",
            "dataType": "double",
            "sourceColumn": "EBITDALTM",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "NetDebt",
            "dataType": "double",
            "sourceColumn": "NetDebt",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "LeverageRatio",
            "dataType": "double",
            "sourceColumn": "LeverageRatio",
            "summarizeBy": "sum"
          },
          {
            "name": "LeverageLimit",
            "dataType": "double",
            "sourceColumn": "LeverageLimit",
            "summarizeBy": "sum"
          },
          {
            "name": "LeverageHeadroom",
            "dataType": "double",
            "sourceColumn": "LeverageHeadroom",
            "summarizeBy": "sum"
          },
          {
            "name": "InterestCoverage",
            "dataType": "double",
            "sourceColumn": "InterestCoverage",
            "summarizeBy": "sum"
          },
          {
            "name": "InterestCoverageLimit",
            "dataType": "double",
            "sourceColumn": "InterestCoverageLimit",
            "summarizeBy": "sum"
          },
          {
            "name": "Liquidity",
            "dataType": "double",
            "sourceColumn": "Liquidity",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "LiquidityMinimum",
            "dataType": "int64",
            "sourceColumn": "LiquidityMinimum",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "LiquidityHeadroom",
            "dataType": "double",
            "sourceColumn": "LiquidityHeadroom",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "CovenantStatus",
            "dataType": "string",
            "sourceColumn": "CovenantStatus",
            "summarizeBy": "none"
          },
          {
            "name": "RiskScore",
            "dataType": "double",
            "sourceColumn": "RiskScore",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactCovenantMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactCovenantMonthly.csv\"), [Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"ScenarioID\", type text}, {\"RevenueLTM\", type number}, {\"EBITDALTM\", type number}, {\"NetDebt\", type number}, {\"LeverageRatio\", type number}, {\"LeverageLimit\", type number}, {\"LeverageHeadroom\", type number}, {\"InterestCoverage\", type number}, {\"InterestCoverageLimit\", type number}, {\"Liquidity\", type number}, {\"LiquidityMinimum\", Int64.Type}, {\"LiquidityHeadroom\", type number}, {\"CovenantStatus\", type text}, {\"RiskScore\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactValuation",
        "lineageTag": "2a5ed483-e6ff-49f4-975f-fbad2ab86b5c",
        "columns": [
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "Method",
            "dataType": "string",
            "sourceColumn": "Method",
            "summarizeBy": "none"
          },
          {
            "name": "MethodSort",
            "dataType": "int64",
            "sourceColumn": "MethodSort",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Multiple",
            "dataType": "double",
            "sourceColumn": "Multiple",
            "summarizeBy": "sum"
          },
          {
            "name": "EnterpriseValue",
            "dataType": "double",
            "sourceColumn": "EnterpriseValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "EquityValue",
            "dataType": "double",
            "sourceColumn": "EquityValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "LowValue",
            "dataType": "double",
            "sourceColumn": "LowValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "HighValue",
            "dataType": "double",
            "sourceColumn": "HighValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactValuation",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactValuation.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ScenarioID\", type text}, {\"Method\", type text}, {\"MethodSort\", Int64.Type}, {\"Multiple\", type number}, {\"EnterpriseValue\", type number}, {\"EquityValue\", type number}, {\"LowValue\", type number}, {\"HighValue\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactSensitivity",
        "lineageTag": "f7f21dc9-a228-4f87-b96e-1a5548b890c2",
        "columns": [
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "Driver",
            "dataType": "string",
            "sourceColumn": "Driver",
            "summarizeBy": "none"
          },
          {
            "name": "CaseLabel",
            "dataType": "string",
            "sourceColumn": "CaseLabel",
            "summarizeBy": "none"
          },
          {
            "name": "DriverCase",
            "dataType": "string",
            "sourceColumn": "DriverCase",
            "summarizeBy": "none"
          },
          {
            "name": "EquityValueDelta",
            "dataType": "double",
            "sourceColumn": "EquityValueDelta",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "EquityValue",
            "dataType": "double",
            "sourceColumn": "EquityValue",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "p_FactSensitivity",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactSensitivity.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ScenarioID\", type text}, {\"Driver\", type text}, {\"CaseLabel\", type text}, {\"DriverCase\", type text}, {\"EquityValueDelta\", type number}, {\"EquityValue\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactRiskRegister",
        "lineageTag": "b9f78405-3093-471d-9e8b-08e2928ff829",
        "columns": [
          {
            "name": "ScenarioID",
            "dataType": "string",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "none"
          },
          {
            "name": "RiskID",
            "dataType": "string",
            "sourceColumn": "RiskID",
            "summarizeBy": "none"
          },
          {
            "name": "RiskCategory",
            "dataType": "string",
            "sourceColumn": "RiskCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Risk",
            "dataType": "string",
            "sourceColumn": "Risk",
            "summarizeBy": "none"
          },
          {
            "name": "Severity",
            "dataType": "string",
            "sourceColumn": "Severity",
            "summarizeBy": "none"
          },
          {
            "name": "Probability",
            "dataType": "double",
            "sourceColumn": "Probability",
            "formatString": "0.0%",
            "summarizeBy": "sum"
          },
          {
            "name": "ExposureUSD",
            "dataType": "double",
            "sourceColumn": "ExposureUSD",
            "formatString": "$#,0;($#,0);$0",
            "summarizeBy": "sum"
          },
          {
            "name": "Owner",
            "dataType": "string",
            "sourceColumn": "Owner",
            "summarizeBy": "none"
          },
          {
            "name": "MitigationStatus",
            "dataType": "string",
            "sourceColumn": "MitigationStatus",
            "summarizeBy": "none"
          },
          {
            "name": "BoardAsk",
            "dataType": "string",
            "sourceColumn": "BoardAsk",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_FactRiskRegister",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactRiskRegister.csv\"), [Delimiter=\",\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ScenarioID\", type text}, {\"RiskID\", type text}, {\"RiskCategory\", type text}, {\"Risk\", type text}, {\"Severity\", type text}, {\"Probability\", type number}, {\"ExposureUSD\", type number}, {\"Owner\", type text}, {\"MitigationStatus\", type text}, {\"BoardAsk\", type text}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactKpiScorecard",
        "lineageTag": "1e57d6ee-d260-461f-8868-833b3a7215fd",
        "columns": [
          {
            "name": "MetricName",
            "dataType": "string",
            "sourceColumn": "MetricName",
            "summarizeBy": "none"
          },
          {
            "name": "MetricFamily",
            "dataType": "string",
            "sourceColumn": "MetricFamily",
            "summarizeBy": "none"
          },
          {
            "name": "ActualDisplay",
            "dataType": "string",
            "sourceColumn": "ActualDisplay",
            "summarizeBy": "none"
          },
          {
            "name": "PlanDisplay",
            "dataType": "string",
            "sourceColumn": "PlanDisplay",
            "summarizeBy": "none"
          },
          {
            "name": "VarianceDisplay",
            "dataType": "string",
            "sourceColumn": "VarianceDisplay",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "BoardNarrative",
            "dataType": "string",
            "sourceColumn": "BoardNarrative",
            "summarizeBy": "none"
          },
          {
            "name": "SortOrder",
            "dataType": "int64",
            "sourceColumn": "SortOrder",
            "formatString": "0",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_FactKpiScorecard",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 20 - Board Investor CFO Pack\\\\data\\\\prepared\\\\FactKpiScorecard.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MetricName\", type text}, {\"MetricFamily\", type text}, {\"ActualDisplay\", type text}, {\"PlanDisplay\", type text}, {\"VarianceDisplay\", type text}, {\"Status\", type text}, {\"BoardNarrative\", type text}, {\"SortOrder\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "KPI_Measures",
        "lineageTag": "8f7ee37a-0669-4215-bfa0-6c944fae0a5b",
        "columns": [
          {
            "name": "MeasureName",
            "dataType": "string",
            "sourceColumn": "MeasureName",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "p_KPI_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = #table(type table [MeasureName = text], {{\"KPI\"}}) in Source"
            }
          }
        ],
        "measures": [
          {
            "name": "Revenue",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[Revenue]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "21cf71fd-cb03-4027-acc4-ab369f484ee6",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Plan Revenue",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[PlanRevenue]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "d1b4d885-a4e1-4b55-8e14-f888fd6754de",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Forecast Revenue",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[ForecastRevenue]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "d2d57873-3842-4e29-9295-63d7cc73b0e2",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Revenue vs Plan",
            "expression": "[Revenue] - [Plan Revenue]",
            "lineageTag": "bcc44a91-dbd4-4e2e-ba98-227c68924c08",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Revenue vs Plan %",
            "expression": "DIVIDE([Revenue vs Plan], [Plan Revenue])",
            "lineageTag": "a246d1c0-22fa-4064-b3ef-b78100800528",
            "formatString": "0.0%"
          },
          {
            "name": "Gross Profit",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[GrossProfit]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "39d505de-5676-4216-81a4-55cd24ef234a",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Gross Margin %",
            "expression": "DIVIDE([Gross Profit], [Revenue])",
            "lineageTag": "52ed4fc6-7d8a-4d31-835f-e5852881b476",
            "formatString": "0.0%"
          },
          {
            "name": "EBITDA",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[EBITDA]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "e7d98e8c-05b3-43f7-b2f8-40f1d3f81f99",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Plan EBITDA",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[PlanEBITDA]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "0df42572-e017-4159-8091-08f05d51ac0f",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "EBITDA vs Plan",
            "expression": "[EBITDA] - [Plan EBITDA]",
            "lineageTag": "7bbd8914-6df6-4017-8a39-2fbca3235b14",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "EBITDA Margin %",
            "expression": "DIVIDE([EBITDA], [Revenue])",
            "lineageTag": "0dc8e078-c380-4ff9-99f0-ae3fa00945f1",
            "formatString": "0.0%"
          },
          {
            "name": "Net Income",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactPnlMonthly[NetIncome]), FactPnlMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "bf6a76ff-0a8c-4f43-b39d-4be81f43ebe0",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Operating Expense",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactOpexMonthly[OperatingExpense]), FactOpexMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "9aa7afdb-9405-4360-9c4b-a3124dd4dec5",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Revenue",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE([Revenue], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "c5efd192-c561-480b-864f-c6a0cf583bea",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Gross Margin %",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE([Gross Margin %], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "ee245c84-d334-404e-b3b6-d729dbf489bf",
            "formatString": "0.0%"
          },
          {
            "name": "Latest EBITDA",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE([EBITDA], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "fda33a96-7b26-4abc-ab92-f52938f919aa",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest EBITDA Margin %",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE([EBITDA Margin %], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "56597234-b3e2-49fa-8ef9-df473aa1d9fc",
            "formatString": "0.0%"
          },
          {
            "name": "Latest Cash Balance",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[CashBalance]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "a05b70f0-7baa-45ad-ab53-ef6f0588dfb8",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Cash Balance",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCashMonthly[CashBalance]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "cc2ff489-8818-4fa7-9bbd-71af62a87b5d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Operating Cash Flow",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactCashMonthly[OperatingCashFlow]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "f243d009-659d-4f43-8fd4-8b5ca5ce9ed5",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Free Cash Flow",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactCashMonthly[FreeCashFlow]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "47dafd33-e031-4061-926d-ead94019fa09",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Free Cash Flow",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[FreeCashFlow]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "e267f746-2062-4cdc-895d-2a22fc79488e",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Net Burn",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCashMonthly[NetBurn]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "41eb3006-981a-4cb6-a079-6adbec8e5c79",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Net Burn",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[NetBurn]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "eaee508e-4d11-468c-baa7-e9f87dabf199",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Runway Months",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCashMonthly[RunwayMonths]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "1a25c6e1-6891-473e-b528-c86a5cdb89ee",
            "formatString": "0.0x"
          },
          {
            "name": "Latest Runway Months",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[RunwayMonths]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "b7b0b38b-e63b-4910-bcad-4153533652a7",
            "formatString": "0.0x"
          },
          {
            "name": "Funding Need",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCashMonthly[FundingNeed]), FactCashMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "24450a50-bf25-4cb4-bd3b-e1fb2817efda",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Latest Funding Need",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCashMonthly[FundingNeed]), FactCashMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "81fb3003-c500-4efd-9a97-519b6337253e",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Statement Actual",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactStatementLines[ValueActual]), FactStatementLines[ScenarioID] = ScenarioID)",
            "lineageTag": "9d7bf0ce-855b-4091-b9a7-02e8dd6e60c7",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Statement Plan",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactStatementLines[ValuePlan]), FactStatementLines[ScenarioID] = ScenarioID)",
            "lineageTag": "1fa0c18c-4511-4bcd-8c5a-b7aae99c8b7d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Statement Forecast",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactStatementLines[ValueForecast]), FactStatementLines[ScenarioID] = ScenarioID)",
            "lineageTag": "eef206ff-0a1f-4c37-ad04-2f8672e222d0",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Statement Variance %",
            "expression": "DIVIDE([Statement Actual] - [Statement Plan], [Statement Plan])",
            "lineageTag": "14c5353a-e427-408e-ac07-f131c6b0ead1",
            "formatString": "0.0%"
          },
          {
            "name": "Enterprise Value",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(AVERAGE(FactValuation[EnterpriseValue]), FactValuation[ScenarioID] = ScenarioID)",
            "lineageTag": "6764dade-6036-44c5-a836-638e0a2d7727",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Equity Value",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(AVERAGE(FactValuation[EquityValue]), FactValuation[ScenarioID] = ScenarioID)",
            "lineageTag": "e7f6efa7-23b3-43aa-a06e-ba55557d9c14",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Valuation Low",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(AVERAGE(FactValuation[LowValue]), FactValuation[ScenarioID] = ScenarioID)",
            "lineageTag": "c6be8f11-910d-4429-bdd1-64e6982a8b3c",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Valuation High",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(AVERAGE(FactValuation[HighValue]), FactValuation[ScenarioID] = ScenarioID)",
            "lineageTag": "8ec27e7c-00b8-4ddf-a97c-56d24d53c860",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Sensitivity Delta",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactSensitivity[EquityValueDelta]), FactSensitivity[ScenarioID] = ScenarioID)",
            "lineageTag": "ac24daf3-bedf-49d4-98e5-675f1445cb90",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Leverage Ratio",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCovenantMonthly[LeverageRatio]), FactCovenantMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "92074c2f-1c75-4385-853c-4bcb4177aa03",
            "formatString": "0.0x"
          },
          {
            "name": "Leverage Limit",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(MAX(FactCovenantMonthly[LeverageLimit]), FactCovenantMonthly[ScenarioID] = ScenarioID)",
            "lineageTag": "1a5086af-1e60-4195-8cbb-dcb53b24684a",
            "formatString": "0.0x"
          },
          {
            "name": "Leverage Headroom",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCovenantMonthly[LeverageHeadroom]), FactCovenantMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "f7b139ee-9545-445f-a432-826a97e8bba4",
            "formatString": "0.0x"
          },
          {
            "name": "Interest Coverage",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCovenantMonthly[InterestCoverage]), FactCovenantMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "37e7f365-498c-4ab7-938b-2c7e5b3f6396",
            "formatString": "0.0x"
          },
          {
            "name": "Liquidity Headroom",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart]) RETURN CALCULATE(MAX(FactCovenantMonthly[LiquidityHeadroom]), FactCovenantMonthly[ScenarioID] = ScenarioID, FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))",
            "lineageTag": "bfc904ac-469d-41af-893d-f524cb1a842f",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Risk Exposure",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(SUM(FactRiskRegister[ExposureUSD]), FactRiskRegister[ScenarioID] = ScenarioID)",
            "lineageTag": "02aee2dc-5cee-4d1a-bf23-e6b50a75c779",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Critical Risk Count",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\") RETURN CALCULATE(COUNTROWS(FactRiskRegister), FactRiskRegister[ScenarioID] = ScenarioID, FactRiskRegister[Severity] = \"Critical\")",
            "lineageTag": "f2203418-2239-488f-81de-f7f782f961c5",
            "formatString": "#,0"
          },
          {
            "name": "Revenue Display",
            "expression": "VAR Value = [Revenue] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "103e887d-6b2a-43c0-8ee0-a018e4755be4"
          },
          {
            "name": "Gross Margin % Display",
            "expression": "FORMAT([Gross Margin %], \"0.0%\")",
            "lineageTag": "c94354e4-c368-4b0c-877e-1e8d34da504f"
          },
          {
            "name": "EBITDA Display",
            "expression": "VAR Value = [EBITDA] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "65ed0626-139c-47b9-9b70-8fde06ecc56b"
          },
          {
            "name": "Cash Balance Display",
            "expression": "VAR Value = [Cash Balance] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "839c473e-9569-4dd8-8151-5976803ec2f6"
          },
          {
            "name": "Runway Months Display",
            "expression": "FORMAT([Runway Months], \"0.0x\")",
            "lineageTag": "7607d8a8-1eb1-43fd-9334-a996a4ff8471"
          },
          {
            "name": "Free Cash Flow Display",
            "expression": "VAR Value = [Free Cash Flow] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "96a25cec-c8b2-40d1-b15a-e0633174b188"
          },
          {
            "name": "Net Burn Display",
            "expression": "VAR Value = [Net Burn] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "4150eaf1-eca1-4d44-8cc0-d52ff19bbfcc"
          },
          {
            "name": "Funding Need Display",
            "expression": "VAR Value = [Funding Need] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "b9aa9922-857b-49b7-b021-19978ace157f"
          },
          {
            "name": "Enterprise Value Display",
            "expression": "VAR Value = [Enterprise Value] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "26ca91d9-7cdf-42c5-b710-609e04a45ed0"
          },
          {
            "name": "Equity Value Display",
            "expression": "VAR Value = [Equity Value] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "918e3727-95f6-40de-9ccb-a90077961c69"
          },
          {
            "name": "Leverage Ratio Display",
            "expression": "FORMAT([Leverage Ratio], \"0.0x\")",
            "lineageTag": "d61fe06e-1af3-47fb-a69f-8e2a0a044945"
          },
          {
            "name": "Leverage Headroom Display",
            "expression": "FORMAT([Leverage Headroom], \"0.0x\")",
            "lineageTag": "769162d2-6282-4480-bd69-4501047bdc02"
          },
          {
            "name": "Risk Exposure Display",
            "expression": "VAR Value = [Risk Exposure] RETURN SWITCH(TRUE(), ABS(Value) >= 1000000000, FORMAT(DIVIDE(Value, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"), ABS(Value) >= 1000000, FORMAT(DIVIDE(Value, 1000000), \"$#,0M;($#,0M);$0M\"), FORMAT(Value, \"$#,0;($#,0);$0\"))",
            "lineageTag": "7b3596aa-9a46-4250-af95-6e330a16ef7f"
          },
          {
            "name": "Revenue KPI",
            "expression": "DIVIDE([Latest Revenue], 1000000)",
            "lineageTag": "12bead6a-b016-40e2-a1ca-5df494835c9a",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M"
          },
          {
            "name": "Gross Margin KPI",
            "expression": "[Latest Gross Margin %]",
            "lineageTag": "f8df333e-1f8f-47c0-9325-f0b1f2d804d7",
            "formatString": "0.0%"
          },
          {
            "name": "EBITDA KPI",
            "expression": "DIVIDE([Latest EBITDA], 1000000)",
            "lineageTag": "7ae61c86-3a4d-4057-a4d0-5fa270234f12",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M"
          },
          {
            "name": "Cash Balance KPI",
            "expression": "DIVIDE([Latest Cash Balance], 1000000)",
            "lineageTag": "501b9c9c-09ac-4407-9463-a3c384cbae1c",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M"
          },
          {
            "name": "Runway Months KPI",
            "expression": "[Latest Runway Months]",
            "lineageTag": "0393ab20-31c8-41ab-8ec1-2e842fe1fd2f",
            "formatString": "0.0x"
          },
          {
            "name": "Free Cash Flow KPI",
            "expression": "DIVIDE([Latest Free Cash Flow], 1000000)",
            "lineageTag": "3a960c15-809f-4637-bd45-5599896e81f8",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M"
          },
          {
            "name": "Net Burn KPI",
            "expression": "DIVIDE([Latest Net Burn], 1000000)",
            "lineageTag": "2bd9d242-5960-4a46-bba1-c9663519821b",
            "formatString": "$#,0M;($#,0M);$0M"
          },
          {
            "name": "Funding Need KPI",
            "expression": "DIVIDE([Latest Funding Need], 1000000)",
            "lineageTag": "8ba20f9b-d82c-4f17-88fb-f442be97a6d3",
            "formatString": "$#,0M;($#,0M);$0M"
          },
          {
            "name": "Enterprise Value KPI",
            "expression": "DIVIDE([Enterprise Value], 1000000000)",
            "lineageTag": "dd7c933a-37a2-482b-a47e-87de8ba08857",
            "formatString": "$#,0.0B;($#,0.0B);$0.0B"
          },
          {
            "name": "Equity Value KPI",
            "expression": "DIVIDE([Equity Value], 1000000000)",
            "lineageTag": "59868134-932f-4238-a5dd-bce80227e14e",
            "formatString": "$#,0.0B;($#,0.0B);$0.0B"
          },
          {
            "name": "Leverage KPI",
            "expression": "[Leverage Ratio]",
            "lineageTag": "793d6598-0709-4110-bb2c-393db8287dac",
            "formatString": "0.0x"
          },
          {
            "name": "Headroom KPI",
            "expression": "[Leverage Headroom]",
            "lineageTag": "d3aecda7-df9f-4650-ac62-3d1d75bbb025",
            "formatString": "0.0x"
          },
          {
            "name": "Risk Exposure KPI",
            "expression": "DIVIDE([Risk Exposure], 1000000)",
            "lineageTag": "315b60fe-3798-4205-9805-9aaff35cc5ef",
            "formatString": "$#,0M;($#,0M);$0M"
          },
          {
            "name": "Revenue Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Revenue]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "47f217bc-4110-4efa-9ac1-81d24cf633d0",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Gross Margin Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Gross Margin %]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "a0157a61-36a5-4593-9e81-ed5f9fb6c941",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "EBITDA Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [EBITDA]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "0a1e5861-6e8a-4f88-9e45-d8b430ace2bc",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cash Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Cash Balance]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%23BE7C10\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "e9d4ae7d-35c8-48aa-a97d-eb8168a8c1ac",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Runway Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Runway Months]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "a1bddffa-7ae0-4e4f-bc72-aac08bffcb9b",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Funding Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Funding Need]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue <= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "29f86cee-674b-49b2-9001-13fcf373a9e5",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Leverage Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Leverage Ratio]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue <= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "9d668405-700f-4429-92bc-666ba0a69afe",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Interest Coverage Sparkline SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Interest Coverage]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "2906cfae-7d69-40ad-bf19-6921a65d3634",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Statement Trend SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Statement Actual]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR StartYValue = 37 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR EndYValue = 37 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 30\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR Points =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 2 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 116\n        VAR YValue = 37 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 30\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nRETURN\n    \"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'><rect x='0' y='0' width='120' height='44' rx='7' fill='%23F3EFFA'/><rect x='0' y='16' width='120' height='12' rx='6' fill='%23DDEEDC'/><line x1='0' y1='22' x2='120' y2='22' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/><polyline points='\" & Points & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/><circle cx='2' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3' fill='%23FFFFFF' stroke='%238F7BAE' stroke-width='1.5'/><circle cx='118' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.5'/></svg>\"",
            "lineageTag": "6a06bba3-c888-4c55-bcfc-f567ae616491",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Board KPI Trend SVG",
            "expression": "VAR MetricName = SELECTEDVALUE(FactKpiScorecard[MetricName])\nRETURN\n    SWITCH(\n        TRUE(),\n        MetricName = \"Revenue\", [Revenue Sparkline SVG],\n        MetricName = \"Gross Margin\", [Gross Margin Sparkline SVG],\n        MetricName = \"EBITDA\", [EBITDA Sparkline SVG],\n        MetricName = \"Cash Balance\", [Cash Sparkline SVG],\n        MetricName = \"Runway\", [Runway Sparkline SVG],\n        MetricName = \"Funding Need\", [Funding Sparkline SVG],\n        MetricName = \"Leverage\", [Leverage Sparkline SVG],\n        MetricName = \"Interest Coverage\", [Interest Coverage Sparkline SVG],\n        [Revenue Sparkline SVG]\n    )",
            "lineageTag": "c5bca219-f852-4ee7-b153-3ea8f7aa6dcc",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Risk Signal SVG",
            "expression": "VAR SeverityValue = SELECTEDVALUE(FactRiskRegister[Severity], \"Watch\")\nVAR ProbabilityValue = MIN(0.98, MAX(0.02, MAX(FactRiskRegister[Probability])))\nVAR MarkerX = 12 + ProbabilityValue * 96\nVAR SeverityColor =\n    SWITCH(\n        SeverityValue,\n        \"Critical\", \"%23B73535\",\n        \"High\", \"%23BE7C10\",\n        \"%231F8E45\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 44'>\" &\n    \"<rect x='0' y='0' width='120' height='44' rx='7' fill='%23F8F5FC'/>\" &\n    \"<rect x='12' y='17' width='32' height='10' rx='5' fill='%23DDEEDC'/>\" &\n    \"<rect x='44' y='17' width='32' height='10' rx='5' fill='%23FFF3D6'/>\" &\n    \"<rect x='76' y='17' width='32' height='10' rx='5' fill='%23F3D7D7'/>\" &\n    \"<line x1='12' y1='32' x2='108' y2='32' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='3 4'/>\" &\n    \"<circle cx='\" & FORMAT(MarkerX, \"0.0\") & \"' cy='22' r='6' fill='\" & SeverityColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(MarkerX, \"0.0\") & \"' cy='22' r='2' fill='%23FFFFFF'/>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "aa72385d-6d0e-4bf0-b62d-fe9070a6f5a0",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Portfolio Signature SVG",
            "expression": "VAR SVG =\n    \"<svg xmlns=\"\"http://www.w3.org/2000/svg\"\" viewBox=\"\"0 0 64 64\"\" role=\"\"img\"\" aria-label=\"\"AT modern FP&amp;A monogram\"\"> <defs> <linearGradient id=\"\"bg\"\" x1=\"\"7\"\" y1=\"\"58\"\" x2=\"\"57\"\" y2=\"\"6\"\" gradientUnits=\"\"userSpaceOnUse\"\"> <stop stop-color=\"\"%230a1323\"\"/> <stop offset=\"\"0.58\"\" stop-color=\"\"%23101b2d\"\"/> <stop offset=\"\"1\"\" stop-color=\"\"%2314303a\"\"/> </linearGradient> <linearGradient id=\"\"accent\"\" x1=\"\"12\"\" y1=\"\"51\"\" x2=\"\"52\"\" y2=\"\"44\"\" gradientUnits=\"\"userSpaceOnUse\"\"> <stop stop-color=\"\"%238ab8ff\"\"/> <stop offset=\"\"1\"\" stop-color=\"\"%238de1d6\"\"/> </linearGradient> </defs> <rect width=\"\"64\"\" height=\"\"64\"\" rx=\"\"14\"\" fill=\"\"url(%23bg)\"\"/> <text x=\"\"8.5\"\" y=\"\"43\"\" fill=\"\"%23f8fbff\"\" font-family=\"\"Arial, Helvetica, sans-serif\"\" font-size=\"\"31\"\" font-weight=\"\"900\"\">AT</text> <rect x=\"\"6\"\" y=\"\"13\"\" width=\"\"56\"\" height=\"\"10\"\" rx=\"\"1.5\"\" fill=\"\"%23101b2d\"\"/> <path d=\"\"M12 50C22 46.5 35 48 52 42.5\"\" fill=\"\"none\"\" stroke=\"\"url(%23accent)\"\" stroke-width=\"\"2.8\"\" stroke-linecap=\"\"round\"\" opacity=\"\"0.88\"\"/> <circle cx=\"\"52\"\" cy=\"\"42.5\"\" r=\"\"2.85\"\" fill=\"\"%23e9bf72\"\"/> </svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "e9e5baf0-bd33-4c69-9c5a-83f580c0596a",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Revenue KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Revenue], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Revenue], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Revenue]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%234F87F5' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%234F87F5' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Revenue</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%234F87F5'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "db6f9f26-d887-4e8f-8db8-8d5737aa9f96",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Margin KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Gross Margin %], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Gross Margin %], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0%\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0%\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue * 100, \"+0.0;-0.0;0.0\") & \"pt\")\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Gross Margin %]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%230F9F95' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%230F9F95' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Margin</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%230F9F95'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "a39a8080-dfa8-4b92-b2f3-d2ba681fece7",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "EBITDA KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([EBITDA], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([EBITDA], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [EBITDA]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%231F8E45' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%231F8E45' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>EBITDA</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%231F8E45'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "68719bc3-013b-49c2-b1ac-77c0107a1886",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cash KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Cash Balance], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Cash Balance], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Cash Balance]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%23BE7C10\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%23BE7C10' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%23BE7C10' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Cash</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%23BE7C10'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "c4e01edc-8229-4ebf-b4fa-b49104b3c70c",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Runway KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Runway Months], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Runway Months], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0x\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0x\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue, \"+0.0x;-0.0x;0.0x\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Runway Months]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%234F87F5' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%234F87F5' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Runway</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%234F87F5'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "152242fe-454a-40be-8d20-0d379799c418",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "FCF KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Free Cash Flow], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Free Cash Flow], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Free Cash Flow]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%230F9F95' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%230F9F95' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>FCF</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%230F9F95'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "c5043742-f1b6-405c-a78b-2db1f4c48532",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Burn KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Net Burn], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Net Burn], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0.0M;($#,0.0M);$0.0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue <= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Net Burn]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23B73535\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%23B73535' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%23B73535' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Burn</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%23B73535'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "dd5c0d3e-f24a-4e11-a809-e97f34f53509",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Funding KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Funding Need], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Funding Need], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0M;($#,0M);$0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0M;($#,0M);$0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue <= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Funding Need]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue <= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%231F8E45' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%231F8E45' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Funding</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%231F8E45'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "f068be97-fad9-4d43-847b-70c0bdd9f6e6",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "EV KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Enterprise Value], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Enterprise Value], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Enterprise Value]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%234F87F5\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%234F87F5' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%234F87F5' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>EV</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%234F87F5'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "f12d0c5d-72cf-4e96-9176-1e870e3d14db",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Equity KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Equity Value], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Equity Value], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000000), \"$#,0.0B;($#,0.0B);$0.0B\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Equity Value]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%231F8E45\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%231F8E45' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%231F8E45' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Equity</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%231F8E45'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "8d20e483-d794-452a-a219-738396fe1904",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Leverage KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Leverage Ratio], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Leverage Ratio], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0x\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0x\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue, \"+0.0x;-0.0x;0.0x\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue <= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Leverage Ratio]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23BE7C10\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%23BE7C10' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%23BE7C10' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Leverage</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%23BE7C10'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "a251fe7f-51bd-43e0-b75d-c87428d2018c",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Headroom KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Leverage Headroom], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Leverage Headroom], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0x\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0x\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue, \"+0.0x;-0.0x;0.0x\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue >= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Leverage Headroom]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F9F95\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%230F9F95' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%230F9F95' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Headroom</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%230F9F95'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "7f367e15-c55d-4e2c-bcf7-4209fb38c02e",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Risk KPI Card SVG",
            "expression": "VAR LatestMonth = MAXX(CALCULATETABLE(VALUES(DimDate[MonthStart]), ALLSELECTED(DimDate), REMOVEFILTERS(DimDate[IsLatestCompleteMonth])), DimDate[MonthStart])\nVAR PriorMonth = EDATE(LatestMonth, -12)\nVAR CurrentValue = CALCULATE([Risk Exposure], FILTER(ALL(DimDate), DimDate[MonthStart] = LatestMonth))\nVAR PriorValue = CALCULATE([Risk Exposure], FILTER(ALL(DimDate), DimDate[MonthStart] = PriorMonth))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), \"$#,0M;($#,0M);$0M\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1000000), \"$#,0M;($#,0M);$0M\"))\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%236E667B\", IF(ChangeValue <= 0, \"%234CAF65\", \"%23C94A4A\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[MonthStart] <= LatestMonth),\n        \"__Value\", [Risk Exposure]\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[MonthStart], DESC), [__Value])\nVAR LowMonth = MINX(TOPN(1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC), DimDate[MonthStart])\nVAR LowValue = MINX(FILTER(CleanTable, DimDate[MonthStart] = LowMonth), [__Value])\nVAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR LowRank = RANKX(CleanTable, DimDate[MonthStart], LowMonth, ASC, DENSE) - 1\nVAR LowXValue = 136 + DIVIDE(LowRank, MAX(1, RowCount - 1), 0) * 92\nVAR LowYValue = 80 - DIVIDE(LowValue - MinValue, MaxValue - MinValue, 0.5) * 42\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23B73535\", \"%23C94A4A\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[MonthStart], , ASC, DENSE) - 1\n        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92\n        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 42\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    ) & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\" &\n    \"<rect x='1' y='1' width='250' height='156' rx='15' fill='%23F4EFFA' stroke='%237142A4' stroke-width='2.5'/>\" &\n    \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%23B73535' opacity='0.9'/>\" &\n    \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%23B73535' opacity='0.95'/>\" &\n    \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\" &\n    \"<text x='36' y='43' font-family='Segoe UI' font-size='15' font-weight='750' fill='%23211A32'>Risk</text>\" &\n    \"<text x='16' y='91' font-family='Segoe UI' font-size='30' font-weight='750' fill='%23B73535'>\" & ValueText & \"</text>\" &\n    \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23FFFFFF' opacity='0.46'/>\" &\n    \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\" &\n    \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23D9D1EB' opacity='0.34'/>\" &\n    \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23D9D1EB' opacity='0.28'/>\" &\n    \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23D9D1EB' opacity='0.24'/>\" &\n    \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23D9D1EB' opacity='0.20'/>\" &\n    \"<line x1='136' y1='65' x2='228' y2='65' stroke='%23B8AECF' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B8AEE6' opacity='0.55'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"<circle cx='136' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='4' fill='%23FFFFFF' stroke='%2377A4F5' stroke-width='2'/>\" &\n    \"<circle cx='\" & FORMAT(LowXValue, \"0.0\") & \"' cy='\" & FORMAT(LowYValue, \"0.0\") & \"' r='4' fill='%23D96A5D' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<circle cx='228' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\" &\n    \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23FFFFFF' opacity='0.64'/>\" &\n    \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>PY</text>\" &\n    \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%236E667B'>\" & PYText & \"</text>\" &\n    \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23211A32'>YoY</text>\" &\n    \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\" &\n    \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "lineageTag": "8085cf7e-e67e-4ebf-a578-4ddccaa0efd2",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Board Status Icon",
            "expression": "SWITCH(TRUE(), [Revenue vs Plan %] >= 0.03, UNICHAR(9650), [Revenue vs Plan %] >= -0.02, UNICHAR(8212), UNICHAR(9660))",
            "lineageTag": "a489c1d4-5d9e-4ccf-9ae1-e8fdc92f5b9a"
          },
          {
            "name": "Board Status Color",
            "expression": "SWITCH(TRUE(), [Revenue vs Plan %] >= 0.03, \"#2FA66A\", [Revenue vs Plan %] >= -0.02, \"#C58A18\", \"#C94A4A\")",
            "lineageTag": "a5a611df-f0e5-4a8c-aa19-e6bff80b9f94"
          },
          {
            "name": "Lens Summary SVG",
            "expression": "VAR YearText =\n    IF(HASONEVALUE(DimDate[Year]), FORMAT(SELECTEDVALUE(DimDate[Year]), \"0\"), \"All Years\")\nVAR ScenarioText =\n    IF(HASONEVALUE(DimScenario[ScenarioName]), SELECTEDVALUE(DimScenario[ScenarioName]), FORMAT(COUNTROWS(VALUES(DimScenario[ScenarioName])), \"0\") & \" scenarios\")\nVAR BUCount = COUNTROWS(VALUES(DimBusinessUnit[BusinessUnit]))\nVAR BUTotal = CALCULATE(COUNTROWS(VALUES(DimBusinessUnit[BusinessUnit])), ALL(DimBusinessUnit[BusinessUnit]))\nVAR BUText =\n    IF(NOT ISFILTERED(DimBusinessUnit[BusinessUnit]) || BUCount = BUTotal,\n        \"All BU\",\n        IF(BUCount = 1, SELECTEDVALUE(DimBusinessUnit[BusinessUnit]), FORMAT(BUCount, \"0\") & \" BU\"))\nVAR RegionCount = COUNTROWS(VALUES(DimRegion[Region]))\nVAR RegionTotal = CALCULATE(COUNTROWS(VALUES(DimRegion[Region])), ALL(DimRegion[Region]))\nVAR RegionText =\n    IF(NOT ISFILTERED(DimRegion[Region]) || RegionCount = RegionTotal,\n        \"All Regions\",\n        IF(RegionCount = 1, SELECTEDVALUE(DimRegion[Region]), FORMAT(RegionCount, \"0\") & \" Regions\"))\nVAR Line1 = LEFT(YearText & \" | \" & ScenarioText, 28)\nVAR Line2 = LEFT(BUText & \" | \" & RegionText, 32)\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='166' height='76' viewBox='0 0 166 76'>\" &\n    \"<rect x='1' y='1' width='164' height='74' rx='8' fill='%233F1A63' stroke='%238E73E7' stroke-width='1.2'/>\" &\n    \"<text x='12' y='20' font-family='Segoe UI' font-size='10.2' font-weight='700' fill='%23CFC3E6'>Current Lens</text>\" &\n    \"<circle cx='148' cy='17' r='3.6' fill='%236EE4CF'/>\" &\n    \"<text x='12' y='42' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='%23FFFFFF'>\" & Line1 & \"</text>\" &\n    \"<text x='12' y='61' font-family='Segoe UI' font-size='9.7' fill='%23CFC3E6'>\" & Line2 & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "c619f885-ffdf-4d23-a340-43f75c8bae44",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Performance Decision Chips SVG",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\")\nVAR Chip1Text = \"Scenario: \" & SWITCH(ScenarioID, \"Upside\", \"Upside\", \"Downside\", \"Downside\", \"Base\")\nVAR Chip2Text = SWITCH(ScenarioID, \"Upside\", \"GM: +1.4 pts\", \"Downside\", \"GM: -0.7 pts\", \"GM: +0.8 pts\")\nVAR Chip3Text = SWITCH(ScenarioID, \"Upside\", \"Runway: >99 mo\", \"Downside\", \"Runway: 18.5 mo\", \"Runway: >99 mo\")\nVAR Chip1Accent = SWITCH(ScenarioID, \"Upside\", \"%230F9F95\", \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip1Fill = SWITCH(ScenarioID, \"Upside\", \"%23EAF7FF\", \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR Chip2Accent = SWITCH(ScenarioID, \"Downside\", \"%23B73535\", \"%230F9F95\")\nVAR Chip2Fill = SWITCH(ScenarioID, \"Downside\", \"%23FCE7E7\", \"%23E7F0FF\")\nVAR Chip3Accent = SWITCH(ScenarioID, \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip3Fill = SWITCH(ScenarioID, \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\" &\n    \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\" &\n    \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='\" & Chip1Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='13' y='13' width='11' height='11' rx='3' fill='\" & Chip1Accent & \"'/>\" &\n    \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\" &\n    \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='\" & Chip2Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='169' y='13' width='11' height='11' rx='3' fill='\" & Chip2Accent & \"'/>\" &\n    \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\" &\n    \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='\" & Chip3Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='333' y='13' width='11' height='11' rx='3' fill='\" & Chip3Accent & \"'/>\" &\n    \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "2f05b1ee-9764-42ca-82c1-e7c3f392fec2",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cash Decision Chips SVG",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\")\nVAR Chip1Text = \"Scenario: \" & SWITCH(ScenarioID, \"Upside\", \"Upside\", \"Downside\", \"Downside\", \"Base\")\nVAR Chip2Text = SWITCH(ScenarioID, \"Upside\", \"Funding: $0M\", \"Downside\", \"Funding: $14M\", \"Funding: $0M\")\nVAR Chip3Text = SWITCH(ScenarioID, \"Upside\", \"FCF: $38.0M\", \"Downside\", \"FCF: ($8.5M)\", \"FCF: $22.5M\")\nVAR Chip1Accent = SWITCH(ScenarioID, \"Upside\", \"%230F9F95\", \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip1Fill = SWITCH(ScenarioID, \"Upside\", \"%23EAF7FF\", \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR Chip2Accent = SWITCH(ScenarioID, \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip2Fill = SWITCH(ScenarioID, \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR Chip3Accent = SWITCH(ScenarioID, \"Downside\", \"%23B73535\", \"%230F9F95\")\nVAR Chip3Fill = SWITCH(ScenarioID, \"Downside\", \"%23FCE7E7\", \"%23E7F0FF\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\" &\n    \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\" &\n    \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='\" & Chip1Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='13' y='13' width='11' height='11' rx='3' fill='\" & Chip1Accent & \"'/>\" &\n    \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\" &\n    \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='\" & Chip2Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='169' y='13' width='11' height='11' rx='3' fill='\" & Chip2Accent & \"'/>\" &\n    \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\" &\n    \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='\" & Chip3Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='333' y='13' width='11' height='11' rx='3' fill='\" & Chip3Accent & \"'/>\" &\n    \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "7defb902-1c3b-44f2-97f8-b30b17d58205",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Risk Decision Chips SVG",
            "expression": "VAR ScenarioID = SELECTEDVALUE(DimScenario[ScenarioID], \"Base\")\nVAR Chip1Text = \"Scenario: \" & SWITCH(ScenarioID, \"Upside\", \"Upside\", \"Downside\", \"Downside\", \"Base\")\nVAR Chip2Text = SWITCH(ScenarioID, \"Upside\", \"Headroom: 2.1x\", \"Downside\", \"Headroom: 0.4x\", \"Headroom: 1.3x\")\nVAR Chip3Text = SWITCH(ScenarioID, \"Upside\", \"Risk: $7M\", \"Downside\", \"Risk: $26M\", \"Risk: $14M\")\nVAR Chip1Accent = SWITCH(ScenarioID, \"Upside\", \"%230F9F95\", \"Downside\", \"%23BE7C10\", \"%232FA66A\")\nVAR Chip1Fill = SWITCH(ScenarioID, \"Upside\", \"%23EAF7FF\", \"Downside\", \"%23FFF3D6\", \"%23E6F4EC\")\nVAR Chip2Accent = SWITCH(ScenarioID, \"Downside\", \"%23BE7C10\", \"%230F9F95\")\nVAR Chip2Fill = SWITCH(ScenarioID, \"Downside\", \"%23FFF3D6\", \"%23E7F0FF\")\nVAR Chip3Accent = SWITCH(ScenarioID, \"Downside\", \"%23B73535\", \"Upside\", \"%232FA66A\", \"%23BE7C10\")\nVAR Chip3Fill = SWITCH(ScenarioID, \"Downside\", \"%23FCE7E7\", \"Upside\", \"%23E6F4EC\", \"%23FFF3D6\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\" &\n    \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\" &\n    \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='\" & Chip1Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='13' y='13' width='11' height='11' rx='3' fill='\" & Chip1Accent & \"'/>\" &\n    \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\" &\n    \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='\" & Chip2Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='169' y='13' width='11' height='11' rx='3' fill='\" & Chip2Accent & \"'/>\" &\n    \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\" &\n    \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='\" & Chip3Fill & \"' stroke='%23FFFFFF' stroke-width='0.9'/>\" &\n    \"<rect x='333' y='13' width='11' height='11' rx='3' fill='\" & Chip3Accent & \"'/>\" &\n    \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "ffa03489-c4e7-45bf-bbae-556cccd64910",
            "dataCategory": "ImageUrl"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Rel_FactPnlMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactPnlMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactPnlMonthly_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactPnlMonthly",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactPnlMonthly_BusinessUnitID_DimBusinessUnit_BusinessUnitID",
        "fromTable": "FactPnlMonthly",
        "fromColumn": "BusinessUnitID",
        "toTable": "DimBusinessUnit",
        "toColumn": "BusinessUnitID"
      },
      {
        "name": "Rel_FactPnlMonthly_RegionID_DimRegion_RegionID",
        "fromTable": "FactPnlMonthly",
        "fromColumn": "RegionID",
        "toTable": "DimRegion",
        "toColumn": "RegionID"
      },
      {
        "name": "Rel_FactOpexMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactOpexMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactOpexMonthly_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactOpexMonthly",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactOpexMonthly_CostCategoryID_DimCostCategory_CostCategoryID",
        "fromTable": "FactOpexMonthly",
        "fromColumn": "CostCategoryID",
        "toTable": "DimCostCategory",
        "toColumn": "CostCategoryID"
      },
      {
        "name": "Rel_FactCashMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactCashMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactCashMonthly_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactCashMonthly",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactStatementLines_MonthStart_DimDate_MonthStart",
        "fromTable": "FactStatementLines",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactStatementLines_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactStatementLines",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactCovenantMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactCovenantMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactCovenantMonthly_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactCovenantMonthly",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactValuation_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactValuation",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactSensitivity_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactSensitivity",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      },
      {
        "name": "Rel_FactRiskRegister_ScenarioID_DimScenario_ScenarioID",
        "fromTable": "FactRiskRegister",
        "fromColumn": "ScenarioID",
        "toTable": "DimScenario",
        "toColumn": "ScenarioID"
      }
    ]
  }
}