Total Transactions = COUNTROWS ( FactTransactions )
Transaction Amount = SUM ( FactTransactions[AmountUSD] )
Flagged Transactions = CALCULATE ( [Total Transactions], FactTransactions[IsFlagged] = "Y" )
Flagged Amount = CALCULATE ( [Transaction Amount], FactTransactions[IsFlagged] = "Y" )
Alert Count = COUNTROWS ( FactAlerts )
Case Count = COUNTROWS ( FactCases )
Suspicious Cases = CALCULATE ( [Case Count], FactCases[Outcome] IN { "Confirmed Suspicious", "SAR Filed" } )
SAR Filed Cases = CALCULATE ( [Case Count], FactCases[SARFiled] = "Y" )
Closed Alerts = CALCULATE ( [Alert Count], FactAlerts[AlertStatus] IN { "Closed False Positive", "Closed True Positive", "SAR Filed" } )
False Positive Alerts = CALCULATE ( [Closed Alerts], FactAlerts[IsFalsePositive] = "Y" )
False Positive Rate = DIVIDE ( [False Positive Alerts], [Closed Alerts] )
True Positive Alerts = CALCULATE ( [Alert Count], FactAlerts[IsTruePositive] = "Y" )
Rule Precision = DIVIDE ( [True Positive Alerts], [Closed Alerts] )
Alert Rate = DIVIDE ( [Alert Count], [Total Transactions] )
Alert to Case Conversion = DIVIDE ( [Case Count], [Alert Count] )
SAR Conversion Rate = DIVIDE ( [SAR Filed Cases], [Case Count] )
Open Cases = CALCULATE ( [Case Count], NOT ( FactCases[CaseStatus] IN { "Closed", "SAR Filed" } ) )
Overdue Cases = CALCULATE ( [Case Count], FactCases[IsOverdue] = "Y" )
SLA Compliance Rate = DIVIDE ( [Case Count] - [Overdue Cases], [Case Count] )
Average Case Age Days = AVERAGE ( FactCases[AgeDays] )
Average Alert Risk Score = AVERAGE ( FactAlerts[RiskScore] )
High Risk Customers = CALCULATE ( DISTINCTCOUNT ( DimCustomer[CustomerKey] ), DimCustomer[CustomerRiskTier] = "High" )
Governance Changes = COUNTROWS ( FactRuleGovernance )
Avg Precision After Tuning = AVERAGE ( FactRuleGovernance[PrecisionAfter] )
Alert Amount = SUM ( FactAlerts[AlertAmountUSD] )
Case Amount = SUM ( FactCases[CaseAmountUSD] )
