{
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "summarizeBy": "none"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none"
          },
          {
            "name": "month_number",
            "dataType": "int64",
            "sourceColumn": "month_number",
            "summarizeBy": "none"
          },
          {
            "name": "month_label",
            "dataType": "string",
            "sourceColumn": "month_label",
            "summarizeBy": "none"
          },
          {
            "name": "is_latest_complete",
            "dataType": "boolean",
            "sourceColumn": "is_latest_complete",
            "summarizeBy": "none"
          },
          {
            "name": "month_index",
            "dataType": "int64",
            "sourceColumn": "month_index",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimDate-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/dim_date.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"date\", type date},\n        {\"year\", Int64.Type},\n        {\"quarter\", type text},\n        {\"month_number\", Int64.Type},\n        {\"month_label\", type text},\n        {\"is_latest_complete\", type logical},\n        {\"month_index\", Int64.Type}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimEntity",
        "columns": [
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity",
            "dataType": "string",
            "sourceColumn": "entity",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "ownership",
            "dataType": "double",
            "sourceColumn": "ownership",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimEntity-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/dim_entity.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"entity_id\", type text},\n        {\"entity\", type text},\n        {\"country\", type text},\n        {\"region\", type text},\n        {\"currency\", type text},\n        {\"ownership\", type number}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimBusinessUnit",
        "columns": [
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimBusinessUnit-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/dim_business_unit.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"business_unit_id\", type text},\n        {\"business_unit\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimAccount",
        "columns": [
          {
            "name": "account_id",
            "dataType": "string",
            "sourceColumn": "account_id",
            "summarizeBy": "none"
          },
          {
            "name": "account",
            "dataType": "string",
            "sourceColumn": "account",
            "summarizeBy": "none"
          },
          {
            "name": "account_group",
            "dataType": "string",
            "sourceColumn": "account_group",
            "summarizeBy": "none"
          },
          {
            "name": "sort_order",
            "dataType": "int64",
            "sourceColumn": "sort_order",
            "summarizeBy": "none"
          },
          {
            "name": "statement",
            "dataType": "string",
            "sourceColumn": "statement",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimAccount-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/dim_account.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"account_id\", type text},\n        {\"account\", type text},\n        {\"account_group\", type text},\n        {\"sort_order\", Int64.Type},\n        {\"statement\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimScenario",
        "columns": [
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none"
          },
          {
            "name": "scenario",
            "dataType": "string",
            "sourceColumn": "scenario",
            "summarizeBy": "none"
          },
          {
            "name": "scenario_type",
            "dataType": "string",
            "sourceColumn": "scenario_type",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimScenario-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/dim_scenario.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"scenario_id\", type text},\n        {\"scenario\", type text},\n        {\"scenario_type\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactFinancials",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none"
          },
          {
            "name": "account_id",
            "dataType": "string",
            "sourceColumn": "account_id",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "amount_local",
            "dataType": "double",
            "sourceColumn": "amount_local",
            "summarizeBy": "none"
          },
          {
            "name": "amount_usd",
            "dataType": "double",
            "sourceColumn": "amount_usd",
            "summarizeBy": "none"
          },
          {
            "name": "fx_rate_to_usd",
            "dataType": "double",
            "sourceColumn": "fx_rate_to_usd",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_teu_or_orders",
            "dataType": "double",
            "sourceColumn": "quantity_teu_or_orders",
            "summarizeBy": "none"
          },
          {
            "name": "is_synthetic",
            "dataType": "boolean",
            "sourceColumn": "is_synthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactFinancials-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/fact_financials.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"entity_id\", type text},\n        {\"business_unit_id\", type text},\n        {\"scenario_id\", type text},\n        {\"account_id\", type text},\n        {\"currency\", type text},\n        {\"amount_local\", type number},\n        {\"amount_usd\", type number},\n        {\"fx_rate_to_usd\", type number},\n        {\"quantity_teu_or_orders\", type number},\n        {\"is_synthetic\", type logical}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactFinancialSummary",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none"
          },
          {
            "name": "scenario",
            "dataType": "string",
            "sourceColumn": "scenario",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "gross_revenue_usd",
            "dataType": "double",
            "sourceColumn": "gross_revenue_usd",
            "summarizeBy": "none"
          },
          {
            "name": "external_revenue_usd",
            "dataType": "double",
            "sourceColumn": "external_revenue_usd",
            "summarizeBy": "none"
          },
          {
            "name": "intercompany_revenue_usd",
            "dataType": "double",
            "sourceColumn": "intercompany_revenue_usd",
            "summarizeBy": "none"
          },
          {
            "name": "intercompany_cost_usd",
            "dataType": "double",
            "sourceColumn": "intercompany_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "intercompany_elimination_usd",
            "dataType": "double",
            "sourceColumn": "intercompany_elimination_usd",
            "summarizeBy": "none"
          },
          {
            "name": "cogs_usd",
            "dataType": "double",
            "sourceColumn": "cogs_usd",
            "summarizeBy": "none"
          },
          {
            "name": "gross_profit_usd",
            "dataType": "double",
            "sourceColumn": "gross_profit_usd",
            "summarizeBy": "none"
          },
          {
            "name": "opex_usd",
            "dataType": "double",
            "sourceColumn": "opex_usd",
            "summarizeBy": "none"
          },
          {
            "name": "ebitda_pre_elim_usd",
            "dataType": "double",
            "sourceColumn": "ebitda_pre_elim_usd",
            "summarizeBy": "none"
          },
          {
            "name": "ebitda_usd",
            "dataType": "double",
            "sourceColumn": "ebitda_usd",
            "summarizeBy": "none"
          },
          {
            "name": "ebitda_margin",
            "dataType": "double",
            "sourceColumn": "ebitda_margin",
            "summarizeBy": "none"
          },
          {
            "name": "operating_income_usd",
            "dataType": "double",
            "sourceColumn": "operating_income_usd",
            "summarizeBy": "none"
          },
          {
            "name": "net_income_usd",
            "dataType": "double",
            "sourceColumn": "net_income_usd",
            "summarizeBy": "none"
          },
          {
            "name": "cash_position_usd",
            "dataType": "double",
            "sourceColumn": "cash_position_usd",
            "summarizeBy": "none"
          },
          {
            "name": "operating_cash_flow_usd",
            "dataType": "double",
            "sourceColumn": "operating_cash_flow_usd",
            "summarizeBy": "none"
          },
          {
            "name": "working_capital_usd",
            "dataType": "double",
            "sourceColumn": "working_capital_usd",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactFinancialSummary-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/fact_financial_summary.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"entity_id\", type text},\n        {\"business_unit_id\", type text},\n        {\"scenario_id\", type text},\n        {\"scenario\", type text},\n        {\"country\", type text},\n        {\"region\", type text},\n        {\"business_unit\", type text},\n        {\"currency\", type text},\n        {\"gross_revenue_usd\", type number},\n        {\"external_revenue_usd\", type number},\n        {\"intercompany_revenue_usd\", type number},\n        {\"intercompany_cost_usd\", type number},\n        {\"intercompany_elimination_usd\", type number},\n        {\"cogs_usd\", type number},\n        {\"gross_profit_usd\", type number},\n        {\"opex_usd\", type number},\n        {\"ebitda_pre_elim_usd\", type number},\n        {\"ebitda_usd\", type number},\n        {\"ebitda_margin\", type number},\n        {\"operating_income_usd\", type number},\n        {\"net_income_usd\", type number},\n        {\"cash_position_usd\", type number},\n        {\"operating_cash_flow_usd\", type number},\n        {\"working_capital_usd\", type number}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactVarianceDriverBridge",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "driver",
            "dataType": "string",
            "sourceColumn": "driver",
            "summarizeBy": "none"
          },
          {
            "name": "driver_sort",
            "dataType": "int64",
            "sourceColumn": "driver_sort",
            "summarizeBy": "none"
          },
          {
            "name": "amount_usd",
            "dataType": "double",
            "sourceColumn": "amount_usd",
            "summarizeBy": "none"
          },
          {
            "name": "variance_sign",
            "dataType": "string",
            "sourceColumn": "variance_sign",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactVarianceDriverBridge-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/fact_variance_driver_bridge.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"entity_id\", type text},\n        {\"business_unit_id\", type text},\n        {\"country\", type text},\n        {\"region\", type text},\n        {\"business_unit\", type text},\n        {\"driver\", type text},\n        {\"driver_sort\", Int64.Type},\n        {\"amount_usd\", type number},\n        {\"variance_sign\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCloseExceptions",
        "columns": [
          {
            "name": "exception_id",
            "dataType": "string",
            "sourceColumn": "exception_id",
            "summarizeBy": "none"
          },
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "exception_type",
            "dataType": "string",
            "sourceColumn": "exception_type",
            "summarizeBy": "none"
          },
          {
            "name": "owner_team",
            "dataType": "string",
            "sourceColumn": "owner_team",
            "summarizeBy": "none"
          },
          {
            "name": "severity",
            "dataType": "string",
            "sourceColumn": "severity",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "amount_usd",
            "dataType": "double",
            "sourceColumn": "amount_usd",
            "summarizeBy": "none"
          },
          {
            "name": "due_date",
            "dataType": "dateTime",
            "sourceColumn": "due_date",
            "summarizeBy": "none"
          },
          {
            "name": "commentary",
            "dataType": "string",
            "sourceColumn": "commentary",
            "summarizeBy": "none"
          },
          {
            "name": "is_synthetic",
            "dataType": "boolean",
            "sourceColumn": "is_synthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactCloseExceptions-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/fact_close_exceptions.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"exception_id\", type text},\n        {\"date_id\", type text},\n        {\"entity_id\", type text},\n        {\"business_unit_id\", type text},\n        {\"country\", type text},\n        {\"region\", type text},\n        {\"business_unit\", type text},\n        {\"exception_type\", type text},\n        {\"owner_team\", type text},\n        {\"severity\", type text},\n        {\"status\", type text},\n        {\"amount_usd\", type number},\n        {\"due_date\", type date},\n        {\"commentary\", type text},\n        {\"is_synthetic\", type logical}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactFXRate",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "to_currency",
            "dataType": "string",
            "sourceColumn": "to_currency",
            "summarizeBy": "none"
          },
          {
            "name": "rate_type",
            "dataType": "string",
            "sourceColumn": "rate_type",
            "summarizeBy": "none"
          },
          {
            "name": "rate_to_usd",
            "dataType": "double",
            "sourceColumn": "rate_to_usd",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactFXRate-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"<PROJECT_ROOT>/data/prepared/fact_fx_rate.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"currency\", type text},\n        {\"to_currency\", type text},\n        {\"rate_type\", type text},\n        {\"rate_to_usd\", type number}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "KPI Measures",
        "columns": [
          {
            "name": "Measure Group",
            "dataType": "string",
            "sourceColumn": "Measure Group",
            "isHidden": true,
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "KPI Measures-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #table(type table [Measure Group = text], {{\"Regional FP&A Consolidation\"}})",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Revenue",
            "expression": "SUM ( FactFinancialSummary[external_revenue_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Consolidated external revenue after excluding intercompany revenue."
          },
          {
            "name": "Gross Revenue",
            "expression": "SUM ( FactFinancialSummary[gross_revenue_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "External plus intercompany revenue before elimination."
          },
          {
            "name": "Intercompany Revenue",
            "expression": "SUM ( FactFinancialSummary[intercompany_revenue_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Intercompany revenue requiring elimination."
          },
          {
            "name": "Intercompany Elimination",
            "expression": "SUM ( FactFinancialSummary[intercompany_elimination_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Net intercompany elimination impact."
          },
          {
            "name": "Gross Profit",
            "expression": "SUM ( FactFinancialSummary[gross_profit_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Revenue minus cost of services."
          },
          {
            "name": "Gross Margin %",
            "expression": "DIVIDE ( [Gross Profit], [Total Revenue] )",
            "formatString": "0.0%",
            "description": "Gross profit divided by consolidated external revenue."
          },
          {
            "name": "OPEX",
            "expression": "SUM ( FactFinancialSummary[opex_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Personnel, facilities, sales and marketing, and G&A."
          },
          {
            "name": "EBITDA",
            "expression": "SUM ( FactFinancialSummary[ebitda_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Gross profit plus OPEX after intercompany elimination."
          },
          {
            "name": "EBITDA Margin %",
            "expression": "DIVIDE ( [EBITDA], [Total Revenue] )",
            "formatString": "0.0%",
            "description": "EBITDA divided by consolidated external revenue."
          },
          {
            "name": "Operating Income",
            "expression": "SUM ( FactFinancialSummary[operating_income_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "EBITDA less depreciation."
          },
          {
            "name": "Net Income",
            "expression": "SUM ( FactFinancialSummary[net_income_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Operating income less interest and tax."
          },
          {
            "name": "Cash Position",
            "expression": "SUM ( FactFinancialSummary[cash_position_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Period-end cash position by entity and BU allocation."
          },
          {
            "name": "Operating Cash Flow",
            "expression": "SUM ( FactFinancialSummary[operating_cash_flow_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Operating cash flow proxy tied to EBITDA conversion."
          },
          {
            "name": "Working Capital",
            "expression": "SUM ( FactFinancialSummary[working_capital_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Working capital proxy for close review."
          },
          {
            "name": "Actual Revenue",
            "expression": "CALCULATE ( [Total Revenue], DimScenario[scenario] = \"Actual\" )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Actual consolidated revenue."
          },
          {
            "name": "Budget Revenue",
            "expression": "CALCULATE ( [Total Revenue], DimScenario[scenario] = \"Budget\" )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Budget consolidated revenue."
          },
          {
            "name": "Revenue Var vs Budget",
            "expression": "[Actual Revenue] - [Budget Revenue]",
            "formatString": "$#,0;($#,0);$0",
            "description": "Actual revenue less budget revenue."
          },
          {
            "name": "Revenue Var %",
            "expression": "DIVIDE ( [Revenue Var vs Budget], [Budget Revenue] )",
            "formatString": "0.0%",
            "description": "Revenue variance divided by budget revenue."
          },
          {
            "name": "Actual EBITDA",
            "expression": "CALCULATE ( [EBITDA], DimScenario[scenario] = \"Actual\" )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Actual EBITDA."
          },
          {
            "name": "Budget EBITDA",
            "expression": "CALCULATE ( [EBITDA], DimScenario[scenario] = \"Budget\" )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Budget EBITDA."
          },
          {
            "name": "EBITDA Var vs Budget",
            "expression": "[Actual EBITDA] - [Budget EBITDA]",
            "formatString": "$#,0;($#,0);$0",
            "description": "Actual EBITDA less budget EBITDA."
          },
          {
            "name": "EBITDA Var %",
            "expression": "DIVIDE ( [EBITDA Var vs Budget], [Budget EBITDA] )",
            "formatString": "0.0%",
            "description": "EBITDA variance divided by budget EBITDA."
          },
          {
            "name": "Forecast EBITDA",
            "expression": "CALCULATE ( [EBITDA], DimScenario[scenario] = \"Forecast\" )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Forecast EBITDA."
          },
          {
            "name": "Forecast Accuracy %",
            "expression": "1 - ABS ( DIVIDE ( [Actual EBITDA] - [Forecast EBITDA], [Actual EBITDA] ) )",
            "formatString": "0.0%",
            "description": "Directional forecast accuracy for EBITDA."
          },
          {
            "name": "Open Exception Count",
            "expression": "CALCULATE ( COUNTROWS ( FactCloseExceptions ), FactCloseExceptions[status] <> \"Closed\" )",
            "formatString": "#,0",
            "description": "Open or in-progress close exceptions."
          },
          {
            "name": "Open Exception Value",
            "expression": "CALCULATE ( SUM ( FactCloseExceptions[amount_usd] ), FactCloseExceptions[status] <> \"Closed\" )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Value attached to unresolved close exceptions."
          },
          {
            "name": "Selected Latest Complete Date",
            "expression": "VAR GlobalLatestComplete =\n    CALCULATE (\n        MAX ( DimDate[date] ),\n        REMOVEFILTERS ( DimDate ),\n        DimDate[is_latest_complete] = TRUE ()\n    )\nVAR SelectedLatest =\n    MAXX (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[date] <= GlobalLatestComplete ),\n        DimDate[date]\n    )\nRETURN\n    COALESCE ( SelectedLatest, GlobalLatestComplete )",
            "formatString": "mmm yyyy",
            "description": "Latest complete date within the selected date context, capped to the global closed period."
          },
          {
            "name": "Selected Latest Complete Period Label",
            "expression": "FORMAT ( [Selected Latest Complete Date], \"MMM yyyy\" )",
            "formatString": "",
            "description": "Display label for the selected latest complete month."
          },
          {
            "name": "Bridge Amount",
            "expression": "SUM ( FactVarianceDriverBridge[amount_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Variance-driver bridge amount with explicit aggregation for native Power BI visuals."
          },
          {
            "name": "Latest Bridge Amount",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Bridge Amount], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Variance-driver bridge amount at selected latest complete period."
          },
          {
            "name": "Exception Amount",
            "expression": "SUM ( FactCloseExceptions[amount_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Close-exception exposure with explicit aggregation for native Power BI visuals."
          },
          {
            "name": "Latest Exception Amount",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Exception Amount], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Close-exception exposure at selected latest complete period."
          },
          {
            "name": "Financial Amount",
            "expression": "SUM ( FactFinancials[amount_usd] )",
            "formatString": "$#,0;($#,0);$0",
            "description": "P&L statement amount with explicit aggregation for native Power BI visuals."
          },
          {
            "name": "Latest Actual Revenue",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Actual Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Actual revenue at selected latest complete period."
          },
          {
            "name": "Latest Budget Revenue",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Budget Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Budget revenue at selected latest complete period."
          },
          {
            "name": "Latest Revenue Var vs Budget",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Revenue Var vs Budget], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Revenue variance at selected latest complete period."
          },
          {
            "name": "Latest Revenue Var %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Revenue Var %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "Revenue variance percent at selected latest complete period."
          },
          {
            "name": "Latest Actual EBITDA",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Actual EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Actual EBITDA at selected latest complete period."
          },
          {
            "name": "Latest Budget EBITDA",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Budget EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Budget EBITDA at selected latest complete period."
          },
          {
            "name": "Latest EBITDA Var vs Budget",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [EBITDA Var vs Budget], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "EBITDA variance at selected latest complete period."
          },
          {
            "name": "Latest EBITDA Var %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [EBITDA Var %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "EBITDA variance percent at selected latest complete period."
          },
          {
            "name": "Latest Gross Revenue",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Gross Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Gross revenue at selected latest complete period."
          },
          {
            "name": "Latest Gross Profit",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Gross Profit], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Gross profit at selected latest complete period."
          },
          {
            "name": "Latest Gross Margin %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Gross Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "Gross margin at selected latest complete period."
          },
          {
            "name": "Latest OPEX",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [OPEX], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "OPEX at selected latest complete period."
          },
          {
            "name": "Latest Net Income",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Net Income], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Net income at selected latest complete period."
          },
          {
            "name": "Latest EBITDA Margin %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [EBITDA Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "EBITDA margin at selected latest complete period."
          },
          {
            "name": "Latest Cash Position",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Cash Position], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Cash position at selected latest complete period."
          },
          {
            "name": "Latest Operating Cash Flow",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Operating Cash Flow], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Operating cash flow at selected latest complete period."
          },
          {
            "name": "Latest Forecast Accuracy %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Forecast Accuracy %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "Forecast accuracy at selected latest complete period."
          },
          {
            "name": "Latest Intercompany Revenue",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Intercompany Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Intercompany revenue at selected latest complete period."
          },
          {
            "name": "Latest Intercompany Elimination",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Intercompany Elimination], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Intercompany elimination impact at selected latest complete period."
          },
          {
            "name": "Latest Open Exception Count",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Open Exception Count], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "#,0",
            "description": "Open close-exception count at selected latest complete period."
          },
          {
            "name": "Latest Open Exception Value",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Open Exception Value], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Open close-exception exposure at selected latest complete period."
          },
          {
            "name": "Display Actual Revenue",
            "expression": "FORMAT ( DIVIDE ( [Latest Actual Revenue], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest revenue KPI card."
          },
          {
            "name": "Display Actual EBITDA",
            "expression": "FORMAT ( DIVIDE ( [Latest Actual EBITDA], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest EBITDA KPI card."
          },
          {
            "name": "Display EBITDA Margin %",
            "expression": "FORMAT ( [Latest EBITDA Margin %], \"0.0%\" )",
            "formatString": "",
            "description": "Text display for latest EBITDA margin KPI card."
          },
          {
            "name": "Display Gross Revenue",
            "expression": "FORMAT ( DIVIDE ( [Latest Gross Revenue], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest gross revenue KPI card."
          },
          {
            "name": "Display Gross Profit",
            "expression": "FORMAT ( DIVIDE ( [Latest Gross Profit], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest gross profit KPI card."
          },
          {
            "name": "Display OPEX",
            "expression": "FORMAT ( DIVIDE ( [Latest OPEX], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest OPEX KPI card."
          },
          {
            "name": "Display Net Income",
            "expression": "FORMAT ( DIVIDE ( [Latest Net Income], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest net income KPI card."
          },
          {
            "name": "Display Intercompany Revenue",
            "expression": "FORMAT ( DIVIDE ( [Latest Intercompany Revenue], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest intercompany revenue KPI card."
          },
          {
            "name": "Display Intercompany Elimination",
            "expression": "FORMAT ( DIVIDE ( [Latest Intercompany Elimination], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest intercompany elimination KPI card."
          },
          {
            "name": "Display Forecast Accuracy %",
            "expression": "FORMAT ( [Latest Forecast Accuracy %], \"0.0%\" )",
            "formatString": "",
            "description": "Text display for latest forecast accuracy KPI card."
          },
          {
            "name": "Display Open Exception Value",
            "expression": "FORMAT ( DIVIDE ( [Latest Open Exception Value], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for latest close-risk KPI card."
          },
          {
            "name": "Display Open Exception Count",
            "expression": "FORMAT ( [Latest Open Exception Count], \"#,0\" )",
            "formatString": "",
            "description": "Text display for latest close-exception count chip."
          },
          {
            "name": "Display Revenue PY",
            "expression": "FORMAT ( DIVIDE ( [Revenue PY], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for prior-year revenue."
          },
          {
            "name": "Display EBITDA PY",
            "expression": "FORMAT ( DIVIDE ( [EBITDA PY], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for prior-year EBITDA."
          },
          {
            "name": "Display Open Exception Value PY",
            "expression": "FORMAT ( DIVIDE ( [Open Exception Value PY], 1000000 ), \"$0.0M;($0.0M);$0.0M\" )",
            "formatString": "",
            "description": "Text display for prior-year open exception value."
          },
          {
            "name": "Display Revenue Var %",
            "expression": "FORMAT ( [Latest Revenue Var %], \"+0.0%;-0.0%;0.0%\" )",
            "formatString": "",
            "description": "Text display for latest revenue variance percent."
          },
          {
            "name": "Display EBITDA Var %",
            "expression": "FORMAT ( [Latest EBITDA Var %], \"+0.0%;-0.0%;0.0%\" )",
            "formatString": "",
            "description": "Text display for latest EBITDA variance percent."
          },
          {
            "name": "Display Forecast Accuracy Delta",
            "expression": "FORMAT ( [Latest Forecast Accuracy %], \"0.0%\" )",
            "formatString": "",
            "description": "Text display for latest forecast accuracy footer."
          },
          {
            "name": "Current Lens Line 1",
            "expression": "VAR ScenarioRaw =\n    IF ( ISFILTERED ( DimScenario[scenario] ), CONCATENATEX ( VALUES ( DimScenario[scenario] ), DimScenario[scenario], \", \" ), \"Actual lens\" )\nRETURN\n    [Selected Latest Complete Period Label] & \" | \" & LEFT ( ScenarioRaw, 24 )",
            "formatString": "",
            "description": "First dynamic line for the Current Lens native panel."
          },
          {
            "name": "Current Lens Line 2",
            "expression": "VAR RegionRaw =\n    IF ( ISFILTERED ( DimEntity[region] ), CONCATENATEX ( VALUES ( DimEntity[region] ), DimEntity[region], \", \" ), \"All regions\" )\nVAR BURaw =\n    IF ( ISFILTERED ( DimBusinessUnit[business_unit] ), CONCATENATEX ( VALUES ( DimBusinessUnit[business_unit] ), DimBusinessUnit[business_unit], \", \" ), \"All BUs\" )\nRETURN\n    LEFT ( BURaw, 28 ) & \" | \" & LEFT ( RegionRaw, 28 )",
            "formatString": "",
            "description": "Second dynamic line for the Current Lens native panel."
          },
          {
            "name": "Revenue PY",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Actual Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Actual revenue for the same month in the prior year."
          },
          {
            "name": "EBITDA PY",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Actual EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Actual EBITDA for the same month in the prior year."
          },
          {
            "name": "Gross Margin PY %",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Gross Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "Gross margin for the same month in the prior year."
          },
          {
            "name": "Cash Position PY",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Cash Position], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Cash position for the same month in the prior year."
          },
          {
            "name": "Open Exception Value PY",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Open Exception Value], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0;($#,0);$0",
            "description": "Open exception value for the same month in the prior year."
          },
          {
            "name": "Revenue KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Actual Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Actual Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = CALCULATE ( [Budget Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Actual Revenue] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%232F5F9E'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%232F5F9E' fill-opacity='0.22' stroke='%232F5F9E' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='14.2' fill='%23F7FAFC' letter-spacing='0'>Revenue</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%232F5F9E' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%232F5F9E' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for revenue with latest value, PY delta, status chip, and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "EBITDA KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Actual EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Actual EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = CALCULATE ( [Budget EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Actual EBITDA] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%232B6F75'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%232B6F75' fill-opacity='0.22' stroke='%232B6F75' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='14.2' fill='%23F7FAFC' letter-spacing='0'>EBITDA</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%232B6F75' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%232B6F75' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for EBITDA with latest value, PY delta, status chip, and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Margin KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [EBITDA Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [EBITDA Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [EBITDA Margin %] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( CurrentValue, \"0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( PriorValue, \"0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DeltaPoints, \"+0.0pt;-0.0pt;0.0pt\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%236F8552'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%236F8552' fill-opacity='0.22' stroke='%236F8552' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='13.0' fill='%23F7FAFC' letter-spacing='0'>EBITDA Margin</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%236F8552' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%236F8552' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for EBITDA margin with prior-year point delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cash KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Cash Position], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Cash Position], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Cash Position] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%23A8894B'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%23A8894B' fill-opacity='0.22' stroke='%23A8894B' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='13.0' fill='%23F7FAFC' letter-spacing='0'>Cash Position</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%23A8894B' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%23A8894B' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for cash position with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Gross Revenue KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Gross Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Gross Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Gross Revenue] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%232F5F9E'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%232F5F9E' fill-opacity='0.22' stroke='%232F5F9E' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='13.0' fill='%23F7FAFC' letter-spacing='0'>Gross Revenue</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%232F5F9E' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%232F5F9E' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for gross revenue with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Gross Profit KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Gross Profit], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Gross Profit], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Gross Profit] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%232B6F75'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%232B6F75' fill-opacity='0.22' stroke='%232B6F75' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='14.2' fill='%23F7FAFC' letter-spacing='0'>Gross Profit</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%232B6F75' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%232B6F75' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for gross profit with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "OPEX KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [OPEX], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [OPEX], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis <= -0.02, \"%236F8552\", IF ( StatusBasis <= 0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis <= -0.02, \"ON TRACK\", IF ( StatusBasis <= 0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue <= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [OPEX] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%23B85A72'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%23B85A72' fill-opacity='0.22' stroke='%23B85A72' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='14.2' fill='%23F7FAFC' letter-spacing='0'>OPEX</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%23B85A72' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%23B85A72' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for OPEX with lower-is-better status and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Net Income KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Net Income], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Net Income], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Net Income] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%236F8552'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%236F8552' fill-opacity='0.22' stroke='%236F8552' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='14.2' fill='%23F7FAFC' letter-spacing='0'>Net Income</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%236F8552' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%236F8552' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for net income with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "IC Revenue KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Intercompany Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Intercompany Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis <= -0.02, \"%236F8552\", IF ( StatusBasis <= 0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis <= -0.02, \"ON TRACK\", IF ( StatusBasis <= 0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue <= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Intercompany Revenue] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%232F5F9E'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%232F5F9E' fill-opacity='0.22' stroke='%232F5F9E' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='14.2' fill='%23F7FAFC' letter-spacing='0'>IC Revenue</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%232F5F9E' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%232F5F9E' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for intercompany revenue with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Intercompany Elimination KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Intercompany Elimination], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Intercompany Elimination], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis <= -0.02, \"%236F8552\", IF ( StatusBasis <= 0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis <= -0.02, \"ON TRACK\", IF ( StatusBasis <= 0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue <= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Intercompany Elimination] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%232B6F75'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%232B6F75' fill-opacity='0.22' stroke='%232B6F75' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='13.0' fill='%23F7FAFC' letter-spacing='0'>IC Elimination</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%232B6F75' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%232B6F75' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for intercompany elimination impact with lower-is-better status and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Close Exceptions KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Open Exception Value], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Open Exception Value], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis <= -0.02, \"%236F8552\", IF ( StatusBasis <= 0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis <= -0.02, \"ON TRACK\", IF ( StatusBasis <= 0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue <= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Open Exception Value] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%23B85A72'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%23B85A72' fill-opacity='0.22' stroke='%23B85A72' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='14.2' fill='%23F7FAFC' letter-spacing='0'>Close Risk</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%23B85A72' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%23B85A72' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for open exception exposure with lower-is-better status and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Forecast Accuracy KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    COALESCE ( CALCULATE ( [Forecast Accuracy %], REMOVEFILTERS ( DimDate ), DimDate[date] = d ), 0 )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    COALESCE ( CALCULATE ( [Forecast Accuracy %], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate ), 0 )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Forecast Accuracy %] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        70,\n        96 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 52\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 172 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 102\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 96 - YRatio * 52\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPoints = \"172,106 \" & LinePoints & \" 274,106\"\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( CurrentValue, \"0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( PriorValue, \"0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DeltaPoints, \"+0.0pt;-0.0pt;0.0pt\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<g clip-path='url(%23sparkClip)'><polygon points='\" & AreaPoints & \"' fill='\" & TrendColor & \"' fill-opacity='0.26'/>\"\n            & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='4.0' stroke-linecap='round' stroke-linejoin='round'/></g>\"\n            & \"<circle cx='172' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='4.4' fill='%231F2630' stroke='%23B9C3CF' stroke-width='1.45'/>\"\n            & \"<circle cx='274' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='5.6' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='172' y1='70' x2='274' y2='70' stroke='%23313B48' stroke-width='4.0' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='135' viewBox='0 0 296 135'>\"\n    & \"<defs><clipPath id='sparkClip'><rect x='170' y='43' width='106' height='64' rx='5'/></clipPath></defs>\"\n    & \"<rect x='1.2' y='1.2' width='293.6' height='132.6' rx='12' fill='%23242B35' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<rect x='13' y='13' width='150' height='4.5' rx='2.25' fill='%23A8894B'/>\"\n    & \"<rect x='13' y='31' width='16' height='16' rx='4.2' fill='%23A8894B' fill-opacity='0.22' stroke='%23A8894B' stroke-width='1.15'/>\"\n    & \"<text x='38' y='45' font-family='Segoe UI Semibold' font-size='13.0' fill='%23F7FAFC' letter-spacing='0'>Forecast Accuracy</text>\"\n    & \"<text x='13' y='98' font-family='Segoe UI Semibold' font-size='38' fill='%23A8894B' letter-spacing='0'>\" & ValueText & \"</text>\"\n    & \"<rect x='162' y='32' width='120' height='82' rx='9' fill='%231F2630' stroke='%233A4655' stroke-width='1.0'/>\"\n    & \"<rect x='170' y='43' width='106' height='64' rx='5.5' fill='%23A8894B' fill-opacity='0.13'/>\"\n    & \"<line x1='170' y1='73' x2='276' y2='73' stroke='%23313B48' stroke-width='1.4' stroke-dasharray='4 5'/>\"\n    & Sparkline\n    & \"<rect x='13' y='110' width='94' height='20' rx='9' fill='%232C3440' stroke='%233A4655' stroke-width='0.75'/>\"\n    & \"<text x='23' y='124' font-family='Segoe UI Semibold' font-size='10.5' fill='%23B9C3CF'>PY \" & PyText & \"</text>\"\n    & \"<rect x='113' y='110' width='76' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.16' stroke='\" & StatusColor & \"' stroke-opacity='0.18'/>\"\n    & \"<text x='151' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.5' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<rect x='195' y='110' width='87' height='20' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.11'/>\"\n    & \"<text x='238.5' y='124' text-anchor='middle' font-family='Segoe UI Semibold' font-size='10.2' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for forecast accuracy with prior-year point delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Lens Summary SVG",
            "expression": "VAR PeriodText = [Selected Latest Complete Period Label]\nVAR RegionRaw =\n    IF ( ISFILTERED ( DimEntity[region] ), CONCATENATEX ( VALUES ( DimEntity[region] ), DimEntity[region], \", \" ), \"All regions\" )\nVAR BURaw =\n    IF ( ISFILTERED ( DimBusinessUnit[business_unit] ), CONCATENATEX ( VALUES ( DimBusinessUnit[business_unit] ), DimBusinessUnit[business_unit], \", \" ), \"All BUs\" )\nVAR ScenarioRaw =\n    IF ( ISFILTERED ( DimScenario[scenario] ), CONCATENATEX ( VALUES ( DimScenario[scenario] ), DimScenario[scenario], \", \" ), \"Actual lens\" )\nVAR ScenarioText = SUBSTITUTE ( LEFT ( ScenarioRaw, 20 ), \"&\", \"and\" )\nVAR RegionText = SUBSTITUTE ( LEFT ( RegionRaw, 24 ), \"&\", \"and\" )\nVAR BUText = SUBSTITUTE ( LEFT ( BURaw, 28 ), \"&\", \"and\" )\nVAR RevVar = [Latest Revenue Var %]\nVAR EbitdaVar = [Latest EBITDA Var %]\nVAR RiskValue = COALESCE ( [Latest Open Exception Value], 0 )\nVAR RevText = SUBSTITUTE ( FORMAT ( RevVar, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" )\nVAR StatusColor = IF ( EbitdaVar >= 0.02, \"%232B6F75\", IF ( EbitdaVar >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR Line1 = SUBSTITUTE ( LEFT ( PeriodText & \" | \" & ScenarioText, 38 ), \"&\", \"and\" )\nVAR Line2 = SUBSTITUTE ( LEFT ( BUText & \" | \" & RegionText, 48 ), \"&\", \"and\" )\nVAR RiskText = \"$\" & FORMAT ( DIVIDE ( RiskValue, 1000000 ), \"0.0M\" )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='568' height='78' viewBox='0 0 568 78'>\"\n    & \"<rect x='18' y='14' width='5' height='50' rx='2.5' fill='%232B6F75'/>\"\n    & \"<circle cx='46' cy='27' r='7.4' fill='\" & StatusColor & \"'/>\"\n    & \"<text x='64' y='28' font-family='Segoe UI Semibold' font-size='14.0' fill='%23F7FAFC'>CURRENT LENS</text>\"\n    & \"<text x='64' y='50' font-family='Segoe UI Semibold' font-size='13.1' fill='%23F7FAFC'>\" & Line1 & \"</text>\"\n    & \"<text x='64' y='66' font-family='Segoe UI' font-size='12.2' fill='%23C7D0DB'>\" & Line2 & \"</text>\"\n    & \"<rect x='244' y='10' width='154' height='58' rx='11' fill='%231F2630' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<text x='321' y='30' text-anchor='middle' font-family='Segoe UI' font-size='11.2' fill='%23C7D0DB'>Revenue var</text>\"\n    & \"<text x='321' y='57' text-anchor='middle' font-family='Segoe UI Semibold' font-size='22.0' fill='%232F5F9E'>\" & RevText & \"</text>\"\n    & \"<rect x='410' y='10' width='144' height='58' rx='11' fill='%231F2630' stroke='%233A4655' stroke-width='1.05'/>\"\n    & \"<text x='482' y='30' text-anchor='middle' font-family='Segoe UI' font-size='11.2' fill='%23C7D0DB'>Close risk</text>\"\n    & \"<text x='482' y='57' text-anchor='middle' font-family='Segoe UI Semibold' font-size='22.0' fill='%23A8894B'>\" & RiskText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "Top-bar Current Lens SVG for selected period, region, BU, revenue variance, and close-risk exposure.",
            "dataCategory": "ImageUrl"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_FactFinancials_date_id_DimDate_date_id",
        "fromTable": "FactFinancials",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactFinancialSummary_date_id_DimDate_date_id",
        "fromTable": "FactFinancialSummary",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactVarianceDriverBridge_date_id_DimDate_date_id",
        "fromTable": "FactVarianceDriverBridge",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactCloseExceptions_date_id_DimDate_date_id",
        "fromTable": "FactCloseExceptions",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactFXRate_date_id_DimDate_date_id",
        "fromTable": "FactFXRate",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactFinancials_entity_id_DimEntity_entity_id",
        "fromTable": "FactFinancials",
        "fromColumn": "entity_id",
        "toTable": "DimEntity",
        "toColumn": "entity_id"
      },
      {
        "name": "rel_FactFinancialSummary_entity_id_DimEntity_entity_id",
        "fromTable": "FactFinancialSummary",
        "fromColumn": "entity_id",
        "toTable": "DimEntity",
        "toColumn": "entity_id"
      },
      {
        "name": "rel_FactVarianceDriverBridge_entity_id_DimEntity_entity_id",
        "fromTable": "FactVarianceDriverBridge",
        "fromColumn": "entity_id",
        "toTable": "DimEntity",
        "toColumn": "entity_id"
      },
      {
        "name": "rel_FactCloseExceptions_entity_id_DimEntity_entity_id",
        "fromTable": "FactCloseExceptions",
        "fromColumn": "entity_id",
        "toTable": "DimEntity",
        "toColumn": "entity_id"
      },
      {
        "name": "rel_FactFinancials_business_unit_id_DimBusinessUnit_business_unit_id",
        "fromTable": "FactFinancials",
        "fromColumn": "business_unit_id",
        "toTable": "DimBusinessUnit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "rel_FactFinancialSummary_business_unit_id_DimBusinessUnit_business_unit_id",
        "fromTable": "FactFinancialSummary",
        "fromColumn": "business_unit_id",
        "toTable": "DimBusinessUnit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "rel_FactVarianceDriverBridge_business_unit_id_DimBusinessUnit_business_unit_id",
        "fromTable": "FactVarianceDriverBridge",
        "fromColumn": "business_unit_id",
        "toTable": "DimBusinessUnit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "rel_FactCloseExceptions_business_unit_id_DimBusinessUnit_business_unit_id",
        "fromTable": "FactCloseExceptions",
        "fromColumn": "business_unit_id",
        "toTable": "DimBusinessUnit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "rel_FactFinancials_scenario_id_DimScenario_scenario_id",
        "fromTable": "FactFinancials",
        "fromColumn": "scenario_id",
        "toTable": "DimScenario",
        "toColumn": "scenario_id"
      },
      {
        "name": "rel_FactFinancialSummary_scenario_id_DimScenario_scenario_id",
        "fromTable": "FactFinancialSummary",
        "fromColumn": "scenario_id",
        "toTable": "DimScenario",
        "toColumn": "scenario_id"
      },
      {
        "name": "rel_FactFinancials_account_id_DimAccount_account_id",
        "fromTable": "FactFinancials",
        "fromColumn": "account_id",
        "toTable": "DimAccount",
        "toColumn": "account_id"
      }
    ]
  }
}
