{
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "summarizeBy": "none"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none"
          },
          {
            "name": "month_number",
            "dataType": "int64",
            "sourceColumn": "month_number",
            "summarizeBy": "none"
          },
          {
            "name": "month_label",
            "dataType": "string",
            "sourceColumn": "month_label",
            "summarizeBy": "none"
          },
          {
            "name": "is_latest_complete",
            "dataType": "boolean",
            "sourceColumn": "is_latest_complete",
            "summarizeBy": "none"
          },
          {
            "name": "month_index",
            "dataType": "int64",
            "sourceColumn": "month_index",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimDate-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/dim_date.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"date\", type date},\n        {\"year\", Int64.Type},\n        {\"quarter\", type text},\n        {\"month_number\", Int64.Type},\n        {\"month_label\", type text},\n        {\"is_latest_complete\", type logical},\n        {\"month_index\", Int64.Type}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimEntity",
        "columns": [
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity",
            "dataType": "string",
            "sourceColumn": "entity",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "ownership",
            "dataType": "double",
            "sourceColumn": "ownership",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimEntity-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/dim_entity.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"entity_id\", type text},\n        {\"entity\", type text},\n        {\"country\", type text},\n        {\"region\", type text},\n        {\"currency\", type text},\n        {\"ownership\", type number}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimBusinessUnit",
        "columns": [
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimBusinessUnit-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/dim_business_unit.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"business_unit_id\", type text},\n        {\"business_unit\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimAccount",
        "columns": [
          {
            "name": "account_id",
            "dataType": "string",
            "sourceColumn": "account_id",
            "summarizeBy": "none"
          },
          {
            "name": "account",
            "dataType": "string",
            "sourceColumn": "account",
            "summarizeBy": "none"
          },
          {
            "name": "account_group",
            "dataType": "string",
            "sourceColumn": "account_group",
            "summarizeBy": "none"
          },
          {
            "name": "sort_order",
            "dataType": "int64",
            "sourceColumn": "sort_order",
            "summarizeBy": "none"
          },
          {
            "name": "statement",
            "dataType": "string",
            "sourceColumn": "statement",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimAccount-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/dim_account.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"account_id\", type text},\n        {\"account\", type text},\n        {\"account_group\", type text},\n        {\"sort_order\", Int64.Type},\n        {\"statement\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimScenario",
        "columns": [
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none"
          },
          {
            "name": "scenario",
            "dataType": "string",
            "sourceColumn": "scenario",
            "summarizeBy": "none"
          },
          {
            "name": "scenario_type",
            "dataType": "string",
            "sourceColumn": "scenario_type",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimScenario-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/dim_scenario.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"scenario_id\", type text},\n        {\"scenario\", type text},\n        {\"scenario_type\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactFinancials",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none"
          },
          {
            "name": "account_id",
            "dataType": "string",
            "sourceColumn": "account_id",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "amount_local",
            "dataType": "double",
            "sourceColumn": "amount_local",
            "summarizeBy": "none"
          },
          {
            "name": "amount_usd",
            "dataType": "double",
            "sourceColumn": "amount_usd",
            "summarizeBy": "none"
          },
          {
            "name": "fx_rate_to_usd",
            "dataType": "double",
            "sourceColumn": "fx_rate_to_usd",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_teu_or_orders",
            "dataType": "double",
            "sourceColumn": "quantity_teu_or_orders",
            "summarizeBy": "none"
          },
          {
            "name": "is_synthetic",
            "dataType": "boolean",
            "sourceColumn": "is_synthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactFinancials-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/fact_financials.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"entity_id\", type text},\n        {\"business_unit_id\", type text},\n        {\"scenario_id\", type text},\n        {\"account_id\", type text},\n        {\"currency\", type text},\n        {\"amount_local\", type number},\n        {\"amount_usd\", type number},\n        {\"fx_rate_to_usd\", type number},\n        {\"quantity_teu_or_orders\", type number},\n        {\"is_synthetic\", type logical}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactFinancialSummary",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none"
          },
          {
            "name": "scenario",
            "dataType": "string",
            "sourceColumn": "scenario",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "gross_revenue_usd",
            "dataType": "double",
            "sourceColumn": "gross_revenue_usd",
            "summarizeBy": "none"
          },
          {
            "name": "external_revenue_usd",
            "dataType": "double",
            "sourceColumn": "external_revenue_usd",
            "summarizeBy": "none"
          },
          {
            "name": "intercompany_revenue_usd",
            "dataType": "double",
            "sourceColumn": "intercompany_revenue_usd",
            "summarizeBy": "none"
          },
          {
            "name": "intercompany_cost_usd",
            "dataType": "double",
            "sourceColumn": "intercompany_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "intercompany_elimination_usd",
            "dataType": "double",
            "sourceColumn": "intercompany_elimination_usd",
            "summarizeBy": "none"
          },
          {
            "name": "cogs_usd",
            "dataType": "double",
            "sourceColumn": "cogs_usd",
            "summarizeBy": "none"
          },
          {
            "name": "gross_profit_usd",
            "dataType": "double",
            "sourceColumn": "gross_profit_usd",
            "summarizeBy": "none"
          },
          {
            "name": "opex_usd",
            "dataType": "double",
            "sourceColumn": "opex_usd",
            "summarizeBy": "none"
          },
          {
            "name": "ebitda_pre_elim_usd",
            "dataType": "double",
            "sourceColumn": "ebitda_pre_elim_usd",
            "summarizeBy": "none"
          },
          {
            "name": "ebitda_usd",
            "dataType": "double",
            "sourceColumn": "ebitda_usd",
            "summarizeBy": "none"
          },
          {
            "name": "ebitda_margin",
            "dataType": "double",
            "sourceColumn": "ebitda_margin",
            "summarizeBy": "none"
          },
          {
            "name": "operating_income_usd",
            "dataType": "double",
            "sourceColumn": "operating_income_usd",
            "summarizeBy": "none"
          },
          {
            "name": "net_income_usd",
            "dataType": "double",
            "sourceColumn": "net_income_usd",
            "summarizeBy": "none"
          },
          {
            "name": "cash_position_usd",
            "dataType": "double",
            "sourceColumn": "cash_position_usd",
            "summarizeBy": "none"
          },
          {
            "name": "operating_cash_flow_usd",
            "dataType": "double",
            "sourceColumn": "operating_cash_flow_usd",
            "summarizeBy": "none"
          },
          {
            "name": "working_capital_usd",
            "dataType": "double",
            "sourceColumn": "working_capital_usd",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactFinancialSummary-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/fact_financial_summary.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"entity_id\", type text},\n        {\"business_unit_id\", type text},\n        {\"scenario_id\", type text},\n        {\"scenario\", type text},\n        {\"country\", type text},\n        {\"region\", type text},\n        {\"business_unit\", type text},\n        {\"currency\", type text},\n        {\"gross_revenue_usd\", type number},\n        {\"external_revenue_usd\", type number},\n        {\"intercompany_revenue_usd\", type number},\n        {\"intercompany_cost_usd\", type number},\n        {\"intercompany_elimination_usd\", type number},\n        {\"cogs_usd\", type number},\n        {\"gross_profit_usd\", type number},\n        {\"opex_usd\", type number},\n        {\"ebitda_pre_elim_usd\", type number},\n        {\"ebitda_usd\", type number},\n        {\"ebitda_margin\", type number},\n        {\"operating_income_usd\", type number},\n        {\"net_income_usd\", type number},\n        {\"cash_position_usd\", type number},\n        {\"operating_cash_flow_usd\", type number},\n        {\"working_capital_usd\", type number}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactVarianceDriverBridge",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "driver",
            "dataType": "string",
            "sourceColumn": "driver",
            "summarizeBy": "none"
          },
          {
            "name": "driver_sort",
            "dataType": "int64",
            "sourceColumn": "driver_sort",
            "summarizeBy": "none"
          },
          {
            "name": "amount_usd",
            "dataType": "double",
            "sourceColumn": "amount_usd",
            "summarizeBy": "none"
          },
          {
            "name": "variance_sign",
            "dataType": "string",
            "sourceColumn": "variance_sign",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactVarianceDriverBridge-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/fact_variance_driver_bridge.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"entity_id\", type text},\n        {\"business_unit_id\", type text},\n        {\"country\", type text},\n        {\"region\", type text},\n        {\"business_unit\", type text},\n        {\"driver\", type text},\n        {\"driver_sort\", Int64.Type},\n        {\"amount_usd\", type number},\n        {\"variance_sign\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCloseExceptions",
        "columns": [
          {
            "name": "exception_id",
            "dataType": "string",
            "sourceColumn": "exception_id",
            "summarizeBy": "none"
          },
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "entity_id",
            "dataType": "string",
            "sourceColumn": "entity_id",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "exception_type",
            "dataType": "string",
            "sourceColumn": "exception_type",
            "summarizeBy": "none"
          },
          {
            "name": "owner_team",
            "dataType": "string",
            "sourceColumn": "owner_team",
            "summarizeBy": "none"
          },
          {
            "name": "severity",
            "dataType": "string",
            "sourceColumn": "severity",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "amount_usd",
            "dataType": "double",
            "sourceColumn": "amount_usd",
            "summarizeBy": "none"
          },
          {
            "name": "due_date",
            "dataType": "dateTime",
            "sourceColumn": "due_date",
            "summarizeBy": "none"
          },
          {
            "name": "commentary",
            "dataType": "string",
            "sourceColumn": "commentary",
            "summarizeBy": "none"
          },
          {
            "name": "is_synthetic",
            "dataType": "boolean",
            "sourceColumn": "is_synthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactCloseExceptions-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/fact_close_exceptions.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"exception_id\", type text},\n        {\"date_id\", type text},\n        {\"entity_id\", type text},\n        {\"country\", type text},\n        {\"region\", type text},\n        {\"exception_type\", type text},\n        {\"owner_team\", type text},\n        {\"severity\", type text},\n        {\"status\", type text},\n        {\"amount_usd\", type number},\n        {\"due_date\", type date},\n        {\"commentary\", type text},\n        {\"is_synthetic\", type logical}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactFXRate",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "to_currency",
            "dataType": "string",
            "sourceColumn": "to_currency",
            "summarizeBy": "none"
          },
          {
            "name": "rate_type",
            "dataType": "string",
            "sourceColumn": "rate_type",
            "summarizeBy": "none"
          },
          {
            "name": "rate_to_usd",
            "dataType": "double",
            "sourceColumn": "rate_to_usd",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactFXRate-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/fact_fx_rate.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"currency\", type text},\n        {\"to_currency\", type text},\n        {\"rate_type\", type text},\n        {\"rate_to_usd\", type number}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "KPI Measures",
        "columns": [
          {
            "name": "Measure Group",
            "dataType": "string",
            "sourceColumn": "Measure Group",
            "isHidden": true,
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "KPI Measures-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #table(type table [Measure Group = text], {{\"Regional FP&A Consolidation\"}})",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Revenue",
            "expression": "SUM ( FactFinancialSummary[external_revenue_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Consolidated external revenue after excluding intercompany revenue."
          },
          {
            "name": "Gross Revenue",
            "expression": "SUM ( FactFinancialSummary[gross_revenue_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "External plus intercompany revenue before elimination."
          },
          {
            "name": "Intercompany Revenue",
            "expression": "SUM ( FactFinancialSummary[intercompany_revenue_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Intercompany revenue requiring elimination."
          },
          {
            "name": "Intercompany Elimination",
            "expression": "SUM ( FactFinancialSummary[intercompany_elimination_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Net intercompany elimination impact."
          },
          {
            "name": "Gross Profit",
            "expression": "SUM ( FactFinancialSummary[gross_profit_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Revenue minus cost of services."
          },
          {
            "name": "Gross Margin %",
            "expression": "DIVIDE ( [Gross Profit], [Total Revenue] )",
            "formatString": "0.0%",
            "description": "Gross profit divided by consolidated external revenue."
          },
          {
            "name": "OPEX",
            "expression": "SUM ( FactFinancialSummary[opex_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Personnel, facilities, sales and marketing, and G&A."
          },
          {
            "name": "EBITDA",
            "expression": "SUM ( FactFinancialSummary[ebitda_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Gross profit plus OPEX after intercompany elimination."
          },
          {
            "name": "EBITDA Margin %",
            "expression": "DIVIDE ( [EBITDA], [Total Revenue] )",
            "formatString": "0.0%",
            "description": "EBITDA divided by consolidated external revenue."
          },
          {
            "name": "Operating Income",
            "expression": "SUM ( FactFinancialSummary[operating_income_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "EBITDA less depreciation."
          },
          {
            "name": "Net Income",
            "expression": "SUM ( FactFinancialSummary[net_income_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Operating income less interest and tax."
          },
          {
            "name": "Cash Position",
            "expression": "SUM ( FactFinancialSummary[cash_position_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Period-end cash position by entity and BU allocation."
          },
          {
            "name": "Operating Cash Flow",
            "expression": "SUM ( FactFinancialSummary[operating_cash_flow_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Operating cash flow proxy tied to EBITDA conversion."
          },
          {
            "name": "Working Capital",
            "expression": "SUM ( FactFinancialSummary[working_capital_usd] )",
            "formatString": "$#,0,,.0M",
            "description": "Working capital proxy for close review."
          },
          {
            "name": "Actual Revenue",
            "expression": "CALCULATE ( [Total Revenue], DimScenario[scenario] = \"Actual\" )",
            "formatString": "$#,0,,.0M",
            "description": "Actual consolidated revenue."
          },
          {
            "name": "Budget Revenue",
            "expression": "CALCULATE ( [Total Revenue], DimScenario[scenario] = \"Budget\" )",
            "formatString": "$#,0,,.0M",
            "description": "Budget consolidated revenue."
          },
          {
            "name": "Revenue Var vs Budget",
            "expression": "[Actual Revenue] - [Budget Revenue]",
            "formatString": "$#,0,,.0M",
            "description": "Actual revenue less budget revenue."
          },
          {
            "name": "Revenue Var %",
            "expression": "DIVIDE ( [Revenue Var vs Budget], [Budget Revenue] )",
            "formatString": "0.0%",
            "description": "Revenue variance divided by budget revenue."
          },
          {
            "name": "Actual EBITDA",
            "expression": "CALCULATE ( [EBITDA], DimScenario[scenario] = \"Actual\" )",
            "formatString": "$#,0,,.0M",
            "description": "Actual EBITDA."
          },
          {
            "name": "Budget EBITDA",
            "expression": "CALCULATE ( [EBITDA], DimScenario[scenario] = \"Budget\" )",
            "formatString": "$#,0,,.0M",
            "description": "Budget EBITDA."
          },
          {
            "name": "EBITDA Var vs Budget",
            "expression": "[Actual EBITDA] - [Budget EBITDA]",
            "formatString": "$#,0,,.0M",
            "description": "Actual EBITDA less budget EBITDA."
          },
          {
            "name": "EBITDA Var %",
            "expression": "DIVIDE ( [EBITDA Var vs Budget], [Budget EBITDA] )",
            "formatString": "0.0%",
            "description": "EBITDA variance divided by budget EBITDA."
          },
          {
            "name": "Forecast EBITDA",
            "expression": "CALCULATE ( [EBITDA], DimScenario[scenario] = \"Forecast\" )",
            "formatString": "$#,0,,.0M",
            "description": "Forecast EBITDA."
          },
          {
            "name": "Forecast Accuracy %",
            "expression": "1 - ABS ( DIVIDE ( [Actual EBITDA] - [Forecast EBITDA], [Actual EBITDA] ) )",
            "formatString": "0.0%",
            "description": "Directional forecast accuracy for EBITDA."
          },
          {
            "name": "Open Exception Count",
            "expression": "CALCULATE ( COUNTROWS ( FactCloseExceptions ), FactCloseExceptions[status] <> \"Closed\" )",
            "formatString": "#,0",
            "description": "Open or in-progress close exceptions."
          },
          {
            "name": "Open Exception Value",
            "expression": "CALCULATE ( SUM ( FactCloseExceptions[amount_usd] ), FactCloseExceptions[status] <> \"Closed\" )",
            "formatString": "$#,0,,.0M",
            "description": "Value attached to unresolved close exceptions."
          },
          {
            "name": "Selected Latest Complete Date",
            "expression": "VAR GlobalLatestComplete =\n    CALCULATE (\n        MAX ( DimDate[date] ),\n        REMOVEFILTERS ( DimDate ),\n        DimDate[is_latest_complete] = TRUE ()\n    )\nVAR SelectedLatest =\n    MAXX (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[date] <= GlobalLatestComplete ),\n        DimDate[date]\n    )\nRETURN\n    COALESCE ( SelectedLatest, GlobalLatestComplete )",
            "formatString": "mmm yyyy",
            "description": "Latest complete date within the selected date context, capped to the global closed period."
          },
          {
            "name": "Selected Latest Complete Period Label",
            "expression": "FORMAT ( [Selected Latest Complete Date], \"MMM yyyy\" )",
            "formatString": "",
            "description": "Display label for the selected latest complete month."
          },
          {
            "name": "Latest Actual Revenue",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Actual Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Actual revenue at selected latest complete period."
          },
          {
            "name": "Latest Budget Revenue",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Budget Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Budget revenue at selected latest complete period."
          },
          {
            "name": "Latest Revenue Var vs Budget",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Revenue Var vs Budget], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Revenue variance at selected latest complete period."
          },
          {
            "name": "Latest Revenue Var %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Revenue Var %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "Revenue variance percent at selected latest complete period."
          },
          {
            "name": "Latest Actual EBITDA",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Actual EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Actual EBITDA at selected latest complete period."
          },
          {
            "name": "Latest Budget EBITDA",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Budget EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Budget EBITDA at selected latest complete period."
          },
          {
            "name": "Latest EBITDA Var vs Budget",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [EBITDA Var vs Budget], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "EBITDA variance at selected latest complete period."
          },
          {
            "name": "Latest EBITDA Var %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [EBITDA Var %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "EBITDA variance percent at selected latest complete period."
          },
          {
            "name": "Latest Gross Revenue",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Gross Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Gross revenue at selected latest complete period."
          },
          {
            "name": "Latest Gross Profit",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Gross Profit], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Gross profit at selected latest complete period."
          },
          {
            "name": "Latest Gross Margin %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Gross Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "Gross margin at selected latest complete period."
          },
          {
            "name": "Latest OPEX",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [OPEX], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "OPEX at selected latest complete period."
          },
          {
            "name": "Latest Net Income",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Net Income], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Net income at selected latest complete period."
          },
          {
            "name": "Latest EBITDA Margin %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [EBITDA Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "EBITDA margin at selected latest complete period."
          },
          {
            "name": "Latest Cash Position",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Cash Position], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Cash position at selected latest complete period."
          },
          {
            "name": "Latest Operating Cash Flow",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Operating Cash Flow], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Operating cash flow at selected latest complete period."
          },
          {
            "name": "Latest Forecast Accuracy %",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Forecast Accuracy %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "Forecast accuracy at selected latest complete period."
          },
          {
            "name": "Latest Intercompany Revenue",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Intercompany Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Intercompany revenue at selected latest complete period."
          },
          {
            "name": "Latest Intercompany Elimination",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Intercompany Elimination], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Intercompany elimination impact at selected latest complete period."
          },
          {
            "name": "Latest Open Exception Count",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Open Exception Count], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "#,0",
            "description": "Open close-exception count at selected latest complete period."
          },
          {
            "name": "Latest Open Exception Value",
            "expression": "VAR d = [Selected Latest Complete Date]\nRETURN\n    CALCULATE ( [Open Exception Value], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Open close-exception exposure at selected latest complete period."
          },
          {
            "name": "Revenue PY",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Actual Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Actual revenue for the same month in the prior year."
          },
          {
            "name": "EBITDA PY",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Actual EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Actual EBITDA for the same month in the prior year."
          },
          {
            "name": "Gross Margin PY %",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Gross Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "0.0%",
            "description": "Gross margin for the same month in the prior year."
          },
          {
            "name": "Cash Position PY",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Cash Position], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Cash position for the same month in the prior year."
          },
          {
            "name": "Open Exception Value PY",
            "expression": "VAR d = EDATE ( [Selected Latest Complete Date], -12 )\nRETURN\n    CALCULATE ( [Open Exception Value], REMOVEFILTERS ( DimDate ), DimDate[date] = d )",
            "formatString": "$#,0,,.0M",
            "description": "Open exception value for the same month in the prior year."
          },
          {
            "name": "Revenue KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Actual Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Actual Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = CALCULATE ( [Budget Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Actual Revenue] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%232F5F9E'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>Revenue</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for revenue with latest value, PY delta, status chip, and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "EBITDA KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Actual EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Actual EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = CALCULATE ( [Budget EBITDA], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Actual EBITDA] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%232B6F75'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>EBITDA</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for EBITDA with latest value, PY delta, status chip, and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Margin KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [EBITDA Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [EBITDA Margin %], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [EBITDA Margin %] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( CurrentValue, \"0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( PriorValue, \"0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DeltaPoints, \"+0.0pt;-0.0pt;0.0pt\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%236F8552'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>EBITDA Margin</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for EBITDA margin with prior-year point delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cash KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Cash Position], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Cash Position], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Cash Position] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%23A8894B'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>Cash Position</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for cash position with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Gross Revenue KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Gross Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Gross Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Gross Revenue] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%232F5F9E'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>Gross Revenue</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for gross revenue with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Gross Profit KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Gross Profit], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Gross Profit], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Gross Profit] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%232B6F75'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>Gross Profit</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for gross profit with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "OPEX KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [OPEX], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [OPEX], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis <= -0.02, \"%236F8552\", IF ( StatusBasis <= 0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis <= -0.02, \"ON TRACK\", IF ( StatusBasis <= 0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue <= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [OPEX] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%23B85A72'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>OPEX</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for OPEX with lower-is-better status and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Net Income KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Net Income], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Net Income], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Net Income] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%236F8552'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>Net Income</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for net income with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "IC Revenue KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Intercompany Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Intercompany Revenue], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis <= -0.02, \"%236F8552\", IF ( StatusBasis <= 0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis <= -0.02, \"ON TRACK\", IF ( StatusBasis <= 0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue <= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Intercompany Revenue] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%232F5F9E'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>IC Revenue</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for intercompany revenue with prior-year delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Intercompany Elimination KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Intercompany Elimination], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Intercompany Elimination], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis <= -0.02, \"%236F8552\", IF ( StatusBasis <= 0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis <= -0.02, \"ON TRACK\", IF ( StatusBasis <= 0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue <= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Intercompany Elimination] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%232B6F75'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>IC Elimination</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for intercompany elimination impact with lower-is-better status and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Close Exceptions KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Open Exception Value], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Open Exception Value], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis <= -0.02, \"%236F8552\", IF ( StatusBasis <= 0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis <= -0.02, \"ON TRACK\", IF ( StatusBasis <= 0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue <= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Open Exception Value] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$0.0M;($0.0M);$0.0M\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%23B85A72'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>Close Risk</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for open exception exposure with lower-is-better status and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Forecast Accuracy KPI Card SVG",
            "expression": "VAR d = [Selected Latest Complete Date]\nVAR LatestIdx =\n    CALCULATE ( MAX ( DimDate[month_index] ), REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR CurrentValue =\n    CALCULATE ( [Forecast Accuracy %], REMOVEFILTERS ( DimDate ), DimDate[date] = d )\nVAR PriorDate = EDATE ( d, -12 )\nVAR PriorValue =\n    CALCULATE ( [Forecast Accuracy %], REMOVEFILTERS ( DimDate ), DimDate[date] = PriorDate )\nVAR BudgetValue = BLANK ()\nVAR ChangePct = DIVIDE ( CurrentValue - PriorValue, ABS ( PriorValue ) )\nVAR DeltaPoints = ( CurrentValue - PriorValue ) * 100\nVAR StatusBasis =\n    IF (\n        NOT ISBLANK ( BudgetValue ),\n        DIVIDE ( CurrentValue - BudgetValue, ABS ( BudgetValue ) ),\n        ChangePct\n    )\nVAR StatusColor =\n    IF ( StatusBasis >= 0.02, \"%236F8552\", IF ( StatusBasis >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR StatusText =\n    IF ( StatusBasis >= 0.02, \"ON TRACK\", IF ( StatusBasis >= -0.02, \"WATCH\", \"ACTION\" ) )\nVAR TrendColor =\n    IF ( CurrentValue >= PriorValue, \"%236F8552\", \"%23B85A72\" )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER (\n            ALL ( DimDate ),\n            DimDate[date] <= d\n                && DimDate[month_index] >= LatestIdx - 11\n        ),\n        \"__Value\", CALCULATE ( [Forecast Accuracy %] )\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[date], ASC ), [__Value] )\nVAR LastValue = MAXX ( TOPN ( 1, CleanTable, DimDate[date], DESC ), [__Value] )\nVAR FirstY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LastY =\n    IF (\n        MaxValue = MinValue,\n        52,\n        74 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\n    )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[date], , ASC, DENSE ) - 1\n        VAR XValue = 164 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 100\n        VAR YRatio =\n            IF (\n                MaxValue = MinValue,\n                0.5,\n                DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 )\n            )\n        VAR YValue = 74 - YRatio * 38\n        RETURN FORMAT ( XValue, \"0.0\", \"en-US\" ) & \",\" & FORMAT ( YValue, \"0.0\", \"en-US\" ),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR ValueText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( CurrentValue, \"0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR PyText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( PriorValue, \"0.0%\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR DeltaText = SUBSTITUTE ( SUBSTITUTE ( FORMAT ( DeltaPoints, \"+0.0pt;-0.0pt;0.0pt\" ), \"%\", \"%25\" ), \"&\", \"and\" )\nVAR Sparkline =\n    IF (\n        RowCount >= 2,\n        \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n            & \"<circle cx='164' cy='\" & FORMAT ( FirstY, \"0.0\", \"en-US\" ) & \"' r='3.2' fill='%23FFFFFF' stroke='%23526173' stroke-width='1.2'/>\"\n            & \"<circle cx='264' cy='\" & FORMAT ( LastY, \"0.0\", \"en-US\" ) & \"' r='4.2' fill='\" & TrendColor & \"'/>\",\n        \"<line x1='164' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='3' stroke-linecap='round'/>\"\n    )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='292' height='104' viewBox='0 0 292 104'>\"\n    & \"<rect x='1' y='1' width='290' height='102' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<rect x='1' y='1' width='290' height='4' rx='2' fill='%23A8894B'/>\"\n    & \"<text x='16' y='24' font-family='Segoe UI Semibold' font-size='10.5' fill='%23526173'>Forecast Accuracy</text>\"\n    & \"<text x='16' y='54' font-family='Segoe UI Semibold' font-size='25' fill='%230F172A'>\" & ValueText & \"</text>\"\n    & \"<rect x='160' y='34' width='108' height='44' rx='8' fill='%23F8FAFC'/>\"\n    & \"<line x1='166' y1='56' x2='264' y2='56' stroke='%23E6ECF2' stroke-width='1' stroke-dasharray='3 5'/>\"\n    & Sparkline\n    & \"<rect x='16' y='72' width='76' height='18' rx='9' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='26' y='85' font-family='Segoe UI' font-size='8.2' fill='%23526173'>PY \" & PyText & \"</text>\"\n    & \"<rect x='98' y='72' width='56' height='18' rx='9' fill='\" & StatusColor & \"' fill-opacity='0.14'/>\"\n    & \"<text x='108' y='85' font-family='Segoe UI Semibold' font-size='8.2' fill='\" & StatusColor & \"'>\" & DeltaText & \"</text>\"\n    & \"<text x='190' y='91' font-family='Segoe UI Semibold' font-size='8' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "SVG KPI card for forecast accuracy with prior-year point delta and sparkline.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Lens Summary SVG",
            "expression": "VAR PeriodText = [Selected Latest Complete Period Label]\nVAR RegionText =\n    IF ( ISFILTERED ( DimEntity[region] ), LEFT ( CONCATENATEX ( VALUES ( DimEntity[region] ), DimEntity[region], \", \" ), 20 ), \"All regions\" )\nVAR BUText =\n    IF ( ISFILTERED ( DimBusinessUnit[business_unit] ), LEFT ( CONCATENATEX ( VALUES ( DimBusinessUnit[business_unit] ), DimBusinessUnit[business_unit], \", \" ), 24 ), \"All BUs\" )\nVAR ScenarioText =\n    IF ( ISFILTERED ( DimScenario[scenario] ), LEFT ( CONCATENATEX ( VALUES ( DimScenario[scenario] ), DimScenario[scenario], \", \" ), 18 ), \"Actual lens\" )\nVAR RevVar = [Latest Revenue Var %]\nVAR EbitdaVar = [Latest EBITDA Var %]\nVAR RiskValue = [Latest Open Exception Value]\nVAR RevText = SUBSTITUTE ( FORMAT ( RevVar, \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" )\nVAR StatusColor = IF ( EbitdaVar >= 0.02, \"%232B6F75\", IF ( EbitdaVar >= -0.02, \"%23A8894B\", \"%23B85A72\" ) )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='536' height='42' viewBox='0 0 536 42'>\"\n    & \"<rect x='0.5' y='0.5' width='535' height='41' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<circle cx='18' cy='21' r='5' fill='\" & StatusColor & \"'/>\"\n    & \"<text x='32' y='17' font-family='Segoe UI Semibold' font-size='9.5' fill='%230F172A'>Current Lens</text>\"\n    & \"<text x='32' y='31' font-family='Segoe UI' font-size='8.3' fill='%23526173'>\" & PeriodText & \" | \" & ScenarioText & \"</text>\"\n    & \"<rect x='174' y='9' width='102' height='24' rx='12' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='186' y='25' font-family='Segoe UI Semibold' font-size='8.4' fill='%232F5F9E'>\" & RegionText & \"</text>\"\n    & \"<rect x='286' y='9' width='118' height='24' rx='12' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='298' y='25' font-family='Segoe UI Semibold' font-size='8.4' fill='%232B6F75'>\" & BUText & \"</text>\"\n    & \"<rect x='414' y='9' width='108' height='24' rx='12' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<text x='426' y='25' font-family='Segoe UI Semibold' font-size='8.2' fill='%23A8894B'>Rev \" & RevText & \" | Risk $\" & FORMAT ( DIVIDE ( RiskValue, 1000000 ), \"0.0M\" ) & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "Top-bar Current Lens SVG for selected period, region, BU, revenue variance, and close-risk exposure.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Regional FP&A Decision Chips SVG",
            "expression": "VAR Blue = \"%232F5F9E\"\nVAR Teal = \"%232B6F75\"\nVAR Gold = \"%23A8894B\"\nVAR Rose = \"%23B85A72\"\nVAR RevColor = IF ( [Latest Revenue Var %] >= 0, Teal, Rose )\nVAR EbitdaColor = IF ( [Latest EBITDA Var %] >= 0, Teal, Rose )\nVAR RiskColor = IF ( [Latest Open Exception Count] = 0, Teal, IF ( [Latest Open Exception Value] < 5000000, Gold, Rose ) )\nVAR ICColor = IF ( ABS ( DIVIDE ( [Latest Intercompany Elimination], [Latest Gross Revenue] ) ) < 0.08, Teal, Gold )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='536' height='68' viewBox='0 0 536 68'>\"\n    & \"<rect x='0.5' y='0.5' width='535' height='67' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<text x='14' y='17' font-family='Segoe UI Semibold' font-size='10' fill='%230F172A'>Decision Signals</text>\"\n    & \"<rect x='14' y='28' width='164' height='28' rx='14' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<circle cx='30' cy='42' r='4' fill='\" & RevColor & \"'/>\"\n    & \"<text x='42' y='39' font-family='Segoe UI' font-size='7.6' fill='%23526173'>Revenue vs budget</text>\"\n    & \"<text x='42' y='51' font-family='Segoe UI Semibold' font-size='8.4' fill='%230F172A'>\" & SUBSTITUTE ( FORMAT ( [Latest Revenue Var %], \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ) & \"</text>\"\n    & \"<rect x='192' y='28' width='164' height='28' rx='14' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<circle cx='208' cy='42' r='4' fill='\" & EbitdaColor & \"'/>\"\n    & \"<text x='220' y='39' font-family='Segoe UI' font-size='7.6' fill='%23526173'>EBITDA vs budget</text>\"\n    & \"<text x='220' y='51' font-family='Segoe UI Semibold' font-size='8.4' fill='%230F172A'>\" & SUBSTITUTE ( FORMAT ( [Latest EBITDA Var %], \"+0.0%;-0.0%;0.0%\" ), \"%\", \"%25\" ) & \"</text>\"\n    & \"<rect x='370' y='28' width='164' height='28' rx='14' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<circle cx='386' cy='42' r='4' fill='\" & RiskColor & \"'/>\"\n    & \"<text x='398' y='39' font-family='Segoe UI' font-size='7.6' fill='%23526173'>Open close risk</text>\"\n    & \"<text x='398' y='51' font-family='Segoe UI Semibold' font-size='8.4' fill='%230F172A'>\" & SUBSTITUTE ( FORMAT ( [Latest Open Exception Count], \"#,0\" ) & \" items | $\" & FORMAT ( DIVIDE ( [Latest Open Exception Value], 1000000 ), \"0.0M\" ), \"%\", \"%25\" ) & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "Executive decision-chip SVG for regional FP&A revenue, EBITDA, and close-risk status.",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Controls Decision Chips SVG",
            "expression": "VAR Blue = \"%232F5F9E\"\nVAR Teal = \"%232B6F75\"\nVAR Gold = \"%23A8894B\"\nVAR Rose = \"%23B85A72\"\nVAR RevColor = IF ( [Latest Revenue Var %] >= 0, Teal, Rose )\nVAR EbitdaColor = IF ( [Latest EBITDA Var %] >= 0, Teal, Rose )\nVAR RiskColor = IF ( [Latest Open Exception Count] = 0, Teal, IF ( [Latest Open Exception Value] < 5000000, Gold, Rose ) )\nVAR ICColor = IF ( ABS ( DIVIDE ( [Latest Intercompany Elimination], [Latest Gross Revenue] ) ) < 0.08, Teal, Gold )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='536' height='68' viewBox='0 0 536 68'>\"\n    & \"<rect x='0.5' y='0.5' width='535' height='67' rx='7' fill='%23FFFFFF' stroke='%23D5DEE8'/>\"\n    & \"<text x='14' y='17' font-family='Segoe UI Semibold' font-size='10' fill='%230F172A'>Control Signals</text>\"\n    & \"<rect x='14' y='28' width='164' height='28' rx='14' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<circle cx='30' cy='42' r='4' fill='\" & ICColor & \"'/>\"\n    & \"<text x='42' y='39' font-family='Segoe UI' font-size='7.6' fill='%23526173'>Intercompany</text>\"\n    & \"<text x='42' y='51' font-family='Segoe UI Semibold' font-size='8.4' fill='%230F172A'>\" & SUBSTITUTE ( \"$\" & FORMAT ( DIVIDE ( ABS ( [Latest Intercompany Elimination] ), 1000000 ), \"0.0M\" ), \"%\", \"%25\" ) & \"</text>\"\n    & \"<rect x='192' y='28' width='164' height='28' rx='14' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<circle cx='208' cy='42' r='4' fill='\" & RiskColor & \"'/>\"\n    & \"<text x='220' y='39' font-family='Segoe UI' font-size='7.6' fill='%23526173'>Close risk</text>\"\n    & \"<text x='220' y='51' font-family='Segoe UI Semibold' font-size='8.4' fill='%230F172A'>\" & SUBSTITUTE ( FORMAT ( [Latest Open Exception Count], \"#,0\" ) & \" open\", \"%\", \"%25\" ) & \"</text>\"\n    & \"<rect x='370' y='28' width='164' height='28' rx='14' fill='%23F8FAFC' stroke='%23D5DEE8'/>\"\n    & \"<circle cx='386' cy='42' r='4' fill='\" & EbitdaColor & \"'/>\"\n    & \"<text x='398' y='39' font-family='Segoe UI' font-size='7.6' fill='%23526173'>Forecast quality</text>\"\n    & \"<text x='398' y='51' font-family='Segoe UI Semibold' font-size='8.4' fill='%230F172A'>\" & SUBSTITUTE ( FORMAT ( [Latest Forecast Accuracy %], \"0.0%\" ), \"%\", \"%25\" ) & \"</text>\"\n    & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "Control decision-chip SVG for intercompany, close risk, and forecast quality.",
            "dataCategory": "ImageUrl"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_FactFinancials_date_id_DimDate_date_id",
        "fromTable": "FactFinancials",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactFinancialSummary_date_id_DimDate_date_id",
        "fromTable": "FactFinancialSummary",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactVarianceDriverBridge_date_id_DimDate_date_id",
        "fromTable": "FactVarianceDriverBridge",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactCloseExceptions_date_id_DimDate_date_id",
        "fromTable": "FactCloseExceptions",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactFXRate_date_id_DimDate_date_id",
        "fromTable": "FactFXRate",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactFinancials_entity_id_DimEntity_entity_id",
        "fromTable": "FactFinancials",
        "fromColumn": "entity_id",
        "toTable": "DimEntity",
        "toColumn": "entity_id"
      },
      {
        "name": "rel_FactFinancialSummary_entity_id_DimEntity_entity_id",
        "fromTable": "FactFinancialSummary",
        "fromColumn": "entity_id",
        "toTable": "DimEntity",
        "toColumn": "entity_id"
      },
      {
        "name": "rel_FactVarianceDriverBridge_entity_id_DimEntity_entity_id",
        "fromTable": "FactVarianceDriverBridge",
        "fromColumn": "entity_id",
        "toTable": "DimEntity",
        "toColumn": "entity_id"
      },
      {
        "name": "rel_FactCloseExceptions_entity_id_DimEntity_entity_id",
        "fromTable": "FactCloseExceptions",
        "fromColumn": "entity_id",
        "toTable": "DimEntity",
        "toColumn": "entity_id"
      },
      {
        "name": "rel_FactFinancials_business_unit_id_DimBusinessUnit_business_unit_id",
        "fromTable": "FactFinancials",
        "fromColumn": "business_unit_id",
        "toTable": "DimBusinessUnit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "rel_FactFinancialSummary_business_unit_id_DimBusinessUnit_business_unit_id",
        "fromTable": "FactFinancialSummary",
        "fromColumn": "business_unit_id",
        "toTable": "DimBusinessUnit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "rel_FactVarianceDriverBridge_business_unit_id_DimBusinessUnit_business_unit_id",
        "fromTable": "FactVarianceDriverBridge",
        "fromColumn": "business_unit_id",
        "toTable": "DimBusinessUnit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "rel_FactFinancials_scenario_id_DimScenario_scenario_id",
        "fromTable": "FactFinancials",
        "fromColumn": "scenario_id",
        "toTable": "DimScenario",
        "toColumn": "scenario_id"
      },
      {
        "name": "rel_FactFinancialSummary_scenario_id_DimScenario_scenario_id",
        "fromTable": "FactFinancialSummary",
        "fromColumn": "scenario_id",
        "toTable": "DimScenario",
        "toColumn": "scenario_id"
      },
      {
        "name": "rel_FactFinancials_account_id_DimAccount_account_id",
        "fromTable": "FactFinancials",
        "fromColumn": "account_id",
        "toTable": "DimAccount",
        "toColumn": "account_id"
      }
    ]
  }
}