Cash Balance =
SUM(FactCashPosition[balance_usd])

Available Cash =
SUM(FactCashPosition[available_cash_usd])

Restricted Cash =
SUM(FactCashPosition[restricted_cash_usd])

Credit Available =
SUM(FactLiquidityFacility[available_usd])

Available Liquidity =
[Available Cash] + [Credit Available]

Minimum Cash Buffer =
SUM(FactLiquidityFacility[min_cash_buffer_usd])

Liquidity Headroom =
[Available Liquidity] - [Minimum Cash Buffer]

AR Outstanding =
SUM(FactARInvoice[outstanding_usd])

Overdue AR =
CALCULATE([AR Outstanding], FactARInvoice[is_overdue] = TRUE())

Overdue AR % =
DIVIDE([Overdue AR], [AR Outstanding])

AP Outstanding =
SUM(FactAPInvoice[outstanding_usd])

AP Due 14 Days =
CALCULATE([AP Outstanding], FactAPInvoice[due_window] = "0-14 days")

Revenue =
SUM(FactWorkingCapital[revenue_usd])

COGS =
SUM(FactWorkingCapital[cogs_usd])

Working Capital =
SUM(FactWorkingCapital[working_capital_usd])

DSO =
DIVIDE(SUM(FactWorkingCapital[ar_balance_usd]), [Revenue]) * 30

DPO =
DIVIDE(SUM(FactWorkingCapital[ap_balance_usd]), [COGS]) * 30

DIO =
DIVIDE(SUM(FactWorkingCapital[inventory_balance_usd]), [COGS]) * 30

Cash Conversion Cycle =
[DSO] + [DIO] - [DPO]

Forecast Closing Cash =
SUM(FactCashForecast[closing_cash_usd])

Forecast Net Cash Flow =
SUM(FactCashForecast[net_cash_flow_usd])

Forecast Receipts =
SUM(FactCashForecast[customer_receipts_usd]) + SUM(FactCashForecast[other_receipts_usd])

Forecast Payments =
SUM(FactCashForecast[supplier_payments_usd]) + SUM(FactCashForecast[payroll_tax_usd]) + SUM(FactCashForecast[capex_usd]) + SUM(FactCashForecast[debt_service_usd])

Cash Runway Weeks =
DIVIDE([Available Liquidity], ABS(AVERAGE(FactCashForecast[net_cash_flow_usd])))

Forecast Error % =
DIVIDE(SUM(FactForecastAccuracy[abs_error_usd]), SUMX(FactForecastAccuracy, ABS(FactForecastAccuracy[actual_net_cash_flow_usd])))

FX Net Exposure =
SUM(FactFXExposure[net_exposure_usd])

Unhedged FX Exposure =
SUM(FactFXExposure[unhedged_exposure_usd])

Unhedged FX % =
DIVIDE([Unhedged FX Exposure], [FX Net Exposure])

Open Risk Value =
CALCULATE(SUM(FactTreasuryRiskAction[amount_usd]), FactTreasuryRiskAction[status] <> "Closed")

Open Risk Count =
CALCULATE(COUNTROWS(FactTreasuryRiskAction), FactTreasuryRiskAction[status] <> "Closed")

Latest Complete Month =
MAXX(FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()), DimDate[date])

Available Liquidity KPI Card SVG =
VAR CurrentPeriod =
    MAXX(
        FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()),
        DimDate[month_index]
    )
VAR PriorPeriod = CurrentPeriod - 12
VAR CurrentValue =
    CALCULATE(
        [Available Liquidity],
        FILTER(ALL(DimDate), DimDate[month_index] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Available Liquidity],
        FILTER(ALL(DimDate), DimDate[month_index] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimDate), DimDate[month_index] <= CurrentPeriod),
        "__Sort", DimDate[month_index],
        "__Value", [Available Liquidity]
    )

VAR CurrentTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), "$0.0M;($0.0M);$0.0M")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(PriorValue, 1000000), "$0.0M;($0.0M);$0.0M"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(CurrentValue - PriorValue, ABS(PriorValue)), "+0.0%;-0.0%;0.0%"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue >= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue >= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue >= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%230F766E'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%230F766E'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Available Liquidity</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%230F766E'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Liquidity Headroom KPI Card SVG =
VAR CurrentPeriod =
    MAXX(
        FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()),
        DimDate[month_index]
    )
VAR PriorPeriod = CurrentPeriod - 12
VAR CurrentValue =
    CALCULATE(
        [Liquidity Headroom],
        FILTER(ALL(DimDate), DimDate[month_index] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Liquidity Headroom],
        FILTER(ALL(DimDate), DimDate[month_index] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimDate), DimDate[month_index] <= CurrentPeriod),
        "__Sort", DimDate[month_index],
        "__Value", [Liquidity Headroom]
    )

VAR CurrentTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), "$0.0M;($0.0M);$0.0M")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(PriorValue, 1000000), "$0.0M;($0.0M);$0.0M"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(CurrentValue - PriorValue, ABS(PriorValue)), "+0.0%;-0.0%;0.0%"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue >= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue >= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue >= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%232F5F9E'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%232F5F9E'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Liquidity Headroom</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%232F5F9E'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Forecast Net Flow KPI Card SVG =
VAR CurrentPeriod =
    MAXX(ALLSELECTED(DimWeek), DimWeek[week_number])
VAR PriorPeriod = CurrentPeriod - 1
VAR CurrentValue =
    CALCULATE(
        [Forecast Net Cash Flow],
        FILTER(ALL(DimWeek), DimWeek[week_number] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Forecast Net Cash Flow],
        FILTER(ALL(DimWeek), DimWeek[week_number] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimWeek), DimWeek[week_number] <= CurrentPeriod),
        "__Sort", DimWeek[week_number],
        "__Value", [Forecast Net Cash Flow]
    )

VAR CurrentTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), "$0.0M;($0.0M);$0.0M")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(PriorValue, 1000000), "$0.0M;($0.0M);$0.0M"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(CurrentValue - PriorValue, ABS(PriorValue)), "+0.0%;-0.0%;0.0%"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue >= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue >= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue >= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%23B68B36'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%23B68B36'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>13W Net Flow</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%23B68B36'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Cash Runway KPI Card SVG =
VAR CurrentPeriod =
    MAXX(ALLSELECTED(DimWeek), DimWeek[week_number])
VAR PriorPeriod = CurrentPeriod - 1
VAR CurrentValue =
    CALCULATE(
        [Cash Runway Weeks],
        FILTER(ALL(DimWeek), DimWeek[week_number] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Cash Runway Weeks],
        FILTER(ALL(DimWeek), DimWeek[week_number] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimWeek), DimWeek[week_number] <= CurrentPeriod),
        "__Sort", DimWeek[week_number],
        "__Value", [Cash Runway Weeks]
    )

VAR CurrentTextRaw = FORMAT(CurrentValue, "0.0") & " wks"
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(PriorValue, "0.0") & " wks")
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(CurrentValue - PriorValue, "+0.0;-0.0;0.0"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue >= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue >= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue >= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%236F8552'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%236F8552'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Cash Runway</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%236F8552'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

AR Outstanding KPI Card SVG =
VAR CurrentPeriod =
    MAXX(
        FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()),
        DimDate[month_index]
    )
VAR PriorPeriod = CurrentPeriod - 12
VAR CurrentValue =
    CALCULATE(
        [AR Outstanding],
        FILTER(ALL(DimDate), DimDate[month_index] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [AR Outstanding],
        FILTER(ALL(DimDate), DimDate[month_index] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimDate), DimDate[month_index] <= CurrentPeriod),
        "__Sort", DimDate[month_index],
        "__Value", [AR Outstanding]
    )

VAR CurrentTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), "$0.0M;($0.0M);$0.0M")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(PriorValue, 1000000), "$0.0M;($0.0M);$0.0M"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(CurrentValue - PriorValue, ABS(PriorValue)), "+0.0%;-0.0%;0.0%"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue >= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue >= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue >= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%232F5F9E'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%232F5F9E'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>AR Outstanding</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%232F5F9E'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Overdue AR KPI Card SVG =
VAR CurrentPeriod =
    MAXX(
        FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()),
        DimDate[month_index]
    )
VAR PriorPeriod = CurrentPeriod - 12
VAR CurrentValue =
    CALCULATE(
        [Overdue AR %],
        FILTER(ALL(DimDate), DimDate[month_index] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Overdue AR %],
        FILTER(ALL(DimDate), DimDate[month_index] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimDate), DimDate[month_index] <= CurrentPeriod),
        "__Sort", DimDate[month_index],
        "__Value", [Overdue AR %]
    )

VAR CurrentTextRaw = FORMAT(CurrentValue, "0.0%")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(PriorValue, "0.0%"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT((CurrentValue - PriorValue) * 100, "+0.0;-0.0;0.0") & "pt")
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue <= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue <= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue <= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%23B85062'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%23B85062'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Overdue AR %25</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%23B85062'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

AP Due 14 Days KPI Card SVG =
VAR CurrentPeriod =
    MAXX(ALLSELECTED(DimWeek), DimWeek[week_number])
VAR PriorPeriod = CurrentPeriod - 1
VAR CurrentValue =
    CALCULATE(
        [AP Due 14 Days],
        FILTER(ALL(DimWeek), DimWeek[week_number] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [AP Due 14 Days],
        FILTER(ALL(DimWeek), DimWeek[week_number] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimWeek), DimWeek[week_number] <= CurrentPeriod),
        "__Sort", DimWeek[week_number],
        "__Value", [AP Due 14 Days]
    )

VAR CurrentTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), "$0.0M;($0.0M);$0.0M")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(PriorValue, 1000000), "$0.0M;($0.0M);$0.0M"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(CurrentValue - PriorValue, ABS(PriorValue)), "+0.0%;-0.0%;0.0%"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue <= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue <= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue <= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%23B68B36'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%23B68B36'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>AP Due 14d</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%23B68B36'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Cash Conversion KPI Card SVG =
VAR CurrentPeriod =
    MAXX(
        FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()),
        DimDate[month_index]
    )
VAR PriorPeriod = CurrentPeriod - 12
VAR CurrentValue =
    CALCULATE(
        [Cash Conversion Cycle],
        FILTER(ALL(DimDate), DimDate[month_index] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Cash Conversion Cycle],
        FILTER(ALL(DimDate), DimDate[month_index] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimDate), DimDate[month_index] <= CurrentPeriod),
        "__Sort", DimDate[month_index],
        "__Value", [Cash Conversion Cycle]
    )

VAR CurrentTextRaw = FORMAT(CurrentValue, "0.0") & "d"
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(PriorValue, "0.0") & "d")
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(CurrentValue - PriorValue, "+0.0;-0.0;0.0"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue <= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue <= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue <= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%236F8552'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%236F8552'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Cash Conversion</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%236F8552'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Forecast Closing Cash KPI Card SVG =
VAR CurrentPeriod =
    MAXX(ALLSELECTED(DimWeek), DimWeek[week_number])
VAR PriorPeriod = CurrentPeriod - 1
VAR CurrentValue =
    CALCULATE(
        [Forecast Closing Cash],
        FILTER(ALL(DimWeek), DimWeek[week_number] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Forecast Closing Cash],
        FILTER(ALL(DimWeek), DimWeek[week_number] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimWeek), DimWeek[week_number] <= CurrentPeriod),
        "__Sort", DimWeek[week_number],
        "__Value", [Forecast Closing Cash]
    )

VAR CurrentTextRaw = FORMAT(DIVIDE(CurrentValue, 1000000), "$0.0M;($0.0M);$0.0M")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(PriorValue, 1000000), "$0.0M;($0.0M);$0.0M"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(DIVIDE(CurrentValue - PriorValue, ABS(PriorValue)), "+0.0%;-0.0%;0.0%"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue >= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue >= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue >= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%230F766E'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%230F766E'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Closing Cash</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%230F766E'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Forecast Error KPI Card SVG =
VAR CurrentPeriod =
    MAXX(
        FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()),
        DimDate[month_index]
    )
VAR PriorPeriod = CurrentPeriod - 12
VAR CurrentValue =
    CALCULATE(
        [Forecast Error %],
        FILTER(ALL(DimDate), DimDate[month_index] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Forecast Error %],
        FILTER(ALL(DimDate), DimDate[month_index] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimDate), DimDate[month_index] <= CurrentPeriod),
        "__Sort", DimDate[month_index],
        "__Value", [Forecast Error %]
    )

VAR CurrentTextRaw = FORMAT(CurrentValue, "0.0%")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(PriorValue, "0.0%"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT((CurrentValue - PriorValue) * 100, "+0.0;-0.0;0.0") & "pt")
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue <= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue <= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue <= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%23B85062'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%23B85062'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Forecast Error</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%23B85062'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Unhedged FX KPI Card SVG =
VAR CurrentPeriod =
    MAXX(
        FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()),
        DimDate[month_index]
    )
VAR PriorPeriod = CurrentPeriod - 12
VAR CurrentValue =
    CALCULATE(
        [Unhedged FX %],
        FILTER(ALL(DimDate), DimDate[month_index] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Unhedged FX %],
        FILTER(ALL(DimDate), DimDate[month_index] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimDate), DimDate[month_index] <= CurrentPeriod),
        "__Sort", DimDate[month_index],
        "__Value", [Unhedged FX %]
    )

VAR CurrentTextRaw = FORMAT(CurrentValue, "0.0%")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(PriorValue, "0.0%"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT((CurrentValue - PriorValue) * 100, "+0.0;-0.0;0.0") & "pt")
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue <= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue <= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue <= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%23B68B36'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%23B68B36'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Unhedged FX %25</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%23B68B36'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Open Risk KPI Card SVG =
VAR CurrentPeriod =
    MAXX(
        FILTER(ALL(DimDate), DimDate[is_latest_complete] = TRUE()),
        DimDate[month_index]
    )
VAR PriorPeriod = CurrentPeriod - 12
VAR CurrentValue =
    CALCULATE(
        [Open Risk Count],
        FILTER(ALL(DimDate), DimDate[month_index] = CurrentPeriod)
    )
VAR PriorValue =
    CALCULATE(
        [Open Risk Count],
        FILTER(ALL(DimDate), DimDate[month_index] = PriorPeriod)
    )
VAR PeriodTable =
    ADDCOLUMNS(
        FILTER(ALLSELECTED(DimDate), DimDate[month_index] <= CurrentPeriod),
        "__Sort", DimDate[month_index],
        "__Value", [Open Risk Count]
    )

VAR CurrentTextRaw = FORMAT(CurrentValue, "#,0")
VAR PriorTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(PriorValue, "#,0"))
VAR DeltaTextRaw = IF(ISBLANK(PriorValue), "n/a", FORMAT(CurrentValue - PriorValue, "+0.0;-0.0;0.0"))
VAR CurrentText = SUBSTITUTE(CurrentTextRaw, "%", "%25")
VAR PriorText = SUBSTITUTE(PriorTextRaw, "%", "%25")
VAR DeltaText = SUBSTITUTE(DeltaTextRaw, "%", "%25")
VAR DeltaColor =
    IF(ISBLANK(PriorValue), "%23607081", IF(CurrentValue <= PriorValue, "%230F766E", "%23B85062"))
VAR CleanTable =
    FILTER(PeriodTable, NOT ISBLANK([__Value]))
VAR RowCount = COUNTROWS(CleanTable)
VAR MinValue = MINX(CleanTable, [__Value])
VAR MaxValue = MAXX(CleanTable, [__Value])
VAR FirstValue = MINX(TOPN(1, CleanTable, [__Sort], ASC), [__Value])
VAR LastValue = MINX(TOPN(1, CleanTable, [__Sort], DESC), [__Value])
VAR StartYValue = 80 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR EndYValue = 80 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 38
VAR TrendColor = IF(LastValue <= FirstValue, "%230F766E", "%23B85062")
VAR BandColor = IF(LastValue <= FirstValue, "%23DDEEDC", "%23F7DADD")
VAR LinePoints =
    CONCATENATEX(
        CleanTable,
        VAR RankValue = RANKX(CleanTable, [__Sort], , ASC, DENSE) - 1
        VAR XValue = 136 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 92
        VAR YValue = 80 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 38
        RETURN FORMAT(XValue, "0.0") & "," & FORMAT(YValue, "0.0"),
        " ",
        [__Sort],
        ASC
    )
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>"
        & "<rect x='1' y='1' width='250' height='156' rx='10' fill='%23FFFFFF' stroke='%23D8E0E7' stroke-width='1.2'/>"
        & "<rect x='12' y='11' width='228' height='4' rx='2' fill='%23B85062'/>"
        & "<rect x='14' y='27' width='12' height='12' rx='3' fill='%23B85062'/>"
        & "<text x='34' y='38' font-family='Segoe UI Semibold' font-size='12.5' fill='%2315202B'>Open Risks</text>"
        & "<text x='14' y='77' font-family='Segoe UI Semibold' font-size='25' fill='%23B85062'>" & CurrentText & "</text>"
        & "<rect x='130' y='30' width='108' height='58' rx='8' fill='%23F3F6F8'/>"
        & "<rect x='136' y='58' width='92' height='12' rx='6' fill='" & BandColor & "'/>"
        & "<line x1='136' y1='64' x2='228' y2='64' stroke='%23AAB7C4' stroke-width='1' stroke-dasharray='4 5'/>"
        & "<polyline points='" & LinePoints & "' fill='none' stroke='" & TrendColor & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"
        & "<circle cx='136' cy='" & FORMAT(StartYValue, "0.0") & "' r='3.6' fill='%23FFFFFF' stroke='%23607081' stroke-width='1.4'/>"
        & "<circle cx='228' cy='" & FORMAT(EndYValue, "0.0") & "' r='4.8' fill='" & TrendColor & "' stroke='%23FFFFFF' stroke-width='1.8'/>"
        & "<rect x='14' y='126' width='98' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<rect x='120' y='126' width='118' height='20' rx='6' fill='%23F8FAFB'/>"
        & "<text x='22' y='140' font-family='Segoe UI' font-size='9.4' fill='%23607081'>PY " & PriorText & "</text>"
        & "<text x='130' y='140' font-family='Segoe UI Semibold' font-size='9.4' fill='" & DeltaColor & "'>Delta " & DeltaText & "</text>"
        & "</svg>"
RETURN IF(RowCount = 0, BLANK(), "data:image/svg+xml;utf8," & SVG)

Current Lens SVG =
VAR RegionCount = COUNTROWS(VALUES(DimEntity[region]))
VAR RegionTotal = CALCULATE(COUNTROWS(VALUES(DimEntity[region])), ALL(DimEntity[region]))
VAR RegionText =
    IF(
        NOT ISFILTERED(DimEntity[region]) || RegionCount = RegionTotal,
        "All Regions",
        IF(RegionCount = 1, SELECTEDVALUE(DimEntity[region]), FORMAT(RegionCount, "0") & " Regions")
    )
VAR EntityCount = COUNTROWS(VALUES(DimEntity[entity]))
VAR EntityTotal = CALCULATE(COUNTROWS(VALUES(DimEntity[entity])), ALL(DimEntity[entity]))
VAR EntityText =
    IF(
        NOT ISFILTERED(DimEntity[entity]) || EntityCount = EntityTotal,
        "All Entities",
        IF(EntityCount = 1, SELECTEDVALUE(DimEntity[entity]), FORMAT(EntityCount, "0") & " Entities")
    )
VAR ScenarioText =
    IF(HASONEVALUE(DimScenario[scenario]), SELECTEDVALUE(DimScenario[scenario]), "All Scenarios")
VAR Line1 = LEFT(RegionText & " | " & ScenarioText, 29)
VAR Line2 = LEFT(EntityText, 30)
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='144' height='76' viewBox='0 0 144 76'>"
        & "<rect x='1' y='1' width='142' height='74' rx='8' fill='%2322313F' stroke='%230F766E' stroke-width='1.2'/>"
        & "<text x='10' y='19' font-family='Segoe UI Semibold' font-size='10.4' fill='%239ACBC6'>Current Lens</text>"
        & "<circle cx='126' cy='16' r='3.4' fill='%230F766E'/>"
        & "<text x='10' y='41' font-family='Segoe UI Semibold' font-size='10.5' fill='%23FFFFFF'>" & Line1 & "</text>"
        & "<text x='10' y='60' font-family='Segoe UI' font-size='9.4' fill='%23D8E0E7'>" & Line2 & "</text>"
        & "</svg>"
RETURN "data:image/svg+xml;utf8," & SVG

Treasury Decision Chips SVG =
VAR Chip1Raw = "Scenario " & COALESCE(SELECTEDVALUE(DimScenario[scenario]), "All")
VAR Chip2Raw = "Headroom " & FORMAT(DIVIDE([Liquidity Headroom], 1000000), "$0M;($0M);$0M")
VAR Chip3Raw = "Runway " & FORMAT([Cash Runway Weeks], "0.0") & " wks"
VAR Chip1 = SUBSTITUTE(Chip1Raw, "%", "%25")
VAR Chip2 = SUBSTITUTE(Chip2Raw, "%", "%25")
VAR Chip3 = SUBSTITUTE(Chip3Raw, "%", "%25")
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>"
        & "<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>"
        & "<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='%23E6F4EC' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='13' y='13' width='11' height='11' rx='3' fill='%230F766E'/>"
        & "<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip1 & "</text>"
        & "<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='%23E7F0FF' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='169' y='13' width='11' height='11' rx='3' fill='%232F5F9E'/>"
        & "<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip2 & "</text>"
        & "<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='%23EEF5E8' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='333' y='13' width='11' height='11' rx='3' fill='%236F8552'/>"
        & "<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip3 & "</text>"
        & "</svg>"
RETURN "data:image/svg+xml;utf8," & SVG

Working Capital Decision Chips SVG =
VAR Chip1Raw = "Overdue " & FORMAT([Overdue AR %], "0.0%")
VAR Chip2Raw = "CCC " & FORMAT([Cash Conversion Cycle], "0.0") & "d"
VAR Chip3Raw = "AP 14d " & FORMAT(DIVIDE([AP Due 14 Days], 1000000), "$0M;($0M);$0M")
VAR Chip1 = SUBSTITUTE(Chip1Raw, "%", "%25")
VAR Chip2 = SUBSTITUTE(Chip2Raw, "%", "%25")
VAR Chip3 = SUBSTITUTE(Chip3Raw, "%", "%25")
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>"
        & "<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>"
        & "<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='%23F7DADD' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='13' y='13' width='11' height='11' rx='3' fill='%23B85062'/>"
        & "<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip1 & "</text>"
        & "<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='%23E7F0FF' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='169' y='13' width='11' height='11' rx='3' fill='%232F5F9E'/>"
        & "<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip2 & "</text>"
        & "<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='%23FFF3D6' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='333' y='13' width='11' height='11' rx='3' fill='%23B68B36'/>"
        & "<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip3 & "</text>"
        & "</svg>"
RETURN "data:image/svg+xml;utf8," & SVG

Risk Decision Chips SVG =
VAR Chip1Raw = "FX unhedged " & FORMAT([Unhedged FX %], "0.0%")
VAR Chip2Raw = "Open risks " & FORMAT([Open Risk Count], "#,0")
VAR Chip3Raw = "Forecast error " & FORMAT([Forecast Error %], "0.0%")
VAR Chip1 = SUBSTITUTE(Chip1Raw, "%", "%25")
VAR Chip2 = SUBSTITUTE(Chip2Raw, "%", "%25")
VAR Chip3 = SUBSTITUTE(Chip3Raw, "%", "%25")
VAR SVG =
    "<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>"
        & "<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>"
        & "<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='%23FFF3D6' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='13' y='13' width='11' height='11' rx='3' fill='%23B68B36'/>"
        & "<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip1 & "</text>"
        & "<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='%23F7DADD' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='169' y='13' width='11' height='11' rx='3' fill='%23B85062'/>"
        & "<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip2 & "</text>"
        & "<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='%23E7F0FF' stroke='%23FFFFFF' stroke-width='0.9'/>"
        & "<rect x='333' y='13' width='11' height='11' rx='3' fill='%232F5F9E'/>"
        & "<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.2' fill='%2315202B'>" & Chip3 & "</text>"
        & "</svg>"
RETURN "data:image/svg+xml;utf8," & SVG
