{
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "summarizeBy": "none"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none"
          },
          {
            "name": "quarter_number",
            "dataType": "int64",
            "sourceColumn": "quarter_number",
            "summarizeBy": "none"
          },
          {
            "name": "month_number",
            "dataType": "int64",
            "sourceColumn": "month_number",
            "summarizeBy": "none"
          },
          {
            "name": "month_label",
            "dataType": "string",
            "sourceColumn": "month_label",
            "summarizeBy": "none"
          },
          {
            "name": "month_index",
            "dataType": "int64",
            "sourceColumn": "month_index",
            "summarizeBy": "none"
          },
          {
            "name": "is_latest_complete",
            "dataType": "string",
            "sourceColumn": "is_latest_complete",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimDate-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/dim_date.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"date\", type date},\n        {\"year\", Int64.Type},\n        {\"quarter\", type text},\n        {\"quarter_number\", Int64.Type},\n        {\"month_number\", Int64.Type},\n        {\"month_label\", type text},\n        {\"month_index\", Int64.Type},\n        {\"is_latest_complete\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "customer_id",
            "dataType": "string",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_name",
            "dataType": "string",
            "sourceColumn": "customer_name",
            "summarizeBy": "none"
          },
          {
            "name": "industry",
            "dataType": "string",
            "sourceColumn": "industry",
            "summarizeBy": "none"
          },
          {
            "name": "segment",
            "dataType": "string",
            "sourceColumn": "segment",
            "summarizeBy": "none"
          },
          {
            "name": "tier",
            "dataType": "string",
            "sourceColumn": "tier",
            "summarizeBy": "none"
          },
          {
            "name": "account_manager",
            "dataType": "string",
            "sourceColumn": "account_manager",
            "summarizeBy": "none"
          },
          {
            "name": "credit_risk_band",
            "dataType": "string",
            "sourceColumn": "credit_risk_band",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimCustomer-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/dim_customer.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"customer_id\", type text},\n        {\"customer_name\", type text},\n        {\"industry\", type text},\n        {\"segment\", type text},\n        {\"tier\", type text},\n        {\"account_manager\", type text},\n        {\"credit_risk_band\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimTradeLane",
        "columns": [
          {
            "name": "lane_id",
            "dataType": "string",
            "sourceColumn": "lane_id",
            "summarizeBy": "none"
          },
          {
            "name": "lane_name",
            "dataType": "string",
            "sourceColumn": "lane_name",
            "summarizeBy": "none"
          },
          {
            "name": "origin_country",
            "dataType": "string",
            "sourceColumn": "origin_country",
            "summarizeBy": "none"
          },
          {
            "name": "origin_node",
            "dataType": "string",
            "sourceColumn": "origin_node",
            "summarizeBy": "none"
          },
          {
            "name": "destination_country",
            "dataType": "string",
            "sourceColumn": "destination_country",
            "summarizeBy": "none"
          },
          {
            "name": "destination_node",
            "dataType": "string",
            "sourceColumn": "destination_node",
            "summarizeBy": "none"
          },
          {
            "name": "mode",
            "dataType": "string",
            "sourceColumn": "mode",
            "summarizeBy": "none"
          },
          {
            "name": "distance_km",
            "dataType": "double",
            "sourceColumn": "distance_km",
            "summarizeBy": "none"
          },
          {
            "name": "lane_cluster",
            "dataType": "string",
            "sourceColumn": "lane_cluster",
            "summarizeBy": "none"
          },
          {
            "name": "strategic_lane",
            "dataType": "string",
            "sourceColumn": "strategic_lane",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimTradeLane-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/dim_trade_lane.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"lane_id\", type text},\n        {\"lane_name\", type text},\n        {\"origin_country\", type text},\n        {\"origin_node\", type text},\n        {\"destination_country\", type text},\n        {\"destination_node\", type text},\n        {\"mode\", type text},\n        {\"distance_km\", type number},\n        {\"lane_cluster\", type text},\n        {\"strategic_lane\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimService",
        "columns": [
          {
            "name": "service_id",
            "dataType": "string",
            "sourceColumn": "service_id",
            "summarizeBy": "none"
          },
          {
            "name": "service",
            "dataType": "string",
            "sourceColumn": "service",
            "summarizeBy": "none"
          },
          {
            "name": "service_family",
            "dataType": "string",
            "sourceColumn": "service_family",
            "summarizeBy": "none"
          },
          {
            "name": "mode",
            "dataType": "string",
            "sourceColumn": "mode",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimService-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/dim_service.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"service_id\", type text},\n        {\"service\", type text},\n        {\"service_family\", type text},\n        {\"mode\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimOffice",
        "columns": [
          {
            "name": "office_id",
            "dataType": "string",
            "sourceColumn": "office_id",
            "summarizeBy": "none"
          },
          {
            "name": "office",
            "dataType": "string",
            "sourceColumn": "office",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimOffice-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/dim_office.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"office_id\", type text},\n        {\"office\", type text},\n        {\"country\", type text},\n        {\"region\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCarrier",
        "columns": [
          {
            "name": "carrier_id",
            "dataType": "string",
            "sourceColumn": "carrier_id",
            "summarizeBy": "none"
          },
          {
            "name": "carrier",
            "dataType": "string",
            "sourceColumn": "carrier",
            "summarizeBy": "none"
          },
          {
            "name": "carrier_type",
            "dataType": "string",
            "sourceColumn": "carrier_type",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DimCarrier-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/dim_carrier.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"carrier_id\", type text},\n        {\"carrier\", type text},\n        {\"carrier_type\", type text}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactShipmentProfitability",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "dataType": "string",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "lane_id",
            "dataType": "string",
            "sourceColumn": "lane_id",
            "summarizeBy": "none"
          },
          {
            "name": "service_id",
            "dataType": "string",
            "sourceColumn": "service_id",
            "summarizeBy": "none"
          },
          {
            "name": "office_id",
            "dataType": "string",
            "sourceColumn": "office_id",
            "summarizeBy": "none"
          },
          {
            "name": "carrier_id",
            "dataType": "string",
            "sourceColumn": "carrier_id",
            "summarizeBy": "none"
          },
          {
            "name": "shipment_count",
            "dataType": "int64",
            "sourceColumn": "shipment_count",
            "summarizeBy": "none"
          },
          {
            "name": "teu",
            "dataType": "double",
            "sourceColumn": "teu",
            "summarizeBy": "none"
          },
          {
            "name": "cbm",
            "dataType": "double",
            "sourceColumn": "cbm",
            "summarizeBy": "none"
          },
          {
            "name": "chargeable_weight_kg",
            "dataType": "double",
            "sourceColumn": "chargeable_weight_kg",
            "summarizeBy": "none"
          },
          {
            "name": "net_revenue_usd",
            "dataType": "double",
            "sourceColumn": "net_revenue_usd",
            "summarizeBy": "none"
          },
          {
            "name": "freight_cost_usd",
            "dataType": "double",
            "sourceColumn": "freight_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "fuel_cost_usd",
            "dataType": "double",
            "sourceColumn": "fuel_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "handling_cost_usd",
            "dataType": "double",
            "sourceColumn": "handling_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "customs_cost_usd",
            "dataType": "double",
            "sourceColumn": "customs_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "demurrage_cost_usd",
            "dataType": "double",
            "sourceColumn": "demurrage_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "claims_cost_usd",
            "dataType": "double",
            "sourceColumn": "claims_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "last_mile_cost_usd",
            "dataType": "double",
            "sourceColumn": "last_mile_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "total_cost_usd",
            "dataType": "double",
            "sourceColumn": "total_cost_usd",
            "summarizeBy": "none"
          },
          {
            "name": "gross_profit_usd",
            "dataType": "double",
            "sourceColumn": "gross_profit_usd",
            "summarizeBy": "none"
          },
          {
            "name": "target_margin_pct",
            "dataType": "double",
            "sourceColumn": "target_margin_pct",
            "summarizeBy": "none"
          },
          {
            "name": "on_time_count",
            "dataType": "int64",
            "sourceColumn": "on_time_count",
            "summarizeBy": "none"
          },
          {
            "name": "delayed_count",
            "dataType": "int64",
            "sourceColumn": "delayed_count",
            "summarizeBy": "none"
          },
          {
            "name": "utilization_pct",
            "dataType": "double",
            "sourceColumn": "utilization_pct",
            "summarizeBy": "none"
          },
          {
            "name": "is_synthetic",
            "dataType": "boolean",
            "sourceColumn": "is_synthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactShipmentProfitability-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/fact_shipment_profitability.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"customer_id\", type text},\n        {\"lane_id\", type text},\n        {\"service_id\", type text},\n        {\"office_id\", type text},\n        {\"carrier_id\", type text},\n        {\"shipment_count\", Int64.Type},\n        {\"teu\", type number},\n        {\"cbm\", type number},\n        {\"chargeable_weight_kg\", type number},\n        {\"net_revenue_usd\", type number},\n        {\"freight_cost_usd\", type number},\n        {\"fuel_cost_usd\", type number},\n        {\"handling_cost_usd\", type number},\n        {\"customs_cost_usd\", type number},\n        {\"demurrage_cost_usd\", type number},\n        {\"claims_cost_usd\", type number},\n        {\"last_mile_cost_usd\", type number},\n        {\"total_cost_usd\", type number},\n        {\"gross_profit_usd\", type number},\n        {\"target_margin_pct\", type number},\n        {\"on_time_count\", Int64.Type},\n        {\"delayed_count\", Int64.Type},\n        {\"utilization_pct\", type number},\n        {\"is_synthetic\", type logical}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCostDriverBridge",
        "columns": [
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "dataType": "string",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "lane_id",
            "dataType": "string",
            "sourceColumn": "lane_id",
            "summarizeBy": "none"
          },
          {
            "name": "driver",
            "dataType": "string",
            "sourceColumn": "driver",
            "summarizeBy": "none"
          },
          {
            "name": "driver_sort",
            "dataType": "int64",
            "sourceColumn": "driver_sort",
            "summarizeBy": "none"
          },
          {
            "name": "amount_usd",
            "dataType": "double",
            "sourceColumn": "amount_usd",
            "summarizeBy": "none"
          },
          {
            "name": "driver_type",
            "dataType": "string",
            "sourceColumn": "driver_type",
            "summarizeBy": "none"
          },
          {
            "name": "is_synthetic",
            "dataType": "boolean",
            "sourceColumn": "is_synthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactCostDriverBridge-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/fact_cost_driver_bridge.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"date_id\", type text},\n        {\"customer_id\", type text},\n        {\"lane_id\", type text},\n        {\"driver\", type text},\n        {\"driver_sort\", Int64.Type},\n        {\"amount_usd\", type number},\n        {\"driver_type\", type text},\n        {\"is_synthetic\", type logical}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "FactActionQueue",
        "columns": [
          {
            "name": "action_id",
            "dataType": "string",
            "sourceColumn": "action_id",
            "summarizeBy": "none"
          },
          {
            "name": "date_id",
            "dataType": "string",
            "sourceColumn": "date_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "dataType": "string",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "lane_id",
            "dataType": "string",
            "sourceColumn": "lane_id",
            "summarizeBy": "none"
          },
          {
            "name": "office_id",
            "dataType": "string",
            "sourceColumn": "office_id",
            "summarizeBy": "none"
          },
          {
            "name": "issue_type",
            "dataType": "string",
            "sourceColumn": "issue_type",
            "summarizeBy": "none"
          },
          {
            "name": "priority",
            "dataType": "string",
            "sourceColumn": "priority",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "owner",
            "dataType": "string",
            "sourceColumn": "owner",
            "summarizeBy": "none"
          },
          {
            "name": "risk_value_usd",
            "dataType": "double",
            "sourceColumn": "risk_value_usd",
            "summarizeBy": "none"
          },
          {
            "name": "target_margin_recovery_usd",
            "dataType": "double",
            "sourceColumn": "target_margin_recovery_usd",
            "summarizeBy": "none"
          },
          {
            "name": "recommended_action",
            "dataType": "string",
            "sourceColumn": "recommended_action",
            "summarizeBy": "none"
          },
          {
            "name": "due_date",
            "dataType": "dateTime",
            "sourceColumn": "due_date",
            "summarizeBy": "none"
          },
          {
            "name": "is_synthetic",
            "dataType": "boolean",
            "sourceColumn": "is_synthetic",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "FactActionQueue-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 17 - Logistics Trade Lane Profitability/data/prepared/fact_action_queue.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {",
                "        {\"action_id\", type text},\n        {\"date_id\", type text},\n        {\"customer_id\", type text},\n        {\"lane_id\", type text},\n        {\"office_id\", type text},\n        {\"issue_type\", type text},\n        {\"priority\", type text},\n        {\"status\", type text},\n        {\"owner\", type text},\n        {\"risk_value_usd\", type number},\n        {\"target_margin_recovery_usd\", type number},\n        {\"recommended_action\", type text},\n        {\"due_date\", type date},\n        {\"is_synthetic\", type logical}",
                "    }, \"en-US\")",
                "in",
                "    TypedColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "KPI Measures",
        "columns": [
          {
            "name": "Measure Group",
            "dataType": "string",
            "sourceColumn": "Measure Group",
            "isHidden": true,
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "KPI Measures-Import",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #table(type table [Measure Group = text], {{\"Logistics Trade Lane Profitability\"}})",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Net Revenue",
            "expression": "SUM(FactShipmentProfitability[net_revenue_usd])",
            "formatString": "$#,0",
            "description": "Total billed revenue after rebates and credits."
          },
          {
            "name": "Freight Cost",
            "expression": "SUM(FactShipmentProfitability[freight_cost_usd])",
            "formatString": "$#,0",
            "description": "Carrier buy rate and main freight cost."
          },
          {
            "name": "Fuel Cost",
            "expression": "SUM(FactShipmentProfitability[fuel_cost_usd])",
            "formatString": "$#,0",
            "description": "Fuel surcharge cost charged by carriers."
          },
          {
            "name": "Demurrage Cost",
            "expression": "SUM(FactShipmentProfitability[demurrage_cost_usd])",
            "formatString": "$#,0",
            "description": "Demurrage and detention leakage."
          },
          {
            "name": "Claims Cost",
            "expression": "SUM(FactShipmentProfitability[claims_cost_usd])",
            "formatString": "$#,0",
            "description": "Claims and service failure cost."
          },
          {
            "name": "Total Cost",
            "expression": "SUM(FactShipmentProfitability[total_cost_usd])",
            "formatString": "$#,0",
            "description": "Total cost-to-serve for shipments."
          },
          {
            "name": "Gross Profit",
            "expression": "SUM(FactShipmentProfitability[gross_profit_usd])",
            "formatString": "$#,0",
            "description": "Net revenue less total shipment cost."
          },
          {
            "name": "GP Margin %",
            "expression": "DIVIDE([Gross Profit], [Net Revenue])",
            "formatString": "0.0%",
            "description": "Gross profit divided by net revenue."
          },
          {
            "name": "Shipment Count",
            "expression": "SUM(FactShipmentProfitability[shipment_count])",
            "formatString": "#,0",
            "description": "Total shipment records weighted by shipment count."
          },
          {
            "name": "TEU",
            "expression": "SUM(FactShipmentProfitability[teu])",
            "formatString": "#,0.0",
            "description": "Twenty-foot equivalent units for ocean lanes."
          },
          {
            "name": "CBM",
            "expression": "SUM(FactShipmentProfitability[cbm])",
            "formatString": "#,0.0",
            "description": "Cubic meter volume handled."
          },
          {
            "name": "Revenue per Shipment",
            "expression": "DIVIDE([Net Revenue], [Shipment Count])",
            "formatString": "$#,0",
            "description": "Net revenue per shipment."
          },
          {
            "name": "Cost per Shipment",
            "expression": "DIVIDE([Total Cost], [Shipment Count])",
            "formatString": "$#,0",
            "description": "Cost-to-serve per shipment."
          },
          {
            "name": "Target Gross Profit",
            "expression": "SUMX(FactShipmentProfitability, FactShipmentProfitability[net_revenue_usd] * FactShipmentProfitability[target_margin_pct])",
            "formatString": "$#,0",
            "description": "Target gross profit using lane/service margin targets."
          },
          {
            "name": "Margin Gap vs Target",
            "expression": "[Gross Profit] - [Target Gross Profit]",
            "formatString": "$#,0",
            "description": "Actual gross profit less target gross profit."
          },
          {
            "name": "Target Margin %",
            "expression": "DIVIDE([Target Gross Profit], [Net Revenue])",
            "formatString": "0.0%",
            "description": "Weighted target margin for selected scope."
          },
          {
            "name": "Margin Gap %",
            "expression": "[GP Margin %] - [Target Margin %]",
            "formatString": "0.0%",
            "description": "Percentage point gap versus target margin."
          },
          {
            "name": "On-Time %",
            "expression": "DIVIDE(SUM(FactShipmentProfitability[on_time_count]), [Shipment Count])",
            "formatString": "0.0%",
            "description": "On-time shipments divided by shipments."
          },
          {
            "name": "Utilization %",
            "expression": "AVERAGE(FactShipmentProfitability[utilization_pct])",
            "formatString": "0.0%",
            "description": "Average equipment/consolidation utilization."
          },
          {
            "name": "Negative Margin Shipments",
            "expression": "CALCULATE([Shipment Count], FILTER(FactShipmentProfitability, FactShipmentProfitability[gross_profit_usd] < 0))",
            "formatString": "#,0",
            "description": "Shipments with negative gross profit."
          },
          {
            "name": "Reprice Opportunity",
            "expression": "SUMX(FILTER(FactShipmentProfitability, FactShipmentProfitability[gross_profit_usd] < 0), -FactShipmentProfitability[gross_profit_usd])",
            "formatString": "$#,0",
            "description": "Gross profit required to bring negative shipments to zero."
          },
          {
            "name": "Bridge Amount",
            "expression": "SUM(FactCostDriverBridge[amount_usd])",
            "formatString": "$#,0",
            "description": "Driver bridge amount for margin gap explanation."
          },
          {
            "name": "Open Actions",
            "expression": "CALCULATE(COUNTROWS(FactActionQueue), FILTER(FactActionQueue, FactActionQueue[status] <> \"Closed\"))",
            "formatString": "#,0",
            "description": "Non-closed commercial/procurement/ops actions."
          },
          {
            "name": "Action Risk Value",
            "expression": "SUM(FactActionQueue[risk_value_usd])",
            "formatString": "$#,0",
            "description": "Margin value at risk in the action queue."
          },
          {
            "name": "Recovery Value",
            "expression": "SUM(FactActionQueue[target_margin_recovery_usd])",
            "formatString": "$#,0",
            "description": "Expected recoverable margin from action queue."
          },
          {
            "name": "Latest Net Revenue",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Net Revenue], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1000000)",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M",
            "description": "Latest selected-period net revenue."
          },
          {
            "name": "Latest Gross Profit",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Gross Profit], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1000000)",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M",
            "description": "Latest selected-period gross profit."
          },
          {
            "name": "Latest GP Margin %",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([GP Margin %], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1)",
            "formatString": "0.0%",
            "description": "Latest selected-period gross profit margin."
          },
          {
            "name": "Latest Reprice Opportunity",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Reprice Opportunity], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1000000)",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M",
            "description": "Latest selected-period reprice opportunity."
          },
          {
            "name": "Latest Revenue per Shipment",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Revenue per Shipment], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1)",
            "formatString": "$#,0",
            "description": "Latest selected-period revenue per shipment."
          },
          {
            "name": "Latest Margin Gap vs Target",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Margin Gap vs Target], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1000000)",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M",
            "description": "Latest selected-period gross profit gap versus target."
          },
          {
            "name": "Latest Negative Margin Shipments",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Negative Margin Shipments], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1)",
            "formatString": "#,0",
            "description": "Latest selected-period negative-margin shipment count."
          },
          {
            "name": "Latest On-Time %",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([On-Time %], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1)",
            "formatString": "0.0%",
            "description": "Latest selected-period on-time percentage."
          },
          {
            "name": "Latest Open Actions",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Open Actions], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1)",
            "formatString": "#,0",
            "description": "Open actions in the selected context."
          },
          {
            "name": "Latest Action Risk Value",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Action Risk Value], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1000000)",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M",
            "description": "Action risk value in the selected context."
          },
          {
            "name": "Latest Recovery Value",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Recovery Value], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1000000)",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M",
            "description": "Recovery value in the selected context."
          },
          {
            "name": "Latest Demurrage Cost",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR LatestValue = CALCULATE([Demurrage Cost], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nRETURN DIVIDE(LatestValue, 1000000)",
            "formatString": "$#,0.0M;($#,0.0M);$0.0M",
            "description": "Latest selected-period demurrage cost."
          },
          {
            "name": "Current Lens Primary",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PeriodText = FORMAT(LatestDate, \"MMM yyyy\")\nVAR ModeCount = COUNTROWS(VALUES(DimTradeLane[mode]))\nVAR ModeTotal = CALCULATE(COUNTROWS(VALUES(DimTradeLane[mode])), ALL(DimTradeLane[mode]))\nVAR ModeText = IF(NOT ISFILTERED(DimTradeLane[mode]) || ModeCount = ModeTotal, \"All modes\", IF(ModeCount = 1, SELECTEDVALUE(DimTradeLane[mode]), FORMAT(ModeCount, \"0\") & \" modes\"))\nVAR SegmentCount = COUNTROWS(VALUES(DimCustomer[segment]))\nVAR SegmentTotal = CALCULATE(COUNTROWS(VALUES(DimCustomer[segment])), ALL(DimCustomer[segment]))\nVAR SegmentText = IF(NOT ISFILTERED(DimCustomer[segment]) || SegmentCount = SegmentTotal, \"All seg\", IF(SegmentCount = 1, SELECTEDVALUE(DimCustomer[segment]), FORMAT(SegmentCount, \"0\") & \" seg\"))\nRETURN LEFT(PeriodText & \" | \" & ModeText & \" | \" & SegmentText, 34)",
            "formatString": "",
            "description": "Dynamic first line for the Current Lens panel."
          },
          {
            "name": "Current Lens Secondary",
            "expression": "VAR OriginText = IF(HASONEVALUE(DimTradeLane[origin_country]), SELECTEDVALUE(DimTradeLane[origin_country]), \"All org\")\nVAR DestText = IF(HASONEVALUE(DimTradeLane[destination_country]), SELECTEDVALUE(DimTradeLane[destination_country]), \"All dest\")\nVAR OfficeText = IF(HASONEVALUE(DimOffice[office]), SELECTEDVALUE(DimOffice[office]), \"All offices\")\nRETURN LEFT(OriginText & \" -> \" & DestText & \" | \" & OfficeText, 42)",
            "formatString": "",
            "description": "Dynamic second line for the Current Lens panel."
          },
          {
            "name": "Executive Decision Text",
            "expression": "VAR GapText = FORMAT(DIVIDE([Margin Gap vs Target], 1000000), \"$0.0M;($0.0M);$0.0M\")\nVAR RepriceText = FORMAT(DIVIDE([Reprice Opportunity], 1000000), \"$0.0M\")\nRETURN IF([Margin Gap vs Target] < 0, \"Reprice | Gap \" & GapText, \"Protect mix | GP \" & FORMAT([GP Margin %], \"0.0%\"))",
            "formatString": "",
            "description": "Dynamic action text for the Executive Overview page."
          },
          {
            "name": "Lane Decision Text",
            "expression": "VAR GapPts = FORMAT([Margin Gap %] * 100, \"+0.0;-0.0;0.0\") & \" pt\"\nRETURN IF([Margin Gap vs Target] < 0, \"Fix lanes | Gap \" & GapPts, \"Scale lanes | Target \" & FORMAT([Target Margin %], \"0.0%\"))",
            "formatString": "",
            "description": "Dynamic action text for the Trade Lane Margin page."
          },
          {
            "name": "Cost Decision Text",
            "expression": "\"Risk \" & FORMAT(DIVIDE([Action Risk Value], 1000000), \"$0.0M\") & \" | Rec \" & FORMAT(DIVIDE([Recovery Value], 1000000), \"$0.0M\")",
            "formatString": "",
            "description": "Dynamic action text for the Cost Drivers & Action Queue page."
          },
          {
            "name": "Current Lens Panel SVG",
            "expression": "VAR LineRaw = [Current Lens Primary]\nVAR LineText = SUBSTITUTE(SUBSTITUTE(LEFT(LineRaw, 38), \"&\", \"and\"), \"%\", \"%25\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='256' height='28' viewBox='0 0 256 28'>\" &\n    \"<rect x='0' y='0' width='256' height='28' fill='%23FFFFFF'/>\" &\n    \"<text x='0' y='9' font-family='Segoe UI' font-size='8.4' font-weight='750' fill='%232563EB'>CURRENT LENS</text>\" &\n    \"<text x='0' y='24' font-family='Segoe UI' font-size='11.4' font-weight='700' fill='%230F172A'>\" & LineText & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "TableEx SVG mini panel for the current filter lens.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Executive Decision Panel SVG",
            "expression": "VAR LineRaw = [Executive Decision Text]\nVAR LineText = SUBSTITUTE(SUBSTITUTE(LEFT(LineRaw, 38), \"&\", \"and\"), \"%\", \"%25\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='244' height='28' viewBox='0 0 244 28'>\" &\n    \"<rect x='0' y='0' width='244' height='28' fill='%23FFFFFF'/>\" &\n    \"<text x='0' y='9' font-family='Segoe UI' font-size='8.4' font-weight='750' fill='%23B45309'>NEXT ACTION</text>\" &\n    \"<text x='0' y='24' font-family='Segoe UI' font-size='11.4' font-weight='700' fill='%230F172A'>\" & LineText & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "TableEx SVG mini panel for executive next action.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Lane Decision Panel SVG",
            "expression": "VAR LineRaw = [Lane Decision Text]\nVAR LineText = SUBSTITUTE(SUBSTITUTE(LEFT(LineRaw, 38), \"&\", \"and\"), \"%\", \"%25\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='244' height='28' viewBox='0 0 244 28'>\" &\n    \"<rect x='0' y='0' width='244' height='28' fill='%23FFFFFF'/>\" &\n    \"<text x='0' y='9' font-family='Segoe UI' font-size='8.4' font-weight='750' fill='%23B45309'>NEXT ACTION</text>\" &\n    \"<text x='0' y='24' font-family='Segoe UI' font-size='11.4' font-weight='700' fill='%230F172A'>\" & LineText & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "TableEx SVG mini panel for lane next action.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Cost Decision Panel SVG",
            "expression": "VAR LineRaw = [Cost Decision Text]\nVAR LineText = SUBSTITUTE(SUBSTITUTE(LEFT(LineRaw, 38), \"&\", \"and\"), \"%\", \"%25\")\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='244' height='28' viewBox='0 0 244 28'>\" &\n    \"<rect x='0' y='0' width='244' height='28' fill='%23FFFFFF'/>\" &\n    \"<text x='0' y='9' font-family='Segoe UI' font-size='8.4' font-weight='750' fill='%23B45309'>NEXT ACTION</text>\" &\n    \"<text x='0' y='24' font-family='Segoe UI' font-size='11.4' font-weight='700' fill='%230F172A'>\" & LineText & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "description": "TableEx SVG mini panel for cost next action.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Net Revenue KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Net Revenue], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Net Revenue], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = SWITCH(TRUE(), ABS(CurrentValue) >= 1000000, FORMAT(DIVIDE(CurrentValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(CurrentValue) >= 1000, FORMAT(DIVIDE(CurrentValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(CurrentValue, \"$#,0;($#,0);$0\"))\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", SWITCH(TRUE(), ABS(PriorValue) >= 1000000, FORMAT(DIVIDE(PriorValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(PriorValue) >= 1000, FORMAT(DIVIDE(PriorValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(PriorValue, \"$#,0;($#,0);$0\")))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue >= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Net Revenue])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue >= FirstValue, \"%232563EB\", \"%23DC2626\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%232563EB' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%232563EB' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Net Revenue</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%232563EB'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%232563EB' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for net revenue.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Gross Profit KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Gross Profit], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Gross Profit], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = SWITCH(TRUE(), ABS(CurrentValue) >= 1000000, FORMAT(DIVIDE(CurrentValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(CurrentValue) >= 1000, FORMAT(DIVIDE(CurrentValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(CurrentValue, \"$#,0;($#,0);$0\"))\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", SWITCH(TRUE(), ABS(PriorValue) >= 1000000, FORMAT(DIVIDE(PriorValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(PriorValue) >= 1000, FORMAT(DIVIDE(PriorValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(PriorValue, \"$#,0;($#,0);$0\")))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue >= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Gross Profit])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue >= FirstValue, \"%2315803D\", \"%23DC2626\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%2315803D' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%2315803D' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Gross Profit</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%2315803D'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%2315803D' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for gross profit.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "GP Margin KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([GP Margin %], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([GP Margin %], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0%\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0%\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue * 100, \"+0.0;-0.0;0.0\") & \" pt\")\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue >= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([GP Margin %])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue >= FirstValue, \"%230F766E\", \"%23DC2626\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%230F766E' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%230F766E' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>GP Margin</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%230F766E'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%230F766E' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for gross profit margin.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Reprice Opportunity KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Reprice Opportunity], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Reprice Opportunity], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = SWITCH(TRUE(), ABS(CurrentValue) >= 1000000, FORMAT(DIVIDE(CurrentValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(CurrentValue) >= 1000, FORMAT(DIVIDE(CurrentValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(CurrentValue, \"$#,0;($#,0);$0\"))\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", SWITCH(TRUE(), ABS(PriorValue) >= 1000000, FORMAT(DIVIDE(PriorValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(PriorValue) >= 1000, FORMAT(DIVIDE(PriorValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(PriorValue, \"$#,0;($#,0);$0\")))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue <= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Reprice Opportunity])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23DC2626\", \"%23DC2626\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%23DC2626' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%23DC2626' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Reprice Opp.</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%23DC2626'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23DC2626' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for reprice opportunity.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Revenue per Shipment KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Revenue per Shipment], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Revenue per Shipment], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"$#,0\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"$#,0\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue >= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Revenue per Shipment])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue >= FirstValue, \"%232563EB\", \"%23DC2626\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%232563EB' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%232563EB' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Rev / Shipment</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%232563EB'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%232563EB' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for revenue per shipment.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Margin Gap KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Margin Gap vs Target], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Margin Gap vs Target], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = SWITCH(TRUE(), ABS(CurrentValue) >= 1000000, FORMAT(DIVIDE(CurrentValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(CurrentValue) >= 1000, FORMAT(DIVIDE(CurrentValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(CurrentValue, \"$#,0;($#,0);$0\"))\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", SWITCH(TRUE(), ABS(PriorValue) >= 1000000, FORMAT(DIVIDE(PriorValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(PriorValue) >= 1000, FORMAT(DIVIDE(PriorValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(PriorValue, \"$#,0;($#,0);$0\")))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue >= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Margin Gap vs Target])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue >= FirstValue, \"%23DC2626\", \"%23DC2626\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%23DC2626' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%23DC2626' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Margin Gap</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%23DC2626'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23DC2626' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for margin gap versus target.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Negative Margin Shipments KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Negative Margin Shipments], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Negative Margin Shipments], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"#,0\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"#,0\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue, \"+#,0;-#,0;0\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue <= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Negative Margin Shipments])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23DC2626\", \"%23DC2626\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%23DC2626' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%23DC2626' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Neg. Margin</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%23DC2626'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23DC2626' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for negative-margin shipments.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "On-Time KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([On-Time %], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([On-Time %], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"0.0%\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"0.0%\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue * 100, \"+0.0;-0.0;0.0\") & \" pt\")\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue >= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([On-Time %])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue >= FirstValue, \"%2315803D\", \"%23DC2626\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%2315803D' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%2315803D' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>On-Time</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%2315803D'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%2315803D' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for on-time performance.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Open Actions KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Open Actions], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Open Actions], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = FORMAT(DIVIDE(CurrentValue, 1), \"#,0\")\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", FORMAT(DIVIDE(PriorValue, 1), \"#,0\"))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(ChangeValue, \"+#,0;-#,0;0\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue <= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Open Actions])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23B45309\", \"%23DC2626\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%23B45309' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%23B45309' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Open Actions</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%23B45309'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B45309' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for open actions.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Action Risk KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Action Risk Value], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Action Risk Value], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = SWITCH(TRUE(), ABS(CurrentValue) >= 1000000, FORMAT(DIVIDE(CurrentValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(CurrentValue) >= 1000, FORMAT(DIVIDE(CurrentValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(CurrentValue, \"$#,0;($#,0);$0\"))\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", SWITCH(TRUE(), ABS(PriorValue) >= 1000000, FORMAT(DIVIDE(PriorValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(PriorValue) >= 1000, FORMAT(DIVIDE(PriorValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(PriorValue, \"$#,0;($#,0);$0\")))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue <= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Action Risk Value])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23DC2626\", \"%23DC2626\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%23DC2626' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%23DC2626' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Action Risk</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%23DC2626'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23DC2626' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for action risk value.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Recovery KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Recovery Value], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Recovery Value], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = SWITCH(TRUE(), ABS(CurrentValue) >= 1000000, FORMAT(DIVIDE(CurrentValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(CurrentValue) >= 1000, FORMAT(DIVIDE(CurrentValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(CurrentValue, \"$#,0;($#,0);$0\"))\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", SWITCH(TRUE(), ABS(PriorValue) >= 1000000, FORMAT(DIVIDE(PriorValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(PriorValue) >= 1000, FORMAT(DIVIDE(PriorValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(PriorValue, \"$#,0;($#,0);$0\")))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue >= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue >= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Recovery Value])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue >= FirstValue, \"%2315803D\", \"%23DC2626\")\nVAR BandColor = IF(LastValue >= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%2315803D' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%2315803D' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Recovery</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%2315803D'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%2315803D' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for recovery value.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Demurrage KPI Card SVG",
            "expression": "VAR LatestDate = MAXX(ALLSELECTED(DimDate), DimDate[date])\nVAR PriorDate = EDATE(LatestDate, -12)\nVAR CurrentValue = CALCULATE([Demurrage Cost], FILTER(ALL(DimDate), DimDate[date] = LatestDate))\nVAR PriorValue = CALCULATE([Demurrage Cost], FILTER(ALL(DimDate), DimDate[date] = PriorDate))\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE(ChangeValue, ABS(PriorValue))\nVAR ValueTextRaw = SWITCH(TRUE(), ABS(CurrentValue) >= 1000000, FORMAT(DIVIDE(CurrentValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(CurrentValue) >= 1000, FORMAT(DIVIDE(CurrentValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(CurrentValue, \"$#,0;($#,0);$0\"))\nVAR PYTextRaw = IF(ISBLANK(PriorValue), \"n/a\", SWITCH(TRUE(), ABS(PriorValue) >= 1000000, FORMAT(DIVIDE(PriorValue, 1000000), \"$0.0M;($0.0M);$0.0M\"), ABS(PriorValue) >= 1000, FORMAT(DIVIDE(PriorValue, 1000), \"$0.0K;($0.0K);$0.0K\"), FORMAT(PriorValue, \"$#,0;($#,0);$0\")))\nVAR YoYTextRaw = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"n/a\", FORMAT(RateValue, \"+0.0%;-0.0%;0.0%\"))\nVAR ValueText = SUBSTITUTE(ValueTextRaw, \"%\", \"%25\")\nVAR PYText = SUBSTITUTE(PYTextRaw, \"%\", \"%25\")\nVAR YoYText = SUBSTITUTE(YoYTextRaw, \"%\", \"%25\")\nVAR YoYColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusText = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"New\", IF(ChangeValue <= 0, \"On track\", \"Watch\"))\nVAR StatusFill = \"%23F8FAFC\"\nVAR StatusBorder = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23CBD5E1\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR StatusColor = IF(ISBLANK(CurrentValue) || ISBLANK(PriorValue), \"%23647569\", IF(ChangeValue <= 0, \"%2315803D\", \"%23DC2626\"))\nVAR MonthTable =\n    ADDCOLUMNS(\n        FILTER(ALLSELECTED(DimDate), DimDate[date] <= LatestDate),\n        \"__Value\", CALCULATE([Demurrage Cost])\n    )\nVAR CleanTable = FILTER(MonthTable, NOT ISBLANK([__Value]))\nVAR RowCount = COUNTROWS(CleanTable)\nVAR MinValue = MINX(CleanTable, [__Value])\nVAR MaxValue = MAXX(CleanTable, [__Value])\nVAR FirstValue = MINX(TOPN(1, CleanTable, DimDate[date], ASC), [__Value])\nVAR LastValue = MINX(TOPN(1, CleanTable, DimDate[date], DESC), [__Value])\nVAR StartYValue = 94 - DIVIDE(FirstValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR EndYValue = 94 - DIVIDE(LastValue - MinValue, MaxValue - MinValue, 0.5) * 52\nVAR TrendColor = IF(LastValue <= FirstValue, \"%23B45309\", \"%23DC2626\")\nVAR BandColor = IF(LastValue <= FirstValue, \"%23E0F2FE\", \"%23FEE2E2\")\nVAR LinePoints =\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN FORMAT(XValue, \"0.0\") & \",\" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    )\nVAR AreaPath =\n    \"M176 102 \" &\n    CONCATENATEX(\n        CleanTable,\n        VAR RankValue = RANKX(CleanTable, DimDate[date], , ASC, DENSE) - 1\n        VAR XValue = 176 + DIVIDE(RankValue, MAX(1, RowCount - 1), 0) * 100\n        VAR YValue = 94 - DIVIDE([__Value] - MinValue, MaxValue - MinValue, 0.5) * 52\n        RETURN \"L\" & FORMAT(XValue, \"0.0\") & \" \" & FORMAT(YValue, \"0.0\"),\n        \" \",\n        DimDate[date],\n        ASC\n    ) & \" L276 102 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='296' height='142' viewBox='0 0 296 142'>\" &\n    \"<defs><filter id='innerTableShadow' x='-4' y='-4' width='304' height='150' filterUnits='userSpaceOnUse'><feDropShadow dx='0' dy='1.4' stdDeviation='1.4' flood-color='%23000000' flood-opacity='0.10'/></filter><clipPath id='sparkClip'><rect x='172' y='35' width='108' height='70' rx='8'/></clipPath></defs>\" &\n    \"<rect x='0' y='0' width='296' height='142' fill='%23FFFFFF'/>\" &\n    \"<rect x='7' y='6' width='282' height='130' rx='10' fill='%23FFFFFF' filter='url(%23innerTableShadow)'/>\" &\n    \"<rect x='9' y='8' width='278' height='126' rx='9' fill='none' stroke='%23CBD5E1' stroke-width='1' opacity='1'/>\" &\n    \"<rect x='14' y='12' width='146' height='5' rx='2.5' fill='%23B45309' opacity='0.92'/>\" &\n    \"<rect x='14' y='30' width='16' height='16' rx='4.5' fill='%23B45309' opacity='0.95'/>\" &\n    \"<circle cx='22' cy='38' r='2.8' fill='%23FFFFFF' opacity='0.88'/>\" &\n    \"<text x='38' y='44' font-family='Segoe UI' font-size='14' font-weight='700' fill='%230F172A'>Demurrage</text>\" &\n    \"<text x='14' y='94' font-family='Segoe UI' font-size='31' font-weight='750' fill='%23B45309'>\" & ValueText & \"</text>\" &\n    \"<rect x='170' y='35' width='112' height='70' rx='8' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<rect x='176' y='67' width='100' height='14' rx='7' fill='\" & BandColor & \"'/>\" &\n    \"<line x1='176' y1='74' x2='276' y2='74' stroke='%23CBD5E1' stroke-width='1' stroke-dasharray='4 5'/>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B45309' opacity='0.16'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.4' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='176' cy='\" & FORMAT(StartYValue, \"0.0\") & \"' r='3.7' fill='%23FFFFFF' stroke='%2394A3B8' stroke-width='1.4'/>\" &\n    \"<circle cx='276' cy='\" & FORMAT(EndYValue, \"0.0\") & \"' r='4.5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='14' y='112' width='88' height='24' rx='6' fill='%23F1F5F9'/>\" &\n    \"<rect x='108' y='112' width='78' height='24' rx='6' fill='%23F8FAFC' stroke='%23E2E8F0' stroke-width='1'/>\" &\n    \"<rect x='192' y='112' width='90' height='24' rx='6' fill='\" & StatusFill & \"' stroke='\" & StatusBorder & \"' stroke-width='1'/>\" &\n    \"<circle cx='204' cy='124' r='3.5' fill='\" & StatusColor & \"'/>\" &\n    \"<text x='22' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='%23475569'>PY</text>\" &\n    \"<text x='44' y='128' font-family='Segoe UI' font-size='10.8' fill='%23475569'>\" & PYText & \"</text>\" &\n    \"<text x='116' y='128' font-family='Segoe UI' font-size='10.8' font-weight='700' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\" &\n    \"<text x='214' y='128' font-family='Segoe UI' font-size='10.6' font-weight='750' fill='\" & StatusColor & \"'>\" & StatusText & \"</text>\" &\n    \"</svg>\"\nRETURN IF(RowCount = 0, BLANK(), \"data:image/svg+xml;utf8,\" & SVG)",
            "formatString": "",
            "description": "TableEx SVG KPI card for demurrage cost.",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_FactShipmentProfitability_date_id_DimDate_date_id",
        "fromTable": "FactShipmentProfitability",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactCostDriverBridge_date_id_DimDate_date_id",
        "fromTable": "FactCostDriverBridge",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactActionQueue_date_id_DimDate_date_id",
        "fromTable": "FactActionQueue",
        "fromColumn": "date_id",
        "toTable": "DimDate",
        "toColumn": "date_id"
      },
      {
        "name": "rel_FactShipmentProfitability_customer_id_DimCustomer_customer_id",
        "fromTable": "FactShipmentProfitability",
        "fromColumn": "customer_id",
        "toTable": "DimCustomer",
        "toColumn": "customer_id"
      },
      {
        "name": "rel_FactCostDriverBridge_customer_id_DimCustomer_customer_id",
        "fromTable": "FactCostDriverBridge",
        "fromColumn": "customer_id",
        "toTable": "DimCustomer",
        "toColumn": "customer_id"
      },
      {
        "name": "rel_FactActionQueue_customer_id_DimCustomer_customer_id",
        "fromTable": "FactActionQueue",
        "fromColumn": "customer_id",
        "toTable": "DimCustomer",
        "toColumn": "customer_id"
      },
      {
        "name": "rel_FactShipmentProfitability_lane_id_DimTradeLane_lane_id",
        "fromTable": "FactShipmentProfitability",
        "fromColumn": "lane_id",
        "toTable": "DimTradeLane",
        "toColumn": "lane_id"
      },
      {
        "name": "rel_FactCostDriverBridge_lane_id_DimTradeLane_lane_id",
        "fromTable": "FactCostDriverBridge",
        "fromColumn": "lane_id",
        "toTable": "DimTradeLane",
        "toColumn": "lane_id"
      },
      {
        "name": "rel_FactActionQueue_lane_id_DimTradeLane_lane_id",
        "fromTable": "FactActionQueue",
        "fromColumn": "lane_id",
        "toTable": "DimTradeLane",
        "toColumn": "lane_id"
      },
      {
        "name": "rel_FactShipmentProfitability_service_id_DimService_service_id",
        "fromTable": "FactShipmentProfitability",
        "fromColumn": "service_id",
        "toTable": "DimService",
        "toColumn": "service_id"
      },
      {
        "name": "rel_FactShipmentProfitability_office_id_DimOffice_office_id",
        "fromTable": "FactShipmentProfitability",
        "fromColumn": "office_id",
        "toTable": "DimOffice",
        "toColumn": "office_id"
      },
      {
        "name": "rel_FactActionQueue_office_id_DimOffice_office_id",
        "fromTable": "FactActionQueue",
        "fromColumn": "office_id",
        "toTable": "DimOffice",
        "toColumn": "office_id"
      },
      {
        "name": "rel_FactShipmentProfitability_carrier_id_DimCarrier_carrier_id",
        "fromTable": "FactShipmentProfitability",
        "fromColumn": "carrier_id",
        "toTable": "DimCarrier",
        "toColumn": "carrier_id"
      }
    ]
  }
}