{
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_date",
        "lineageTag": "93a235e6-8b62-4573-9249-0d78d0950183",
        "columns": [
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_start",
            "dataType": "dateTime",
            "sourceColumn": "month_start",
            "summarizeBy": "none",
            "formatString": "Long Date"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none"
          },
          {
            "name": "month_no",
            "dataType": "int64",
            "sourceColumn": "month_no",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "month_name",
            "dataType": "string",
            "sourceColumn": "month_name",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_year",
            "dataType": "int64",
            "sourceColumn": "fiscal_year",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "month_index",
            "dataType": "int64",
            "sourceColumn": "month_index",
            "summarizeBy": "none",
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\dim_date.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"date_key\", type text}, {\"month_start\", type date}, {\"year\", Int64.Type}, {\"quarter\", type text}, {\"month_no\", Int64.Type}, {\"month_name\", type text}, {\"fiscal_year\", Int64.Type}, {\"month_index\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_business_unit",
        "lineageTag": "57c37f77-cebd-40a0-aca2-8c222f5ec5b5",
        "columns": [
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "portfolio",
            "dataType": "string",
            "sourceColumn": "portfolio",
            "summarizeBy": "none"
          },
          {
            "name": "annual_revenue_usd",
            "dataType": "double",
            "sourceColumn": "annual_revenue_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_business_unit",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\dim_business_unit.csv\"), [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"business_unit_id\", type text}, {\"business_unit\", type text}, {\"portfolio\", type text}, {\"annual_revenue_usd\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_facility",
        "lineageTag": "648ba499-ed1b-4415-9a0b-e22d0cc79c43",
        "columns": [
          {
            "name": "facility_id",
            "dataType": "string",
            "sourceColumn": "facility_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "facility",
            "dataType": "string",
            "sourceColumn": "facility",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "default_business_unit",
            "dataType": "string",
            "sourceColumn": "default_business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "latitude",
            "dataType": "double",
            "sourceColumn": "latitude",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "longitude",
            "dataType": "double",
            "sourceColumn": "longitude",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_facility",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\dim_facility.csv\"), [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"facility_id\", type text}, {\"facility\", type text}, {\"country\", type text}, {\"region\", type text}, {\"default_business_unit\", type text}, {\"latitude\", type number}, {\"longitude\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_activity",
        "lineageTag": "69a56444-7af7-461a-8571-48f38cc8bf3b",
        "columns": [
          {
            "name": "activity_id",
            "dataType": "string",
            "sourceColumn": "activity_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "activity",
            "dataType": "string",
            "sourceColumn": "activity",
            "summarizeBy": "none"
          },
          {
            "name": "scope",
            "dataType": "string",
            "sourceColumn": "scope",
            "summarizeBy": "none"
          },
          {
            "name": "ghg_category",
            "dataType": "string",
            "sourceColumn": "ghg_category",
            "summarizeBy": "none"
          },
          {
            "name": "activity_unit",
            "dataType": "string",
            "sourceColumn": "activity_unit",
            "summarizeBy": "none"
          },
          {
            "name": "base_emission_factor",
            "dataType": "double",
            "sourceColumn": "base_emission_factor",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_activity",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\dim_activity.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"activity_id\", type text}, {\"activity\", type text}, {\"scope\", type text}, {\"ghg_category\", type text}, {\"activity_unit\", type text}, {\"base_emission_factor\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_supplier",
        "lineageTag": "6856018c-58c3-4fde-8c65-71d593fa6695",
        "columns": [
          {
            "name": "supplier_id",
            "dataType": "string",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "supplier",
            "dataType": "string",
            "sourceColumn": "supplier",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_category",
            "dataType": "string",
            "sourceColumn": "supplier_category",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_country",
            "dataType": "string",
            "sourceColumn": "supplier_country",
            "summarizeBy": "none"
          },
          {
            "name": "carbon_risk_tier",
            "dataType": "string",
            "sourceColumn": "carbon_risk_tier",
            "summarizeBy": "none"
          },
          {
            "name": "target_status",
            "dataType": "string",
            "sourceColumn": "target_status",
            "summarizeBy": "none"
          },
          {
            "name": "data_quality_score",
            "dataType": "double",
            "sourceColumn": "data_quality_score",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_supplier",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\dim_supplier.csv\"), [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"supplier_id\", type text}, {\"supplier\", type text}, {\"supplier_category\", type text}, {\"supplier_country\", type text}, {\"carbon_risk_tier\", type text}, {\"target_status\", type text}, {\"data_quality_score\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_carbon_scenario",
        "lineageTag": "8f2d2c9f-b33d-4df2-9849-e25385b32d9d",
        "columns": [
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "scenario",
            "dataType": "string",
            "sourceColumn": "scenario",
            "summarizeBy": "none"
          },
          {
            "name": "carbon_price_usd_per_t",
            "dataType": "double",
            "sourceColumn": "carbon_price_usd_per_t",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "probability_weight",
            "dataType": "double",
            "sourceColumn": "probability_weight",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_carbon_scenario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\dim_carbon_scenario.csv\"), [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"scenario_id\", type text}, {\"scenario\", type text}, {\"carbon_price_usd_per_t\", type number}, {\"probability_weight\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_emissions",
        "lineageTag": "c97d9228-74ab-4ce8-bb2d-8b913b1fc535",
        "columns": [
          {
            "name": "emission_record_id",
            "dataType": "string",
            "sourceColumn": "emission_record_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "facility_id",
            "dataType": "string",
            "sourceColumn": "facility_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "supplier_id",
            "dataType": "string",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "activity_id",
            "dataType": "string",
            "sourceColumn": "activity_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "scope",
            "dataType": "string",
            "sourceColumn": "scope",
            "summarizeBy": "none"
          },
          {
            "name": "ghg_category",
            "dataType": "string",
            "sourceColumn": "ghg_category",
            "summarizeBy": "none"
          },
          {
            "name": "activity_volume",
            "dataType": "double",
            "sourceColumn": "activity_volume",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "activity_unit",
            "dataType": "string",
            "sourceColumn": "activity_unit",
            "summarizeBy": "none"
          },
          {
            "name": "emission_factor",
            "dataType": "double",
            "sourceColumn": "emission_factor",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "emissions_tco2e",
            "dataType": "double",
            "sourceColumn": "emissions_tco2e",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "spend_usd",
            "dataType": "double",
            "sourceColumn": "spend_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "revenue_usd",
            "dataType": "double",
            "sourceColumn": "revenue_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "data_quality_score",
            "dataType": "double",
            "sourceColumn": "data_quality_score",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_fact_emissions",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\fact_emissions.csv\"), [Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"emission_record_id\", type text}, {\"date_key\", type text}, {\"business_unit_id\", type text}, {\"facility_id\", type text}, {\"supplier_id\", type text}, {\"activity_id\", type text}, {\"scope\", type text}, {\"ghg_category\", type text}, {\"activity_volume\", type number}, {\"activity_unit\", type text}, {\"emission_factor\", type number}, {\"emissions_tco2e\", type number}, {\"spend_usd\", type number}, {\"revenue_usd\", type number}, {\"data_quality_score\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_supplier_month",
        "lineageTag": "ba026d33-c0ba-4fc5-8344-463a5fb50695",
        "columns": [
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_id",
            "dataType": "string",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "supplier",
            "dataType": "string",
            "sourceColumn": "supplier",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_category",
            "dataType": "string",
            "sourceColumn": "supplier_category",
            "summarizeBy": "none"
          },
          {
            "name": "carbon_risk_tier",
            "dataType": "string",
            "sourceColumn": "carbon_risk_tier",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_country",
            "dataType": "string",
            "sourceColumn": "supplier_country",
            "summarizeBy": "none"
          },
          {
            "name": "target_status",
            "dataType": "string",
            "sourceColumn": "target_status",
            "summarizeBy": "none"
          },
          {
            "name": "emissions_tco2e",
            "dataType": "double",
            "sourceColumn": "emissions_tco2e",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "spend_usd",
            "dataType": "double",
            "sourceColumn": "spend_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "supplier_intensity_tco2e_per_musd",
            "dataType": "double",
            "sourceColumn": "supplier_intensity_tco2e_per_musd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "data_quality_score",
            "dataType": "double",
            "sourceColumn": "data_quality_score",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_fact_supplier_month",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\fact_supplier_month.csv\"), [Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"date_key\", type text}, {\"supplier_id\", type text}, {\"supplier\", type text}, {\"supplier_category\", type text}, {\"carbon_risk_tier\", type text}, {\"supplier_country\", type text}, {\"target_status\", type text}, {\"emissions_tco2e\", type number}, {\"spend_usd\", type number}, {\"supplier_intensity_tco2e_per_musd\", type number}, {\"data_quality_score\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_carbon_exposure",
        "lineageTag": "531b2120-afd1-40dd-bb4f-90ea1b07aff9",
        "columns": [
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key",
            "summarizeBy": "none"
          },
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "scenario",
            "dataType": "string",
            "sourceColumn": "scenario",
            "summarizeBy": "none"
          },
          {
            "name": "carbon_price_usd_per_t",
            "dataType": "double",
            "sourceColumn": "carbon_price_usd_per_t",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "emissions_tco2e",
            "dataType": "double",
            "sourceColumn": "emissions_tco2e",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "carbon_cost_usd",
            "dataType": "double",
            "sourceColumn": "carbon_cost_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "probability_weighted_cost_usd",
            "dataType": "double",
            "sourceColumn": "probability_weighted_cost_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          }
        ],
        "partitions": [
          {
            "name": "p_fact_carbon_exposure",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\fact_carbon_exposure.csv\"), [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"date_key\", type text}, {\"scenario_id\", type text}, {\"scenario\", type text}, {\"carbon_price_usd_per_t\", type number}, {\"emissions_tco2e\", type number}, {\"carbon_cost_usd\", type number}, {\"probability_weighted_cost_usd\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_abatement_initiatives",
        "lineageTag": "8b4c4d9c-5caa-4968-8729-675ab26eb24e",
        "columns": [
          {
            "name": "initiative_id",
            "dataType": "string",
            "sourceColumn": "initiative_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "initiative",
            "dataType": "string",
            "sourceColumn": "initiative",
            "summarizeBy": "none"
          },
          {
            "name": "scope",
            "dataType": "string",
            "sourceColumn": "scope",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "implementation_status",
            "dataType": "string",
            "sourceColumn": "implementation_status",
            "summarizeBy": "none"
          },
          {
            "name": "start_year",
            "dataType": "int64",
            "sourceColumn": "start_year",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "capex_usd",
            "dataType": "double",
            "sourceColumn": "capex_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "annual_reduction_tco2e",
            "dataType": "double",
            "sourceColumn": "annual_reduction_tco2e",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "annual_opex_savings_usd",
            "dataType": "double",
            "sourceColumn": "annual_opex_savings_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "avoided_carbon_cost_usd_at_90",
            "dataType": "double",
            "sourceColumn": "avoided_carbon_cost_usd_at_90",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "net_annual_benefit_usd_at_90",
            "dataType": "double",
            "sourceColumn": "net_annual_benefit_usd_at_90",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "payback_years_at_90",
            "dataType": "double",
            "sourceColumn": "payback_years_at_90",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "roi_at_90",
            "dataType": "double",
            "sourceColumn": "roi_at_90",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          },
          {
            "name": "macc_usd_per_tco2e",
            "dataType": "double",
            "sourceColumn": "macc_usd_per_tco2e",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          }
        ],
        "partitions": [
          {
            "name": "p_fact_abatement_initiatives",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 18 - ESG Carbon Finance\\\\data\\\\prepared\\\\fact_abatement_initiatives.csv\"), [Delimiter=\",\", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"initiative_id\", type text}, {\"initiative\", type text}, {\"scope\", type text}, {\"business_unit\", type text}, {\"implementation_status\", type text}, {\"start_year\", Int64.Type}, {\"capex_usd\", type number}, {\"annual_reduction_tco2e\", type number}, {\"annual_opex_savings_usd\", type number}, {\"avoided_carbon_cost_usd_at_90\", type number}, {\"net_annual_benefit_usd_at_90\", type number}, {\"payback_years_at_90\", type number}, {\"roi_at_90\", type number}, {\"macc_usd_per_tco2e\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "KPI_Measures",
        "lineageTag": "979b1f0b-403c-401d-a97b-7c42bc85740c",
        "columns": [
          {
            "name": "MeasureName",
            "dataType": "string",
            "sourceColumn": "MeasureName",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "p_KPI_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = #table(type table [MeasureName = text], {{\"KPI\"}}) in Source"
            }
          }
        ],
        "measures": [
          {
            "name": "Total Emissions tCO2e",
            "expression": "SUM ( fact_emissions[emissions_tco2e] )",
            "formatString": "#,0.0",
            "lineageTag": "88e48bf2-957d-44c4-9b24-0f3f017af89a"
          },
          {
            "name": "Scope 1 Emissions tCO2e",
            "expression": "CALCULATE ( [Total Emissions tCO2e], fact_emissions[scope] = \"Scope 1\" )",
            "formatString": "#,0.0",
            "lineageTag": "9aad4c4b-ff06-45f5-9b77-289db0eaaeb2"
          },
          {
            "name": "Scope 2 Emissions tCO2e",
            "expression": "CALCULATE ( [Total Emissions tCO2e], fact_emissions[scope] = \"Scope 2\" )",
            "formatString": "#,0.0",
            "lineageTag": "f055013d-340e-4f99-bda8-7a4b571fa648"
          },
          {
            "name": "Scope 3 Emissions tCO2e",
            "expression": "CALCULATE ( [Total Emissions tCO2e], fact_emissions[scope] = \"Scope 3\" )",
            "formatString": "#,0.0",
            "lineageTag": "9cf25fe4-6ade-4ad3-8d05-cd9c5ae2479b"
          },
          {
            "name": "Total Spend USD",
            "expression": "SUM ( fact_emissions[spend_usd] )",
            "formatString": "$#,0",
            "lineageTag": "6da97efc-e7d3-47f2-aaf7-22893f35f9a0"
          },
          {
            "name": "Revenue USD",
            "expression": "SUM ( fact_emissions[revenue_usd] )",
            "formatString": "$#,0",
            "lineageTag": "1b6f67f7-ad30-451a-a7ba-528612123db8"
          },
          {
            "name": "Emissions Intensity tCO2e per $M Revenue",
            "expression": "DIVIDE ( [Total Emissions tCO2e], [Revenue USD] ) * 1000000",
            "formatString": "#,0.0",
            "lineageTag": "e49bab3f-67b5-4ae6-a534-25816c82b49b"
          },
          {
            "name": "Selected Carbon Price USD/t",
            "expression": "SELECTEDVALUE ( dim_carbon_scenario[carbon_price_usd_per_t], 50 )",
            "formatString": "$#,0",
            "lineageTag": "a70f9019-93b2-4a17-9187-e3942c86b978"
          },
          {
            "name": "Carbon Cost USD",
            "expression": "[Total Emissions tCO2e] * [Selected Carbon Price USD/t]",
            "formatString": "$#,0",
            "lineageTag": "2eb897f6-5615-49c4-970c-5d962fce3748"
          },
          {
            "name": "Scenario Carbon Cost USD",
            "expression": "SUM ( fact_carbon_exposure[carbon_cost_usd] )",
            "formatString": "$#,0",
            "lineageTag": "f9f7fa4e-8070-4aa9-9562-60002f1b1483"
          },
          {
            "name": "Probability Weighted Carbon Cost USD",
            "expression": "SUM ( fact_carbon_exposure[probability_weighted_cost_usd] )",
            "formatString": "$#,0",
            "lineageTag": "a9e2fe6f-23d4-4c55-8f2b-00bc6b00d555"
          },
          {
            "name": "Stress Scenario Carbon Cost USD",
            "expression": "CALCULATE ( [Scenario Carbon Cost USD], dim_carbon_scenario[scenario] = \"Stress price shock\" )",
            "formatString": "$#,0",
            "lineageTag": "a7eff2df-1e6b-436f-bf3d-56391f727622"
          },
          {
            "name": "Supplier Emissions tCO2e",
            "expression": "SUM ( fact_supplier_month[emissions_tco2e] )",
            "formatString": "#,0.0",
            "lineageTag": "5e5d3700-5b6e-46df-9cb1-1c5f5e96aa13"
          },
          {
            "name": "Supplier Spend USD",
            "expression": "SUM ( fact_supplier_month[spend_usd] )",
            "formatString": "$#,0",
            "lineageTag": "17c154c3-0b7b-4555-a2ca-2c64985bf19e"
          },
          {
            "name": "Supplier Intensity tCO2e per $M Spend",
            "expression": "DIVIDE ( [Supplier Emissions tCO2e], [Supplier Spend USD] ) * 1000000",
            "formatString": "#,0.0",
            "lineageTag": "af4a7aed-d428-4805-9e4f-444bb4c86929"
          },
          {
            "name": "High Risk Supplier Emissions tCO2e",
            "expression": "CALCULATE ( [Supplier Emissions tCO2e], fact_supplier_month[carbon_risk_tier] = \"High\" )",
            "formatString": "#,0.0",
            "lineageTag": "a97eb67c-1878-4f8a-905f-4a6792c2cde4"
          },
          {
            "name": "Average Data Quality Score",
            "expression": "AVERAGE ( fact_supplier_month[data_quality_score] )",
            "formatString": "0.0%",
            "lineageTag": "bb0ddcba-e61e-4626-8f54-80cf2afb0a3d"
          },
          {
            "name": "Abatement Annual Reduction tCO2e",
            "expression": "SUM ( fact_abatement_initiatives[annual_reduction_tco2e] )",
            "formatString": "#,0",
            "lineageTag": "2e3709b2-897a-471c-b162-a762919f9d21"
          },
          {
            "name": "Abatement Capex USD",
            "expression": "SUM ( fact_abatement_initiatives[capex_usd] )",
            "formatString": "$#,0",
            "lineageTag": "111697f4-7874-46bd-a61a-4dc5fe28e95e"
          },
          {
            "name": "Planned Abatement Capex USD",
            "expression": "CALCULATE ( [Abatement Capex USD], fact_abatement_initiatives[implementation_status] = \"Planned\" )",
            "formatString": "$#,0",
            "lineageTag": "aeade363-c76a-41ff-b78e-2dca8933942d"
          },
          {
            "name": "Committed and In Flight Reduction tCO2e",
            "expression": "CALCULATE ( [Abatement Annual Reduction tCO2e], fact_abatement_initiatives[implementation_status] IN { \"Committed\", \"In flight\", \"Implemented\" } )",
            "formatString": "#,0",
            "lineageTag": "48930a67-07f2-407a-8e9c-02882d8fcba4"
          },
          {
            "name": "Avoided Carbon Cost USD at Selected Price",
            "expression": "[Abatement Annual Reduction tCO2e] * [Selected Carbon Price USD/t]",
            "formatString": "$#,0",
            "lineageTag": "63c61bf2-8e4b-4db3-8822-23fe9c7f8aea"
          },
          {
            "name": "Abatement Annual Benefit USD",
            "expression": "SUM ( fact_abatement_initiatives[annual_opex_savings_usd] ) + [Avoided Carbon Cost USD at Selected Price]",
            "formatString": "$#,0",
            "lineageTag": "d2245c91-24c6-44bb-a903-de041de13d16"
          },
          {
            "name": "Abatement ROI",
            "expression": "DIVIDE ( [Abatement Annual Benefit USD], [Abatement Capex USD] )",
            "formatString": "0.0%",
            "lineageTag": "744ff27c-db51-4624-a587-20a1ce0b763a"
          },
          {
            "name": "Payback Years",
            "expression": "DIVIDE ( [Abatement Capex USD], [Abatement Annual Benefit USD] )",
            "formatString": "0.0",
            "lineageTag": "b5b63ce5-e7d1-417f-86b2-4bca171d5f3e"
          },
          {
            "name": "MACC USD per tCO2e",
            "expression": "DIVIDE ( DIVIDE ( [Abatement Capex USD], 7 ) - SUM ( fact_abatement_initiatives[annual_opex_savings_usd] ), [Abatement Annual Reduction tCO2e] )",
            "formatString": "$#,0.0",
            "lineageTag": "89ce03ab-c12c-4fe9-8932-9a3fa1c187b9"
          },
          {
            "name": "Latest Month Emissions tCO2e",
            "expression": "VAR LatestMonth = MAX ( dim_date[date_key] ) RETURN CALCULATE ( [Total Emissions tCO2e], dim_date[date_key] = LatestMonth )",
            "formatString": "#,0.0",
            "lineageTag": "5a0c3929-de30-4b79-8e4d-9a7fc74224cd"
          },
          {
            "name": "YoY Emissions Change %",
            "expression": "VAR CurrentEmissions = [Total Emissions tCO2e] VAR PriorEmissions = CALCULATE ( [Total Emissions tCO2e], DATEADD ( dim_date[month_start], -1, YEAR ) ) RETURN DIVIDE ( CurrentEmissions - PriorEmissions, PriorEmissions )",
            "formatString": "0.0%",
            "lineageTag": "119ea95e-268d-4d08-951d-a51620fe7d74"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Rel_fact_emissions_date_key_dim_date_date_key",
        "fromTable": "fact_emissions",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date_key"
      },
      {
        "name": "Rel_fact_supplier_month_date_key_dim_date_date_key",
        "fromTable": "fact_supplier_month",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date_key"
      },
      {
        "name": "Rel_fact_carbon_exposure_date_key_dim_date_date_key",
        "fromTable": "fact_carbon_exposure",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date_key"
      },
      {
        "name": "Rel_fact_emissions_business_unit_id_dim_business_unit_business_unit_id",
        "fromTable": "fact_emissions",
        "fromColumn": "business_unit_id",
        "toTable": "dim_business_unit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "Rel_fact_emissions_facility_id_dim_facility_facility_id",
        "fromTable": "fact_emissions",
        "fromColumn": "facility_id",
        "toTable": "dim_facility",
        "toColumn": "facility_id"
      },
      {
        "name": "Rel_fact_emissions_activity_id_dim_activity_activity_id",
        "fromTable": "fact_emissions",
        "fromColumn": "activity_id",
        "toTable": "dim_activity",
        "toColumn": "activity_id"
      },
      {
        "name": "Rel_fact_emissions_supplier_id_dim_supplier_supplier_id",
        "fromTable": "fact_emissions",
        "fromColumn": "supplier_id",
        "toTable": "dim_supplier",
        "toColumn": "supplier_id"
      },
      {
        "name": "Rel_fact_supplier_month_supplier_id_dim_supplier_supplier_id",
        "fromTable": "fact_supplier_month",
        "fromColumn": "supplier_id",
        "toTable": "dim_supplier",
        "toColumn": "supplier_id"
      },
      {
        "name": "Rel_fact_carbon_exposure_scenario_id_dim_carbon_scenario_scenario_id",
        "fromTable": "fact_carbon_exposure",
        "fromColumn": "scenario_id",
        "toTable": "dim_carbon_scenario",
        "toColumn": "scenario_id"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}