{
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_date",
        "lineageTag": "83ade245-3456-45aa-878a-17771b40e366",
        "columns": [
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_start",
            "dataType": "dateTime",
            "sourceColumn": "month_start",
            "summarizeBy": "none",
            "formatString": "Long Date"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none"
          },
          {
            "name": "month_no",
            "dataType": "int64",
            "sourceColumn": "month_no",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "month_name",
            "dataType": "string",
            "sourceColumn": "month_name",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_year",
            "dataType": "int64",
            "sourceColumn": "fiscal_year",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "month_index",
            "dataType": "int64",
            "sourceColumn": "month_index",
            "summarizeBy": "none",
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\dim_date.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"date_key\", type text}, {\"month_start\", type date}, {\"year\", Int64.Type}, {\"quarter\", type text}, {\"month_no\", Int64.Type}, {\"month_name\", type text}, {\"fiscal_year\", Int64.Type}, {\"month_index\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_business_unit",
        "lineageTag": "742e645b-f126-4d5f-b19e-e63248521ecc",
        "columns": [
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "portfolio",
            "dataType": "string",
            "sourceColumn": "portfolio",
            "summarizeBy": "none"
          },
          {
            "name": "annual_revenue_usd",
            "dataType": "double",
            "sourceColumn": "annual_revenue_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_business_unit",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\dim_business_unit.csv\"), [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"business_unit_id\", type text}, {\"business_unit\", type text}, {\"portfolio\", type text}, {\"annual_revenue_usd\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_facility",
        "lineageTag": "c611a83a-60f1-49b0-a76b-2cc3961327da",
        "columns": [
          {
            "name": "facility_id",
            "dataType": "string",
            "sourceColumn": "facility_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "facility",
            "dataType": "string",
            "sourceColumn": "facility",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "default_business_unit",
            "dataType": "string",
            "sourceColumn": "default_business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "latitude",
            "dataType": "double",
            "sourceColumn": "latitude",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "longitude",
            "dataType": "double",
            "sourceColumn": "longitude",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_facility",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\dim_facility.csv\"), [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"facility_id\", type text}, {\"facility\", type text}, {\"country\", type text}, {\"region\", type text}, {\"default_business_unit\", type text}, {\"latitude\", type number}, {\"longitude\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_activity",
        "lineageTag": "d7fe84f7-c7d6-449f-917a-5d1ef1e2fd9f",
        "columns": [
          {
            "name": "activity_id",
            "dataType": "string",
            "sourceColumn": "activity_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "activity",
            "dataType": "string",
            "sourceColumn": "activity",
            "summarizeBy": "none"
          },
          {
            "name": "scope",
            "dataType": "string",
            "sourceColumn": "scope",
            "summarizeBy": "none"
          },
          {
            "name": "ghg_category",
            "dataType": "string",
            "sourceColumn": "ghg_category",
            "summarizeBy": "none"
          },
          {
            "name": "activity_unit",
            "dataType": "string",
            "sourceColumn": "activity_unit",
            "summarizeBy": "none"
          },
          {
            "name": "base_emission_factor",
            "dataType": "double",
            "sourceColumn": "base_emission_factor",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_activity",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\dim_activity.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"activity_id\", type text}, {\"activity\", type text}, {\"scope\", type text}, {\"ghg_category\", type text}, {\"activity_unit\", type text}, {\"base_emission_factor\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_supplier",
        "lineageTag": "3cd8b4fd-e9b5-49d9-b3de-9f5a924ff3ef",
        "columns": [
          {
            "name": "supplier_id",
            "dataType": "string",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "supplier",
            "dataType": "string",
            "sourceColumn": "supplier",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_category",
            "dataType": "string",
            "sourceColumn": "supplier_category",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_country",
            "dataType": "string",
            "sourceColumn": "supplier_country",
            "summarizeBy": "none"
          },
          {
            "name": "carbon_risk_tier",
            "dataType": "string",
            "sourceColumn": "carbon_risk_tier",
            "summarizeBy": "none"
          },
          {
            "name": "target_status",
            "dataType": "string",
            "sourceColumn": "target_status",
            "summarizeBy": "none"
          },
          {
            "name": "data_quality_score",
            "dataType": "double",
            "sourceColumn": "data_quality_score",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_supplier",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\dim_supplier.csv\"), [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"supplier_id\", type text}, {\"supplier\", type text}, {\"supplier_category\", type text}, {\"supplier_country\", type text}, {\"carbon_risk_tier\", type text}, {\"target_status\", type text}, {\"data_quality_score\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_carbon_scenario",
        "lineageTag": "6a901576-3f62-4117-9953-27acf964804a",
        "columns": [
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "scenario",
            "dataType": "string",
            "sourceColumn": "scenario",
            "summarizeBy": "none"
          },
          {
            "name": "carbon_price_usd_per_t",
            "dataType": "double",
            "sourceColumn": "carbon_price_usd_per_t",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "probability_weight",
            "dataType": "double",
            "sourceColumn": "probability_weight",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_dim_carbon_scenario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\dim_carbon_scenario.csv\"), [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"scenario_id\", type text}, {\"scenario\", type text}, {\"carbon_price_usd_per_t\", type number}, {\"probability_weight\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_emissions",
        "lineageTag": "2dab75d2-7ec5-4e94-8c00-15f9059779a9",
        "columns": [
          {
            "name": "emission_record_id",
            "dataType": "string",
            "sourceColumn": "emission_record_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit_id",
            "dataType": "string",
            "sourceColumn": "business_unit_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "facility_id",
            "dataType": "string",
            "sourceColumn": "facility_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "supplier_id",
            "dataType": "string",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "activity_id",
            "dataType": "string",
            "sourceColumn": "activity_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "scope",
            "dataType": "string",
            "sourceColumn": "scope",
            "summarizeBy": "none"
          },
          {
            "name": "ghg_category",
            "dataType": "string",
            "sourceColumn": "ghg_category",
            "summarizeBy": "none"
          },
          {
            "name": "activity_volume",
            "dataType": "double",
            "sourceColumn": "activity_volume",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "activity_unit",
            "dataType": "string",
            "sourceColumn": "activity_unit",
            "summarizeBy": "none"
          },
          {
            "name": "emission_factor",
            "dataType": "double",
            "sourceColumn": "emission_factor",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "emissions_tco2e",
            "dataType": "double",
            "sourceColumn": "emissions_tco2e",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "spend_usd",
            "dataType": "double",
            "sourceColumn": "spend_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "revenue_usd",
            "dataType": "double",
            "sourceColumn": "revenue_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "data_quality_score",
            "dataType": "double",
            "sourceColumn": "data_quality_score",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_fact_emissions",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\fact_emissions.csv\"), [Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"emission_record_id\", type text}, {\"date_key\", type text}, {\"business_unit_id\", type text}, {\"facility_id\", type text}, {\"supplier_id\", type text}, {\"activity_id\", type text}, {\"scope\", type text}, {\"ghg_category\", type text}, {\"activity_volume\", type number}, {\"activity_unit\", type text}, {\"emission_factor\", type number}, {\"emissions_tco2e\", type number}, {\"spend_usd\", type number}, {\"revenue_usd\", type number}, {\"data_quality_score\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_supplier_month",
        "lineageTag": "cfbaa398-4123-44f2-93fa-43d8d933adab",
        "columns": [
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_id",
            "dataType": "string",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "supplier",
            "dataType": "string",
            "sourceColumn": "supplier",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_category",
            "dataType": "string",
            "sourceColumn": "supplier_category",
            "summarizeBy": "none"
          },
          {
            "name": "carbon_risk_tier",
            "dataType": "string",
            "sourceColumn": "carbon_risk_tier",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_country",
            "dataType": "string",
            "sourceColumn": "supplier_country",
            "summarizeBy": "none"
          },
          {
            "name": "target_status",
            "dataType": "string",
            "sourceColumn": "target_status",
            "summarizeBy": "none"
          },
          {
            "name": "emissions_tco2e",
            "dataType": "double",
            "sourceColumn": "emissions_tco2e",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "spend_usd",
            "dataType": "double",
            "sourceColumn": "spend_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "supplier_intensity_tco2e_per_musd",
            "dataType": "double",
            "sourceColumn": "supplier_intensity_tco2e_per_musd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "data_quality_score",
            "dataType": "double",
            "sourceColumn": "data_quality_score",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_fact_supplier_month",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\fact_supplier_month.csv\"), [Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"date_key\", type text}, {\"supplier_id\", type text}, {\"supplier\", type text}, {\"supplier_category\", type text}, {\"carbon_risk_tier\", type text}, {\"supplier_country\", type text}, {\"target_status\", type text}, {\"emissions_tco2e\", type number}, {\"spend_usd\", type number}, {\"supplier_intensity_tco2e_per_musd\", type number}, {\"data_quality_score\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_carbon_exposure",
        "lineageTag": "b917136d-7c28-4a86-ac9f-b74a7a9d061b",
        "columns": [
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key",
            "summarizeBy": "none"
          },
          {
            "name": "scenario_id",
            "dataType": "string",
            "sourceColumn": "scenario_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "scenario",
            "dataType": "string",
            "sourceColumn": "scenario",
            "summarizeBy": "none"
          },
          {
            "name": "carbon_price_usd_per_t",
            "dataType": "double",
            "sourceColumn": "carbon_price_usd_per_t",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "emissions_tco2e",
            "dataType": "double",
            "sourceColumn": "emissions_tco2e",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "carbon_cost_usd",
            "dataType": "double",
            "sourceColumn": "carbon_cost_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "probability_weighted_cost_usd",
            "dataType": "double",
            "sourceColumn": "probability_weighted_cost_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          }
        ],
        "partitions": [
          {
            "name": "p_fact_carbon_exposure",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\fact_carbon_exposure.csv\"), [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"date_key\", type text}, {\"scenario_id\", type text}, {\"scenario\", type text}, {\"carbon_price_usd_per_t\", type number}, {\"emissions_tco2e\", type number}, {\"carbon_cost_usd\", type number}, {\"probability_weighted_cost_usd\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_abatement_initiatives",
        "lineageTag": "5fa7b1fd-5fe0-4aa5-ab36-43d82a2ec235",
        "columns": [
          {
            "name": "initiative_id",
            "dataType": "string",
            "sourceColumn": "initiative_id",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "initiative",
            "dataType": "string",
            "sourceColumn": "initiative",
            "summarizeBy": "none"
          },
          {
            "name": "scope",
            "dataType": "string",
            "sourceColumn": "scope",
            "summarizeBy": "none"
          },
          {
            "name": "business_unit",
            "dataType": "string",
            "sourceColumn": "business_unit",
            "summarizeBy": "none"
          },
          {
            "name": "implementation_status",
            "dataType": "string",
            "sourceColumn": "implementation_status",
            "summarizeBy": "none"
          },
          {
            "name": "start_year",
            "dataType": "int64",
            "sourceColumn": "start_year",
            "summarizeBy": "none",
            "formatString": "0"
          },
          {
            "name": "capex_usd",
            "dataType": "double",
            "sourceColumn": "capex_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "annual_reduction_tco2e",
            "dataType": "double",
            "sourceColumn": "annual_reduction_tco2e",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "annual_opex_savings_usd",
            "dataType": "double",
            "sourceColumn": "annual_opex_savings_usd",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "avoided_carbon_cost_usd_at_90",
            "dataType": "double",
            "sourceColumn": "avoided_carbon_cost_usd_at_90",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "net_annual_benefit_usd_at_90",
            "dataType": "double",
            "sourceColumn": "net_annual_benefit_usd_at_90",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          },
          {
            "name": "payback_years_at_90",
            "dataType": "double",
            "sourceColumn": "payback_years_at_90",
            "summarizeBy": "sum",
            "formatString": "#,0.00"
          },
          {
            "name": "roi_at_90",
            "dataType": "double",
            "sourceColumn": "roi_at_90",
            "summarizeBy": "sum",
            "formatString": "0.0%"
          },
          {
            "name": "macc_usd_per_tco2e",
            "dataType": "double",
            "sourceColumn": "macc_usd_per_tco2e",
            "summarizeBy": "sum",
            "formatString": "$#,0"
          }
        ],
        "partitions": [
          {
            "name": "p_fact_abatement_initiatives",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data\\\\prepared\\\\fact_abatement_initiatives.csv\"), [Delimiter=\",\", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"initiative_id\", type text}, {\"initiative\", type text}, {\"scope\", type text}, {\"business_unit\", type text}, {\"implementation_status\", type text}, {\"start_year\", Int64.Type}, {\"capex_usd\", type number}, {\"annual_reduction_tco2e\", type number}, {\"annual_opex_savings_usd\", type number}, {\"avoided_carbon_cost_usd_at_90\", type number}, {\"net_annual_benefit_usd_at_90\", type number}, {\"payback_years_at_90\", type number}, {\"roi_at_90\", type number}, {\"macc_usd_per_tco2e\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "KPI_Measures",
        "lineageTag": "44105dc8-2ec1-45da-ba55-ac20d8b699c4",
        "columns": [
          {
            "name": "MeasureName",
            "dataType": "string",
            "sourceColumn": "MeasureName",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "p_KPI_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = #table(type table [MeasureName = text], {{\"KPI\"}}) in Source"
            }
          }
        ],
        "measures": [
          {
            "name": "Total Emissions tCO2e",
            "expression": "SUM ( fact_emissions[emissions_tco2e] )",
            "lineageTag": "55989c99-a858-4ba5-8d94-d6dc36796cc3",
            "formatString": "#,0.0"
          },
          {
            "name": "Scope 1 Emissions tCO2e",
            "expression": "CALCULATE ( [Total Emissions tCO2e], fact_emissions[scope] = \"Scope 1\" )",
            "lineageTag": "00567b76-822f-471f-bb2a-5b759218b1d1",
            "formatString": "#,0.0"
          },
          {
            "name": "Scope 2 Emissions tCO2e",
            "expression": "CALCULATE ( [Total Emissions tCO2e], fact_emissions[scope] = \"Scope 2\" )",
            "lineageTag": "f4f0618f-077b-4f04-8c7a-ae48f320fa44",
            "formatString": "#,0.0"
          },
          {
            "name": "Scope 3 Emissions tCO2e",
            "expression": "CALCULATE ( [Total Emissions tCO2e], fact_emissions[scope] = \"Scope 3\" )",
            "lineageTag": "c235b7d6-32cc-4e37-b393-a450f312e2e9",
            "formatString": "#,0.0"
          },
          {
            "name": "Total Spend USD",
            "expression": "SUM ( fact_emissions[spend_usd] )",
            "lineageTag": "34486cf9-ef2e-4d5d-85cb-c89f6d759b2d",
            "formatString": "$#,0"
          },
          {
            "name": "Revenue USD",
            "expression": "SUM ( fact_emissions[revenue_usd] )",
            "lineageTag": "74aac23d-f08c-4229-82a8-12a0f04edeef",
            "formatString": "$#,0"
          },
          {
            "name": "Emissions Intensity tCO2e per $M Revenue",
            "expression": "DIVIDE ( [Total Emissions tCO2e], [Revenue USD] ) * 1000000",
            "lineageTag": "0d9bdddc-4095-4ea4-a8be-0b3e91a2f7d0",
            "formatString": "#,0.0"
          },
          {
            "name": "Selected Carbon Price USD/t",
            "expression": "SELECTEDVALUE ( dim_carbon_scenario[carbon_price_usd_per_t], 50 )",
            "lineageTag": "ffc47515-df9d-4e6f-b60f-90dbff7fe786",
            "formatString": "$#,0"
          },
          {
            "name": "Carbon Cost USD",
            "expression": "[Total Emissions tCO2e] * [Selected Carbon Price USD/t]",
            "lineageTag": "959e46c3-01dc-40b5-8ae2-916364e73d0a",
            "formatString": "$#,0"
          },
          {
            "name": "Scenario Carbon Cost USD",
            "expression": "SUM ( fact_carbon_exposure[carbon_cost_usd] )",
            "lineageTag": "34d864ed-6d2a-490a-b368-8f539a9e8bec",
            "formatString": "$#,0"
          },
          {
            "name": "Probability Weighted Carbon Cost USD",
            "expression": "SUM ( fact_carbon_exposure[probability_weighted_cost_usd] )",
            "lineageTag": "157f8ffa-90d2-4ff2-8afc-4cacf74ce898",
            "formatString": "$#,0"
          },
          {
            "name": "Stress Scenario Carbon Cost USD",
            "expression": "CALCULATE ( [Scenario Carbon Cost USD], dim_carbon_scenario[scenario] = \"Stress price shock\" )",
            "lineageTag": "9c21bb5b-ac8d-4788-a67b-e2a9888452aa",
            "formatString": "$#,0"
          },
          {
            "name": "Supplier Emissions tCO2e",
            "expression": "SUM ( fact_supplier_month[emissions_tco2e] )",
            "lineageTag": "beaa2629-e51b-4b04-962d-77b8971a1424",
            "formatString": "#,0.0"
          },
          {
            "name": "Supplier Spend USD",
            "expression": "SUM ( fact_supplier_month[spend_usd] )",
            "lineageTag": "1ceb26a8-c5b3-4c40-998e-352bc2bf50c2",
            "formatString": "$#,0"
          },
          {
            "name": "Supplier Intensity tCO2e per $M Spend",
            "expression": "DIVIDE ( [Supplier Emissions tCO2e], [Supplier Spend USD] ) * 1000000",
            "lineageTag": "2e5e3675-3c07-4134-961f-c733e61b5408",
            "formatString": "#,0.0"
          },
          {
            "name": "High Risk Supplier Emissions tCO2e",
            "expression": "CALCULATE ( [Supplier Emissions tCO2e], fact_supplier_month[carbon_risk_tier] = \"High\" )",
            "lineageTag": "ba9d1fc4-ca99-4424-a40b-680aa5a5bfa1",
            "formatString": "#,0.0"
          },
          {
            "name": "Average Data Quality Score",
            "expression": "AVERAGE ( fact_supplier_month[data_quality_score] )",
            "lineageTag": "37fe3e96-f290-4458-a2bc-a4a42b637fcc",
            "formatString": "0.0%"
          },
          {
            "name": "Abatement Annual Reduction tCO2e",
            "expression": "SUM ( fact_abatement_initiatives[annual_reduction_tco2e] )",
            "lineageTag": "73a65fa4-65a9-474c-818b-a3d1421ece65",
            "formatString": "#,0"
          },
          {
            "name": "Abatement Capex USD",
            "expression": "SUM ( fact_abatement_initiatives[capex_usd] )",
            "lineageTag": "643da05c-34a2-4e4a-b862-30129fe2cded",
            "formatString": "$#,0"
          },
          {
            "name": "Planned Abatement Capex USD",
            "expression": "CALCULATE ( [Abatement Capex USD], fact_abatement_initiatives[implementation_status] = \"Planned\" )",
            "lineageTag": "c06624e9-43a2-456c-80d3-81789d38aa92",
            "formatString": "$#,0"
          },
          {
            "name": "Committed and In Flight Reduction tCO2e",
            "expression": "CALCULATE ( [Abatement Annual Reduction tCO2e], fact_abatement_initiatives[implementation_status] IN { \"Committed\", \"In flight\", \"Implemented\" } )",
            "lineageTag": "25150de4-fef5-442b-b75b-4eca739a815f",
            "formatString": "#,0"
          },
          {
            "name": "Avoided Carbon Cost USD at Selected Price",
            "expression": "[Abatement Annual Reduction tCO2e] * [Selected Carbon Price USD/t]",
            "lineageTag": "1eafd657-ea5c-481d-8bb2-eb4b07a93aac",
            "formatString": "$#,0"
          },
          {
            "name": "Abatement Annual Benefit USD",
            "expression": "SUM ( fact_abatement_initiatives[annual_opex_savings_usd] ) + [Avoided Carbon Cost USD at Selected Price]",
            "lineageTag": "bd63109e-786f-4c26-88c7-dd6049f447f2",
            "formatString": "$#,0"
          },
          {
            "name": "Abatement ROI",
            "expression": "DIVIDE ( [Abatement Annual Benefit USD], [Abatement Capex USD] )",
            "lineageTag": "025b3e54-aada-4a79-bb91-e0f6dc84a11b",
            "formatString": "0.0%"
          },
          {
            "name": "Payback Years",
            "expression": "DIVIDE ( [Abatement Capex USD], [Abatement Annual Benefit USD] )",
            "lineageTag": "5d653d03-f711-48c8-bd45-b71fb29f9741",
            "formatString": "0.0"
          },
          {
            "name": "MACC USD per tCO2e",
            "expression": "DIVIDE ( DIVIDE ( [Abatement Capex USD], 7 ) - SUM ( fact_abatement_initiatives[annual_opex_savings_usd] ), [Abatement Annual Reduction tCO2e] )",
            "lineageTag": "b0da9f30-52a9-4e29-a0c0-312230b367eb",
            "formatString": "$#,0.0"
          },
          {
            "name": "Latest Month Emissions tCO2e",
            "expression": "VAR LatestMonth = MAX ( dim_date[date_key] ) RETURN CALCULATE ( [Total Emissions tCO2e], dim_date[date_key] = LatestMonth )",
            "lineageTag": "367d1bff-50c3-420f-931e-fbe2d9923db0",
            "formatString": "#,0.0"
          },
          {
            "name": "YoY Emissions Change %",
            "expression": "VAR CurrentEmissions = [Total Emissions tCO2e] VAR PriorEmissions = CALCULATE ( [Total Emissions tCO2e], DATEADD ( dim_date[month_start], -1, YEAR ) ) RETURN DIVIDE ( CurrentEmissions - PriorEmissions, PriorEmissions )",
            "lineageTag": "4fe01f2d-a06f-402e-8678-e140a757a69d",
            "formatString": "0.0%"
          },
          {
            "name": "No Verified Target Suppliers",
            "expression": "CALCULATE ( DISTINCTCOUNT ( dim_supplier[supplier_id] ), dim_supplier[target_status] = \"No verified target\" )",
            "lineageTag": "cccea799-5737-4f37-ac08-33c441ab079a",
            "formatString": "#,0"
          },
          {
            "name": "2026 Target Gap tCO2e",
            "expression": "VAR Months2026 = CALCULATE ( DISTINCTCOUNT ( dim_date[date_key] ), FILTER ( ALL ( dim_date ), dim_date[year] = 2026 ) ) VAR RunRate = DIVIDE ( CALCULATE ( [Total Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[year] = 2026 ) ), Months2026 ) * 12 VAR MonthCount = CALCULATE ( DISTINCTCOUNT ( dim_date[date_key] ), ALL ( dim_date ) ) VAR AnnualBaseline = DIVIDE ( CALCULATE ( [Total Emissions tCO2e], ALL ( dim_date ) ), DIVIDE ( MonthCount, 12 ) ) RETURN RunRate - AnnualBaseline * 0.86",
            "lineageTag": "d1098470-95f1-4fbd-b687-61a682d45640",
            "formatString": "#,0.0"
          },
          {
            "name": "Total Emissions KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Total Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Total Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000 ), \"#,0.0K\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000 ), \"#,0.0K\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Total Emissions tCO2e] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%232A9D8F\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%232A9D8F' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Total emissions</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%232A9D8F'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%232A9D8F' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%232A9D8F' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "2b1b84bc-1a83-4bbe-b008-e7b1f71ac6b2",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Carbon Cost KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Carbon Cost USD], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Carbon Cost USD], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$#,0.0M;($#,0.0M);$0.0M\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$#,0.0M;($#,0.0M);$0.0M\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Carbon Cost USD] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23F4A261\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23F4A261' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Carbon cost</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23F4A261'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23F4A261' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23F4A261' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "881076b6-6452-44a3-a66c-af21df0e0201",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Intensity KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Emissions Intensity tCO2e per $M Revenue], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Emissions Intensity tCO2e per $M Revenue], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1 ), \"#,0.0\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1 ), \"#,0.0\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Emissions Intensity tCO2e per $M Revenue] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23B7D968\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23B7D968' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Intensity</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23B7D968'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B7D968' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23B7D968' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "3697a9a4-08ea-4fe1-aa28-ec32603c2a36",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "YoY Change KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [YoY Emissions Change %], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [YoY Emissions Change %], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1 ), \"0.0%\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1 ), \"0.0%\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [YoY Emissions Change %] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23E76F51\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23E76F51' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>YoY change</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23E76F51'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23E76F51' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23E76F51' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "c595d7a0-1008-4ac7-b27a-3c72173c31ed",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Latest Month KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Latest Month Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Latest Month Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000 ), \"#,0.0K\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000 ), \"#,0.0K\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Latest Month Emissions tCO2e] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%238AB17D\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%238AB17D' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Latest month</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%238AB17D'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%238AB17D' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%238AB17D' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "b679ef19-ced8-4dd9-b486-0d87077b67dd",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Scope 1 KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Scope 1 Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Scope 1 Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000 ), \"#,0.0K\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000 ), \"#,0.0K\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Scope 1 Emissions tCO2e] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23E76F51\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23E76F51' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Scope 1</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23E76F51'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23E76F51' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23E76F51' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "5668277d-a860-4fae-b4d6-5a1129f5af71",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Scope 2 KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Scope 2 Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Scope 2 Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000 ), \"#,0.0K\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000 ), \"#,0.0K\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Scope 2 Emissions tCO2e] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23F4A261\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23F4A261' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Scope 2</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23F4A261'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23F4A261' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23F4A261' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "04ecc0c5-971a-463f-a564-fb4bd4c76d7d",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Scope 3 KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Scope 3 Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Scope 3 Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000 ), \"#,0.0K\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000 ), \"#,0.0K\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Scope 3 Emissions tCO2e] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%232A9D8F\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%232A9D8F' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Scope 3</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%232A9D8F'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%232A9D8F' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%232A9D8F' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "657e0baf-5a9b-4b51-bdd2-77a79a4744fe",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Supplier Intensity KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Supplier Intensity tCO2e per $M Spend], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Supplier Intensity tCO2e per $M Spend], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1 ), \"#,0.0\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1 ), \"#,0.0\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Supplier Intensity tCO2e per $M Spend] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23B7D968\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23B7D968' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Supplier intensity</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23B7D968'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B7D968' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23B7D968' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "9f8402f5-1093-43b6-b21b-fffbbf85d510",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Carbon Price KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Selected Carbon Price USD/t], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Selected Carbon Price USD/t], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1 ), \"$#,0\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1 ), \"$#,0\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Selected Carbon Price USD/t] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23F4A261\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23F4A261' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Carbon price</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23F4A261'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23F4A261' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23F4A261' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "9983e81b-2912-40c1-a78e-37ad4ca3a212",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Scenario Cost KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Scenario Carbon Cost USD], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Scenario Carbon Cost USD], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$#,0.0M;($#,0.0M);$0.0M\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$#,0.0M;($#,0.0M);$0.0M\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Scenario Carbon Cost USD] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23E76F51\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23E76F51' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Scenario cost</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23E76F51'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23E76F51' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23E76F51' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "2ee0fe13-fdd5-48b5-9ba0-916101854a22",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Annual Reduction KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Abatement Annual Reduction tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Abatement Annual Reduction tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000 ), \"#,0.0K\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000 ), \"#,0.0K\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue >= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Abatement Annual Reduction tCO2e] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%232A9D8F\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%232A9D8F' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Annual reduction</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%232A9D8F'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%232A9D8F' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%232A9D8F' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "95ce1471-8a2a-483a-b3c9-9ce02eb3a6d9",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Abatement ROI KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Abatement ROI], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Abatement ROI], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1 ), \"0.0%\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1 ), \"0.0%\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue >= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Abatement ROI] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%23B7D968\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23B7D968' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Abatement ROI</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23B7D968'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23B7D968' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23B7D968' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "5adf0509-de39-448d-9c80-3205455566a7",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Payback KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Payback Years], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Payback Years], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1 ), \"0.0\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1 ), \"0.0\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Payback Years] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%238AB17D\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%238AB17D' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Payback years</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%238AB17D'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%238AB17D' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%238AB17D' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "abfb7044-aa64-4551-be73-3c734a2d33b2",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "High Risk KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [High Risk Supplier Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [High Risk Supplier Emissions tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000 ), \"#,0.0K\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000 ), \"#,0.0K\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [High Risk Supplier Emissions tCO2e] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23E76F51\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23E76F51' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>High-risk emissions</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23E76F51'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23E76F51' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23E76F51' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "82751a44-8c69-4712-8152-9f4b5f19c8f8",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "No Target KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [No Verified Target Suppliers], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [No Verified Target Suppliers], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1 ), \"#,0\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1 ), \"#,0\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [No Verified Target Suppliers] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23F4A261\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23F4A261' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>No target suppliers</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23F4A261'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23F4A261' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23F4A261' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "0dc81a69-0d82-4aa5-bb81-6b86bf59329c",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Data Quality KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Average Data Quality Score], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Average Data Quality Score], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1 ), \"0.0%\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1 ), \"0.0%\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue >= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Average Data Quality Score] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%232A9D8F\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%232A9D8F' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Data quality</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%232A9D8F'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%232A9D8F' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%232A9D8F' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "ae854dd8-f438-4422-9b07-fd74c62456e8",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Target Gap KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [2026 Target Gap tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [2026 Target Gap tCO2e], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000 ), \"#,0.0K\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000 ), \"#,0.0K\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [2026 Target Gap tCO2e] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%23E76F51\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%23E76F51' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>2026 target gap</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%23E76F51'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%23E76F51' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%23E76F51' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "90a59a81-c836-4eda-b0de-55b72c7d8fc2",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Planned Capex KPI Card SVG",
            "expression": "VAR LatestKey = MAX ( dim_date[date_key] )\nVAR PriorKey =\n    MAXX (\n        FILTER ( ALL ( dim_date ), dim_date[date_key] < LatestKey ),\n        dim_date[date_key]\n    )\nVAR CurrentValue =\n    CALCULATE ( [Planned Abatement Capex USD], FILTER ( ALL ( dim_date ), dim_date[date_key] = LatestKey ) )\nVAR PriorValue =\n    CALCULATE ( [Planned Abatement Capex USD], FILTER ( ALL ( dim_date ), dim_date[date_key] = PriorKey ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR RateValue = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( DIVIDE ( CurrentValue, 1000000 ), \"$#,0.0M;($#,0.0M);$0.0M\" )\nVAR PriorTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( DIVIDE ( PriorValue, 1000000 ), \"$#,0.0M;($#,0.0M);$0.0M\" ) )\nVAR DeltaTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( RateValue, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PriorText = SUBSTITUTE ( PriorTextRaw, \"%\", \"%25\" )\nVAR DeltaText = SUBSTITUTE ( DeltaTextRaw, \"%\", \"%25\" )\nVAR DeltaColor =\n    IF ( ISBLANK ( PriorValue ), \"%23606E66\", IF ( ChangeValue <= 0, \"%232A9D8F\", \"%23E76F51\" ) )\nVAR MonthTable =\n    TOPN (\n        10,\n        ADDCOLUMNS (\n            ALLSELECTED ( dim_date ),\n            \"__Value\", CALCULATE ( [Planned Abatement Capex USD] )\n        ),\n        dim_date[date_key],\n        DESC\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, dim_date[date_key], DESC ), [__Value] )\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%238AB17D\", \"%23E76F51\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23E4F4ED\", \"%23FBE7E1\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    )\nVAR AreaPath =\n    \"M184 88 \" &\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, dim_date[date_key], , ASC, DENSE ) - 1\n        VAR XValue = 184 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 86\n        VAR YValue = 78 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 38\n        RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        dim_date[date_key],\n        ASC\n    ) & \" L270 88 Z\"\nVAR StartYValue = 78 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR EndYValue = 78 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 38\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='300' height='150' viewBox='0 0 300 150'>\" &\n    \"<defs><clipPath id='sparkClip'><rect x='176' y='35' width='106' height='52' rx='9'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='298' height='148' rx='12' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1.6'/>\" &\n    \"<rect x='16' y='13' width='164' height='4.5' rx='2.2' fill='%238AB17D' opacity='0.92'/>\" &\n    \"<text x='16' y='43' font-family='Segoe UI' font-size='16' font-weight='760' fill='%23202A25'>Planned capex</text>\" &\n    \"<text x='16' y='96' font-family='Segoe UI' font-size='48' font-weight='780' fill='%238AB17D'>\" & ValueText & \"</text>\" &\n    \"<rect x='174' y='31' width='112' height='60' rx='10' fill='%23F2F6F4'/>\" &\n    \"<rect x='184' y='62' width='86' height='10' rx='5' fill='\" & BandColor & \"'/>\" &\n    \"<g clip-path='url(%23sparkClip)'>\" &\n    \"<path d='\" & AreaPath & \"' fill='%238AB17D' opacity='0.14'/>\" &\n    \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round'/>\" &\n    \"</g>\" &\n    \"<circle cx='184' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='3.8' fill='%23FFFFFF' stroke='%238AB17D' stroke-width='1.8'/>\" &\n    \"<circle cx='270' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='4.6' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='1.8'/>\" &\n    \"<rect x='16' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<rect x='156' y='110' width='128' height='28' rx='8' fill='%23F4F7F5'/>\" &\n    \"<text x='28' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Prev</text>\" &\n    \"<text x='28' y='138' font-family='Segoe UI' font-size='12.6' font-weight='650' fill='%23202A25'>\" & PriorText & \"</text>\" &\n    \"<text x='168' y='123' font-family='Segoe UI' font-size='10.5' font-weight='700' fill='%235B6C5D'>Delta</text>\" &\n    \"<text x='168' y='138' font-family='Segoe UI' font-size='13' font-weight='760' fill='\" & DeltaColor & \"'>\" & DeltaText & \"</text>\" &\n    \"</svg>\"\nRETURN IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "lineageTag": "6d75f00e-e879-4a2e-b0e6-540086fd1730",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Lens Summary SVG",
            "expression": "VAR YearText =\n    IF ( HASONEVALUE ( dim_date[year] ), FORMAT ( SELECTEDVALUE ( dim_date[year] ), \"0\" ), \"All Years\" )\nVAR RegionCount = COUNTROWS ( VALUES ( dim_facility[region] ) )\nVAR RegionTotal = CALCULATE ( COUNTROWS ( VALUES ( dim_facility[region] ) ), ALL ( dim_facility[region] ) )\nVAR RegionText =\n    IF (\n        NOT ISFILTERED ( dim_facility[region] ) || RegionCount = RegionTotal,\n        \"All Regions\",\n        IF ( RegionCount = 1, SELECTEDVALUE ( dim_facility[region] ), FORMAT ( RegionCount, \"0\" ) & \" regions\" )\n    )\nVAR BUCount = COUNTROWS ( VALUES ( dim_business_unit[business_unit] ) )\nVAR BUTotal = CALCULATE ( COUNTROWS ( VALUES ( dim_business_unit[business_unit] ) ), ALL ( dim_business_unit[business_unit] ) )\nVAR BUText =\n    IF (\n        NOT ISFILTERED ( dim_business_unit[business_unit] ) || BUCount = BUTotal,\n        \"All BU\",\n        IF ( BUCount = 1, SELECTEDVALUE ( dim_business_unit[business_unit] ), FORMAT ( BUCount, \"0\" ) & \" BU\" )\n    )\nVAR ScopeText =\n    IF ( HASONEVALUE ( fact_emissions[scope] ), SELECTEDVALUE ( fact_emissions[scope] ), \"All Scopes\" )\nVAR ScenarioText =\n    IF ( HASONEVALUE ( dim_carbon_scenario[scenario] ), SELECTEDVALUE ( dim_carbon_scenario[scenario] ), \"All Prices\" )\nVAR CostText = FORMAT ( DIVIDE ( [Carbon Cost USD], 1000000 ), \"$0.0M\" )\nVAR PriceText = FORMAT ( [Selected Carbon Price USD/t], \"$0/t\" )\nVAR Line1 = LEFT ( YearText & \" | \" & RegionText, 30 )\nVAR Line2 = LEFT ( BUText & \" | \" & ScopeText & \" | \" & ScenarioText, 32 )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='740' height='84' viewBox='0 0 740 84'>\" &\n    \"<defs><clipPath id='scopeClip'><rect x='276' y='43' width='282' height='25'/></clipPath></defs>\" &\n    \"<rect x='1' y='1' width='738' height='82' rx='14' fill='%231C4A39' stroke='%232A9D8F' stroke-width='1.4'/>\" &\n    \"<rect x='22' y='14' width='136' height='4' rx='2' fill='%232A9D8F' opacity='0.95'/>\" &\n    \"<text x='22' y='36' font-family='Segoe UI' font-size='12.2' font-weight='760' fill='%23BFD1C8'>Current Lens</text>\" &\n    \"<text x='22' y='66' font-family='Segoe UI' font-size='21' font-weight='780' fill='%23FFFFFF'>\" & Line1 & \"</text>\" &\n    \"<text x='276' y='36' font-family='Segoe UI' font-size='12' font-weight='700' fill='%23BFD1C8'>Scope context</text>\" &\n    \"<text x='276' y='64' font-family='Segoe UI' font-size='13.2' font-weight='680' fill='%23FFFFFF' clip-path='url(%23scopeClip)'>\" & Line2 & \"</text>\" &\n    \"<rect x='574' y='14' width='84' height='56' rx='10' fill='%23235143'/>\" &\n    \"<text x='586' y='33' font-family='Segoe UI' font-size='9.2' font-weight='700' fill='%23BFD1C8'>Carbon cost</text>\" &\n    \"<text x='586' y='59' font-family='Segoe UI' font-size='19' font-weight='780' fill='%23B7D968'>\" & CostText & \"</text>\" &\n    \"<rect x='668' y='14' width='58' height='56' rx='10' fill='%23235143'/>\" &\n    \"<text x='676' y='33' font-family='Segoe UI' font-size='8.2' font-weight='700' fill='%23BFD1C8'>Price</text>\" &\n    \"<text x='676' y='59' font-family='Segoe UI' font-size='18' font-weight='780' fill='%23FFFFFF'>\" & PriceText & \"</text>\" &\n    \"</svg>\"\nRETURN \"data:image/svg+xml;utf8,\" & SVG",
            "lineageTag": "f0c8c271-70b1-4bb9-92d2-209cccf8287f",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "_QA Table Card Style Version",
            "expression": "\"v39_dynamic_table_cards\"",
            "lineageTag": "f40bbcd1-6543-4356-9bf0-7529d80398b4",
            "isHidden": true
          },
          {
            "name": "Executive Detail Table SVG",
            "expression": "VAR BaseRows =\n    SELECTCOLUMNS (\n        SUMMARIZECOLUMNS (\n            dim_business_unit[business_unit],\n            dim_facility[region],\n            \"__TCO2e\", [Total Emissions tCO2e],\n            \"__Cost\", [Carbon Cost USD]\n        ),\n        \"__BU\", dim_business_unit[business_unit],\n        \"__Region\", dim_facility[region],\n        \"__TCO2e\", [__TCO2e],\n        \"__Cost\", [__Cost]\n    )\nVAR FilteredRows =\n    FILTER ( BaseRows, NOT ISBLANK ( [__Cost] ) && [__Cost] <> 0 )\nVAR TopRowsRaw =\n    TOPN ( 4, FilteredRows, [__Cost], DESC, [__TCO2e], DESC, [__BU], ASC )\nVAR TopRows =\n    ADDCOLUMNS (\n        TopRowsRaw,\n        \"__Rank\", RANKX ( TopRowsRaw, [__Cost] + DIVIDE ( [__TCO2e], 1000000000 ), , DESC, DENSE )\n    )\nVAR MaxTCO2e = MAXX ( TopRows, [__TCO2e] )\nVAR MaxCost = MAXX ( TopRows, [__Cost] )\nVAR Header =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='620' height='198' viewBox='0 0 620 198'>\" &\n    \"<rect x='1' y='1' width='618' height='196' rx='10' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1'/>\" &\n    \"<rect x='1' y='1' width='618' height='66' rx='10' fill='%23FAFCFB'/>\" &\n    \"<rect x='1' y='56' width='618' height='1' fill='%23E4ECE7'/>\" &\n    \"<rect x='16' y='16' width='210.8' height='4' rx='2' fill='%232A9D8F' opacity='0.82'/>\" &\n    \"<text x='16' y='40' font-family='Segoe UI' font-size='13.6' font-weight='780' fill='%23202A25'>Executive Detail</text>\" &\n    \"<text x='16' y='58' font-family='Segoe UI' font-size='9.4' fill='%235B6C5D'>Dynamic carbon finance follow-up priorities</text>\" &\n    \"<rect x='532' y='18' width='68' height='28' rx='14' fill='%23F0F5F2'/>\" &\n    \"<circle cx='546' cy='32' r='4' fill='%232A9D8F'/>\" &\n    \"<text x='558' y='36' font-family='Segoe UI' font-size='9.4' font-weight='720' fill='%23202A25'>Top \" & FORMAT ( COUNTROWS ( TopRows ), \"0\" ) & \"</text>\" &\n    \"<rect x='16' y='70' width='588' height='22' rx='5' fill='%23EAF1ED'/>\" &\n    \"<text x='20' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Business Unit</text>\" &\n    \"<text x='172.1' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Region</text>\" &\n    \"<text x='366.8' y='85' text-anchor='end' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>tCO2e</text>\" &\n    \"<text x='488.5' y='85' text-anchor='end' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Cost</text>\" &\n    \"<text x='496.5' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Action</text>\"\nVAR Body =\n    IF (\n        ISEMPTY ( TopRows ),\n        \"<text x='20' y='125' font-family='Segoe UI' font-size='10' fill='%235B6C5D'>No rows for the selected filters</text>\",\n        CONCATENATEX (\n            TopRows,\n            VAR R = [__Rank]\n            VAR Y = 96 + ( R - 1 ) * 18\n            VAR RowFill = IF ( MOD ( R, 2 ) = 1, \"%23F8FBF9\", \"%23FFFFFF\" )\n            VAR AccentOpacity = IF ( R = 1, \"0.72\", \"0.22\" )\n            VAR TBar = MAX ( 8, 89.4 * DIVIDE ( [__TCO2e], MaxTCO2e, 0 ) )\n            VAR CBar = MAX ( 8, 109.7 * DIVIDE ( [__Cost], MaxCost, 0 ) )\n            VAR ActionText = IF ( R <= 2, \"Prioritize\", \"Monitor\" )\n            VAR ActionFill = IF ( R <= 2, \"%23FBE7E1\", \"%23FFF2D9\" )\n            VAR ActionColor = IF ( R <= 2, \"%238C3B2D\", \"%23714C10\" )\n            VAR ActionW = IF ( R <= 2, 76, 58.6 )\n            RETURN\n                \"<rect x='16' y='\" & FORMAT ( Y, \"0\" ) & \"' width='588' height='17' rx='5' fill='\" & RowFill & \"'/>\" &\n                \"<rect x='16' y='\" & FORMAT ( Y, \"0\" ) & \"' width='3' height='17' rx='1.5' fill='%232A9D8F' opacity='\" & AccentOpacity & \"'/>\" &\n                \"<text x='20' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' font-family='Segoe UI' font-size='9.2' font-weight='\" & IF ( R = 1, \"700\", \"520\" ) & \"' fill='%23202A25'>\" & LEFT ( [__BU], 19 ) & \"</text>\" &\n                \"<text x='172.1' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' font-family='Segoe UI' font-size='9.2' fill='%23202A25'>\" & LEFT ( [__Region], 10 ) & \"</text>\" &\n                \"<rect x='275.4' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='89.4' height='2.4' rx='1.2' fill='%23E5EEE8'/>\" &\n                \"<rect x='275.4' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='\" & FORMAT ( TBar, \"0.0\" ) & \"' height='2.4' rx='1.2' fill='%232A9D8F' opacity='0.62'/>\" &\n                \"<text x='366.8' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' text-anchor='end' font-family='Segoe UI' font-size='9.2' font-weight='680' fill='%23202A25'>\" & FORMAT ( DIVIDE ( [__TCO2e], 1000 ), \"0.0K\" ) & \"</text>\" &\n                \"<rect x='376.8' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='109.7' height='2.4' rx='1.2' fill='%23E5EEE8'/>\" &\n                \"<rect x='376.8' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='\" & FORMAT ( CBar, \"0.0\" ) & \"' height='2.4' rx='1.2' fill='%232A9D8F' opacity='0.62'/>\" &\n                \"<text x='488.5' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' text-anchor='end' font-family='Segoe UI' font-size='9.2' font-weight='680' fill='%23202A25'>\" & FORMAT ( DIVIDE ( [__Cost], 1000000 ), \"$0.0M\" ) & \"</text>\" &\n                \"<rect x='493.5' y='\" & FORMAT ( Y + 3, \"0\" ) & \"' width='\" & FORMAT ( ActionW, \"0.0\" ) & \"' height='13' rx='6.5' fill='\" & ActionFill & \"'/>\" &\n                \"<text x='\" & FORMAT ( 493.5 + ActionW / 2, \"0.0\" ) & \"' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' text-anchor='middle' font-family='Segoe UI' font-size='8.4' font-weight='720' fill='\" & ActionColor & \"'>\" & ActionText & \"</text>\",\n            \"\",\n            [__Rank],\n            ASC\n        )\n    )\nRETURN \"data:image/svg+xml;utf8,\" & Header & Body & \"</svg>\"",
            "lineageTag": "6f17be95-f158-4283-b5de-e7028f24044b",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Supplier Risk Table SVG",
            "expression": "VAR BaseRows =\n    SELECTCOLUMNS (\n        SUMMARIZECOLUMNS (\n            dim_supplier[supplier],\n            dim_supplier[carbon_risk_tier],\n            dim_supplier[target_status],\n            \"__Emissions\", [Total Emissions tCO2e],\n            \"__Spend\", [Total Spend USD],\n            \"__Intensity\", DIVIDE ( [Total Emissions tCO2e], [Total Spend USD] ) * 1000000\n        ),\n        \"__Supplier\", dim_supplier[supplier],\n        \"__Risk\", dim_supplier[carbon_risk_tier],\n        \"__Target\", dim_supplier[target_status],\n        \"__Emissions\", [__Emissions],\n        \"__Intensity\", [__Intensity]\n    )\nVAR FilteredRows =\n    FILTER (\n        BaseRows,\n        NOT ISBLANK ( [__Intensity] )\n            && [__Intensity] > 0\n            && ( [__Risk] = \"High\" || [__Target] = \"No verified target\" )\n    )\nVAR TopRowsRaw =\n    TOPN ( 5, FilteredRows, [__Intensity], DESC, [__Emissions], DESC, [__Supplier], ASC )\nVAR TopRows =\n    ADDCOLUMNS (\n        TopRowsRaw,\n        \"__Rank\", RANKX ( TopRowsRaw, [__Intensity] + DIVIDE ( [__Emissions], 1000000000 ), , DESC, DENSE )\n    )\nVAR MaxIntensity = MAXX ( TopRows, [__Intensity] )\nVAR Header =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='1240' height='198' viewBox='0 0 1240 198'>\" &\n    \"<rect x='1' y='1' width='1238' height='196' rx='10' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1'/>\" &\n    \"<rect x='1' y='1' width='1238' height='66' rx='10' fill='%23FAFCFB'/>\" &\n    \"<rect x='1' y='56' width='1238' height='1' fill='%23E4ECE7'/>\" &\n    \"<rect x='16' y='16' width='421.6' height='4' rx='2' fill='%23E76F51' opacity='0.82'/>\" &\n    \"<text x='16' y='40' font-family='Segoe UI' font-size='13.6' font-weight='780' fill='%23202A25'>Supplier Risk Table</text>\" &\n    \"<text x='16' y='58' font-family='Segoe UI' font-size='9.4' fill='%235B6C5D'>Dynamic supplier risk and spend-normalized intensity</text>\" &\n    \"<rect x='1152' y='18' width='68' height='28' rx='14' fill='%23F0F5F2'/>\" &\n    \"<circle cx='1166' cy='32' r='4' fill='%23E76F51'/>\" &\n    \"<text x='1178' y='36' font-family='Segoe UI' font-size='9.4' font-weight='720' fill='%23202A25'>Top \" & FORMAT ( COUNTROWS ( TopRows ), \"0\" ) & \"</text>\" &\n    \"<rect x='16' y='70' width='1208' height='22' rx='5' fill='%23EAF1ED'/>\" &\n    \"<text x='20' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Supplier</text>\" &\n    \"<text x='516.1' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Risk</text>\" &\n    \"<text x='688.7' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Target</text>\" &\n    \"<text x='1220' y='85' text-anchor='end' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Intensity</text>\"\nVAR Body =\n    IF (\n        ISEMPTY ( TopRows ),\n        \"<text x='20' y='125' font-family='Segoe UI' font-size='10' fill='%235B6C5D'>No supplier rows for selected filters</text>\",\n        CONCATENATEX (\n            TopRows,\n            VAR R = [__Rank]\n            VAR Y = 96 + ( R - 1 ) * 18\n            VAR RowFill = IF ( MOD ( R, 2 ) = 1, \"%23F8FBF9\", \"%23FFFFFF\" )\n            VAR AccentOpacity = IF ( R = 1, \"0.72\", \"0.22\" )\n            VAR RiskFill = IF ( [__Risk] = \"High\", \"%23FBE7E1\", IF ( [__Risk] = \"Medium\", \"%23FFF2D9\", \"%23EAF3EA\" ) )\n            VAR RiskColor = IF ( [__Risk] = \"High\", \"%238C3B2D\", IF ( [__Risk] = \"Medium\", \"%23714C10\", \"%231F5B43\" ) )\n            VAR TargetFill = IF ( [__Target] = \"No verified target\", \"%23FBE7E1\", IF ( [__Target] = \"Supplier target\", \"%23FFF2D9\", \"%23EAF3EA\" ) )\n            VAR TargetColor = IF ( [__Target] = \"No verified target\", \"%238C3B2D\", IF ( [__Target] = \"Supplier target\", \"%23714C10\", \"%231F5B43\" ) )\n            VAR TargetW = MIN ( 122.4, MAX ( 70, LEN ( [__Target] ) * 5.8 + 18 ) )\n            VAR BarValue = MAX ( 8, 160.6 * DIVIDE ( [__Intensity], MaxIntensity, 0 ) )\n            RETURN\n                \"<rect x='16' y='\" & FORMAT ( Y, \"0\" ) & \"' width='1208' height='17' rx='5' fill='\" & RowFill & \"'/>\" &\n                \"<rect x='16' y='\" & FORMAT ( Y, \"0\" ) & \"' width='3' height='17' rx='1.5' fill='%23E76F51' opacity='\" & AccentOpacity & \"'/>\" &\n                \"<text x='20' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' font-family='Segoe UI' font-size='9.2' font-weight='\" & IF ( R = 1, \"700\", \"520\" ) & \"' fill='%23202A25'>\" & LEFT ( [__Supplier], 32 ) & \"</text>\" &\n                \"<rect x='513.1' y='\" & FORMAT ( Y + 3, \"0\" ) & \"' width='46' height='13' rx='6.5' fill='\" & RiskFill & \"'/>\" &\n                \"<text x='\" & FORMAT ( 536.1, \"0.0\" ) & \"' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' text-anchor='middle' font-family='Segoe UI' font-size='8.4' font-weight='720' fill='\" & RiskColor & \"'>\" & [__Risk] & \"</text>\" &\n                \"<rect x='685.7' y='\" & FORMAT ( Y + 3, \"0\" ) & \"' width='\" & FORMAT ( TargetW, \"0.0\" ) & \"' height='13' rx='6.5' fill='\" & TargetFill & \"'/>\" &\n                \"<text x='\" & FORMAT ( 685.7 + TargetW / 2, \"0.0\" ) & \"' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' text-anchor='middle' font-family='Segoe UI' font-size='8.4' font-weight='720' fill='\" & TargetColor & \"'>\" & LEFT ( [__Target], 20 ) & \"</text>\" &\n                \"<rect x='1057.4' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='160.6' height='2.4' rx='1.2' fill='%23E5EEE8'/>\" &\n                \"<rect x='1057.4' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='\" & FORMAT ( BarValue, \"0.0\" ) & \"' height='2.4' rx='1.2' fill='%23E76F51' opacity='0.62'/>\" &\n                \"<text x='1220' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' text-anchor='end' font-family='Segoe UI' font-size='9.2' font-weight='680' fill='%23202A25'>\" & FORMAT ( [__Intensity], \"0\" ) & \"</text>\",\n            \"\",\n            [__Rank],\n            ASC\n        )\n    )\nRETURN \"data:image/svg+xml;utf8,\" & Header & Body & \"</svg>\"",
            "lineageTag": "b693850c-bf31-4448-8cc2-dd9a888a9e92",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Abatement Action Queue SVG",
            "expression": "VAR SelectedScopes = VALUES ( fact_emissions[scope] )\nVAR SelectedBUs = VALUES ( dim_business_unit[business_unit] )\nVAR SelectedYears = VALUES ( dim_date[year] )\nVAR BaseRows =\n    SELECTCOLUMNS (\n        SUMMARIZECOLUMNS (\n            fact_abatement_initiatives[initiative],\n            fact_abatement_initiatives[implementation_status],\n            fact_abatement_initiatives[scope],\n            TREATAS ( SelectedScopes, fact_abatement_initiatives[scope] ),\n            TREATAS ( SelectedBUs, fact_abatement_initiatives[business_unit] ),\n            TREATAS ( SelectedYears, fact_abatement_initiatives[start_year] ),\n            \"__Capex\", [Abatement Capex USD],\n            \"__Reduction\", [Abatement Annual Reduction tCO2e],\n            \"__Benefit\", [Abatement Annual Benefit USD],\n            \"__ROI\", [Abatement ROI]\n        ),\n        \"__Initiative\", fact_abatement_initiatives[initiative],\n        \"__Status\", fact_abatement_initiatives[implementation_status],\n        \"__Scope\", fact_abatement_initiatives[scope],\n        \"__Capex\", [__Capex],\n        \"__ROI\", [__ROI],\n        \"__Benefit\", [__Benefit]\n    )\nVAR FilteredRows =\n    FILTER ( BaseRows, NOT ISBLANK ( [__ROI] ) && [__ROI] <> 0 )\nVAR TopRowsRaw =\n    TOPN ( 4, FilteredRows, [__ROI], DESC, [__Benefit], DESC, [__Initiative], ASC )\nVAR TopRows =\n    ADDCOLUMNS (\n        TopRowsRaw,\n        \"__Rank\", RANKX ( TopRowsRaw, [__ROI] + DIVIDE ( [__Benefit], 1000000000000 ), , DESC, DENSE )\n    )\nVAR MaxCapex = MAXX ( TopRows, [__Capex] )\nVAR MaxROI = MAXX ( TopRows, [__ROI] )\nVAR Header =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='1240' height='198' viewBox='0 0 1240 198'>\" &\n    \"<rect x='1' y='1' width='1238' height='196' rx='10' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1'/>\" &\n    \"<rect x='1' y='1' width='1238' height='66' rx='10' fill='%23FAFCFB'/>\" &\n    \"<rect x='1' y='56' width='1238' height='1' fill='%23E4ECE7'/>\" &\n    \"<rect x='16' y='16' width='421.6' height='4' rx='2' fill='%23B7D968' opacity='0.82'/>\" &\n    \"<text x='16' y='40' font-family='Segoe UI' font-size='13.6' font-weight='780' fill='%23202A25'>Abatement Action Queue</text>\" &\n    \"<text x='16' y='58' font-family='Segoe UI' font-size='9.4' fill='%235B6C5D'>Dynamic investment case by status, capex and ROI</text>\" &\n    \"<rect x='1152' y='18' width='68' height='28' rx='14' fill='%23F0F5F2'/>\" &\n    \"<circle cx='1166' cy='32' r='4' fill='%23B7D968'/>\" &\n    \"<text x='1178' y='36' font-family='Segoe UI' font-size='9.4' font-weight='720' fill='%23202A25'>Top \" & FORMAT ( COUNTROWS ( TopRows ), \"0\" ) & \"</text>\" &\n    \"<rect x='16' y='70' width='1208' height='22' rx='5' fill='%23EAF1ED'/>\" &\n    \"<text x='20' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Initiative</text>\" &\n    \"<text x='526.6' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Status</text>\" &\n    \"<text x='760.4' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Scope</text>\" &\n    \"<text x='1083.6' y='85' text-anchor='end' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Capex</text>\" &\n    \"<text x='1220' y='85' text-anchor='end' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>ROI</text>\"\nVAR Body =\n    IF (\n        ISEMPTY ( TopRows ),\n        \"<text x='20' y='125' font-family='Segoe UI' font-size='10' fill='%235B6C5D'>No initiatives for selected filters</text>\",\n        CONCATENATEX (\n            TopRows,\n            VAR R = [__Rank]\n            VAR Y = 96 + ( R - 1 ) * 18\n            VAR RowFill = IF ( MOD ( R, 2 ) = 1, \"%23F8FBF9\", \"%23FFFFFF\" )\n            VAR AccentOpacity = IF ( R = 1, \"0.72\", \"0.22\" )\n            VAR StatusFill =\n                SWITCH ( TRUE (), [__Status] = \"Planned\", \"%23FBE7E1\", [__Status] = \"In flight\", \"%23FFF2D9\", \"%23EAF3EA\" )\n            VAR StatusColor =\n                SWITCH ( TRUE (), [__Status] = \"Planned\", \"%238C3B2D\", [__Status] = \"In flight\", \"%23714C10\", \"%231F5B43\" )\n            VAR StatusW = MIN ( 92, MAX ( 58, LEN ( [__Status] ) * 5.8 + 18 ) )\n            VAR CapexBar = MAX ( 8, 163.4 * DIVIDE ( [__Capex], MaxCapex, 0 ) )\n            VAR RoiBar = MAX ( 8, 124.4 * DIVIDE ( [__ROI], MaxROI, 0 ) )\n            RETURN\n                \"<rect x='16' y='\" & FORMAT ( Y, \"0\" ) & \"' width='1208' height='17' rx='5' fill='\" & RowFill & \"'/>\" &\n                \"<rect x='16' y='\" & FORMAT ( Y, \"0\" ) & \"' width='3' height='17' rx='1.5' fill='%23B7D968' opacity='\" & AccentOpacity & \"'/>\" &\n                \"<text x='20' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' font-family='Segoe UI' font-size='9.2' font-weight='\" & IF ( R = 1, \"700\", \"520\" ) & \"' fill='%23202A25'>\" & LEFT ( [__Initiative], 34 ) & \"</text>\" &\n                \"<rect x='523.6' y='\" & FORMAT ( Y + 3, \"0\" ) & \"' width='\" & FORMAT ( StatusW, \"0.0\" ) & \"' height='13' rx='6.5' fill='\" & StatusFill & \"'/>\" &\n                \"<text x='\" & FORMAT ( 523.6 + StatusW / 2, \"0.0\" ) & \"' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' text-anchor='middle' font-family='Segoe UI' font-size='8.4' font-weight='720' fill='\" & StatusColor & \"'>\" & [__Status] & \"</text>\" &\n                \"<text x='760.4' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' font-family='Segoe UI' font-size='9.2' fill='%23202A25'>\" & [__Scope] & \"</text>\" &\n                \"<rect x='918.3' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='163.4' height='2.4' rx='1.2' fill='%23E5EEE8'/>\" &\n                \"<rect x='918.3' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='\" & FORMAT ( CapexBar, \"0.0\" ) & \"' height='2.4' rx='1.2' fill='%23B7D968' opacity='0.62'/>\" &\n                \"<text x='1083.6' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' text-anchor='end' font-family='Segoe UI' font-size='9.2' font-weight='680' fill='%23202A25'>\" & FORMAT ( DIVIDE ( [__Capex], 1000000 ), \"$0.0M\" ) & \"</text>\" &\n                \"<rect x='1093.6' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='124.4' height='2.4' rx='1.2' fill='%23E5EEE8'/>\" &\n                \"<rect x='1093.6' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='\" & FORMAT ( RoiBar, \"0.0\" ) & \"' height='2.4' rx='1.2' fill='%23B7D968' opacity='0.62'/>\" &\n                \"<text x='1220' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' text-anchor='end' font-family='Segoe UI' font-size='9.2' font-weight='680' fill='%23202A25'>\" & FORMAT ( [__ROI], \"0.0%\" ) & \"</text>\",\n            \"\",\n            [__Rank],\n            ASC\n        )\n    )\nRETURN \"data:image/svg+xml;utf8,\" & Header & Body & \"</svg>\"",
            "lineageTag": "728aaed4-032d-4eb9-817c-f816516568e5",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Risk Action Queue SVG",
            "expression": "VAR BaseRows =\n    SELECTCOLUMNS (\n        SUMMARIZECOLUMNS (\n            dim_supplier[supplier],\n            dim_supplier[carbon_risk_tier],\n            dim_supplier[target_status],\n            \"__Emissions\", [Total Emissions tCO2e],\n            \"__Spend\", [Total Spend USD],\n            \"__Intensity\", DIVIDE ( [Total Emissions tCO2e], [Total Spend USD] ) * 1000000\n        ),\n        \"__Supplier\", dim_supplier[supplier],\n        \"__Risk\", dim_supplier[carbon_risk_tier],\n        \"__Target\", dim_supplier[target_status],\n        \"__Emissions\", [__Emissions],\n        \"__Intensity\", [__Intensity]\n    )\nVAR FilteredRows =\n    FILTER (\n        BaseRows,\n        NOT ISBLANK ( [__Intensity] )\n            && [__Intensity] > 0\n            && ( [__Risk] = \"High\" || [__Target] = \"No verified target\" )\n    )\nVAR TopRowsRaw =\n    TOPN ( 5, FilteredRows, [__Intensity], DESC, [__Emissions], DESC, [__Supplier], ASC )\nVAR TopRows =\n    ADDCOLUMNS (\n        TopRowsRaw,\n        \"__Rank\", RANKX ( TopRowsRaw, [__Intensity] + DIVIDE ( [__Emissions], 1000000000 ), , DESC, DENSE )\n    )\nVAR MaxIntensity = MAXX ( TopRows, [__Intensity] )\nVAR Header =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='620' height='198' viewBox='0 0 620 198'>\" &\n    \"<rect x='1' y='1' width='618' height='196' rx='10' fill='%23FFFFFF' stroke='%23D9E2DC' stroke-width='1'/>\" &\n    \"<rect x='1' y='1' width='618' height='66' rx='10' fill='%23FAFCFB'/>\" &\n    \"<rect x='1' y='56' width='618' height='1' fill='%23E4ECE7'/>\" &\n    \"<rect x='16' y='16' width='210.8' height='4' rx='2' fill='%23E76F51' opacity='0.82'/>\" &\n    \"<text x='16' y='40' font-family='Segoe UI' font-size='13.6' font-weight='780' fill='%23202A25'>Risk Action Queue</text>\" &\n    \"<text x='16' y='58' font-family='Segoe UI' font-size='9.4' fill='%235B6C5D'>Dynamic supplier follow-up for CFO/ESG review</text>\" &\n    \"<rect x='532' y='18' width='68' height='28' rx='14' fill='%23F0F5F2'/>\" &\n    \"<circle cx='546' cy='32' r='4' fill='%23E76F51'/>\" &\n    \"<text x='558' y='36' font-family='Segoe UI' font-size='9.4' font-weight='720' fill='%23202A25'>Top \" & FORMAT ( COUNTROWS ( TopRows ), \"0\" ) & \"</text>\" &\n    \"<rect x='16' y='70' width='588' height='22' rx='5' fill='%23EAF1ED'/>\" &\n    \"<text x='20' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Supplier</text>\" &\n    \"<text x='228.2' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Risk</text>\" &\n    \"<text x='326.2' y='85' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Target</text>\" &\n    \"<text x='600' y='85' text-anchor='end' font-family='Segoe UI' font-size='8.9' font-weight='760' fill='%23202A25'>Intensity</text>\"\nVAR Body =\n    IF (\n        ISEMPTY ( TopRows ),\n        \"<text x='20' y='125' font-family='Segoe UI' font-size='10' fill='%235B6C5D'>No supplier rows for selected filters</text>\",\n        CONCATENATEX (\n            TopRows,\n            VAR R = [__Rank]\n            VAR Y = 96 + ( R - 1 ) * 18\n            VAR RowFill = IF ( MOD ( R, 2 ) = 1, \"%23F8FBF9\", \"%23FFFFFF\" )\n            VAR AccentOpacity = IF ( R = 1, \"0.72\", \"0.22\" )\n            VAR RiskFill = IF ( [__Risk] = \"High\", \"%23FBE7E1\", IF ( [__Risk] = \"Medium\", \"%23FFF2D9\", \"%23EAF3EA\" ) )\n            VAR RiskColor = IF ( [__Risk] = \"High\", \"%238C3B2D\", IF ( [__Risk] = \"Medium\", \"%23714C10\", \"%231F5B43\" ) )\n            VAR TargetFill = IF ( [__Target] = \"No verified target\", \"%23FBE7E1\", IF ( [__Target] = \"Supplier target\", \"%23FFF2D9\", \"%23EAF3EA\" ) )\n            VAR TargetColor = IF ( [__Target] = \"No verified target\", \"%238C3B2D\", IF ( [__Target] = \"Supplier target\", \"%23714C10\", \"%231F5B43\" ) )\n            VAR TargetW = MIN ( 122.4, MAX ( 70, LEN ( [__Target] ) * 5.8 + 18 ) )\n            VAR BarValue = MAX ( 8, 98.3 * DIVIDE ( [__Intensity], MaxIntensity, 0 ) )\n            RETURN\n                \"<rect x='16' y='\" & FORMAT ( Y, \"0\" ) & \"' width='588' height='17' rx='5' fill='\" & RowFill & \"'/>\" &\n                \"<rect x='16' y='\" & FORMAT ( Y, \"0\" ) & \"' width='3' height='17' rx='1.5' fill='%23E76F51' opacity='\" & AccentOpacity & \"'/>\" &\n                \"<text x='20' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' font-family='Segoe UI' font-size='9.2' font-weight='\" & IF ( R = 1, \"700\", \"520\" ) & \"' fill='%23202A25'>\" & LEFT ( [__Supplier], 20 ) & \"</text>\" &\n                \"<rect x='225.2' y='\" & FORMAT ( Y + 3, \"0\" ) & \"' width='46' height='13' rx='6.5' fill='\" & RiskFill & \"'/>\" &\n                \"<text x='\" & FORMAT ( 248.2, \"0.0\" ) & \"' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' text-anchor='middle' font-family='Segoe UI' font-size='8.4' font-weight='720' fill='\" & RiskColor & \"'>\" & [__Risk] & \"</text>\" &\n                \"<rect x='323.2' y='\" & FORMAT ( Y + 3, \"0\" ) & \"' width='\" & FORMAT ( TargetW, \"0.0\" ) & \"' height='13' rx='6.5' fill='\" & TargetFill & \"'/>\" &\n                \"<text x='\" & FORMAT ( 323.2 + TargetW / 2, \"0.0\" ) & \"' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' text-anchor='middle' font-family='Segoe UI' font-size='8.4' font-weight='720' fill='\" & TargetColor & \"'>\" & LEFT ( [__Target], 20 ) & \"</text>\" &\n                \"<rect x='499.8' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='98.3' height='2.4' rx='1.2' fill='%23E5EEE8'/>\" &\n                \"<rect x='499.8' y='\" & FORMAT ( Y + 13, \"0\" ) & \"' width='\" & FORMAT ( BarValue, \"0.0\" ) & \"' height='2.4' rx='1.2' fill='%23E76F51' opacity='0.62'/>\" &\n                \"<text x='600' y='\" & FORMAT ( Y + 11, \"0\" ) & \"' text-anchor='end' font-family='Segoe UI' font-size='9.2' font-weight='680' fill='%23202A25'>\" & FORMAT ( [__Intensity], \"0\" ) & \"</text>\",\n            \"\",\n            [__Rank],\n            ASC\n        )\n    )\nRETURN \"data:image/svg+xml;utf8,\" & Header & Body & \"</svg>\"",
            "lineageTag": "82d9af6b-7353-4f68-abe8-c6b1e2ddb155",
            "dataCategory": "ImageUrl"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Rel_fact_emissions_date_key_dim_date_date_key",
        "fromTable": "fact_emissions",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date_key"
      },
      {
        "name": "Rel_fact_supplier_month_date_key_dim_date_date_key",
        "fromTable": "fact_supplier_month",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date_key"
      },
      {
        "name": "Rel_fact_carbon_exposure_date_key_dim_date_date_key",
        "fromTable": "fact_carbon_exposure",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date_key"
      },
      {
        "name": "Rel_fact_emissions_business_unit_id_dim_business_unit_business_unit_id",
        "fromTable": "fact_emissions",
        "fromColumn": "business_unit_id",
        "toTable": "dim_business_unit",
        "toColumn": "business_unit_id"
      },
      {
        "name": "Rel_fact_emissions_facility_id_dim_facility_facility_id",
        "fromTable": "fact_emissions",
        "fromColumn": "facility_id",
        "toTable": "dim_facility",
        "toColumn": "facility_id"
      },
      {
        "name": "Rel_fact_emissions_activity_id_dim_activity_activity_id",
        "fromTable": "fact_emissions",
        "fromColumn": "activity_id",
        "toTable": "dim_activity",
        "toColumn": "activity_id"
      },
      {
        "name": "Rel_fact_emissions_supplier_id_dim_supplier_supplier_id",
        "fromTable": "fact_emissions",
        "fromColumn": "supplier_id",
        "toTable": "dim_supplier",
        "toColumn": "supplier_id"
      },
      {
        "name": "Rel_fact_supplier_month_supplier_id_dim_supplier_supplier_id",
        "fromTable": "fact_supplier_month",
        "fromColumn": "supplier_id",
        "toTable": "dim_supplier",
        "toColumn": "supplier_id"
      },
      {
        "name": "Rel_fact_carbon_exposure_scenario_id_dim_carbon_scenario_scenario_id",
        "fromTable": "fact_carbon_exposure",
        "fromColumn": "scenario_id",
        "toTable": "dim_carbon_scenario",
        "toColumn": "scenario_id"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}