table DimDate

	column date_id
		dataType: string
		summarizeBy: none
		sourceColumn: date_id

	column date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: date

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: string
		summarizeBy: none
		sourceColumn: quarter

	column month_number
		dataType: int64
		summarizeBy: none
		sourceColumn: month_number

	column month_label
		dataType: string
		summarizeBy: none
		sourceColumn: month_label

	column is_latest_complete
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_latest_complete

	column month_index
		dataType: int64
		summarizeBy: none
		sourceColumn: month_index

	partition DimDate-Import = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/dim_date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {
				        {"date_id", type text},
				        {"date", type date},
				        {"year", Int64.Type},
				        {"quarter", type text},
				        {"month_number", Int64.Type},
				        {"month_label", type text},
				        {"is_latest_complete", type logical},
				        {"month_index", Int64.Type}
				    }, "en-US")
				in
				    TypedColumns

