{
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DimDate",
        "lineageTag": "98803711-b1b7-4410-83a2-b742013ea964",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "lineageTag": "fc79b815-ad37-43ec-a7ea-cf219daeeaba",
            "summarizeBy": "none"
          },
          {
            "name": "MonthLabel",
            "dataType": "string",
            "sourceColumn": "MonthLabel",
            "lineageTag": "453c9e06-5090-407f-a563-a6d30fcabe00",
            "summarizeBy": "none"
          },
          {
            "name": "MonthIndex",
            "dataType": "int64",
            "sourceColumn": "MonthIndex",
            "lineageTag": "edbb0c88-0e5e-4fd8-83cc-1f3e2cd3f6cf",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "lineageTag": "9e667f1b-b7d6-4203-a563-f98d2e798b7f",
            "formatString": "0"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "lineageTag": "ae8b62c4-d7c4-4071-bd7d-0b725de3eefa",
            "summarizeBy": "none"
          },
          {
            "name": "IsLatestCompleteMonth",
            "dataType": "dateTime",
            "sourceColumn": "IsLatestCompleteMonth",
            "lineageTag": "a2371ea5-ba02-4029-84f9-7717e07bd073",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_DimDate",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\DimDate.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"MonthLabel\", type text}, {\"MonthIndex\", Int64.Type}, {\"Year\", Int64.Type}, {\"Quarter\", type text}, {\"IsLatestCompleteMonth\", type date}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimPlan",
        "lineageTag": "44ff7a2d-7228-4ad7-a0f8-c91cab97ca43",
        "columns": [
          {
            "name": "PlanID",
            "dataType": "string",
            "sourceColumn": "PlanID",
            "lineageTag": "6af8f466-8742-4677-bb7c-fea0cbbf1067",
            "summarizeBy": "none"
          },
          {
            "name": "PlanName",
            "dataType": "string",
            "sourceColumn": "PlanName",
            "lineageTag": "8d7fbe99-5d7f-4a23-a69f-c388a180f79b",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "lineageTag": "931b69f7-72f5-4cea-8940-05b43e596297",
            "summarizeBy": "none"
          },
          {
            "name": "BaseMRR",
            "dataType": "int64",
            "sourceColumn": "BaseMRR",
            "lineageTag": "0104ffda-faef-4601-b535-1b76b84a2edf",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "GrossMarginTarget",
            "dataType": "double",
            "sourceColumn": "GrossMarginTarget",
            "lineageTag": "1d62531b-68d0-476a-9381-f42c6811591e",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "MonthlyChurnTarget",
            "dataType": "double",
            "sourceColumn": "MonthlyChurnTarget",
            "lineageTag": "9ce380e4-0f03-48c9-947b-2e0d373dde43"
          },
          {
            "name": "TargetCAC",
            "dataType": "int64",
            "sourceColumn": "TargetCAC",
            "lineageTag": "26644a59-2c19-40a8-9b37-ef21738487e7",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "BenchmarkPaybackMonths",
            "dataType": "int64",
            "sourceColumn": "BenchmarkPaybackMonths",
            "lineageTag": "95448015-4ed9-4aac-bd15-af1976433361",
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "p_DimPlan",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\DimPlan.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"PlanID\", type text}, {\"PlanName\", type text}, {\"Segment\", type text}, {\"BaseMRR\", Int64.Type}, {\"GrossMarginTarget\", type number}, {\"MonthlyChurnTarget\", type number}, {\"TargetCAC\", Int64.Type}, {\"BenchmarkPaybackMonths\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimChannel",
        "lineageTag": "919c3493-74a7-46ee-84ab-7c86b85ce57a",
        "columns": [
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "25745f8f-13a0-4724-9a72-47be8f9cfb01",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelName",
            "dataType": "string",
            "sourceColumn": "ChannelName",
            "lineageTag": "833328e1-b11c-4686-a137-606152aa493f",
            "summarizeBy": "none"
          },
          {
            "name": "Motion",
            "dataType": "string",
            "sourceColumn": "Motion",
            "lineageTag": "fcd0c629-3b01-4468-a734-3887a5afabe8",
            "summarizeBy": "none"
          },
          {
            "name": "SourceType",
            "dataType": "string",
            "sourceColumn": "SourceType",
            "lineageTag": "1b3aa882-bf65-496e-9512-73fda19e009c",
            "summarizeBy": "none"
          },
          {
            "name": "CACIndex",
            "dataType": "double",
            "sourceColumn": "CACIndex",
            "lineageTag": "b4ca97c0-0158-413e-8034-12eaa9190e6d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "QualityIndex",
            "dataType": "double",
            "sourceColumn": "QualityIndex",
            "lineageTag": "a0ce052d-275c-48d7-abde-25c56df454f1"
          }
        ],
        "partitions": [
          {
            "name": "p_DimChannel",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\DimChannel.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"ChannelID\", type text}, {\"ChannelName\", type text}, {\"Motion\", type text}, {\"SourceType\", type text}, {\"CACIndex\", type number}, {\"QualityIndex\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimRegion",
        "lineageTag": "4471dbd0-a223-45db-bd56-8fe700b04477",
        "columns": [
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "e4f2f5b9-cedb-4ebf-b506-18fa68325d37",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "87dfa6c9-46ef-4a89-b4fe-82469582c256",
            "summarizeBy": "none"
          },
          {
            "name": "GeoGroup",
            "dataType": "string",
            "sourceColumn": "GeoGroup",
            "lineageTag": "3d174be7-ebf0-404c-9f9e-ab488c69ab31",
            "summarizeBy": "none"
          },
          {
            "name": "ScaleIndex",
            "dataType": "double",
            "sourceColumn": "ScaleIndex",
            "lineageTag": "009e21b1-ac85-44b8-8a35-0d8cacc16608"
          }
        ],
        "partitions": [
          {
            "name": "p_DimRegion",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\DimRegion.csv\"), [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"RegionID\", type text}, {\"Region\", type text}, {\"GeoGroup\", type text}, {\"ScaleIndex\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "lineageTag": "23588ce9-3d0c-4597-8b1c-a652f8c27472",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "lineageTag": "a895faf9-29c1-4fd9-a729-ae5af573f4da",
            "summarizeBy": "none"
          },
          {
            "name": "AccountName",
            "dataType": "string",
            "sourceColumn": "AccountName",
            "lineageTag": "68c73aab-a1bf-41a7-bdac-e0b3e47b2626",
            "summarizeBy": "none"
          },
          {
            "name": "PlanID",
            "dataType": "string",
            "sourceColumn": "PlanID",
            "lineageTag": "9a08d52b-6666-45fc-8061-318a8ebee10d",
            "summarizeBy": "none"
          },
          {
            "name": "PlanName",
            "dataType": "string",
            "sourceColumn": "PlanName",
            "lineageTag": "8f271c28-e959-41ee-95ad-5c00eed4553f",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "lineageTag": "61406f76-2448-4b79-b33c-b6846d7ffa83",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "be9fa413-1eac-46f1-9a8f-da97beb0f252",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelName",
            "dataType": "string",
            "sourceColumn": "ChannelName",
            "lineageTag": "633a9949-c113-4823-973d-1f6fd87d19d7",
            "summarizeBy": "none"
          },
          {
            "name": "Motion",
            "dataType": "string",
            "sourceColumn": "Motion",
            "lineageTag": "60d37b65-c348-43ad-be91-a0ef8101cca6",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "1fd72ac6-703a-4151-a8f2-59229414393f",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "6ae38dcf-e3d8-4aec-a860-a96a76f89ca7",
            "summarizeBy": "none"
          },
          {
            "name": "Industry",
            "dataType": "string",
            "sourceColumn": "Industry",
            "lineageTag": "2ae6b8ba-28de-46b4-a95e-d9ac3c95c564",
            "summarizeBy": "none"
          },
          {
            "name": "AcquisitionMonth",
            "dataType": "dateTime",
            "sourceColumn": "AcquisitionMonth",
            "lineageTag": "19eff3ef-411f-44d6-b1ca-ee515bd2eb93",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_DimCustomer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\DimCustomer.csv\"), [Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"CustomerID\", type text}, {\"AccountName\", type text}, {\"PlanID\", type text}, {\"PlanName\", type text}, {\"Segment\", type text}, {\"ChannelID\", type text}, {\"ChannelName\", type text}, {\"Motion\", type text}, {\"RegionID\", type text}, {\"Region\", type text}, {\"Industry\", type text}, {\"AcquisitionMonth\", type date}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactSubscriptionMonthly",
        "lineageTag": "989216d9-5e61-4a0a-aca4-c721e984892a",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "lineageTag": "298aa02e-c6ce-4634-88e3-5159eaf6e88c",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "lineageTag": "8bc9448e-c100-4bec-99fe-72707bb7d025",
            "summarizeBy": "none"
          },
          {
            "name": "PlanID",
            "dataType": "string",
            "sourceColumn": "PlanID",
            "lineageTag": "a6924bba-d5bf-412f-852c-6f08a88b628d",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "51ebf0f7-92d5-4b60-a410-0bbd5b52ee84",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "b5f32a70-0b48-4ab8-95c1-7ec5790118ab",
            "summarizeBy": "none"
          },
          {
            "name": "BeginningMRR",
            "dataType": "double",
            "sourceColumn": "BeginningMRR",
            "lineageTag": "39390f74-5dec-46f2-a83a-0bed27434a17",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "NewMRR",
            "dataType": "double",
            "sourceColumn": "NewMRR",
            "lineageTag": "33e79d84-fe7c-444a-9a4b-d604acd84a17",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ExpansionMRR",
            "dataType": "double",
            "sourceColumn": "ExpansionMRR",
            "lineageTag": "24297441-702e-4545-91e9-3b5d038e97af",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ContractionMRR",
            "dataType": "double",
            "sourceColumn": "ContractionMRR",
            "lineageTag": "61601e98-b293-45f9-9370-8d797fe0e0a3",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ChurnMRR",
            "dataType": "double",
            "sourceColumn": "ChurnMRR",
            "lineageTag": "68f2b136-1b2e-4d3b-b49c-b6ba8c13d76a",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "EndingMRR",
            "dataType": "double",
            "sourceColumn": "EndingMRR",
            "lineageTag": "1f1a8f01-3431-48c1-93c1-30371a55c542",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "RecognizedRevenue",
            "dataType": "double",
            "sourceColumn": "RecognizedRevenue",
            "lineageTag": "743b6ec1-eb84-4f0c-a896-ec7f9c6fc7cc",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "GrossMargin",
            "dataType": "double",
            "sourceColumn": "GrossMargin",
            "lineageTag": "2d62d99e-205d-43b2-88b5-593adbbb6169",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Seats",
            "dataType": "int64",
            "sourceColumn": "Seats",
            "lineageTag": "93197b7f-2259-4a4e-9143-93add3107c96",
            "formatString": "0"
          },
          {
            "name": "StartingLogo",
            "dataType": "int64",
            "sourceColumn": "StartingLogo",
            "lineageTag": "59e81eb6-6242-4348-9fd6-7c6500368878",
            "formatString": "0"
          },
          {
            "name": "ActiveLogo",
            "dataType": "int64",
            "sourceColumn": "ActiveLogo",
            "lineageTag": "217e64e3-70dd-4a36-904e-d7c1ada79630",
            "formatString": "0"
          },
          {
            "name": "NewLogo",
            "dataType": "int64",
            "sourceColumn": "NewLogo",
            "lineageTag": "7bdc9738-d1d6-429f-92d3-3047df4e1336",
            "formatString": "0"
          },
          {
            "name": "ChurnedLogo",
            "dataType": "int64",
            "sourceColumn": "ChurnedLogo",
            "lineageTag": "163dc815-7161-404c-bbac-80a5d6aa99ae",
            "formatString": "0"
          },
          {
            "name": "IsSynthetic",
            "dataType": "string",
            "sourceColumn": "IsSynthetic",
            "lineageTag": "f9f33267-0068-4ba2-8499-834a0ced1b84",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_FactSubscriptionMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\FactSubscriptionMonthly.csv\"), [Delimiter=\",\", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"CustomerID\", type text}, {\"PlanID\", type text}, {\"ChannelID\", type text}, {\"RegionID\", type text}, {\"BeginningMRR\", type number}, {\"NewMRR\", type number}, {\"ExpansionMRR\", type number}, {\"ContractionMRR\", type number}, {\"ChurnMRR\", type number}, {\"EndingMRR\", type number}, {\"RecognizedRevenue\", type number}, {\"GrossMargin\", type number}, {\"Seats\", Int64.Type}, {\"StartingLogo\", Int64.Type}, {\"ActiveLogo\", Int64.Type}, {\"NewLogo\", Int64.Type}, {\"ChurnedLogo\", Int64.Type}, {\"IsSynthetic\", type text}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactMRRMovement",
        "lineageTag": "b03599d6-075f-4750-957b-69561b9ec630",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "lineageTag": "7cdf0ddc-63a2-42eb-8d47-ac77eea915fe",
            "summarizeBy": "none"
          },
          {
            "name": "MovementType",
            "dataType": "string",
            "sourceColumn": "MovementType",
            "lineageTag": "f13b00b9-e8ae-4d74-9388-699b22373621",
            "summarizeBy": "none"
          },
          {
            "name": "MovementSort",
            "dataType": "int64",
            "sourceColumn": "MovementSort",
            "lineageTag": "b1ccfff4-a7a0-460d-9ba9-77b1d73cf9b2",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "ARRMovement",
            "dataType": "double",
            "sourceColumn": "ARRMovement",
            "lineageTag": "65951bf3-5f1f-4c8d-bc43-497cae19fb5c",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "FavorableFlag",
            "dataType": "int64",
            "sourceColumn": "FavorableFlag",
            "lineageTag": "3d50e52f-5284-4942-aae0-c4f40c669e8e",
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "p_FactMRRMovement",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\FactMRRMovement.csv\"), [Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"MovementType\", type text}, {\"MovementSort\", Int64.Type}, {\"ARRMovement\", type number}, {\"FavorableFlag\", Int64.Type}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactCohortRetention",
        "lineageTag": "09b4fee6-9d52-4b34-aa28-6dafd0a75a4d",
        "columns": [
          {
            "name": "CohortMonth",
            "dataType": "dateTime",
            "sourceColumn": "CohortMonth",
            "lineageTag": "fc0fc9ea-ab40-407a-a47c-19c14b7ac530",
            "summarizeBy": "none"
          },
          {
            "name": "CohortLabel",
            "dataType": "string",
            "sourceColumn": "CohortLabel",
            "lineageTag": "0dadfff3-8af9-4a6a-bc06-eac958a840ef",
            "summarizeBy": "none"
          },
          {
            "name": "ActivityMonth",
            "dataType": "dateTime",
            "sourceColumn": "ActivityMonth",
            "lineageTag": "8b1dfbf4-e0d6-4dc3-8831-141d2d66f107",
            "summarizeBy": "none"
          },
          {
            "name": "MonthsSinceCohort",
            "dataType": "int64",
            "sourceColumn": "MonthsSinceCohort",
            "lineageTag": "2b886a9c-eaa6-4316-b85a-76a48b2647a8",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "PlanID",
            "dataType": "string",
            "sourceColumn": "PlanID",
            "lineageTag": "0380d2dd-35c6-4b64-a6d3-aa3a4e934009",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "70b38673-c0fd-4edf-a13d-9b8c14172f24",
            "summarizeBy": "none"
          },
          {
            "name": "CohortStartMRR",
            "dataType": "double",
            "sourceColumn": "CohortStartMRR",
            "lineageTag": "42d7a9f4-45cc-42d1-b59c-5b444a92438c",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "RetainedMRR",
            "dataType": "double",
            "sourceColumn": "RetainedMRR",
            "lineageTag": "48f46d30-74b6-48c8-8ef8-8f4bd1ace82c",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ExpansionMRR",
            "dataType": "double",
            "sourceColumn": "ExpansionMRR",
            "lineageTag": "167b8589-251a-4481-b588-8664757eb2ca",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ContractionMRR",
            "dataType": "double",
            "sourceColumn": "ContractionMRR",
            "lineageTag": "7a675e24-3d7f-4282-9403-2df4199f8cef",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "StartLogos",
            "dataType": "int64",
            "sourceColumn": "StartLogos",
            "lineageTag": "284f0e55-8021-486d-967e-231469528a33",
            "formatString": "0"
          },
          {
            "name": "ActiveLogos",
            "dataType": "int64",
            "sourceColumn": "ActiveLogos",
            "lineageTag": "2f9d7ef9-2de3-458f-9f20-fec918e6ee2e",
            "formatString": "0"
          },
          {
            "name": "ChurnedLogos",
            "dataType": "int64",
            "sourceColumn": "ChurnedLogos",
            "lineageTag": "7b52212a-9a54-48f9-8737-0d74064e9501",
            "formatString": "0"
          },
          {
            "name": "NetRetentionRate",
            "dataType": "double",
            "sourceColumn": "NetRetentionRate",
            "lineageTag": "4c5155b1-f63e-48f1-bb41-593f9e08b13b",
            "formatString": "0.0%"
          },
          {
            "name": "GrossRetentionRate",
            "dataType": "double",
            "sourceColumn": "GrossRetentionRate",
            "lineageTag": "f68ee417-7ed8-4e8e-8e0c-5d4ca1774b33",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_FactCohortRetention",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\FactCohortRetention.csv\"), [Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"CohortMonth\", type date}, {\"CohortLabel\", type text}, {\"ActivityMonth\", type date}, {\"MonthsSinceCohort\", Int64.Type}, {\"PlanID\", type text}, {\"ChannelID\", type text}, {\"CohortStartMRR\", type number}, {\"RetainedMRR\", type number}, {\"ExpansionMRR\", type number}, {\"ContractionMRR\", type number}, {\"StartLogos\", Int64.Type}, {\"ActiveLogos\", Int64.Type}, {\"ChurnedLogos\", Int64.Type}, {\"NetRetentionRate\", type number}, {\"GrossRetentionRate\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactAcquisitionMonthly",
        "lineageTag": "414840d9-0c10-4e1a-b6a8-48d396ba1821",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "lineageTag": "d4644f5a-adf3-446f-a580-92058afa368e",
            "summarizeBy": "none"
          },
          {
            "name": "PlanID",
            "dataType": "string",
            "sourceColumn": "PlanID",
            "lineageTag": "0443c656-09b8-4cda-b7e2-b0dd5fd47f48",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "8bdaf23c-8efb-481a-86c2-6673a6c2a456",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "6c3e92d1-043b-4362-afaf-1d18be9039a9",
            "summarizeBy": "none"
          },
          {
            "name": "NewCustomers",
            "dataType": "int64",
            "sourceColumn": "NewCustomers",
            "lineageTag": "8fd78464-7cdd-4083-baf6-649f41a3c74f",
            "formatString": "0"
          },
          {
            "name": "NewARRBooked",
            "dataType": "double",
            "sourceColumn": "NewARRBooked",
            "lineageTag": "d9d5d1d3-d39c-44cf-969f-60a000ded3ab",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "SalesMarketingSpend",
            "dataType": "double",
            "sourceColumn": "SalesMarketingSpend",
            "lineageTag": "311e436a-a488-419b-a6b6-c2d8cbe73c90",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "SalesPipelineARR",
            "dataType": "double",
            "sourceColumn": "SalesPipelineARR",
            "lineageTag": "9276aaae-9fce-412c-abaa-5e7849659124",
            "formatString": "$#,0;($#,0);$0"
          }
        ],
        "partitions": [
          {
            "name": "p_FactAcquisitionMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\FactAcquisitionMonthly.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"PlanID\", type text}, {\"ChannelID\", type text}, {\"RegionID\", type text}, {\"NewCustomers\", Int64.Type}, {\"NewARRBooked\", type number}, {\"SalesMarketingSpend\", type number}, {\"SalesPipelineARR\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactFinanceMonthly",
        "lineageTag": "2e769849-c978-49dc-85e2-e4e11c16aa6e",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "lineageTag": "5ac6b5ba-56c9-4d5c-986d-3a37c380f3c6",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "sourceColumn": "Revenue",
            "lineageTag": "05b5b382-96cc-4844-bc1d-8f01f56b147b",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "COGS",
            "dataType": "double",
            "sourceColumn": "COGS",
            "lineageTag": "f1bf26bd-11b5-4b8b-a497-d44317d1b975"
          },
          {
            "name": "GrossMargin",
            "dataType": "double",
            "sourceColumn": "GrossMargin",
            "lineageTag": "6c00c201-be87-4dc8-9879-a409f38bb0b0",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "SalesMarketingExpense",
            "dataType": "double",
            "sourceColumn": "SalesMarketingExpense",
            "lineageTag": "3b5dffb3-885f-48c9-a2e8-480a09b3124e",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ResearchDevelopmentExpense",
            "dataType": "double",
            "sourceColumn": "ResearchDevelopmentExpense",
            "lineageTag": "d0666c7c-9a74-4d93-bc61-ba30811f18c8",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "GeneralAdminExpense",
            "dataType": "double",
            "sourceColumn": "GeneralAdminExpense",
            "lineageTag": "a6e95b38-0868-4dbc-b47d-a278975e63a7",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "CustomerSuccessExpense",
            "dataType": "double",
            "sourceColumn": "CustomerSuccessExpense",
            "lineageTag": "28935bef-6dc7-4f5f-a6ab-8d6adc76893e",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "EBITDA",
            "dataType": "double",
            "sourceColumn": "EBITDA",
            "lineageTag": "a7a8ca26-4964-4505-8e2d-253fda5fe683"
          },
          {
            "name": "CashBalance",
            "dataType": "double",
            "sourceColumn": "CashBalance",
            "lineageTag": "9eea9228-7abf-43cf-94ff-44874d81d4a4",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "NetBurn",
            "dataType": "double",
            "sourceColumn": "NetBurn",
            "lineageTag": "69e238a7-44ea-4d44-b56b-778997076513",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ActualARR",
            "dataType": "double",
            "sourceColumn": "ActualARR",
            "lineageTag": "13216509-bf3c-46c9-b4c9-d43b9cfbdafb",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "PlanARR",
            "dataType": "double",
            "sourceColumn": "PlanARR",
            "lineageTag": "6d141c33-fb36-4312-a002-59f3f37db3c1",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ForecastARR",
            "dataType": "double",
            "sourceColumn": "ForecastARR",
            "lineageTag": "4cdff1aa-04b6-4c34-b7fb-2f12cfd723bb",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ARRGrowthPct",
            "dataType": "double",
            "sourceColumn": "ARRGrowthPct",
            "lineageTag": "28beaf4d-da28-4be4-b7ad-062e29018d4f",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_FactFinanceMonthly",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\FactFinanceMonthly.csv\"), [Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"Revenue\", type number}, {\"COGS\", type number}, {\"GrossMargin\", type number}, {\"SalesMarketingExpense\", type number}, {\"ResearchDevelopmentExpense\", type number}, {\"GeneralAdminExpense\", type number}, {\"CustomerSuccessExpense\", type number}, {\"EBITDA\", type number}, {\"CashBalance\", type number}, {\"NetBurn\", type number}, {\"ActualARR\", type number}, {\"PlanARR\", type number}, {\"ForecastARR\", type number}, {\"ARRGrowthPct\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactForecast",
        "lineageTag": "485b5d1d-a8c5-44ce-9c49-df8f234b9caf",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "lineageTag": "4c1860de-e8a3-459e-93ca-a803c08d6544",
            "summarizeBy": "none"
          },
          {
            "name": "Scenario",
            "dataType": "string",
            "sourceColumn": "Scenario",
            "lineageTag": "0c71d63f-fe25-4105-b703-d8655313685e",
            "summarizeBy": "none"
          },
          {
            "name": "ARRValue",
            "dataType": "double",
            "sourceColumn": "ARRValue",
            "lineageTag": "3c9ac54e-4bf9-437a-a411-4c81a55ce50d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "RevenueValue",
            "dataType": "double",
            "sourceColumn": "RevenueValue",
            "lineageTag": "539828b7-64c8-4daf-a24a-128fa3727b4e",
            "formatString": "$#,0;($#,0);$0"
          }
        ],
        "partitions": [
          {
            "name": "p_FactForecast",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\FactForecast.csv\"), [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"Scenario\", type text}, {\"ARRValue\", type number}, {\"RevenueValue\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactAccountHealth",
        "lineageTag": "ddf8102d-1c90-4bd1-a664-889a8d9375c9",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "lineageTag": "3b46d6b0-ccbd-4cd6-982f-7d1dbcfe36a6",
            "summarizeBy": "none"
          },
          {
            "name": "AccountName",
            "dataType": "string",
            "sourceColumn": "AccountName",
            "lineageTag": "a0aa9651-c7ba-457a-ba91-0b9e152a4044",
            "summarizeBy": "none"
          },
          {
            "name": "PlanID",
            "dataType": "string",
            "sourceColumn": "PlanID",
            "lineageTag": "794ba4cf-5824-4f57-a8e8-8ba565ab8af9",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "8fd0a049-b495-4169-909c-e7deed2169f0",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "52dad6a6-b4ae-42f8-8936-db7197e21aed",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "lineageTag": "447fb4e5-301c-4702-91f2-c623f8b241b7",
            "summarizeBy": "none"
          },
          {
            "name": "Industry",
            "dataType": "string",
            "sourceColumn": "Industry",
            "lineageTag": "5960abbd-46c5-47c5-93b8-8ce3d5366fbe",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentARR",
            "dataType": "double",
            "sourceColumn": "CurrentARR",
            "lineageTag": "f36adb26-bd15-4ee9-9b61-8b43117da0dd",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "Seats",
            "dataType": "int64",
            "sourceColumn": "Seats",
            "lineageTag": "e1079298-9884-417f-8d20-7d78f2c978d8",
            "formatString": "0"
          },
          {
            "name": "HealthScore",
            "dataType": "double",
            "sourceColumn": "HealthScore",
            "lineageTag": "4d434237-7037-489f-a2fe-3b2308d003c0"
          },
          {
            "name": "RenewalRisk",
            "dataType": "string",
            "sourceColumn": "RenewalRisk",
            "lineageTag": "e17af764-e18c-4ea7-ac60-5043e7f8ae43",
            "summarizeBy": "none"
          },
          {
            "name": "NextAction",
            "dataType": "string",
            "sourceColumn": "NextAction",
            "lineageTag": "0fa128a4-36c4-4e7a-a12e-3e4204a8909c",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "p_FactAccountHealth",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\FactAccountHealth.csv\"), [Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"CustomerID\", type text}, {\"AccountName\", type text}, {\"PlanID\", type text}, {\"ChannelID\", type text}, {\"RegionID\", type text}, {\"Segment\", type text}, {\"Industry\", type text}, {\"CurrentARR\", type number}, {\"Seats\", Int64.Type}, {\"HealthScore\", type number}, {\"RenewalRisk\", type text}, {\"NextAction\", type text}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "MonthlyKPIs",
        "lineageTag": "0f91e46b-4b62-467a-ab26-25b77a9582c2",
        "columns": [
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "MonthStart",
            "lineageTag": "9fc64f12-a6a6-4a8e-8c29-36c7f6e74082",
            "summarizeBy": "none"
          },
          {
            "name": "BeginningMRR",
            "dataType": "double",
            "sourceColumn": "BeginningMRR",
            "lineageTag": "5f5039af-df31-4d94-8d44-9fcbe5813d7a",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "NewMRR",
            "dataType": "double",
            "sourceColumn": "NewMRR",
            "lineageTag": "224273ff-0303-45ba-8938-c96ffd0218e8",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ExpansionMRR",
            "dataType": "double",
            "sourceColumn": "ExpansionMRR",
            "lineageTag": "3f7ec028-5f2d-45a1-98e2-28f0d69d15a5",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ContractionMRR",
            "dataType": "double",
            "sourceColumn": "ContractionMRR",
            "lineageTag": "d1210e33-cef8-4326-99d9-040dd617db13",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "ChurnMRR",
            "dataType": "double",
            "sourceColumn": "ChurnMRR",
            "lineageTag": "f014a7d2-ed95-4a2a-b33e-654802ca0521",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "EndingMRR",
            "dataType": "double",
            "sourceColumn": "EndingMRR",
            "lineageTag": "fc1e0f25-b9d1-49ff-ab21-037c0cfcff53",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "RecognizedRevenue",
            "dataType": "double",
            "sourceColumn": "RecognizedRevenue",
            "lineageTag": "53aacba6-4b86-405f-b8ec-9885b1a8aeb5",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "GrossMargin",
            "dataType": "double",
            "sourceColumn": "GrossMargin",
            "lineageTag": "e4248af3-9ba3-4848-a175-002e4a29f17d",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "StartingCustomers",
            "dataType": "int64",
            "sourceColumn": "StartingCustomers",
            "lineageTag": "2b0b600a-b180-46bf-9235-6b21e1befb37",
            "formatString": "0"
          },
          {
            "name": "ActiveCustomers",
            "dataType": "int64",
            "sourceColumn": "ActiveCustomers",
            "lineageTag": "7030756b-16b2-4105-8c6f-e228bcd2f320",
            "formatString": "0"
          },
          {
            "name": "NewCustomers",
            "dataType": "int64",
            "sourceColumn": "NewCustomers",
            "lineageTag": "1573f39e-8fc9-4c29-a196-d55cad9be556",
            "formatString": "0"
          },
          {
            "name": "ChurnedCustomers",
            "dataType": "int64",
            "sourceColumn": "ChurnedCustomers",
            "lineageTag": "a0ccc503-b229-4d2c-b4fb-f30e394dc192",
            "formatString": "0"
          },
          {
            "name": "MonthLabel",
            "dataType": "string",
            "sourceColumn": "MonthLabel",
            "lineageTag": "db3f74fd-bc0b-4f97-8fd5-7c35bceff91b",
            "summarizeBy": "none"
          },
          {
            "name": "MonthIndex",
            "dataType": "int64",
            "sourceColumn": "MonthIndex",
            "lineageTag": "f0a36a58-4c21-4b8e-b4a0-edf40e6e688f",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "ARR",
            "dataType": "double",
            "sourceColumn": "ARR",
            "lineageTag": "88ec3410-d57c-4e88-8cab-410690dadb7f",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "NetNewARR",
            "dataType": "double",
            "sourceColumn": "NetNewARR",
            "lineageTag": "66bb6656-c24f-4d89-a016-bf1aec4b78ad",
            "formatString": "$#,0;($#,0);$0"
          },
          {
            "name": "NRR",
            "dataType": "double",
            "sourceColumn": "NRR",
            "lineageTag": "3ee362c2-7560-45be-a40b-d8753478f19c"
          },
          {
            "name": "GRR",
            "dataType": "double",
            "sourceColumn": "GRR",
            "lineageTag": "1f1b0207-6e9b-43b8-ac3e-57d482b42670"
          },
          {
            "name": "RevenueChurnRate",
            "dataType": "double",
            "sourceColumn": "RevenueChurnRate",
            "lineageTag": "c4ade086-d35b-4ba6-bfbf-5bfafd4e4ac8",
            "formatString": "0.0%"
          },
          {
            "name": "LogoChurnRate",
            "dataType": "double",
            "sourceColumn": "LogoChurnRate",
            "lineageTag": "404d41fc-e6a3-44d8-93ce-779c627399c1",
            "formatString": "0.0%"
          },
          {
            "name": "GrossMarginPct",
            "dataType": "double",
            "sourceColumn": "GrossMarginPct",
            "lineageTag": "e7cd23c8-25b9-40ea-bb05-09a00e24f2ba",
            "formatString": "0.0%"
          },
          {
            "name": "ARRGrowthPct",
            "dataType": "double",
            "sourceColumn": "ARRGrowthPct",
            "lineageTag": "137f84a2-e090-44fc-9794-a5de80cab482",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "p_MonthlyKPIs",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\Win\\\\OneDrive\\\\Codex\\\\Portfolio\\\\BI\\\\Project 15 - SaaS CFO Metrics\\\\data\\\\prepared\\\\MonthlyKPIs.csv\"), [Delimiter=\",\", Columns=23, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"MonthStart\", type date}, {\"BeginningMRR\", type number}, {\"NewMRR\", type number}, {\"ExpansionMRR\", type number}, {\"ContractionMRR\", type number}, {\"ChurnMRR\", type number}, {\"EndingMRR\", type number}, {\"RecognizedRevenue\", type number}, {\"GrossMargin\", type number}, {\"StartingCustomers\", Int64.Type}, {\"ActiveCustomers\", Int64.Type}, {\"NewCustomers\", Int64.Type}, {\"ChurnedCustomers\", Int64.Type}, {\"MonthLabel\", type text}, {\"MonthIndex\", Int64.Type}, {\"ARR\", type number}, {\"NetNewARR\", type number}, {\"NRR\", type number}, {\"GRR\", type number}, {\"RevenueChurnRate\", type number}, {\"LogoChurnRate\", type number}, {\"GrossMarginPct\", type number}, {\"ARRGrowthPct\", type number}}, \"en-US\")",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "KPI_Measures",
        "lineageTag": "e1df893e-a73e-4155-b8be-8771c3ecfb50",
        "columns": [
          {
            "name": "MeasureName",
            "dataType": "string",
            "sourceColumn": "MeasureName",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "p_KPI_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = #table(type table [MeasureName = text], {{\"KPI\"}}) in Source"
            }
          }
        ],
        "measures": [
          {
            "name": "Beginning MRR",
            "expression": "SUM ( FactSubscriptionMonthly[BeginningMRR] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "9e2145c1-9a3c-4f35-a276-0f18874d6487"
          },
          {
            "name": "Ending MRR",
            "expression": "SUM ( FactSubscriptionMonthly[EndingMRR] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "f0fef635-484d-4146-9189-235daaf02dde"
          },
          {
            "name": "ARR",
            "expression": "[Ending MRR] * 12",
            "formatString": "$#,0,,.0M",
            "lineageTag": "785a0457-6776-4526-8e20-91d6e95b34da"
          },
          {
            "name": "New ARR",
            "expression": "SUM ( FactSubscriptionMonthly[NewMRR] ) * 12",
            "formatString": "$#,0,,.0M",
            "lineageTag": "d2fc41b5-d0a5-4c6b-a7bd-7371c8262559"
          },
          {
            "name": "Expansion ARR",
            "expression": "SUM ( FactSubscriptionMonthly[ExpansionMRR] ) * 12",
            "formatString": "$#,0,,.0M",
            "lineageTag": "55d0d224-e19d-4552-8fbb-e1bf9a7800c8"
          },
          {
            "name": "Contraction ARR",
            "expression": "ABS ( SUM ( FactSubscriptionMonthly[ContractionMRR] ) ) * 12",
            "formatString": "$#,0,,.0M",
            "lineageTag": "626ad466-ef44-4fe7-9c59-bf7a671161bc"
          },
          {
            "name": "Churn ARR",
            "expression": "ABS ( SUM ( FactSubscriptionMonthly[ChurnMRR] ) ) * 12",
            "formatString": "$#,0,,.0M",
            "lineageTag": "2473296d-9926-4875-b939-69a481bd6a5b"
          },
          {
            "name": "Net New ARR",
            "expression": "[New ARR] + [Expansion ARR] - [Contraction ARR] - [Churn ARR]",
            "formatString": "$#,0,,.0M",
            "lineageTag": "a76c5a66-9839-4f94-9794-7d9807857608"
          },
          {
            "name": "ARR Movement",
            "expression": "SUM ( FactMRRMovement[ARRMovement] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "b2644e3e-b159-458f-bee5-f1ef04e8be4f"
          },
          {
            "name": "Revenue",
            "expression": "SUM ( FactSubscriptionMonthly[RecognizedRevenue] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "ec6ddc8f-704b-43ef-9902-0f054edb81ef"
          },
          {
            "name": "Gross Margin",
            "expression": "SUM ( FactSubscriptionMonthly[GrossMargin] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "a0d58969-6d9f-4b13-aa7d-0192cdf2271b"
          },
          {
            "name": "Gross Margin %",
            "expression": "DIVIDE ( [Gross Margin], [Revenue] )",
            "formatString": "0.0%",
            "lineageTag": "a6f70f75-3018-4896-b163-f2d7096efdde"
          },
          {
            "name": "Starting Customers",
            "expression": "SUM ( FactSubscriptionMonthly[StartingLogo] )",
            "formatString": "#,0",
            "lineageTag": "5a2b73a0-903e-4a71-a6fc-a3e7a63b8bb0"
          },
          {
            "name": "Active Customers",
            "expression": "SUM ( FactSubscriptionMonthly[ActiveLogo] )",
            "formatString": "#,0",
            "lineageTag": "09077c4f-8923-4ad6-b6be-8cfb444c53e1"
          },
          {
            "name": "New Customers",
            "expression": "SUM ( FactSubscriptionMonthly[NewLogo] )",
            "formatString": "#,0",
            "lineageTag": "a08a1297-2e01-4c07-ab40-c74de8c647ed"
          },
          {
            "name": "Churned Customers",
            "expression": "SUM ( FactSubscriptionMonthly[ChurnedLogo] )",
            "formatString": "#,0",
            "lineageTag": "7306e4b9-ad7e-41a2-a625-f4b6bcb60978"
          },
          {
            "name": "NRR",
            "expression": "DIVIDE ( [Ending MRR] - SUM ( FactSubscriptionMonthly[NewMRR] ), [Beginning MRR] )",
            "formatString": "0.0%",
            "lineageTag": "826bea0d-758d-494e-a4af-29b71c5c14c9"
          },
          {
            "name": "GRR",
            "expression": "DIVIDE ( [Beginning MRR] - [Contraction ARR] / 12 - [Churn ARR] / 12, [Beginning MRR] )",
            "formatString": "0.0%",
            "lineageTag": "f56a816f-32a5-45c9-a021-ce7e22118427"
          },
          {
            "name": "Revenue Churn Rate",
            "expression": "DIVIDE ( [Churn ARR], [Beginning MRR] * 12 )",
            "formatString": "0.0%",
            "lineageTag": "201cf65d-ed08-43c5-9add-5c43180bc4e9"
          },
          {
            "name": "Logo Churn Rate",
            "expression": "DIVIDE ( [Churned Customers], [Starting Customers] )",
            "formatString": "0.0%",
            "lineageTag": "19d4efc5-6e75-4152-bf1b-bf68f6b47d8b"
          },
          {
            "name": "S&M Spend",
            "expression": "SUM ( FactAcquisitionMonthly[SalesMarketingSpend] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "cb059cee-24a5-4132-9812-816d17b235bf"
          },
          {
            "name": "New ARR Booked",
            "expression": "SUM ( FactAcquisitionMonthly[NewARRBooked] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "5c5e4844-2198-4181-a9d1-2a1f22eb8603"
          },
          {
            "name": "CAC",
            "expression": "DIVIDE ( [S&M Spend], SUM ( FactAcquisitionMonthly[NewCustomers] ) )",
            "formatString": "$#,0",
            "lineageTag": "89d4c570-8b8c-44bd-b266-7572f5ccd0d5"
          },
          {
            "name": "ARPA",
            "expression": "DIVIDE ( [Ending MRR], [Active Customers] )",
            "formatString": "$#,0",
            "lineageTag": "f03a7cab-d38c-4db6-8c1f-c488df3294bc"
          },
          {
            "name": "LTV",
            "expression": "DIVIDE ( [ARPA] * 12 * [Gross Margin %], [Revenue Churn Rate] )",
            "formatString": "$#,0",
            "lineageTag": "a15ed4c8-c0b8-473d-8a65-4231138c0333"
          },
          {
            "name": "LTV CAC Ratio",
            "expression": "DIVIDE ( [LTV], [CAC] )",
            "formatString": "0.0x",
            "lineageTag": "a78fdf20-f38f-43d7-b0d2-288b09b7047a"
          },
          {
            "name": "CAC Payback Months",
            "expression": "DIVIDE ( [CAC], DIVIDE ( [Gross Margin], [Active Customers] ) )",
            "formatString": "0.0",
            "lineageTag": "c34df212-3b24-432a-ad84-db3da1540cbb"
          },
          {
            "name": "Magic Number",
            "expression": "DIVIDE ( [Net New ARR], [S&M Spend] )",
            "formatString": "0.0x",
            "lineageTag": "0731f6ee-d380-4d6d-a79c-1286719cbc36"
          },
          {
            "name": "EBITDA",
            "expression": "SUM ( FactFinanceMonthly[EBITDA] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "8660933b-53dc-4d5f-bdce-3cae6c443f2f"
          },
          {
            "name": "EBITDA Margin",
            "expression": "DIVIDE ( [EBITDA], SUM ( FactFinanceMonthly[Revenue] ) )",
            "formatString": "0.0%",
            "lineageTag": "1cc34abb-276b-4b55-9a7b-cc0e035a59db"
          },
          {
            "name": "ARR Growth %",
            "expression": "AVERAGE ( FactFinanceMonthly[ARRGrowthPct] )",
            "formatString": "0.0%",
            "lineageTag": "85cc2fe4-8a5f-4e62-ac5d-0b28b1c114a2"
          },
          {
            "name": "Rule of 40",
            "expression": "[ARR Growth %] + [EBITDA Margin]",
            "formatString": "0.0%",
            "lineageTag": "d744f1dd-385f-4242-b612-5057830ae4e6"
          },
          {
            "name": "Net Burn",
            "expression": "SUM ( FactFinanceMonthly[NetBurn] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "06c277a1-9bbd-49d3-a6c6-028cefd5d4f6"
          },
          {
            "name": "Cash Balance",
            "expression": "SUM ( FactFinanceMonthly[CashBalance] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "4d4c7c66-ebc7-48af-9ecb-7115f58b28bf"
          },
          {
            "name": "Burn Multiple",
            "expression": "DIVIDE ( [Net Burn], DIVIDE ( [Net New ARR], 12 ) )",
            "formatString": "0.0x",
            "lineageTag": "9881c4f6-fd98-41d7-a7bf-507d2e3736c3"
          },
          {
            "name": "Forecast ARR",
            "expression": "SUM ( FactFinanceMonthly[ForecastARR] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "96cca008-d1c4-45b5-b40d-5e4673cbf47b"
          },
          {
            "name": "Plan ARR",
            "expression": "SUM ( FactFinanceMonthly[PlanARR] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "7ff66f7e-182e-417a-8217-0405422955fb"
          },
          {
            "name": "Forecast Accuracy",
            "expression": "1 - DIVIDE ( ABS ( [ARR] - [Forecast ARR] ), [ARR] )",
            "formatString": "0.0%",
            "lineageTag": "e333644b-77c6-4420-9c3e-52876db45a86"
          },
          {
            "name": "Cohort NRR",
            "expression": "DIVIDE ( SUM ( FactCohortRetention[RetainedMRR] ), SUM ( FactCohortRetention[CohortStartMRR] ) )",
            "formatString": "0.0%",
            "lineageTag": "7da3bf07-2ae6-4048-adea-197aaa19b19c"
          },
          {
            "name": "Cohort GRR",
            "expression": "DIVIDE ( SUM ( FactCohortRetention[RetainedMRR] ) - SUM ( FactCohortRetention[ExpansionMRR] ), SUM ( FactCohortRetention[CohortStartMRR] ) )",
            "formatString": "0.0%",
            "lineageTag": "867ea29b-69c6-477d-88e4-0cb31a167d6a"
          },
          {
            "name": "Cohort Active Logos",
            "expression": "SUM ( FactCohortRetention[ActiveLogos] )",
            "formatString": "#,0",
            "lineageTag": "343862c1-26b2-4f77-87f1-133e6c7b37b6"
          },
          {
            "name": "Cohort LTV",
            "expression": "DIVIDE ( SUM ( FactCohortRetention[RetainedMRR] ) * 12, SUM ( FactCohortRetention[StartLogos] ) )",
            "formatString": "$#,0",
            "lineageTag": "3dd7d252-cd2b-4dd9-872c-d6e2cf1cd46a"
          },
          {
            "name": "Scenario ARR",
            "expression": "SUM ( FactForecast[ARRValue] )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "7802c568-f7d0-4382-a973-e89367c2f94c"
          },
          {
            "name": "Account Health Score",
            "expression": "AVERAGE ( FactAccountHealth[HealthScore] )",
            "formatString": "0.0",
            "lineageTag": "1dda7b24-61d0-4d1b-b080-4064faf5a45a"
          },
          {
            "name": "Latest ARR",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "130f8813-ee30-47a8-9ba5-6c4717f3fff3"
          },
          {
            "name": "Latest Net New ARR",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [Net New ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "d339d21c-d6e9-4c83-a990-35a3538f5a88"
          },
          {
            "name": "Latest NRR",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [NRR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "0.0%",
            "lineageTag": "93a65f2b-0ff7-4fcf-960c-ae6ee59f555f"
          },
          {
            "name": "Latest GRR",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [GRR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "0.0%",
            "lineageTag": "52822606-459e-4191-a2e3-814f30a30ca3"
          },
          {
            "name": "Latest Expansion ARR",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [Expansion ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "16141bde-d6d1-4a9f-96c3-e211b61c2e95"
          },
          {
            "name": "Latest Churn ARR",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [Churn ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "$#,0,,.0M",
            "lineageTag": "43f7cb68-b804-4b45-a083-9504e946ed70"
          },
          {
            "name": "Latest Logo Churn Rate",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [Logo Churn Rate], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "0.0%",
            "lineageTag": "9f023d18-3b9d-4554-b399-a4bd9213bdb1"
          },
          {
            "name": "Latest CAC Payback",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [CAC Payback Months], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "0.0",
            "lineageTag": "1fa9b2a1-faa8-4508-bd25-bf4229212cd1"
          },
          {
            "name": "Latest LTV CAC Ratio",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [LTV CAC Ratio], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "0.0x",
            "lineageTag": "19c59505-0e27-4ff1-9537-c2b6a2225d77"
          },
          {
            "name": "Latest Rule of 40",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [Rule of 40], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "0.0%",
            "lineageTag": "43be4c4a-75d4-4d66-ae4f-79e76c2c4190"
          },
          {
            "name": "Latest Burn Multiple",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [Burn Multiple], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "0.0x",
            "lineageTag": "786f67e7-ebd3-49b0-a095-38b7873ba5dc"
          },
          {
            "name": "Latest Forecast Accuracy",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nRETURN\n    CALCULATE ( [Forecast Accuracy], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )",
            "formatString": "0.0%",
            "lineageTag": "5751271c-d6c2-408b-a59e-b10f33107982"
          },
          {
            "name": "ARR YoY %",
            "expression": "DIVIDE ( [Latest ARR] - CALCULATE ( [ARR], DATEADD ( DimDate[MonthStart], -12, MONTH ) ), CALCULATE ( [ARR], DATEADD ( DimDate[MonthStart], -12, MONTH ) ) )",
            "formatString": "0.0%",
            "lineageTag": "42d30913-845b-4790-b07f-686ff30704a9"
          },
          {
            "name": "NRR YoY pp",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [NRR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [NRR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nRETURN\n    CurrentValue - PriorValue",
            "formatString": "0.0%",
            "lineageTag": "351a7971-9244-4450-b3d9-8d72989b2029"
          },
          {
            "name": "Forecast Accuracy YoY pp",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [Forecast Accuracy], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [Forecast Accuracy], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nRETURN\n    CurrentValue - PriorValue",
            "formatString": "0.0%",
            "lineageTag": "9cd6fa19-9716-4f8c-941f-2b9247d35c7c"
          },
          {
            "name": "Portfolio Signature SVG",
            "expression": "VAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='148' height='78' viewBox='0 0 148 78'>\"\n        & \"<rect x='0' y='0' width='148' height='78' rx='11' fill='%2310243A'/>\"\n        & \"<rect x='12' y='12' width='34' height='34' rx='8' fill='%232563EB'/>\"\n        & \"<path d='M20 39 L27 24 L34 39' stroke='%23FFFFFF' stroke-width='3' fill='none' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<text x='56' y='28' font-family='Segoe UI Semibold' font-size='16' fill='%23FFFFFF'>SaaS CFO</text>\"\n        & \"<text x='56' y='46' font-family='Segoe UI' font-size='9.2' fill='%23D8E2EF'>Project 15</text>\"\n        & \"<text x='12' y='66' font-family='Segoe UI' font-size='9.2' fill='%2394A3B8'>Metrics cockpit</text>\"\n        & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "lineageTag": "d828709f-4758-48fc-88a9-de8be74e2476",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Lens Summary SVG",
            "expression": "VAR YearText =\n    IF ( HASONEVALUE ( DimDate[Year] ), FORMAT ( SELECTEDVALUE ( DimDate[Year] ), \"0\" ), \"All Years\" )\nVAR SegmentCount = COUNTROWS ( VALUES ( DimPlan[Segment] ) )\nVAR SegmentTotal = CALCULATE ( COUNTROWS ( VALUES ( DimPlan[Segment] ) ), ALL ( DimPlan[Segment] ) )\nVAR SegmentText =\n    IF (\n        NOT ISFILTERED ( DimPlan[Segment] ) || SegmentCount = SegmentTotal,\n        \"All Segments\",\n        IF ( SegmentCount = 1, SELECTEDVALUE ( DimPlan[Segment] ), FORMAT ( SegmentCount, \"0\" ) & \" Segments\" )\n    )\nVAR MotionCount = COUNTROWS ( VALUES ( DimChannel[Motion] ) )\nVAR MotionTotal = CALCULATE ( COUNTROWS ( VALUES ( DimChannel[Motion] ) ), ALL ( DimChannel[Motion] ) )\nVAR MotionText =\n    IF (\n        NOT ISFILTERED ( DimChannel[Motion] ) || MotionCount = MotionTotal,\n        \"All Motions\",\n        IF ( MotionCount = 1, SELECTEDVALUE ( DimChannel[Motion] ), FORMAT ( MotionCount, \"0\" ) & \" Motions\" )\n    )\nVAR RegionCount = COUNTROWS ( VALUES ( DimRegion[Region] ) )\nVAR RegionTotal = CALCULATE ( COUNTROWS ( VALUES ( DimRegion[Region] ) ), ALL ( DimRegion[Region] ) )\nVAR RegionText =\n    IF (\n        NOT ISFILTERED ( DimRegion[Region] ) || RegionCount = RegionTotal,\n        \"All Regions\",\n        IF ( RegionCount = 1, SELECTEDVALUE ( DimRegion[Region] ), FORMAT ( RegionCount, \"0\" ) & \" Regions\" )\n    )\nVAR Line1 = LEFT ( YearText & \" | \" & SegmentText, 30 )\nVAR Line2 = LEFT ( MotionText & \" | \" & RegionText, 32 )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='148' height='80' viewBox='0 0 148 80'>\"\n        & \"<rect x='1' y='1' width='146' height='78' rx='9' fill='%2310243A' stroke='%232563EB' stroke-width='1.2'/>\"\n        & \"<text x='12' y='21' font-family='Segoe UI' font-size='10.2' font-weight='700' fill='%23D8E2EF'>Current Lens</text>\"\n        & \"<circle cx='130' cy='17' r='3.6' fill='%230F766E'/>\"\n        & \"<text x='12' y='43' font-family='Segoe UI' font-size='11.6' font-weight='750' fill='%23FFFFFF'>\" & Line1 & \"</text>\"\n        & \"<text x='12' y='62' font-family='Segoe UI' font-size='9.5' fill='%23D8E2EF'>\" & Line2 & \"</text>\"\n        & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "lineageTag": "a9beb65a-063e-4d2c-8f6d-ee469048346e",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Executive Decision Chips SVG",
            "expression": "VAR Chip1Text = \"ARR: \" & FORMAT ( [Latest ARR], \"$#,0,,.0M\" )\nVAR Chip2Text = \"Rule 40: \" & FORMAT ( [Latest Rule of 40], \"0.0%\" )\nVAR Chip3Text = \"NRR: \" & FORMAT ( [Latest NRR], \"0.0%\" )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\"\n        & \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\"\n        & \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='%23E7F0FF' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='13' y='13' width='11' height='11' rx='3' fill='%232563EB'/>\"\n        & \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\"\n        & \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='%23E6F4EC' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='169' y='13' width='11' height='11' rx='3' fill='%2316A34A'/>\"\n        & \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\"\n        & \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='%23E7F0FF' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='333' y='13' width='11' height='11' rx='3' fill='%230F766E'/>\"\n        & \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\"\n        & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "lineageTag": "921217aa-b1c0-4452-9d19-3d9782d5e7ec",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Retention Decision Chips SVG",
            "expression": "VAR Chip1Text = \"NRR: \" & FORMAT ( [Latest NRR], \"0.0%\" )\nVAR Chip2Text = \"GRR: \" & FORMAT ( [Latest GRR], \"0.0%\" )\nVAR Chip3Text = \"Logo Churn: \" & FORMAT ( [Latest Logo Churn Rate], \"0.0%\" )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\"\n        & \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\"\n        & \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='%23E7F0FF' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='13' y='13' width='11' height='11' rx='3' fill='%230F766E'/>\"\n        & \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\"\n        & \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='%23E6F4EC' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='169' y='13' width='11' height='11' rx='3' fill='%2316A34A'/>\"\n        & \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\"\n        & \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='%23FCE7E7' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='333' y='13' width='11' height='11' rx='3' fill='%23DC2626'/>\"\n        & \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\"\n        & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "lineageTag": "253a6202-a6ea-427e-87ff-69215cbe0d12",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Efficiency Decision Chips SVG",
            "expression": "VAR Chip1Text = \"Payback: \" & FORMAT ( [Latest CAC Payback], \"0.0\" )\nVAR Chip2Text = \"Burn: \" & FORMAT ( [Latest Burn Multiple], \"0.0x\" )\nVAR Chip3Text = \"Forecast: \" & FORMAT ( [Latest Forecast Accuracy], \"0.0%\" )\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='490' height='38' viewBox='0 0 490 38'>\"\n        & \"<rect x='0' y='0' width='490' height='38' rx='8' fill='none'/>\"\n        & \"<rect x='0.5' y='2.5' width='142' height='33' rx='7' fill='%23FFF3D6' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='13' y='13' width='11' height='11' rx='3' fill='%23F59E0B'/>\"\n        & \"<text x='36' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip1Text & \"</text>\"\n        & \"<rect x='156.5' y='2.5' width='150' height='33' rx='7' fill='%23FCE7E7' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='169' y='13' width='11' height='11' rx='3' fill='%23DC2626'/>\"\n        & \"<text x='192' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip2Text & \"</text>\"\n        & \"<rect x='320.5' y='2.5' width='168' height='33' rx='7' fill='%23E7F0FF' stroke='%23FFFFFF' stroke-width='0.9'/>\"\n        & \"<rect x='333' y='13' width='11' height='11' rx='3' fill='%232563EB'/>\"\n        & \"<text x='356' y='23.5' font-family='Segoe UI Semibold' font-size='12.5' fill='%23261C3C'>\" & Chip3Text & \"</text>\"\n        & \"</svg>\"\nRETURN\n    \"data:image/svg+xml;utf8,\" & SVG",
            "formatString": "",
            "lineageTag": "87b58ea5-36c4-4cdf-8a9b-7b975b7f140d",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "ARR KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"$#,0,,.0M\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"$#,0,,.0M\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue >= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [ARR]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%232563EB' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%232563EB' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>ARR</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%232563EB'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "bd494d1e-f0e8-422b-9bd3-a8a70461647c",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Net New ARR KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [Net New ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [Net New ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"$#,0,,.0M\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"$#,0,,.0M\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue >= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [Net New ARR]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%2316A34A' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%2316A34A' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>Net New ARR</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%2316A34A'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "808d6729-7fe0-4bf4-a50c-4bfeb2d135e9",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "NRR KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [NRR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [NRR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue >= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [NRR]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%230F766E' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%230F766E' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>NRR</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%230F766E'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "0ade51ca-2362-451e-8c4e-0338587e35d5",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "GRR KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [GRR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [GRR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue >= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [GRR]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%2316A34A' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%2316A34A' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>GRR</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%2316A34A'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "63547277-1e5e-4f54-af45-70253cad81a1",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Expansion ARR KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [Expansion ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [Expansion ARR], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"$#,0,,.0M\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"$#,0,,.0M\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue >= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [Expansion ARR]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%237C3AED' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%237C3AED' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>Expansion ARR</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%237C3AED'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "cde8dd38-c820-47d0-bc08-e5e5f90bd29a",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Logo Churn KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [Logo Churn Rate], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [Logo Churn Rate], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue <= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [Logo Churn Rate]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], DESC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%23DC2626' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%23DC2626' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>Logo Churn</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%23DC2626'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "b7f75e75-9e57-4637-86fe-ae8f183ef6e9",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Rule of 40 KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [Rule of 40], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [Rule of 40], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue >= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [Rule of 40]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%230EA5E9' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%230EA5E9' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>Rule of 40</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%230EA5E9'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "c676efef-7743-4d77-b72b-615af5592e4b",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "CAC Payback KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [CAC Payback Months], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [CAC Payback Months], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue <= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [CAC Payback Months]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], DESC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%23F59E0B' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%23F59E0B' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>Payback</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%23F59E0B'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "d66d27fa-5289-4113-8f1e-bba4041224c0",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "LTV CAC KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [LTV CAC Ratio], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [LTV CAC Ratio], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0x\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0x\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue >= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [LTV CAC Ratio]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%237C3AED' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%237C3AED' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>LTV:CAC</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%237C3AED'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "812206c3-cf91-4c68-980a-52cbd3ef1c91",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Burn Multiple KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [Burn Multiple], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [Burn Multiple], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0x\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0x\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue <= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [Burn Multiple]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], DESC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue <= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue <= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%23DC2626' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%23DC2626' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>Burn Multiple</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%23DC2626'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "5dc4d724-0dfa-4ace-8af7-f595c42da616",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Forecast Accuracy KPI Card SVG",
            "expression": "VAR LatestMonth =\n    MAXX (\n        CALCULATETABLE (\n            VALUES ( DimDate[MonthStart] ),\n            ALLSELECTED ( DimDate ),\n            REMOVEFILTERS ( DimDate[IsLatestCompleteMonth] )\n        ),\n        DimDate[MonthStart]\n    )\nVAR PriorMonth = EDATE ( LatestMonth, -12 )\nVAR CurrentValue = CALCULATE ( [Forecast Accuracy], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = LatestMonth ) )\nVAR PriorValue = CALCULATE ( [Forecast Accuracy], FILTER ( ALL ( DimDate ), DimDate[MonthStart] = PriorMonth ) )\nVAR ChangeValue = CurrentValue - PriorValue\nVAR ChangePct = DIVIDE ( ChangeValue, ABS ( PriorValue ) )\nVAR ValueTextRaw = FORMAT ( CurrentValue, \"0.0%\" )\nVAR PYTextRaw = IF ( ISBLANK ( PriorValue ), \"n/a\", FORMAT ( PriorValue, \"0.0%\" ) )\nVAR YoYTextRaw = IF ( ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ), \"n/a\", FORMAT ( ChangePct, \"+0.0%;-0.0%;0.0%\" ) )\nVAR ValueText = SUBSTITUTE ( ValueTextRaw, \"%\", \"%25\" )\nVAR PYText = SUBSTITUTE ( PYTextRaw, \"%\", \"%25\" )\nVAR YoYText = SUBSTITUTE ( YoYTextRaw, \"%\", \"%25\" )\nVAR YoYColor =\n    IF (\n        ISBLANK ( CurrentValue ) || ISBLANK ( PriorValue ),\n        \"%2364748B\",\n        IF ( ChangeValue >= 0, \"%2316A34A\", \"%23DC2626\" )\n    )\nVAR MonthTable =\n    ADDCOLUMNS (\n        FILTER ( ALLSELECTED ( DimDate ), DimDate[MonthStart] <= LatestMonth ),\n        \"__Value\", [Forecast Accuracy]\n    )\nVAR CleanTable = FILTER ( MonthTable, NOT ISBLANK ( [__Value] ) )\nVAR RowCount = COUNTROWS ( CleanTable )\nVAR MinValue = MINX ( CleanTable, [__Value] )\nVAR MaxValue = MAXX ( CleanTable, [__Value] )\nVAR FirstValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], ASC ), [__Value] )\nVAR LastValue = MINX ( TOPN ( 1, CleanTable, DimDate[MonthStart], DESC ), [__Value] )\nVAR BadMonth = MINX ( TOPN ( 1, CleanTable, [__Value], ASC, DimDate[MonthStart], ASC ), DimDate[MonthStart] )\nVAR BadValue = MINX ( FILTER ( CleanTable, DimDate[MonthStart] = BadMonth ), [__Value] )\nVAR StartYValue = 80 - DIVIDE ( FirstValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR EndYValue = 80 - DIVIDE ( LastValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR BadRank = RANKX ( CleanTable, DimDate[MonthStart], BadMonth, ASC, DENSE ) - 1\nVAR BadXValue = 136 + DIVIDE ( BadRank, MAX ( 1, RowCount - 1 ), 0 ) * 92\nVAR BadYValue = 80 - DIVIDE ( BadValue - MinValue, MaxValue - MinValue, 0.5 ) * 42\nVAR TrendColor = IF ( LastValue >= FirstValue, \"%2316A34A\", \"%23DC2626\" )\nVAR BandColor = IF ( LastValue >= FirstValue, \"%23DDEEDC\", \"%23F3D7D7\" )\nVAR LinePoints =\n    CONCATENATEX (\n        CleanTable,\n        VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n        VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n        VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n        RETURN FORMAT ( XValue, \"0.0\" ) & \",\" & FORMAT ( YValue, \"0.0\" ),\n        \" \",\n        DimDate[MonthStart],\n        ASC\n    )\nVAR AreaPath =\n    \"M136 84 \"\n        & CONCATENATEX (\n            CleanTable,\n            VAR RankValue = RANKX ( CleanTable, DimDate[MonthStart], , ASC, DENSE ) - 1\n            VAR XValue = 136 + DIVIDE ( RankValue, MAX ( 1, RowCount - 1 ), 0 ) * 92\n            VAR YValue = 80 - DIVIDE ( [__Value] - MinValue, MaxValue - MinValue, 0.5 ) * 42\n            RETURN \"L\" & FORMAT ( XValue, \"0.0\" ) & \" \" & FORMAT ( YValue, \"0.0\" ),\n            \" \",\n            DimDate[MonthStart],\n            ASC\n        )\n        & \" L228 84 Z\"\nVAR SVG =\n    \"<svg xmlns='http://www.w3.org/2000/svg' width='252' height='158' viewBox='0 0 252 158'>\"\n        & \"<rect x='1' y='1' width='250' height='156' rx='12' fill='%23FFFFFF' stroke='%23DCE3EC' stroke-width='1.4'/>\"\n        & \"<rect x='16' y='13' width='220' height='4.5' rx='2.25' fill='%232563EB' opacity='0.92'/>\"\n        & \"<rect x='16' y='32' width='13' height='13' rx='3' fill='%232563EB' opacity='0.95'/>\"\n        & \"<circle cx='22.5' cy='38.5' r='2.2' fill='%23FFFFFF' opacity='0.85'/>\"\n        & \"<text x='36' y='43' font-family='Segoe UI' font-size='14.5' font-weight='750' fill='%23111827'>Forecast</text>\"\n        & \"<text x='16' y='91' font-family='Segoe UI' font-size='28' font-weight='750' fill='%232563EB'>\" & ValueText & \"</text>\"\n        & \"<rect x='130' y='34' width='104' height='54' rx='8' fill='%23F3F6FA'/>\"\n        & \"<rect x='136' y='59' width='92' height='12' rx='6' fill='\" & BandColor & \"'/>\"\n        & \"<rect x='141' y='52' width='12' height='26' rx='2' fill='%23DCE3EC' opacity='0.48'/>\"\n        & \"<rect x='160' y='48' width='12' height='30' rx='2' fill='%23DCE3EC' opacity='0.38'/>\"\n        & \"<rect x='179' y='44' width='12' height='34' rx='2' fill='%23DCE3EC' opacity='0.30'/>\"\n        & \"<rect x='198' y='40' width='12' height='38' rx='2' fill='%23DCE3EC' opacity='0.24'/>\"\n        & \"<line x1='136' y1='65' x2='228' y2='65' stroke='%2394A3B8' stroke-width='1' stroke-dasharray='4 5'/>\"\n        & \"<path d='\" & AreaPath & \"' fill='%23DBEAFE' opacity='0.60'/>\"\n        & \"<polyline points='\" & LinePoints & \"' fill='none' stroke='\" & TrendColor & \"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>\"\n        & \"<circle cx='136' cy='\" & FORMAT ( StartYValue, \"0.0\" ) & \"' r='4' fill='%23FFFFFF' stroke='%232563EB' stroke-width='2'/>\"\n        & \"<circle cx='\" & FORMAT ( BadXValue, \"0.0\" ) & \"' cy='\" & FORMAT ( BadYValue, \"0.0\" ) & \"' r='4' fill='%23F59E0B' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<circle cx='228' cy='\" & FORMAT ( EndYValue, \"0.0\" ) & \"' r='5' fill='\" & TrendColor & \"' stroke='%23FFFFFF' stroke-width='2'/>\"\n        & \"<rect x='16' y='112' width='101' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<rect x='126' y='112' width='110' height='36' rx='8' fill='%23F8FAFC'/>\"\n        & \"<text x='24' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>PY</text>\"\n        & \"<text x='24' y='143' font-family='Segoe UI' font-size='12.2' fill='%2364748B'>\" & PYText & \"</text>\"\n        & \"<text x='136' y='127' font-family='Segoe UI' font-size='11.5' font-weight='750' fill='%23111827'>YoY</text>\"\n        & \"<polygon points='138,134 144,144 132,144' fill='\" & YoYColor & \"'/>\"\n        & \"<text x='152' y='143' font-family='Segoe UI' font-size='12.2' font-weight='750' fill='\" & YoYColor & \"'>\" & YoYText & \"</text>\"\n        & \"</svg>\"\nRETURN\n    IF ( RowCount = 0, BLANK (), \"data:image/svg+xml;utf8,\" & SVG )",
            "formatString": "",
            "lineageTag": "c6af0f51-b325-421b-b08b-d96387eff42a",
            "dataType": "string",
            "dataCategory": "ImageUrl"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Rel_FactSubscriptionMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactSubscriptionMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactSubscriptionMonthly_PlanID_DimPlan_PlanID",
        "fromTable": "FactSubscriptionMonthly",
        "fromColumn": "PlanID",
        "toTable": "DimPlan",
        "toColumn": "PlanID"
      },
      {
        "name": "Rel_FactSubscriptionMonthly_ChannelID_DimChannel_ChannelID",
        "fromTable": "FactSubscriptionMonthly",
        "fromColumn": "ChannelID",
        "toTable": "DimChannel",
        "toColumn": "ChannelID"
      },
      {
        "name": "Rel_FactSubscriptionMonthly_RegionID_DimRegion_RegionID",
        "fromTable": "FactSubscriptionMonthly",
        "fromColumn": "RegionID",
        "toTable": "DimRegion",
        "toColumn": "RegionID"
      },
      {
        "name": "Rel_FactMRRMovement_MonthStart_DimDate_MonthStart",
        "fromTable": "FactMRRMovement",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactCohortRetention_ActivityMonth_DimDate_MonthStart",
        "fromTable": "FactCohortRetention",
        "fromColumn": "ActivityMonth",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactCohortRetention_PlanID_DimPlan_PlanID",
        "fromTable": "FactCohortRetention",
        "fromColumn": "PlanID",
        "toTable": "DimPlan",
        "toColumn": "PlanID"
      },
      {
        "name": "Rel_FactCohortRetention_ChannelID_DimChannel_ChannelID",
        "fromTable": "FactCohortRetention",
        "fromColumn": "ChannelID",
        "toTable": "DimChannel",
        "toColumn": "ChannelID"
      },
      {
        "name": "Rel_FactAcquisitionMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactAcquisitionMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactAcquisitionMonthly_PlanID_DimPlan_PlanID",
        "fromTable": "FactAcquisitionMonthly",
        "fromColumn": "PlanID",
        "toTable": "DimPlan",
        "toColumn": "PlanID"
      },
      {
        "name": "Rel_FactAcquisitionMonthly_ChannelID_DimChannel_ChannelID",
        "fromTable": "FactAcquisitionMonthly",
        "fromColumn": "ChannelID",
        "toTable": "DimChannel",
        "toColumn": "ChannelID"
      },
      {
        "name": "Rel_FactAcquisitionMonthly_RegionID_DimRegion_RegionID",
        "fromTable": "FactAcquisitionMonthly",
        "fromColumn": "RegionID",
        "toTable": "DimRegion",
        "toColumn": "RegionID"
      },
      {
        "name": "Rel_FactFinanceMonthly_MonthStart_DimDate_MonthStart",
        "fromTable": "FactFinanceMonthly",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactForecast_MonthStart_DimDate_MonthStart",
        "fromTable": "FactForecast",
        "fromColumn": "MonthStart",
        "toTable": "DimDate",
        "toColumn": "MonthStart"
      },
      {
        "name": "Rel_FactAccountHealth_PlanID_DimPlan_PlanID",
        "fromTable": "FactAccountHealth",
        "fromColumn": "PlanID",
        "toTable": "DimPlan",
        "toColumn": "PlanID"
      },
      {
        "name": "Rel_FactAccountHealth_ChannelID_DimChannel_ChannelID",
        "fromTable": "FactAccountHealth",
        "fromColumn": "ChannelID",
        "toTable": "DimChannel",
        "toColumn": "ChannelID"
      },
      {
        "name": "Rel_FactAccountHealth_RegionID_DimRegion_RegionID",
        "fromTable": "FactAccountHealth",
        "fromColumn": "RegionID",
        "toTable": "DimRegion",
        "toColumn": "RegionID"
      }
    ]
  }
}