table DimAccount

	column account_id
		dataType: string
		summarizeBy: none
		sourceColumn: account_id

	column account
		dataType: string
		summarizeBy: none
		sourceColumn: account

	column account_group
		dataType: string
		summarizeBy: none
		sourceColumn: account_group

	column sort_order
		dataType: int64
		summarizeBy: none
		sourceColumn: sort_order

	column statement
		dataType: string
		summarizeBy: none
		sourceColumn: statement

	partition DimAccount-Import = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/Win/OneDrive/Codex/Portfolio/BI/Project 13 - Regional FP&A Consolidation/data/prepared/dim_account.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {
				        {"account_id", type text},
				        {"account", type text},
				        {"account_group", type text},
				        {"sort_order", Int64.Type},
				        {"statement", type text}
				    }, "en-US")
				in
				    TypedColumns

