table FactFinancials

	column date_id
		dataType: string
		summarizeBy: none
		sourceColumn: date_id

	column entity_id
		dataType: string
		summarizeBy: none
		sourceColumn: entity_id

	column business_unit_id
		dataType: string
		summarizeBy: none
		sourceColumn: business_unit_id

	column scenario_id
		dataType: string
		summarizeBy: none
		sourceColumn: scenario_id

	column account_id
		dataType: string
		summarizeBy: none
		sourceColumn: account_id

	column currency
		dataType: string
		summarizeBy: none
		sourceColumn: currency

	column amount_local
		dataType: double
		summarizeBy: none
		sourceColumn: amount_local

	column amount_usd
		dataType: double
		summarizeBy: none
		sourceColumn: amount_usd

	column fx_rate_to_usd
		dataType: double
		summarizeBy: none
		sourceColumn: fx_rate_to_usd

	column quantity_teu_or_orders
		dataType: double
		summarizeBy: none
		sourceColumn: quantity_teu_or_orders

	column is_synthetic
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_synthetic

	partition FactFinancials-Import = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("<PROJECT_ROOT>/data/prepared/fact_financials.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {
				        {"date_id", type text},
				        {"entity_id", type text},
				        {"business_unit_id", type text},
				        {"scenario_id", type text},
				        {"account_id", type text},
				        {"currency", type text},
				        {"amount_local", type number},
				        {"amount_usd", type number},
				        {"fx_rate_to_usd", type number},
				        {"quantity_teu_or_orders", type number},
				        {"is_synthetic", type logical}
				    }, "en-US")
				in
				    TypedColumns
