Actual Revenue = SUM ( fact_manufacturing_month[actual_revenue] )
Budget Revenue = SUM ( fact_manufacturing_month[budget_revenue] )
Actual COGS = SUM ( fact_manufacturing_month[actual_cogs] )
Standard COGS = SUM ( fact_manufacturing_month[standard_cogs] )
Actual Material Cost = SUM ( fact_manufacturing_month[actual_material_cost] )
Actual Labor Cost = SUM ( fact_manufacturing_month[actual_labor_cost] )
Actual Overhead Cost = SUM ( fact_manufacturing_month[actual_overhead_cost] )
Scrap Cost = SUM ( fact_manufacturing_month[scrap_cost] )
Rework Cost = SUM ( fact_manufacturing_month[rework_cost] )
Yield Loss Cost = SUM ( fact_manufacturing_month[yield_loss_cost] )
Material Variance = SUM ( fact_manufacturing_month[material_variance] )
Labor Variance = SUM ( fact_manufacturing_month[labor_variance] )
Overhead Variance = SUM ( fact_manufacturing_month[overhead_variance] )
Cost Variance vs Standard = [Actual COGS] - [Standard COGS]
Gross Margin = [Actual Revenue] - [Actual COGS]
Gross Margin % = DIVIDE ( [Gross Margin], [Actual Revenue] )
Produced Units = SUM ( fact_manufacturing_month[produced_units] )
Good Units = SUM ( fact_manufacturing_month[good_units] )
Scrap Units = SUM ( fact_manufacturing_month[scrap_units] )
Rework Units = SUM ( fact_manufacturing_month[rework_units] )
Yield % = DIVIDE ( [Good Units], [Produced Units] )
Scrap Rate = DIVIDE ( [Scrap Units], [Produced Units] )
Unit Cost = DIVIDE ( [Actual COGS], [Good Units] )
Standard Unit Cost = DIVIDE ( [Standard COGS], [Good Units] )
Run Hours = SUM ( fact_manufacturing_month[run_hours] )
Available Hours = SUM ( fact_manufacturing_month[available_hours] )
Downtime Hours = SUM ( fact_manufacturing_month[downtime_hours] )
Utilization % = DIVIDE ( [Run Hours], [Available Hours] )
Capacity Units = SUM ( fact_manufacturing_month[capacity_units] )
Capacity Gap Units = [Capacity Units] - [Produced Units]
Inventory Value = SUM ( fact_manufacturing_month[inventory_value] )
Slow Moving Inventory = SUM ( fact_manufacturing_month[slow_moving_inventory_value] )
Inventory Days = DIVIDE ( [Inventory Value], [Actual COGS] ) * 30
Bridge Amount = SUM ( fact_cost_variance_bridge[bridge_amount] )
Current Month Index = COALESCE ( SELECTEDVALUE ( dim_date[month_index] ), MAXX ( ALL ( dim_date ), dim_date[month_index] ) )
Current Revenue = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Actual Revenue], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Actual COGS = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Actual COGS], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Standard COGS = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Standard COGS], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Gross Margin = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Gross Margin], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current GM % = DIVIDE ( [Current Gross Margin], [Current Revenue] )
Current Cost Variance = [Current Actual COGS] - [Current Standard COGS]
Current Unit Cost = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Unit Cost], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Yield % = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Yield %], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Scrap Rate = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Scrap Rate], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Utilization % = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Utilization %], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Inventory Value = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Inventory Value], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Inventory Days = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Inventory Days], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Material Variance = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Material Variance], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Labor Variance = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Labor Variance], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Overhead Variance = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Overhead Variance], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Yield Loss Cost = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Yield Loss Cost], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Current Capacity Gap Units = VAR CurrentMonth = [Current Month Index] RETURN CALCULATE ( [Capacity Gap Units], FILTER ( ALL ( dim_date ), dim_date[month_index] = CurrentMonth ) )
Scenario Material Cost Reduction % = SELECTEDVALUE ( dim_scenario[material_cost_reduction_pct], 0 )
Scenario Labor Efficiency Gain % = SELECTEDVALUE ( dim_scenario[labor_efficiency_gain_pct], 0 )
Scenario OH Absorption Gain % = SELECTEDVALUE ( dim_scenario[overhead_absorption_gain_pct], 0 )
Scenario Scrap Reduction % = SELECTEDVALUE ( dim_scenario[scrap_reduction_pct], 0 )
Scenario Volume Delta % = SELECTEDVALUE ( dim_scenario[volume_delta_pct], 0 )
Scenario Cost Savings = [Current Material Variance] * [Scenario Material Cost Reduction %] + [Current Labor Variance] * [Scenario Labor Efficiency Gain %] + [Current Overhead Variance] * [Scenario OH Absorption Gain %] + [Current Yield Loss Cost] * [Scenario Scrap Reduction %]
Scenario Gross Margin = [Current Gross Margin] + [Scenario Cost Savings] + [Current Gross Margin] * [Scenario Volume Delta %]
Scenario GM % = DIVIDE ( [Scenario Gross Margin], [Current Revenue] * ( 1 + [Scenario Volume Delta %] ) )
Scenario EBITDA Uplift = [Scenario Gross Margin] - [Current Gross Margin]
Spark Revenue Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Actual Revenue], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Gross Margin Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Gross Margin], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark GM % Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Gross Margin %], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Cost Variance Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Cost Variance vs Standard], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Unit Cost Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Unit Cost], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Yield Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Yield %], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Material Variance Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Material Variance], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Labor Variance Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Labor Variance], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Overhead Variance Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Overhead Variance], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Yield Loss Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Yield Loss Cost], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Actual COGS Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Actual COGS], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Standard COGS Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Standard COGS], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Scrap Rate Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Scrap Rate], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Utilization Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Utilization %], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Capacity Gap Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Capacity Gap Units], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Inventory Value Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Inventory Value], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Inventory Days Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Inventory Days], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
Spark Scenario EBITDA Uplift Trend = VAR SparkMonth = SELECTEDVALUE ( dim_spark_date[year_month] ) RETURN CALCULATE ( [Scenario EBITDA Uplift], REMOVEFILTERS ( dim_date ), TREATAS ( { SparkMonth }, dim_date[year_month] ) )
